.type V

.decl Rule(n: number)
.input Rule

.decl years(v0: V, v1: V)
.input years

.decl yearOfRelease(v0: V, v1: V)
.input yearOfRelease

.decl year(v0: V, v1: V)
.input year

.decl writer(v0: V, v1: V)
.input writer

.decl wikisourcelangProperty(v0: V, v1: V)
.input wikisourcelangProperty

.decl Igenre(v0: V, v1: V)
.input Igenre

.decl genre(v0: V, v1: V)
.decl years_exists(v0: V, v1: V, r: number)
.output years_exists

.decl yearOfRelease_exists(v0: V, v1: V, r: number)
.output yearOfRelease_exists

.decl year_exists(v0: V, v1: V, r: number)
.output year_exists

.decl writer_exists(v0: V, v1: V, r: number)
.output writer_exists

.decl wikisourcelangProperty_exists(v0: V, v1: V, r: number)
.output wikisourcelangProperty_exists

.decl Igenre_exists(v0: V, v1: V, r: number)
.output Igenre_exists

.decl genre_exists(v0: V, v1: V, r: number)
.output genre_exists



genre(v0, v1) :- years(v0, v1), Rule(0).
genre_exists(v0, v1, r) :- years(v0, v1), r = 0, Rule(0).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), Rule(r), Rule(0).
genre(v0, v1) :- years(v1, v0), Rule(1).
genre_exists(v0, v1, r) :- years(v1, v0), r = 1, Rule(1).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), Rule(r), Rule(1).
genre(v0, v1) :- yearOfRelease(v0, v1), Rule(2).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), r = 2, Rule(2).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), Rule(r), Rule(2).
genre(v0, v1) :- yearOfRelease(v1, v0), Rule(3).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), r = 3, Rule(3).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), Rule(r), Rule(3).
genre(v0, v1) :- year(v0, v1), Rule(4).
genre_exists(v0, v1, r) :- year(v0, v1), r = 4, Rule(4).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), Rule(r), Rule(4).
genre(v0, v1) :- year(v1, v0), Rule(5).
genre_exists(v0, v1, r) :- year(v1, v0), r = 5, Rule(5).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), Rule(r), Rule(5).
genre(v0, v1) :- writer(v0, v1), Rule(6).
genre_exists(v0, v1, r) :- writer(v0, v1), r = 6, Rule(6).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), Rule(r), Rule(6).
genre(v0, v1) :- writer(v1, v0), Rule(7).
genre_exists(v0, v1, r) :- writer(v1, v0), r = 7, Rule(7).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), Rule(r), Rule(7).
genre(v0, v1) :- wikisourcelangProperty(v0, v1), Rule(8).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), r = 8, Rule(8).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(8).
genre(v0, v1) :- wikisourcelangProperty(v1, v0), Rule(9).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), r = 9, Rule(9).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(9).
genre(v0, v1) :- Igenre(v0, v1), Rule(10).
genre_exists(v0, v1, r) :- Igenre(v0, v1), r = 10, Rule(10).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v1, r), Rule(r), Rule(10).
genre(v0, v1) :- Igenre(v1, v0), Rule(11).
genre_exists(v0, v1, r) :- Igenre(v1, v0), r = 11, Rule(11).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v0, r), Rule(r), Rule(11).
genre(v0, v1) :- genre(v0, v1), Rule(12).
genre_exists(v0, v1, r) :- genre(v0, v1), r = 12, Rule(12).
genre_exists(v0, v1, r) :- genre_exists(v0, v1, r), Rule(r), Rule(12).
genre(v0, v1) :- genre(v1, v0), Rule(13).
genre_exists(v0, v1, r) :- genre(v1, v0), r = 13, Rule(13).
genre_exists(v0, v1, r) :- genre_exists(v1, v0, r), Rule(r), Rule(13).
genre(v0, v1) :- years(v0, v1), years(v0, v1), Rule(14).
genre_exists(v0, v1, r) :- years(v0, v1), years(v0, v1), r = 14, Rule(14).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), years(v0, v1), Rule(r), Rule(14).
genre_exists(v0, v1, r) :- years(v0, v1), years_exists(v0, v1, r), Rule(r), Rule(14).
genre(v0, v1) :- years(v0, v1), years(v1, v0), Rule(15).
genre_exists(v0, v1, r) :- years(v0, v1), years(v1, v0), r = 15, Rule(15).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), years(v1, v0), Rule(r), Rule(15).
genre_exists(v0, v1, r) :- years(v0, v1), years_exists(v1, v0, r), Rule(r), Rule(15).
genre(v0, v1) :- years(v1, v0), years(v1, v0), Rule(16).
genre_exists(v0, v1, r) :- years(v1, v0), years(v1, v0), r = 16, Rule(16).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), years(v1, v0), Rule(r), Rule(16).
genre_exists(v0, v1, r) :- years(v1, v0), years_exists(v1, v0, r), Rule(r), Rule(16).
genre(v0, v1) :- years(v1, v0), years(v0, v1), Rule(17).
genre_exists(v0, v1, r) :- years(v1, v0), years(v0, v1), r = 17, Rule(17).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), years(v0, v1), Rule(r), Rule(17).
genre_exists(v0, v1, r) :- years(v1, v0), years_exists(v0, v1, r), Rule(r), Rule(17).
genre(v0, v1) :- years(v2, v1), years(v0, v2), Rule(18).
genre_exists(v0, v1, r) :- years(v2, v1), years(v0, v2), r = 18, Rule(18).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), years(v0, v2), Rule(r), Rule(18).
genre_exists(v0, v1, r) :- years(v2, v1), years_exists(v0, v2, r), Rule(r), Rule(18).
genre(v0, v1) :- years(v1, v2), years(v2, v0), Rule(19).
genre_exists(v0, v1, r) :- years(v1, v2), years(v2, v0), r = 19, Rule(19).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), years(v2, v0), Rule(r), Rule(19).
genre_exists(v0, v1, r) :- years(v1, v2), years_exists(v2, v0, r), Rule(r), Rule(19).
genre(v0, v1) :- years(v2, v0), years(v1, v2), Rule(20).
genre_exists(v0, v1, r) :- years(v2, v0), years(v1, v2), r = 20, Rule(20).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), years(v1, v2), Rule(r), Rule(20).
genre_exists(v0, v1, r) :- years(v2, v0), years_exists(v1, v2, r), Rule(r), Rule(20).
genre(v0, v1) :- years(v2, v0), years(v2, v1), Rule(21).
genre_exists(v0, v1, r) :- years(v2, v0), years(v2, v1), r = 21, Rule(21).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), years(v2, v1), Rule(r), Rule(21).
genre_exists(v0, v1, r) :- years(v2, v0), years_exists(v2, v1, r), Rule(r), Rule(21).
genre(v0, v1) :- years(v0, v2), years(v1, v2), Rule(22).
genre_exists(v0, v1, r) :- years(v0, v2), years(v1, v2), r = 22, Rule(22).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), years(v1, v2), Rule(r), Rule(22).
genre_exists(v0, v1, r) :- years(v0, v2), years_exists(v1, v2, r), Rule(r), Rule(22).
genre(v0, v1) :- years(v0, v2), years(v2, v1), Rule(23).
genre_exists(v0, v1, r) :- years(v0, v2), years(v2, v1), r = 23, Rule(23).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), years(v2, v1), Rule(r), Rule(23).
genre_exists(v0, v1, r) :- years(v0, v2), years_exists(v2, v1, r), Rule(r), Rule(23).
genre(v0, v1) :- years(v2, v1), years(v2, v0), Rule(24).
genre_exists(v0, v1, r) :- years(v2, v1), years(v2, v0), r = 24, Rule(24).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), years(v2, v0), Rule(r), Rule(24).
genre_exists(v0, v1, r) :- years(v2, v1), years_exists(v2, v0, r), Rule(r), Rule(24).
genre(v0, v1) :- years(v1, v2), years(v0, v2), Rule(25).
genre_exists(v0, v1, r) :- years(v1, v2), years(v0, v2), r = 25, Rule(25).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), years(v0, v2), Rule(r), Rule(25).
genre_exists(v0, v1, r) :- years(v1, v2), years_exists(v0, v2, r), Rule(r), Rule(25).
genre(v0, v1) :- years(v0, v1), yearOfRelease(v0, v1), Rule(26).
genre_exists(v0, v1, r) :- years(v0, v1), yearOfRelease(v0, v1), r = 26, Rule(26).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), yearOfRelease(v0, v1), Rule(r), Rule(26).
genre_exists(v0, v1, r) :- years(v0, v1), yearOfRelease_exists(v0, v1, r), Rule(r), Rule(26).
genre(v0, v1) :- years(v0, v1), yearOfRelease(v1, v0), Rule(27).
genre_exists(v0, v1, r) :- years(v0, v1), yearOfRelease(v1, v0), r = 27, Rule(27).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), yearOfRelease(v1, v0), Rule(r), Rule(27).
genre_exists(v0, v1, r) :- years(v0, v1), yearOfRelease_exists(v1, v0, r), Rule(r), Rule(27).
genre(v0, v1) :- years(v1, v0), yearOfRelease(v1, v0), Rule(28).
genre_exists(v0, v1, r) :- years(v1, v0), yearOfRelease(v1, v0), r = 28, Rule(28).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), yearOfRelease(v1, v0), Rule(r), Rule(28).
genre_exists(v0, v1, r) :- years(v1, v0), yearOfRelease_exists(v1, v0, r), Rule(r), Rule(28).
genre(v0, v1) :- years(v1, v0), yearOfRelease(v0, v1), Rule(29).
genre_exists(v0, v1, r) :- years(v1, v0), yearOfRelease(v0, v1), r = 29, Rule(29).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), yearOfRelease(v0, v1), Rule(r), Rule(29).
genre_exists(v0, v1, r) :- years(v1, v0), yearOfRelease_exists(v0, v1, r), Rule(r), Rule(29).
genre(v0, v1) :- years(v2, v1), yearOfRelease(v0, v2), Rule(30).
genre_exists(v0, v1, r) :- years(v2, v1), yearOfRelease(v0, v2), r = 30, Rule(30).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), yearOfRelease(v0, v2), Rule(r), Rule(30).
genre_exists(v0, v1, r) :- years(v2, v1), yearOfRelease_exists(v0, v2, r), Rule(r), Rule(30).
genre(v0, v1) :- years(v1, v2), yearOfRelease(v2, v0), Rule(31).
genre_exists(v0, v1, r) :- years(v1, v2), yearOfRelease(v2, v0), r = 31, Rule(31).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), yearOfRelease(v2, v0), Rule(r), Rule(31).
genre_exists(v0, v1, r) :- years(v1, v2), yearOfRelease_exists(v2, v0, r), Rule(r), Rule(31).
genre(v0, v1) :- years(v2, v0), yearOfRelease(v1, v2), Rule(32).
genre_exists(v0, v1, r) :- years(v2, v0), yearOfRelease(v1, v2), r = 32, Rule(32).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), yearOfRelease(v1, v2), Rule(r), Rule(32).
genre_exists(v0, v1, r) :- years(v2, v0), yearOfRelease_exists(v1, v2, r), Rule(r), Rule(32).
genre(v0, v1) :- years(v2, v0), yearOfRelease(v2, v1), Rule(33).
genre_exists(v0, v1, r) :- years(v2, v0), yearOfRelease(v2, v1), r = 33, Rule(33).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), yearOfRelease(v2, v1), Rule(r), Rule(33).
genre_exists(v0, v1, r) :- years(v2, v0), yearOfRelease_exists(v2, v1, r), Rule(r), Rule(33).
genre(v0, v1) :- years(v0, v2), yearOfRelease(v1, v2), Rule(34).
genre_exists(v0, v1, r) :- years(v0, v2), yearOfRelease(v1, v2), r = 34, Rule(34).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), yearOfRelease(v1, v2), Rule(r), Rule(34).
genre_exists(v0, v1, r) :- years(v0, v2), yearOfRelease_exists(v1, v2, r), Rule(r), Rule(34).
genre(v0, v1) :- years(v0, v2), yearOfRelease(v2, v1), Rule(35).
genre_exists(v0, v1, r) :- years(v0, v2), yearOfRelease(v2, v1), r = 35, Rule(35).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), yearOfRelease(v2, v1), Rule(r), Rule(35).
genre_exists(v0, v1, r) :- years(v0, v2), yearOfRelease_exists(v2, v1, r), Rule(r), Rule(35).
genre(v0, v1) :- years(v2, v1), yearOfRelease(v2, v0), Rule(36).
genre_exists(v0, v1, r) :- years(v2, v1), yearOfRelease(v2, v0), r = 36, Rule(36).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), yearOfRelease(v2, v0), Rule(r), Rule(36).
genre_exists(v0, v1, r) :- years(v2, v1), yearOfRelease_exists(v2, v0, r), Rule(r), Rule(36).
genre(v0, v1) :- years(v1, v2), yearOfRelease(v0, v2), Rule(37).
genre_exists(v0, v1, r) :- years(v1, v2), yearOfRelease(v0, v2), r = 37, Rule(37).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), yearOfRelease(v0, v2), Rule(r), Rule(37).
genre_exists(v0, v1, r) :- years(v1, v2), yearOfRelease_exists(v0, v2, r), Rule(r), Rule(37).
genre(v0, v1) :- years(v0, v1), year(v0, v1), Rule(38).
genre_exists(v0, v1, r) :- years(v0, v1), year(v0, v1), r = 38, Rule(38).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), year(v0, v1), Rule(r), Rule(38).
genre_exists(v0, v1, r) :- years(v0, v1), year_exists(v0, v1, r), Rule(r), Rule(38).
genre(v0, v1) :- years(v0, v1), year(v1, v0), Rule(39).
genre_exists(v0, v1, r) :- years(v0, v1), year(v1, v0), r = 39, Rule(39).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), year(v1, v0), Rule(r), Rule(39).
genre_exists(v0, v1, r) :- years(v0, v1), year_exists(v1, v0, r), Rule(r), Rule(39).
genre(v0, v1) :- years(v1, v0), year(v1, v0), Rule(40).
genre_exists(v0, v1, r) :- years(v1, v0), year(v1, v0), r = 40, Rule(40).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), year(v1, v0), Rule(r), Rule(40).
genre_exists(v0, v1, r) :- years(v1, v0), year_exists(v1, v0, r), Rule(r), Rule(40).
genre(v0, v1) :- years(v1, v0), year(v0, v1), Rule(41).
genre_exists(v0, v1, r) :- years(v1, v0), year(v0, v1), r = 41, Rule(41).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), year(v0, v1), Rule(r), Rule(41).
genre_exists(v0, v1, r) :- years(v1, v0), year_exists(v0, v1, r), Rule(r), Rule(41).
genre(v0, v1) :- years(v2, v1), year(v0, v2), Rule(42).
genre_exists(v0, v1, r) :- years(v2, v1), year(v0, v2), r = 42, Rule(42).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), year(v0, v2), Rule(r), Rule(42).
genre_exists(v0, v1, r) :- years(v2, v1), year_exists(v0, v2, r), Rule(r), Rule(42).
genre(v0, v1) :- years(v1, v2), year(v2, v0), Rule(43).
genre_exists(v0, v1, r) :- years(v1, v2), year(v2, v0), r = 43, Rule(43).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), year(v2, v0), Rule(r), Rule(43).
genre_exists(v0, v1, r) :- years(v1, v2), year_exists(v2, v0, r), Rule(r), Rule(43).
genre(v0, v1) :- years(v2, v0), year(v1, v2), Rule(44).
genre_exists(v0, v1, r) :- years(v2, v0), year(v1, v2), r = 44, Rule(44).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), year(v1, v2), Rule(r), Rule(44).
genre_exists(v0, v1, r) :- years(v2, v0), year_exists(v1, v2, r), Rule(r), Rule(44).
genre(v0, v1) :- years(v2, v0), year(v2, v1), Rule(45).
genre_exists(v0, v1, r) :- years(v2, v0), year(v2, v1), r = 45, Rule(45).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), year(v2, v1), Rule(r), Rule(45).
genre_exists(v0, v1, r) :- years(v2, v0), year_exists(v2, v1, r), Rule(r), Rule(45).
genre(v0, v1) :- years(v0, v2), year(v1, v2), Rule(46).
genre_exists(v0, v1, r) :- years(v0, v2), year(v1, v2), r = 46, Rule(46).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), year(v1, v2), Rule(r), Rule(46).
genre_exists(v0, v1, r) :- years(v0, v2), year_exists(v1, v2, r), Rule(r), Rule(46).
genre(v0, v1) :- years(v0, v2), year(v2, v1), Rule(47).
genre_exists(v0, v1, r) :- years(v0, v2), year(v2, v1), r = 47, Rule(47).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), year(v2, v1), Rule(r), Rule(47).
genre_exists(v0, v1, r) :- years(v0, v2), year_exists(v2, v1, r), Rule(r), Rule(47).
genre(v0, v1) :- years(v2, v1), year(v2, v0), Rule(48).
genre_exists(v0, v1, r) :- years(v2, v1), year(v2, v0), r = 48, Rule(48).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), year(v2, v0), Rule(r), Rule(48).
genre_exists(v0, v1, r) :- years(v2, v1), year_exists(v2, v0, r), Rule(r), Rule(48).
genre(v0, v1) :- years(v1, v2), year(v0, v2), Rule(49).
genre_exists(v0, v1, r) :- years(v1, v2), year(v0, v2), r = 49, Rule(49).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), year(v0, v2), Rule(r), Rule(49).
genre_exists(v0, v1, r) :- years(v1, v2), year_exists(v0, v2, r), Rule(r), Rule(49).
genre(v0, v1) :- years(v0, v1), writer(v0, v1), Rule(50).
genre_exists(v0, v1, r) :- years(v0, v1), writer(v0, v1), r = 50, Rule(50).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), writer(v0, v1), Rule(r), Rule(50).
genre_exists(v0, v1, r) :- years(v0, v1), writer_exists(v0, v1, r), Rule(r), Rule(50).
genre(v0, v1) :- years(v0, v1), writer(v1, v0), Rule(51).
genre_exists(v0, v1, r) :- years(v0, v1), writer(v1, v0), r = 51, Rule(51).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), writer(v1, v0), Rule(r), Rule(51).
genre_exists(v0, v1, r) :- years(v0, v1), writer_exists(v1, v0, r), Rule(r), Rule(51).
genre(v0, v1) :- years(v1, v0), writer(v1, v0), Rule(52).
genre_exists(v0, v1, r) :- years(v1, v0), writer(v1, v0), r = 52, Rule(52).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), writer(v1, v0), Rule(r), Rule(52).
genre_exists(v0, v1, r) :- years(v1, v0), writer_exists(v1, v0, r), Rule(r), Rule(52).
genre(v0, v1) :- years(v1, v0), writer(v0, v1), Rule(53).
genre_exists(v0, v1, r) :- years(v1, v0), writer(v0, v1), r = 53, Rule(53).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), writer(v0, v1), Rule(r), Rule(53).
genre_exists(v0, v1, r) :- years(v1, v0), writer_exists(v0, v1, r), Rule(r), Rule(53).
genre(v0, v1) :- years(v2, v1), writer(v0, v2), Rule(54).
genre_exists(v0, v1, r) :- years(v2, v1), writer(v0, v2), r = 54, Rule(54).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), writer(v0, v2), Rule(r), Rule(54).
genre_exists(v0, v1, r) :- years(v2, v1), writer_exists(v0, v2, r), Rule(r), Rule(54).
genre(v0, v1) :- years(v1, v2), writer(v2, v0), Rule(55).
genre_exists(v0, v1, r) :- years(v1, v2), writer(v2, v0), r = 55, Rule(55).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), writer(v2, v0), Rule(r), Rule(55).
genre_exists(v0, v1, r) :- years(v1, v2), writer_exists(v2, v0, r), Rule(r), Rule(55).
genre(v0, v1) :- years(v2, v0), writer(v1, v2), Rule(56).
genre_exists(v0, v1, r) :- years(v2, v0), writer(v1, v2), r = 56, Rule(56).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), writer(v1, v2), Rule(r), Rule(56).
genre_exists(v0, v1, r) :- years(v2, v0), writer_exists(v1, v2, r), Rule(r), Rule(56).
genre(v0, v1) :- years(v2, v0), writer(v2, v1), Rule(57).
genre_exists(v0, v1, r) :- years(v2, v0), writer(v2, v1), r = 57, Rule(57).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), writer(v2, v1), Rule(r), Rule(57).
genre_exists(v0, v1, r) :- years(v2, v0), writer_exists(v2, v1, r), Rule(r), Rule(57).
genre(v0, v1) :- years(v0, v2), writer(v1, v2), Rule(58).
genre_exists(v0, v1, r) :- years(v0, v2), writer(v1, v2), r = 58, Rule(58).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), writer(v1, v2), Rule(r), Rule(58).
genre_exists(v0, v1, r) :- years(v0, v2), writer_exists(v1, v2, r), Rule(r), Rule(58).
genre(v0, v1) :- years(v0, v2), writer(v2, v1), Rule(59).
genre_exists(v0, v1, r) :- years(v0, v2), writer(v2, v1), r = 59, Rule(59).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), writer(v2, v1), Rule(r), Rule(59).
genre_exists(v0, v1, r) :- years(v0, v2), writer_exists(v2, v1, r), Rule(r), Rule(59).
genre(v0, v1) :- years(v2, v1), writer(v2, v0), Rule(60).
genre_exists(v0, v1, r) :- years(v2, v1), writer(v2, v0), r = 60, Rule(60).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), writer(v2, v0), Rule(r), Rule(60).
genre_exists(v0, v1, r) :- years(v2, v1), writer_exists(v2, v0, r), Rule(r), Rule(60).
genre(v0, v1) :- years(v1, v2), writer(v0, v2), Rule(61).
genre_exists(v0, v1, r) :- years(v1, v2), writer(v0, v2), r = 61, Rule(61).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), writer(v0, v2), Rule(r), Rule(61).
genre_exists(v0, v1, r) :- years(v1, v2), writer_exists(v0, v2, r), Rule(r), Rule(61).
genre(v0, v1) :- years(v0, v1), wikisourcelangProperty(v0, v1), Rule(62).
genre_exists(v0, v1, r) :- years(v0, v1), wikisourcelangProperty(v0, v1), r = 62, Rule(62).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(62).
genre_exists(v0, v1, r) :- years(v0, v1), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(62).
genre(v0, v1) :- years(v0, v1), wikisourcelangProperty(v1, v0), Rule(63).
genre_exists(v0, v1, r) :- years(v0, v1), wikisourcelangProperty(v1, v0), r = 63, Rule(63).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(63).
genre_exists(v0, v1, r) :- years(v0, v1), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(63).
genre(v0, v1) :- years(v1, v0), wikisourcelangProperty(v1, v0), Rule(64).
genre_exists(v0, v1, r) :- years(v1, v0), wikisourcelangProperty(v1, v0), r = 64, Rule(64).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(64).
genre_exists(v0, v1, r) :- years(v1, v0), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(64).
genre(v0, v1) :- years(v1, v0), wikisourcelangProperty(v0, v1), Rule(65).
genre_exists(v0, v1, r) :- years(v1, v0), wikisourcelangProperty(v0, v1), r = 65, Rule(65).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(65).
genre_exists(v0, v1, r) :- years(v1, v0), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(65).
genre(v0, v1) :- years(v2, v1), wikisourcelangProperty(v0, v2), Rule(66).
genre_exists(v0, v1, r) :- years(v2, v1), wikisourcelangProperty(v0, v2), r = 66, Rule(66).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(66).
genre_exists(v0, v1, r) :- years(v2, v1), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(66).
genre(v0, v1) :- years(v1, v2), wikisourcelangProperty(v2, v0), Rule(67).
genre_exists(v0, v1, r) :- years(v1, v2), wikisourcelangProperty(v2, v0), r = 67, Rule(67).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(67).
genre_exists(v0, v1, r) :- years(v1, v2), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(67).
genre(v0, v1) :- years(v2, v0), wikisourcelangProperty(v1, v2), Rule(68).
genre_exists(v0, v1, r) :- years(v2, v0), wikisourcelangProperty(v1, v2), r = 68, Rule(68).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(68).
genre_exists(v0, v1, r) :- years(v2, v0), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(68).
genre(v0, v1) :- years(v2, v0), wikisourcelangProperty(v2, v1), Rule(69).
genre_exists(v0, v1, r) :- years(v2, v0), wikisourcelangProperty(v2, v1), r = 69, Rule(69).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(69).
genre_exists(v0, v1, r) :- years(v2, v0), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(69).
genre(v0, v1) :- years(v0, v2), wikisourcelangProperty(v1, v2), Rule(70).
genre_exists(v0, v1, r) :- years(v0, v2), wikisourcelangProperty(v1, v2), r = 70, Rule(70).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(70).
genre_exists(v0, v1, r) :- years(v0, v2), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(70).
genre(v0, v1) :- years(v0, v2), wikisourcelangProperty(v2, v1), Rule(71).
genre_exists(v0, v1, r) :- years(v0, v2), wikisourcelangProperty(v2, v1), r = 71, Rule(71).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(71).
genre_exists(v0, v1, r) :- years(v0, v2), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(71).
genre(v0, v1) :- years(v2, v1), wikisourcelangProperty(v2, v0), Rule(72).
genre_exists(v0, v1, r) :- years(v2, v1), wikisourcelangProperty(v2, v0), r = 72, Rule(72).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(72).
genre_exists(v0, v1, r) :- years(v2, v1), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(72).
genre(v0, v1) :- years(v1, v2), wikisourcelangProperty(v0, v2), Rule(73).
genre_exists(v0, v1, r) :- years(v1, v2), wikisourcelangProperty(v0, v2), r = 73, Rule(73).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(73).
genre_exists(v0, v1, r) :- years(v1, v2), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(73).
genre(v0, v1) :- years(v0, v1), Igenre(v0, v1), Rule(74).
genre_exists(v0, v1, r) :- years(v0, v1), Igenre(v0, v1), r = 74, Rule(74).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), Igenre(v0, v1), Rule(r), Rule(74).
genre_exists(v0, v1, r) :- years(v0, v1), Igenre_exists(v0, v1, r), Rule(r), Rule(74).
genre(v0, v1) :- years(v0, v1), Igenre(v1, v0), Rule(75).
genre_exists(v0, v1, r) :- years(v0, v1), Igenre(v1, v0), r = 75, Rule(75).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), Igenre(v1, v0), Rule(r), Rule(75).
genre_exists(v0, v1, r) :- years(v0, v1), Igenre_exists(v1, v0, r), Rule(r), Rule(75).
genre(v0, v1) :- years(v1, v0), Igenre(v1, v0), Rule(76).
genre_exists(v0, v1, r) :- years(v1, v0), Igenre(v1, v0), r = 76, Rule(76).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), Igenre(v1, v0), Rule(r), Rule(76).
genre_exists(v0, v1, r) :- years(v1, v0), Igenre_exists(v1, v0, r), Rule(r), Rule(76).
genre(v0, v1) :- years(v1, v0), Igenre(v0, v1), Rule(77).
genre_exists(v0, v1, r) :- years(v1, v0), Igenre(v0, v1), r = 77, Rule(77).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), Igenre(v0, v1), Rule(r), Rule(77).
genre_exists(v0, v1, r) :- years(v1, v0), Igenre_exists(v0, v1, r), Rule(r), Rule(77).
genre(v0, v1) :- years(v2, v1), Igenre(v0, v2), Rule(78).
genre_exists(v0, v1, r) :- years(v2, v1), Igenre(v0, v2), r = 78, Rule(78).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), Igenre(v0, v2), Rule(r), Rule(78).
genre_exists(v0, v1, r) :- years(v2, v1), Igenre_exists(v0, v2, r), Rule(r), Rule(78).
genre(v0, v1) :- years(v1, v2), Igenre(v2, v0), Rule(79).
genre_exists(v0, v1, r) :- years(v1, v2), Igenre(v2, v0), r = 79, Rule(79).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), Igenre(v2, v0), Rule(r), Rule(79).
genre_exists(v0, v1, r) :- years(v1, v2), Igenre_exists(v2, v0, r), Rule(r), Rule(79).
genre(v0, v1) :- years(v2, v0), Igenre(v1, v2), Rule(80).
genre_exists(v0, v1, r) :- years(v2, v0), Igenre(v1, v2), r = 80, Rule(80).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), Igenre(v1, v2), Rule(r), Rule(80).
genre_exists(v0, v1, r) :- years(v2, v0), Igenre_exists(v1, v2, r), Rule(r), Rule(80).
genre(v0, v1) :- years(v2, v0), Igenre(v2, v1), Rule(81).
genre_exists(v0, v1, r) :- years(v2, v0), Igenre(v2, v1), r = 81, Rule(81).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), Igenre(v2, v1), Rule(r), Rule(81).
genre_exists(v0, v1, r) :- years(v2, v0), Igenre_exists(v2, v1, r), Rule(r), Rule(81).
genre(v0, v1) :- years(v0, v2), Igenre(v1, v2), Rule(82).
genre_exists(v0, v1, r) :- years(v0, v2), Igenre(v1, v2), r = 82, Rule(82).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), Igenre(v1, v2), Rule(r), Rule(82).
genre_exists(v0, v1, r) :- years(v0, v2), Igenre_exists(v1, v2, r), Rule(r), Rule(82).
genre(v0, v1) :- years(v0, v2), Igenre(v2, v1), Rule(83).
genre_exists(v0, v1, r) :- years(v0, v2), Igenre(v2, v1), r = 83, Rule(83).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), Igenre(v2, v1), Rule(r), Rule(83).
genre_exists(v0, v1, r) :- years(v0, v2), Igenre_exists(v2, v1, r), Rule(r), Rule(83).
genre(v0, v1) :- years(v2, v1), Igenre(v2, v0), Rule(84).
genre_exists(v0, v1, r) :- years(v2, v1), Igenre(v2, v0), r = 84, Rule(84).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), Igenre(v2, v0), Rule(r), Rule(84).
genre_exists(v0, v1, r) :- years(v2, v1), Igenre_exists(v2, v0, r), Rule(r), Rule(84).
genre(v0, v1) :- years(v1, v2), Igenre(v0, v2), Rule(85).
genre_exists(v0, v1, r) :- years(v1, v2), Igenre(v0, v2), r = 85, Rule(85).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), Igenre(v0, v2), Rule(r), Rule(85).
genre_exists(v0, v1, r) :- years(v1, v2), Igenre_exists(v0, v2, r), Rule(r), Rule(85).
genre(v0, v1) :- years(v0, v1), genre(v0, v1), Rule(86).
genre_exists(v0, v1, r) :- years(v0, v1), genre(v0, v1), r = 86, Rule(86).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), genre(v0, v1), Rule(r), Rule(86).
genre_exists(v0, v1, r) :- years(v0, v1), genre_exists(v0, v1, r), Rule(r), Rule(86).
genre(v0, v1) :- years(v0, v1), genre(v1, v0), Rule(87).
genre_exists(v0, v1, r) :- years(v0, v1), genre(v1, v0), r = 87, Rule(87).
genre_exists(v0, v1, r) :- years_exists(v0, v1, r), genre(v1, v0), Rule(r), Rule(87).
genre_exists(v0, v1, r) :- years(v0, v1), genre_exists(v1, v0, r), Rule(r), Rule(87).
genre(v0, v1) :- years(v1, v0), genre(v1, v0), Rule(88).
genre_exists(v0, v1, r) :- years(v1, v0), genre(v1, v0), r = 88, Rule(88).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), genre(v1, v0), Rule(r), Rule(88).
genre_exists(v0, v1, r) :- years(v1, v0), genre_exists(v1, v0, r), Rule(r), Rule(88).
genre(v0, v1) :- years(v1, v0), genre(v0, v1), Rule(89).
genre_exists(v0, v1, r) :- years(v1, v0), genre(v0, v1), r = 89, Rule(89).
genre_exists(v0, v1, r) :- years_exists(v1, v0, r), genre(v0, v1), Rule(r), Rule(89).
genre_exists(v0, v1, r) :- years(v1, v0), genre_exists(v0, v1, r), Rule(r), Rule(89).
genre(v0, v1) :- years(v2, v1), genre(v0, v2), Rule(90).
genre_exists(v0, v1, r) :- years(v2, v1), genre(v0, v2), r = 90, Rule(90).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), genre(v0, v2), Rule(r), Rule(90).
genre_exists(v0, v1, r) :- years(v2, v1), genre_exists(v0, v2, r), Rule(r), Rule(90).
genre(v0, v1) :- years(v1, v2), genre(v2, v0), Rule(91).
genre_exists(v0, v1, r) :- years(v1, v2), genre(v2, v0), r = 91, Rule(91).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), genre(v2, v0), Rule(r), Rule(91).
genre_exists(v0, v1, r) :- years(v1, v2), genre_exists(v2, v0, r), Rule(r), Rule(91).
genre(v0, v1) :- years(v2, v0), genre(v1, v2), Rule(92).
genre_exists(v0, v1, r) :- years(v2, v0), genre(v1, v2), r = 92, Rule(92).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), genre(v1, v2), Rule(r), Rule(92).
genre_exists(v0, v1, r) :- years(v2, v0), genre_exists(v1, v2, r), Rule(r), Rule(92).
genre(v0, v1) :- years(v2, v0), genre(v2, v1), Rule(93).
genre_exists(v0, v1, r) :- years(v2, v0), genre(v2, v1), r = 93, Rule(93).
genre_exists(v0, v1, r) :- years_exists(v2, v0, r), genre(v2, v1), Rule(r), Rule(93).
genre_exists(v0, v1, r) :- years(v2, v0), genre_exists(v2, v1, r), Rule(r), Rule(93).
genre(v0, v1) :- years(v0, v2), genre(v1, v2), Rule(94).
genre_exists(v0, v1, r) :- years(v0, v2), genre(v1, v2), r = 94, Rule(94).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), genre(v1, v2), Rule(r), Rule(94).
genre_exists(v0, v1, r) :- years(v0, v2), genre_exists(v1, v2, r), Rule(r), Rule(94).
genre(v0, v1) :- years(v0, v2), genre(v2, v1), Rule(95).
genre_exists(v0, v1, r) :- years(v0, v2), genre(v2, v1), r = 95, Rule(95).
genre_exists(v0, v1, r) :- years_exists(v0, v2, r), genre(v2, v1), Rule(r), Rule(95).
genre_exists(v0, v1, r) :- years(v0, v2), genre_exists(v2, v1, r), Rule(r), Rule(95).
genre(v0, v1) :- years(v2, v1), genre(v2, v0), Rule(96).
genre_exists(v0, v1, r) :- years(v2, v1), genre(v2, v0), r = 96, Rule(96).
genre_exists(v0, v1, r) :- years_exists(v2, v1, r), genre(v2, v0), Rule(r), Rule(96).
genre_exists(v0, v1, r) :- years(v2, v1), genre_exists(v2, v0, r), Rule(r), Rule(96).
genre(v0, v1) :- years(v1, v2), genre(v0, v2), Rule(97).
genre_exists(v0, v1, r) :- years(v1, v2), genre(v0, v2), r = 97, Rule(97).
genre_exists(v0, v1, r) :- years_exists(v1, v2, r), genre(v0, v2), Rule(r), Rule(97).
genre_exists(v0, v1, r) :- years(v1, v2), genre_exists(v0, v2, r), Rule(r), Rule(97).
genre(v0, v1) :- yearOfRelease(v0, v1), yearOfRelease(v0, v1), Rule(98).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), yearOfRelease(v0, v1), r = 98, Rule(98).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), yearOfRelease(v0, v1), Rule(r), Rule(98).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), yearOfRelease_exists(v0, v1, r), Rule(r), Rule(98).
genre(v0, v1) :- yearOfRelease(v0, v1), yearOfRelease(v1, v0), Rule(99).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), yearOfRelease(v1, v0), r = 99, Rule(99).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), yearOfRelease(v1, v0), Rule(r), Rule(99).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), yearOfRelease_exists(v1, v0, r), Rule(r), Rule(99).
genre(v0, v1) :- yearOfRelease(v1, v0), yearOfRelease(v1, v0), Rule(100).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), yearOfRelease(v1, v0), r = 100, Rule(100).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), yearOfRelease(v1, v0), Rule(r), Rule(100).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), yearOfRelease_exists(v1, v0, r), Rule(r), Rule(100).
genre(v0, v1) :- yearOfRelease(v1, v0), yearOfRelease(v0, v1), Rule(101).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), yearOfRelease(v0, v1), r = 101, Rule(101).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), yearOfRelease(v0, v1), Rule(r), Rule(101).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), yearOfRelease_exists(v0, v1, r), Rule(r), Rule(101).
genre(v0, v1) :- yearOfRelease(v2, v1), yearOfRelease(v0, v2), Rule(102).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), yearOfRelease(v0, v2), r = 102, Rule(102).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), yearOfRelease(v0, v2), Rule(r), Rule(102).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), yearOfRelease_exists(v0, v2, r), Rule(r), Rule(102).
genre(v0, v1) :- yearOfRelease(v1, v2), yearOfRelease(v2, v0), Rule(103).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), yearOfRelease(v2, v0), r = 103, Rule(103).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), yearOfRelease(v2, v0), Rule(r), Rule(103).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), yearOfRelease_exists(v2, v0, r), Rule(r), Rule(103).
genre(v0, v1) :- yearOfRelease(v2, v0), yearOfRelease(v1, v2), Rule(104).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), yearOfRelease(v1, v2), r = 104, Rule(104).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), yearOfRelease(v1, v2), Rule(r), Rule(104).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), yearOfRelease_exists(v1, v2, r), Rule(r), Rule(104).
genre(v0, v1) :- yearOfRelease(v2, v0), yearOfRelease(v2, v1), Rule(105).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), yearOfRelease(v2, v1), r = 105, Rule(105).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), yearOfRelease(v2, v1), Rule(r), Rule(105).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), yearOfRelease_exists(v2, v1, r), Rule(r), Rule(105).
genre(v0, v1) :- yearOfRelease(v0, v2), yearOfRelease(v1, v2), Rule(106).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), yearOfRelease(v1, v2), r = 106, Rule(106).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), yearOfRelease(v1, v2), Rule(r), Rule(106).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), yearOfRelease_exists(v1, v2, r), Rule(r), Rule(106).
genre(v0, v1) :- yearOfRelease(v0, v2), yearOfRelease(v2, v1), Rule(107).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), yearOfRelease(v2, v1), r = 107, Rule(107).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), yearOfRelease(v2, v1), Rule(r), Rule(107).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), yearOfRelease_exists(v2, v1, r), Rule(r), Rule(107).
genre(v0, v1) :- yearOfRelease(v2, v1), yearOfRelease(v2, v0), Rule(108).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), yearOfRelease(v2, v0), r = 108, Rule(108).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), yearOfRelease(v2, v0), Rule(r), Rule(108).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), yearOfRelease_exists(v2, v0, r), Rule(r), Rule(108).
genre(v0, v1) :- yearOfRelease(v1, v2), yearOfRelease(v0, v2), Rule(109).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), yearOfRelease(v0, v2), r = 109, Rule(109).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), yearOfRelease(v0, v2), Rule(r), Rule(109).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), yearOfRelease_exists(v0, v2, r), Rule(r), Rule(109).
genre(v0, v1) :- yearOfRelease(v0, v1), year(v0, v1), Rule(110).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), year(v0, v1), r = 110, Rule(110).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), year(v0, v1), Rule(r), Rule(110).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), year_exists(v0, v1, r), Rule(r), Rule(110).
genre(v0, v1) :- yearOfRelease(v0, v1), year(v1, v0), Rule(111).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), year(v1, v0), r = 111, Rule(111).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), year(v1, v0), Rule(r), Rule(111).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), year_exists(v1, v0, r), Rule(r), Rule(111).
genre(v0, v1) :- yearOfRelease(v1, v0), year(v1, v0), Rule(112).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), year(v1, v0), r = 112, Rule(112).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), year(v1, v0), Rule(r), Rule(112).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), year_exists(v1, v0, r), Rule(r), Rule(112).
genre(v0, v1) :- yearOfRelease(v1, v0), year(v0, v1), Rule(113).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), year(v0, v1), r = 113, Rule(113).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), year(v0, v1), Rule(r), Rule(113).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), year_exists(v0, v1, r), Rule(r), Rule(113).
genre(v0, v1) :- yearOfRelease(v2, v1), year(v0, v2), Rule(114).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), year(v0, v2), r = 114, Rule(114).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), year(v0, v2), Rule(r), Rule(114).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), year_exists(v0, v2, r), Rule(r), Rule(114).
genre(v0, v1) :- yearOfRelease(v1, v2), year(v2, v0), Rule(115).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), year(v2, v0), r = 115, Rule(115).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), year(v2, v0), Rule(r), Rule(115).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), year_exists(v2, v0, r), Rule(r), Rule(115).
genre(v0, v1) :- yearOfRelease(v2, v0), year(v1, v2), Rule(116).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), year(v1, v2), r = 116, Rule(116).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), year(v1, v2), Rule(r), Rule(116).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), year_exists(v1, v2, r), Rule(r), Rule(116).
genre(v0, v1) :- yearOfRelease(v2, v0), year(v2, v1), Rule(117).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), year(v2, v1), r = 117, Rule(117).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), year(v2, v1), Rule(r), Rule(117).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), year_exists(v2, v1, r), Rule(r), Rule(117).
genre(v0, v1) :- yearOfRelease(v0, v2), year(v1, v2), Rule(118).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), year(v1, v2), r = 118, Rule(118).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), year(v1, v2), Rule(r), Rule(118).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), year_exists(v1, v2, r), Rule(r), Rule(118).
genre(v0, v1) :- yearOfRelease(v0, v2), year(v2, v1), Rule(119).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), year(v2, v1), r = 119, Rule(119).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), year(v2, v1), Rule(r), Rule(119).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), year_exists(v2, v1, r), Rule(r), Rule(119).
genre(v0, v1) :- yearOfRelease(v2, v1), year(v2, v0), Rule(120).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), year(v2, v0), r = 120, Rule(120).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), year(v2, v0), Rule(r), Rule(120).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), year_exists(v2, v0, r), Rule(r), Rule(120).
genre(v0, v1) :- yearOfRelease(v1, v2), year(v0, v2), Rule(121).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), year(v0, v2), r = 121, Rule(121).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), year(v0, v2), Rule(r), Rule(121).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), year_exists(v0, v2, r), Rule(r), Rule(121).
genre(v0, v1) :- yearOfRelease(v0, v1), writer(v0, v1), Rule(122).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), writer(v0, v1), r = 122, Rule(122).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), writer(v0, v1), Rule(r), Rule(122).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), writer_exists(v0, v1, r), Rule(r), Rule(122).
genre(v0, v1) :- yearOfRelease(v0, v1), writer(v1, v0), Rule(123).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), writer(v1, v0), r = 123, Rule(123).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), writer(v1, v0), Rule(r), Rule(123).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), writer_exists(v1, v0, r), Rule(r), Rule(123).
genre(v0, v1) :- yearOfRelease(v1, v0), writer(v1, v0), Rule(124).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), writer(v1, v0), r = 124, Rule(124).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), writer(v1, v0), Rule(r), Rule(124).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), writer_exists(v1, v0, r), Rule(r), Rule(124).
genre(v0, v1) :- yearOfRelease(v1, v0), writer(v0, v1), Rule(125).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), writer(v0, v1), r = 125, Rule(125).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), writer(v0, v1), Rule(r), Rule(125).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), writer_exists(v0, v1, r), Rule(r), Rule(125).
genre(v0, v1) :- yearOfRelease(v2, v1), writer(v0, v2), Rule(126).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), writer(v0, v2), r = 126, Rule(126).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), writer(v0, v2), Rule(r), Rule(126).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), writer_exists(v0, v2, r), Rule(r), Rule(126).
genre(v0, v1) :- yearOfRelease(v1, v2), writer(v2, v0), Rule(127).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), writer(v2, v0), r = 127, Rule(127).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), writer(v2, v0), Rule(r), Rule(127).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), writer_exists(v2, v0, r), Rule(r), Rule(127).
genre(v0, v1) :- yearOfRelease(v2, v0), writer(v1, v2), Rule(128).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), writer(v1, v2), r = 128, Rule(128).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), writer(v1, v2), Rule(r), Rule(128).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), writer_exists(v1, v2, r), Rule(r), Rule(128).
genre(v0, v1) :- yearOfRelease(v2, v0), writer(v2, v1), Rule(129).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), writer(v2, v1), r = 129, Rule(129).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), writer(v2, v1), Rule(r), Rule(129).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), writer_exists(v2, v1, r), Rule(r), Rule(129).
genre(v0, v1) :- yearOfRelease(v0, v2), writer(v1, v2), Rule(130).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), writer(v1, v2), r = 130, Rule(130).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), writer(v1, v2), Rule(r), Rule(130).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), writer_exists(v1, v2, r), Rule(r), Rule(130).
genre(v0, v1) :- yearOfRelease(v0, v2), writer(v2, v1), Rule(131).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), writer(v2, v1), r = 131, Rule(131).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), writer(v2, v1), Rule(r), Rule(131).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), writer_exists(v2, v1, r), Rule(r), Rule(131).
genre(v0, v1) :- yearOfRelease(v2, v1), writer(v2, v0), Rule(132).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), writer(v2, v0), r = 132, Rule(132).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), writer(v2, v0), Rule(r), Rule(132).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), writer_exists(v2, v0, r), Rule(r), Rule(132).
genre(v0, v1) :- yearOfRelease(v1, v2), writer(v0, v2), Rule(133).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), writer(v0, v2), r = 133, Rule(133).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), writer(v0, v2), Rule(r), Rule(133).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), writer_exists(v0, v2, r), Rule(r), Rule(133).
genre(v0, v1) :- yearOfRelease(v0, v1), wikisourcelangProperty(v0, v1), Rule(134).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), wikisourcelangProperty(v0, v1), r = 134, Rule(134).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(134).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(134).
genre(v0, v1) :- yearOfRelease(v0, v1), wikisourcelangProperty(v1, v0), Rule(135).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), wikisourcelangProperty(v1, v0), r = 135, Rule(135).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(135).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(135).
genre(v0, v1) :- yearOfRelease(v1, v0), wikisourcelangProperty(v1, v0), Rule(136).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), wikisourcelangProperty(v1, v0), r = 136, Rule(136).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(136).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(136).
genre(v0, v1) :- yearOfRelease(v1, v0), wikisourcelangProperty(v0, v1), Rule(137).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), wikisourcelangProperty(v0, v1), r = 137, Rule(137).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(137).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(137).
genre(v0, v1) :- yearOfRelease(v2, v1), wikisourcelangProperty(v0, v2), Rule(138).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), wikisourcelangProperty(v0, v2), r = 138, Rule(138).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(138).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(138).
genre(v0, v1) :- yearOfRelease(v1, v2), wikisourcelangProperty(v2, v0), Rule(139).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), wikisourcelangProperty(v2, v0), r = 139, Rule(139).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(139).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(139).
genre(v0, v1) :- yearOfRelease(v2, v0), wikisourcelangProperty(v1, v2), Rule(140).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), wikisourcelangProperty(v1, v2), r = 140, Rule(140).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(140).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(140).
genre(v0, v1) :- yearOfRelease(v2, v0), wikisourcelangProperty(v2, v1), Rule(141).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), wikisourcelangProperty(v2, v1), r = 141, Rule(141).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(141).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(141).
genre(v0, v1) :- yearOfRelease(v0, v2), wikisourcelangProperty(v1, v2), Rule(142).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), wikisourcelangProperty(v1, v2), r = 142, Rule(142).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(142).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(142).
genre(v0, v1) :- yearOfRelease(v0, v2), wikisourcelangProperty(v2, v1), Rule(143).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), wikisourcelangProperty(v2, v1), r = 143, Rule(143).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(143).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(143).
genre(v0, v1) :- yearOfRelease(v2, v1), wikisourcelangProperty(v2, v0), Rule(144).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), wikisourcelangProperty(v2, v0), r = 144, Rule(144).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(144).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(144).
genre(v0, v1) :- yearOfRelease(v1, v2), wikisourcelangProperty(v0, v2), Rule(145).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), wikisourcelangProperty(v0, v2), r = 145, Rule(145).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(145).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(145).
genre(v0, v1) :- yearOfRelease(v0, v1), Igenre(v0, v1), Rule(146).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), Igenre(v0, v1), r = 146, Rule(146).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), Igenre(v0, v1), Rule(r), Rule(146).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), Igenre_exists(v0, v1, r), Rule(r), Rule(146).
genre(v0, v1) :- yearOfRelease(v0, v1), Igenre(v1, v0), Rule(147).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), Igenre(v1, v0), r = 147, Rule(147).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), Igenre(v1, v0), Rule(r), Rule(147).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), Igenre_exists(v1, v0, r), Rule(r), Rule(147).
genre(v0, v1) :- yearOfRelease(v1, v0), Igenre(v1, v0), Rule(148).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), Igenre(v1, v0), r = 148, Rule(148).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), Igenre(v1, v0), Rule(r), Rule(148).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), Igenre_exists(v1, v0, r), Rule(r), Rule(148).
genre(v0, v1) :- yearOfRelease(v1, v0), Igenre(v0, v1), Rule(149).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), Igenre(v0, v1), r = 149, Rule(149).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), Igenre(v0, v1), Rule(r), Rule(149).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), Igenre_exists(v0, v1, r), Rule(r), Rule(149).
genre(v0, v1) :- yearOfRelease(v2, v1), Igenre(v0, v2), Rule(150).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), Igenre(v0, v2), r = 150, Rule(150).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), Igenre(v0, v2), Rule(r), Rule(150).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), Igenre_exists(v0, v2, r), Rule(r), Rule(150).
genre(v0, v1) :- yearOfRelease(v1, v2), Igenre(v2, v0), Rule(151).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), Igenre(v2, v0), r = 151, Rule(151).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), Igenre(v2, v0), Rule(r), Rule(151).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), Igenre_exists(v2, v0, r), Rule(r), Rule(151).
genre(v0, v1) :- yearOfRelease(v2, v0), Igenre(v1, v2), Rule(152).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), Igenre(v1, v2), r = 152, Rule(152).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), Igenre(v1, v2), Rule(r), Rule(152).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), Igenre_exists(v1, v2, r), Rule(r), Rule(152).
genre(v0, v1) :- yearOfRelease(v2, v0), Igenre(v2, v1), Rule(153).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), Igenre(v2, v1), r = 153, Rule(153).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), Igenre(v2, v1), Rule(r), Rule(153).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), Igenre_exists(v2, v1, r), Rule(r), Rule(153).
genre(v0, v1) :- yearOfRelease(v0, v2), Igenre(v1, v2), Rule(154).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), Igenre(v1, v2), r = 154, Rule(154).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), Igenre(v1, v2), Rule(r), Rule(154).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), Igenre_exists(v1, v2, r), Rule(r), Rule(154).
genre(v0, v1) :- yearOfRelease(v0, v2), Igenre(v2, v1), Rule(155).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), Igenre(v2, v1), r = 155, Rule(155).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), Igenre(v2, v1), Rule(r), Rule(155).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), Igenre_exists(v2, v1, r), Rule(r), Rule(155).
genre(v0, v1) :- yearOfRelease(v2, v1), Igenre(v2, v0), Rule(156).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), Igenre(v2, v0), r = 156, Rule(156).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), Igenre(v2, v0), Rule(r), Rule(156).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), Igenre_exists(v2, v0, r), Rule(r), Rule(156).
genre(v0, v1) :- yearOfRelease(v1, v2), Igenre(v0, v2), Rule(157).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), Igenre(v0, v2), r = 157, Rule(157).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), Igenre(v0, v2), Rule(r), Rule(157).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), Igenre_exists(v0, v2, r), Rule(r), Rule(157).
genre(v0, v1) :- yearOfRelease(v0, v1), genre(v0, v1), Rule(158).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), genre(v0, v1), r = 158, Rule(158).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), genre(v0, v1), Rule(r), Rule(158).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), genre_exists(v0, v1, r), Rule(r), Rule(158).
genre(v0, v1) :- yearOfRelease(v0, v1), genre(v1, v0), Rule(159).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), genre(v1, v0), r = 159, Rule(159).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v1, r), genre(v1, v0), Rule(r), Rule(159).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v1), genre_exists(v1, v0, r), Rule(r), Rule(159).
genre(v0, v1) :- yearOfRelease(v1, v0), genre(v1, v0), Rule(160).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), genre(v1, v0), r = 160, Rule(160).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), genre(v1, v0), Rule(r), Rule(160).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), genre_exists(v1, v0, r), Rule(r), Rule(160).
genre(v0, v1) :- yearOfRelease(v1, v0), genre(v0, v1), Rule(161).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), genre(v0, v1), r = 161, Rule(161).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v0, r), genre(v0, v1), Rule(r), Rule(161).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v0), genre_exists(v0, v1, r), Rule(r), Rule(161).
genre(v0, v1) :- yearOfRelease(v2, v1), genre(v0, v2), Rule(162).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), genre(v0, v2), r = 162, Rule(162).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), genre(v0, v2), Rule(r), Rule(162).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), genre_exists(v0, v2, r), Rule(r), Rule(162).
genre(v0, v1) :- yearOfRelease(v1, v2), genre(v2, v0), Rule(163).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), genre(v2, v0), r = 163, Rule(163).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), genre(v2, v0), Rule(r), Rule(163).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), genre_exists(v2, v0, r), Rule(r), Rule(163).
genre(v0, v1) :- yearOfRelease(v2, v0), genre(v1, v2), Rule(164).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), genre(v1, v2), r = 164, Rule(164).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), genre(v1, v2), Rule(r), Rule(164).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), genre_exists(v1, v2, r), Rule(r), Rule(164).
genre(v0, v1) :- yearOfRelease(v2, v0), genre(v2, v1), Rule(165).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), genre(v2, v1), r = 165, Rule(165).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v0, r), genre(v2, v1), Rule(r), Rule(165).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v0), genre_exists(v2, v1, r), Rule(r), Rule(165).
genre(v0, v1) :- yearOfRelease(v0, v2), genre(v1, v2), Rule(166).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), genre(v1, v2), r = 166, Rule(166).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), genre(v1, v2), Rule(r), Rule(166).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), genre_exists(v1, v2, r), Rule(r), Rule(166).
genre(v0, v1) :- yearOfRelease(v0, v2), genre(v2, v1), Rule(167).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), genre(v2, v1), r = 167, Rule(167).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v0, v2, r), genre(v2, v1), Rule(r), Rule(167).
genre_exists(v0, v1, r) :- yearOfRelease(v0, v2), genre_exists(v2, v1, r), Rule(r), Rule(167).
genre(v0, v1) :- yearOfRelease(v2, v1), genre(v2, v0), Rule(168).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), genre(v2, v0), r = 168, Rule(168).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v2, v1, r), genre(v2, v0), Rule(r), Rule(168).
genre_exists(v0, v1, r) :- yearOfRelease(v2, v1), genre_exists(v2, v0, r), Rule(r), Rule(168).
genre(v0, v1) :- yearOfRelease(v1, v2), genre(v0, v2), Rule(169).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), genre(v0, v2), r = 169, Rule(169).
genre_exists(v0, v1, r) :- yearOfRelease_exists(v1, v2, r), genre(v0, v2), Rule(r), Rule(169).
genre_exists(v0, v1, r) :- yearOfRelease(v1, v2), genre_exists(v0, v2, r), Rule(r), Rule(169).
genre(v0, v1) :- year(v0, v1), year(v0, v1), Rule(170).
genre_exists(v0, v1, r) :- year(v0, v1), year(v0, v1), r = 170, Rule(170).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), year(v0, v1), Rule(r), Rule(170).
genre_exists(v0, v1, r) :- year(v0, v1), year_exists(v0, v1, r), Rule(r), Rule(170).
genre(v0, v1) :- year(v0, v1), year(v1, v0), Rule(171).
genre_exists(v0, v1, r) :- year(v0, v1), year(v1, v0), r = 171, Rule(171).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), year(v1, v0), Rule(r), Rule(171).
genre_exists(v0, v1, r) :- year(v0, v1), year_exists(v1, v0, r), Rule(r), Rule(171).
genre(v0, v1) :- year(v1, v0), year(v1, v0), Rule(172).
genre_exists(v0, v1, r) :- year(v1, v0), year(v1, v0), r = 172, Rule(172).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), year(v1, v0), Rule(r), Rule(172).
genre_exists(v0, v1, r) :- year(v1, v0), year_exists(v1, v0, r), Rule(r), Rule(172).
genre(v0, v1) :- year(v1, v0), year(v0, v1), Rule(173).
genre_exists(v0, v1, r) :- year(v1, v0), year(v0, v1), r = 173, Rule(173).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), year(v0, v1), Rule(r), Rule(173).
genre_exists(v0, v1, r) :- year(v1, v0), year_exists(v0, v1, r), Rule(r), Rule(173).
genre(v0, v1) :- year(v2, v1), year(v0, v2), Rule(174).
genre_exists(v0, v1, r) :- year(v2, v1), year(v0, v2), r = 174, Rule(174).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), year(v0, v2), Rule(r), Rule(174).
genre_exists(v0, v1, r) :- year(v2, v1), year_exists(v0, v2, r), Rule(r), Rule(174).
genre(v0, v1) :- year(v1, v2), year(v2, v0), Rule(175).
genre_exists(v0, v1, r) :- year(v1, v2), year(v2, v0), r = 175, Rule(175).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), year(v2, v0), Rule(r), Rule(175).
genre_exists(v0, v1, r) :- year(v1, v2), year_exists(v2, v0, r), Rule(r), Rule(175).
genre(v0, v1) :- year(v2, v0), year(v1, v2), Rule(176).
genre_exists(v0, v1, r) :- year(v2, v0), year(v1, v2), r = 176, Rule(176).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), year(v1, v2), Rule(r), Rule(176).
genre_exists(v0, v1, r) :- year(v2, v0), year_exists(v1, v2, r), Rule(r), Rule(176).
genre(v0, v1) :- year(v2, v0), year(v2, v1), Rule(177).
genre_exists(v0, v1, r) :- year(v2, v0), year(v2, v1), r = 177, Rule(177).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), year(v2, v1), Rule(r), Rule(177).
genre_exists(v0, v1, r) :- year(v2, v0), year_exists(v2, v1, r), Rule(r), Rule(177).
genre(v0, v1) :- year(v0, v2), year(v1, v2), Rule(178).
genre_exists(v0, v1, r) :- year(v0, v2), year(v1, v2), r = 178, Rule(178).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), year(v1, v2), Rule(r), Rule(178).
genre_exists(v0, v1, r) :- year(v0, v2), year_exists(v1, v2, r), Rule(r), Rule(178).
genre(v0, v1) :- year(v0, v2), year(v2, v1), Rule(179).
genre_exists(v0, v1, r) :- year(v0, v2), year(v2, v1), r = 179, Rule(179).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), year(v2, v1), Rule(r), Rule(179).
genre_exists(v0, v1, r) :- year(v0, v2), year_exists(v2, v1, r), Rule(r), Rule(179).
genre(v0, v1) :- year(v2, v1), year(v2, v0), Rule(180).
genre_exists(v0, v1, r) :- year(v2, v1), year(v2, v0), r = 180, Rule(180).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), year(v2, v0), Rule(r), Rule(180).
genre_exists(v0, v1, r) :- year(v2, v1), year_exists(v2, v0, r), Rule(r), Rule(180).
genre(v0, v1) :- year(v1, v2), year(v0, v2), Rule(181).
genre_exists(v0, v1, r) :- year(v1, v2), year(v0, v2), r = 181, Rule(181).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), year(v0, v2), Rule(r), Rule(181).
genre_exists(v0, v1, r) :- year(v1, v2), year_exists(v0, v2, r), Rule(r), Rule(181).
genre(v0, v1) :- year(v0, v1), writer(v0, v1), Rule(182).
genre_exists(v0, v1, r) :- year(v0, v1), writer(v0, v1), r = 182, Rule(182).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), writer(v0, v1), Rule(r), Rule(182).
genre_exists(v0, v1, r) :- year(v0, v1), writer_exists(v0, v1, r), Rule(r), Rule(182).
genre(v0, v1) :- year(v0, v1), writer(v1, v0), Rule(183).
genre_exists(v0, v1, r) :- year(v0, v1), writer(v1, v0), r = 183, Rule(183).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), writer(v1, v0), Rule(r), Rule(183).
genre_exists(v0, v1, r) :- year(v0, v1), writer_exists(v1, v0, r), Rule(r), Rule(183).
genre(v0, v1) :- year(v1, v0), writer(v1, v0), Rule(184).
genre_exists(v0, v1, r) :- year(v1, v0), writer(v1, v0), r = 184, Rule(184).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), writer(v1, v0), Rule(r), Rule(184).
genre_exists(v0, v1, r) :- year(v1, v0), writer_exists(v1, v0, r), Rule(r), Rule(184).
genre(v0, v1) :- year(v1, v0), writer(v0, v1), Rule(185).
genre_exists(v0, v1, r) :- year(v1, v0), writer(v0, v1), r = 185, Rule(185).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), writer(v0, v1), Rule(r), Rule(185).
genre_exists(v0, v1, r) :- year(v1, v0), writer_exists(v0, v1, r), Rule(r), Rule(185).
genre(v0, v1) :- year(v2, v1), writer(v0, v2), Rule(186).
genre_exists(v0, v1, r) :- year(v2, v1), writer(v0, v2), r = 186, Rule(186).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), writer(v0, v2), Rule(r), Rule(186).
genre_exists(v0, v1, r) :- year(v2, v1), writer_exists(v0, v2, r), Rule(r), Rule(186).
genre(v0, v1) :- year(v1, v2), writer(v2, v0), Rule(187).
genre_exists(v0, v1, r) :- year(v1, v2), writer(v2, v0), r = 187, Rule(187).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), writer(v2, v0), Rule(r), Rule(187).
genre_exists(v0, v1, r) :- year(v1, v2), writer_exists(v2, v0, r), Rule(r), Rule(187).
genre(v0, v1) :- year(v2, v0), writer(v1, v2), Rule(188).
genre_exists(v0, v1, r) :- year(v2, v0), writer(v1, v2), r = 188, Rule(188).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), writer(v1, v2), Rule(r), Rule(188).
genre_exists(v0, v1, r) :- year(v2, v0), writer_exists(v1, v2, r), Rule(r), Rule(188).
genre(v0, v1) :- year(v2, v0), writer(v2, v1), Rule(189).
genre_exists(v0, v1, r) :- year(v2, v0), writer(v2, v1), r = 189, Rule(189).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), writer(v2, v1), Rule(r), Rule(189).
genre_exists(v0, v1, r) :- year(v2, v0), writer_exists(v2, v1, r), Rule(r), Rule(189).
genre(v0, v1) :- year(v0, v2), writer(v1, v2), Rule(190).
genre_exists(v0, v1, r) :- year(v0, v2), writer(v1, v2), r = 190, Rule(190).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), writer(v1, v2), Rule(r), Rule(190).
genre_exists(v0, v1, r) :- year(v0, v2), writer_exists(v1, v2, r), Rule(r), Rule(190).
genre(v0, v1) :- year(v0, v2), writer(v2, v1), Rule(191).
genre_exists(v0, v1, r) :- year(v0, v2), writer(v2, v1), r = 191, Rule(191).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), writer(v2, v1), Rule(r), Rule(191).
genre_exists(v0, v1, r) :- year(v0, v2), writer_exists(v2, v1, r), Rule(r), Rule(191).
genre(v0, v1) :- year(v2, v1), writer(v2, v0), Rule(192).
genre_exists(v0, v1, r) :- year(v2, v1), writer(v2, v0), r = 192, Rule(192).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), writer(v2, v0), Rule(r), Rule(192).
genre_exists(v0, v1, r) :- year(v2, v1), writer_exists(v2, v0, r), Rule(r), Rule(192).
genre(v0, v1) :- year(v1, v2), writer(v0, v2), Rule(193).
genre_exists(v0, v1, r) :- year(v1, v2), writer(v0, v2), r = 193, Rule(193).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), writer(v0, v2), Rule(r), Rule(193).
genre_exists(v0, v1, r) :- year(v1, v2), writer_exists(v0, v2, r), Rule(r), Rule(193).
genre(v0, v1) :- year(v0, v1), wikisourcelangProperty(v0, v1), Rule(194).
genre_exists(v0, v1, r) :- year(v0, v1), wikisourcelangProperty(v0, v1), r = 194, Rule(194).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(194).
genre_exists(v0, v1, r) :- year(v0, v1), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(194).
genre(v0, v1) :- year(v0, v1), wikisourcelangProperty(v1, v0), Rule(195).
genre_exists(v0, v1, r) :- year(v0, v1), wikisourcelangProperty(v1, v0), r = 195, Rule(195).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(195).
genre_exists(v0, v1, r) :- year(v0, v1), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(195).
genre(v0, v1) :- year(v1, v0), wikisourcelangProperty(v1, v0), Rule(196).
genre_exists(v0, v1, r) :- year(v1, v0), wikisourcelangProperty(v1, v0), r = 196, Rule(196).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(196).
genre_exists(v0, v1, r) :- year(v1, v0), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(196).
genre(v0, v1) :- year(v1, v0), wikisourcelangProperty(v0, v1), Rule(197).
genre_exists(v0, v1, r) :- year(v1, v0), wikisourcelangProperty(v0, v1), r = 197, Rule(197).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(197).
genre_exists(v0, v1, r) :- year(v1, v0), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(197).
genre(v0, v1) :- year(v2, v1), wikisourcelangProperty(v0, v2), Rule(198).
genre_exists(v0, v1, r) :- year(v2, v1), wikisourcelangProperty(v0, v2), r = 198, Rule(198).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(198).
genre_exists(v0, v1, r) :- year(v2, v1), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(198).
genre(v0, v1) :- year(v1, v2), wikisourcelangProperty(v2, v0), Rule(199).
genre_exists(v0, v1, r) :- year(v1, v2), wikisourcelangProperty(v2, v0), r = 199, Rule(199).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(199).
genre_exists(v0, v1, r) :- year(v1, v2), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(199).
genre(v0, v1) :- year(v2, v0), wikisourcelangProperty(v1, v2), Rule(200).
genre_exists(v0, v1, r) :- year(v2, v0), wikisourcelangProperty(v1, v2), r = 200, Rule(200).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(200).
genre_exists(v0, v1, r) :- year(v2, v0), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(200).
genre(v0, v1) :- year(v2, v0), wikisourcelangProperty(v2, v1), Rule(201).
genre_exists(v0, v1, r) :- year(v2, v0), wikisourcelangProperty(v2, v1), r = 201, Rule(201).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(201).
genre_exists(v0, v1, r) :- year(v2, v0), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(201).
genre(v0, v1) :- year(v0, v2), wikisourcelangProperty(v1, v2), Rule(202).
genre_exists(v0, v1, r) :- year(v0, v2), wikisourcelangProperty(v1, v2), r = 202, Rule(202).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(202).
genre_exists(v0, v1, r) :- year(v0, v2), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(202).
genre(v0, v1) :- year(v0, v2), wikisourcelangProperty(v2, v1), Rule(203).
genre_exists(v0, v1, r) :- year(v0, v2), wikisourcelangProperty(v2, v1), r = 203, Rule(203).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(203).
genre_exists(v0, v1, r) :- year(v0, v2), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(203).
genre(v0, v1) :- year(v2, v1), wikisourcelangProperty(v2, v0), Rule(204).
genre_exists(v0, v1, r) :- year(v2, v1), wikisourcelangProperty(v2, v0), r = 204, Rule(204).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(204).
genre_exists(v0, v1, r) :- year(v2, v1), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(204).
genre(v0, v1) :- year(v1, v2), wikisourcelangProperty(v0, v2), Rule(205).
genre_exists(v0, v1, r) :- year(v1, v2), wikisourcelangProperty(v0, v2), r = 205, Rule(205).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(205).
genre_exists(v0, v1, r) :- year(v1, v2), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(205).
genre(v0, v1) :- year(v0, v1), Igenre(v0, v1), Rule(206).
genre_exists(v0, v1, r) :- year(v0, v1), Igenre(v0, v1), r = 206, Rule(206).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), Igenre(v0, v1), Rule(r), Rule(206).
genre_exists(v0, v1, r) :- year(v0, v1), Igenre_exists(v0, v1, r), Rule(r), Rule(206).
genre(v0, v1) :- year(v0, v1), Igenre(v1, v0), Rule(207).
genre_exists(v0, v1, r) :- year(v0, v1), Igenre(v1, v0), r = 207, Rule(207).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), Igenre(v1, v0), Rule(r), Rule(207).
genre_exists(v0, v1, r) :- year(v0, v1), Igenre_exists(v1, v0, r), Rule(r), Rule(207).
genre(v0, v1) :- year(v1, v0), Igenre(v1, v0), Rule(208).
genre_exists(v0, v1, r) :- year(v1, v0), Igenre(v1, v0), r = 208, Rule(208).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), Igenre(v1, v0), Rule(r), Rule(208).
genre_exists(v0, v1, r) :- year(v1, v0), Igenre_exists(v1, v0, r), Rule(r), Rule(208).
genre(v0, v1) :- year(v1, v0), Igenre(v0, v1), Rule(209).
genre_exists(v0, v1, r) :- year(v1, v0), Igenre(v0, v1), r = 209, Rule(209).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), Igenre(v0, v1), Rule(r), Rule(209).
genre_exists(v0, v1, r) :- year(v1, v0), Igenre_exists(v0, v1, r), Rule(r), Rule(209).
genre(v0, v1) :- year(v2, v1), Igenre(v0, v2), Rule(210).
genre_exists(v0, v1, r) :- year(v2, v1), Igenre(v0, v2), r = 210, Rule(210).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), Igenre(v0, v2), Rule(r), Rule(210).
genre_exists(v0, v1, r) :- year(v2, v1), Igenre_exists(v0, v2, r), Rule(r), Rule(210).
genre(v0, v1) :- year(v1, v2), Igenre(v2, v0), Rule(211).
genre_exists(v0, v1, r) :- year(v1, v2), Igenre(v2, v0), r = 211, Rule(211).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), Igenre(v2, v0), Rule(r), Rule(211).
genre_exists(v0, v1, r) :- year(v1, v2), Igenre_exists(v2, v0, r), Rule(r), Rule(211).
genre(v0, v1) :- year(v2, v0), Igenre(v1, v2), Rule(212).
genre_exists(v0, v1, r) :- year(v2, v0), Igenre(v1, v2), r = 212, Rule(212).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), Igenre(v1, v2), Rule(r), Rule(212).
genre_exists(v0, v1, r) :- year(v2, v0), Igenre_exists(v1, v2, r), Rule(r), Rule(212).
genre(v0, v1) :- year(v2, v0), Igenre(v2, v1), Rule(213).
genre_exists(v0, v1, r) :- year(v2, v0), Igenre(v2, v1), r = 213, Rule(213).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), Igenre(v2, v1), Rule(r), Rule(213).
genre_exists(v0, v1, r) :- year(v2, v0), Igenre_exists(v2, v1, r), Rule(r), Rule(213).
genre(v0, v1) :- year(v0, v2), Igenre(v1, v2), Rule(214).
genre_exists(v0, v1, r) :- year(v0, v2), Igenre(v1, v2), r = 214, Rule(214).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), Igenre(v1, v2), Rule(r), Rule(214).
genre_exists(v0, v1, r) :- year(v0, v2), Igenre_exists(v1, v2, r), Rule(r), Rule(214).
genre(v0, v1) :- year(v0, v2), Igenre(v2, v1), Rule(215).
genre_exists(v0, v1, r) :- year(v0, v2), Igenre(v2, v1), r = 215, Rule(215).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), Igenre(v2, v1), Rule(r), Rule(215).
genre_exists(v0, v1, r) :- year(v0, v2), Igenre_exists(v2, v1, r), Rule(r), Rule(215).
genre(v0, v1) :- year(v2, v1), Igenre(v2, v0), Rule(216).
genre_exists(v0, v1, r) :- year(v2, v1), Igenre(v2, v0), r = 216, Rule(216).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), Igenre(v2, v0), Rule(r), Rule(216).
genre_exists(v0, v1, r) :- year(v2, v1), Igenre_exists(v2, v0, r), Rule(r), Rule(216).
genre(v0, v1) :- year(v1, v2), Igenre(v0, v2), Rule(217).
genre_exists(v0, v1, r) :- year(v1, v2), Igenre(v0, v2), r = 217, Rule(217).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), Igenre(v0, v2), Rule(r), Rule(217).
genre_exists(v0, v1, r) :- year(v1, v2), Igenre_exists(v0, v2, r), Rule(r), Rule(217).
genre(v0, v1) :- year(v0, v1), genre(v0, v1), Rule(218).
genre_exists(v0, v1, r) :- year(v0, v1), genre(v0, v1), r = 218, Rule(218).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), genre(v0, v1), Rule(r), Rule(218).
genre_exists(v0, v1, r) :- year(v0, v1), genre_exists(v0, v1, r), Rule(r), Rule(218).
genre(v0, v1) :- year(v0, v1), genre(v1, v0), Rule(219).
genre_exists(v0, v1, r) :- year(v0, v1), genre(v1, v0), r = 219, Rule(219).
genre_exists(v0, v1, r) :- year_exists(v0, v1, r), genre(v1, v0), Rule(r), Rule(219).
genre_exists(v0, v1, r) :- year(v0, v1), genre_exists(v1, v0, r), Rule(r), Rule(219).
genre(v0, v1) :- year(v1, v0), genre(v1, v0), Rule(220).
genre_exists(v0, v1, r) :- year(v1, v0), genre(v1, v0), r = 220, Rule(220).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), genre(v1, v0), Rule(r), Rule(220).
genre_exists(v0, v1, r) :- year(v1, v0), genre_exists(v1, v0, r), Rule(r), Rule(220).
genre(v0, v1) :- year(v1, v0), genre(v0, v1), Rule(221).
genre_exists(v0, v1, r) :- year(v1, v0), genre(v0, v1), r = 221, Rule(221).
genre_exists(v0, v1, r) :- year_exists(v1, v0, r), genre(v0, v1), Rule(r), Rule(221).
genre_exists(v0, v1, r) :- year(v1, v0), genre_exists(v0, v1, r), Rule(r), Rule(221).
genre(v0, v1) :- year(v2, v1), genre(v0, v2), Rule(222).
genre_exists(v0, v1, r) :- year(v2, v1), genre(v0, v2), r = 222, Rule(222).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), genre(v0, v2), Rule(r), Rule(222).
genre_exists(v0, v1, r) :- year(v2, v1), genre_exists(v0, v2, r), Rule(r), Rule(222).
genre(v0, v1) :- year(v1, v2), genre(v2, v0), Rule(223).
genre_exists(v0, v1, r) :- year(v1, v2), genre(v2, v0), r = 223, Rule(223).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), genre(v2, v0), Rule(r), Rule(223).
genre_exists(v0, v1, r) :- year(v1, v2), genre_exists(v2, v0, r), Rule(r), Rule(223).
genre(v0, v1) :- year(v2, v0), genre(v1, v2), Rule(224).
genre_exists(v0, v1, r) :- year(v2, v0), genre(v1, v2), r = 224, Rule(224).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), genre(v1, v2), Rule(r), Rule(224).
genre_exists(v0, v1, r) :- year(v2, v0), genre_exists(v1, v2, r), Rule(r), Rule(224).
genre(v0, v1) :- year(v2, v0), genre(v2, v1), Rule(225).
genre_exists(v0, v1, r) :- year(v2, v0), genre(v2, v1), r = 225, Rule(225).
genre_exists(v0, v1, r) :- year_exists(v2, v0, r), genre(v2, v1), Rule(r), Rule(225).
genre_exists(v0, v1, r) :- year(v2, v0), genre_exists(v2, v1, r), Rule(r), Rule(225).
genre(v0, v1) :- year(v0, v2), genre(v1, v2), Rule(226).
genre_exists(v0, v1, r) :- year(v0, v2), genre(v1, v2), r = 226, Rule(226).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), genre(v1, v2), Rule(r), Rule(226).
genre_exists(v0, v1, r) :- year(v0, v2), genre_exists(v1, v2, r), Rule(r), Rule(226).
genre(v0, v1) :- year(v0, v2), genre(v2, v1), Rule(227).
genre_exists(v0, v1, r) :- year(v0, v2), genre(v2, v1), r = 227, Rule(227).
genre_exists(v0, v1, r) :- year_exists(v0, v2, r), genre(v2, v1), Rule(r), Rule(227).
genre_exists(v0, v1, r) :- year(v0, v2), genre_exists(v2, v1, r), Rule(r), Rule(227).
genre(v0, v1) :- year(v2, v1), genre(v2, v0), Rule(228).
genre_exists(v0, v1, r) :- year(v2, v1), genre(v2, v0), r = 228, Rule(228).
genre_exists(v0, v1, r) :- year_exists(v2, v1, r), genre(v2, v0), Rule(r), Rule(228).
genre_exists(v0, v1, r) :- year(v2, v1), genre_exists(v2, v0, r), Rule(r), Rule(228).
genre(v0, v1) :- year(v1, v2), genre(v0, v2), Rule(229).
genre_exists(v0, v1, r) :- year(v1, v2), genre(v0, v2), r = 229, Rule(229).
genre_exists(v0, v1, r) :- year_exists(v1, v2, r), genre(v0, v2), Rule(r), Rule(229).
genre_exists(v0, v1, r) :- year(v1, v2), genre_exists(v0, v2, r), Rule(r), Rule(229).
genre(v0, v1) :- writer(v0, v1), writer(v0, v1), Rule(230).
genre_exists(v0, v1, r) :- writer(v0, v1), writer(v0, v1), r = 230, Rule(230).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), writer(v0, v1), Rule(r), Rule(230).
genre_exists(v0, v1, r) :- writer(v0, v1), writer_exists(v0, v1, r), Rule(r), Rule(230).
genre(v0, v1) :- writer(v0, v1), writer(v1, v0), Rule(231).
genre_exists(v0, v1, r) :- writer(v0, v1), writer(v1, v0), r = 231, Rule(231).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), writer(v1, v0), Rule(r), Rule(231).
genre_exists(v0, v1, r) :- writer(v0, v1), writer_exists(v1, v0, r), Rule(r), Rule(231).
genre(v0, v1) :- writer(v1, v0), writer(v1, v0), Rule(232).
genre_exists(v0, v1, r) :- writer(v1, v0), writer(v1, v0), r = 232, Rule(232).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), writer(v1, v0), Rule(r), Rule(232).
genre_exists(v0, v1, r) :- writer(v1, v0), writer_exists(v1, v0, r), Rule(r), Rule(232).
genre(v0, v1) :- writer(v1, v0), writer(v0, v1), Rule(233).
genre_exists(v0, v1, r) :- writer(v1, v0), writer(v0, v1), r = 233, Rule(233).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), writer(v0, v1), Rule(r), Rule(233).
genre_exists(v0, v1, r) :- writer(v1, v0), writer_exists(v0, v1, r), Rule(r), Rule(233).
genre(v0, v1) :- writer(v2, v1), writer(v0, v2), Rule(234).
genre_exists(v0, v1, r) :- writer(v2, v1), writer(v0, v2), r = 234, Rule(234).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), writer(v0, v2), Rule(r), Rule(234).
genre_exists(v0, v1, r) :- writer(v2, v1), writer_exists(v0, v2, r), Rule(r), Rule(234).
genre(v0, v1) :- writer(v1, v2), writer(v2, v0), Rule(235).
genre_exists(v0, v1, r) :- writer(v1, v2), writer(v2, v0), r = 235, Rule(235).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), writer(v2, v0), Rule(r), Rule(235).
genre_exists(v0, v1, r) :- writer(v1, v2), writer_exists(v2, v0, r), Rule(r), Rule(235).
genre(v0, v1) :- writer(v2, v0), writer(v1, v2), Rule(236).
genre_exists(v0, v1, r) :- writer(v2, v0), writer(v1, v2), r = 236, Rule(236).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), writer(v1, v2), Rule(r), Rule(236).
genre_exists(v0, v1, r) :- writer(v2, v0), writer_exists(v1, v2, r), Rule(r), Rule(236).
genre(v0, v1) :- writer(v2, v0), writer(v2, v1), Rule(237).
genre_exists(v0, v1, r) :- writer(v2, v0), writer(v2, v1), r = 237, Rule(237).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), writer(v2, v1), Rule(r), Rule(237).
genre_exists(v0, v1, r) :- writer(v2, v0), writer_exists(v2, v1, r), Rule(r), Rule(237).
genre(v0, v1) :- writer(v0, v2), writer(v1, v2), Rule(238).
genre_exists(v0, v1, r) :- writer(v0, v2), writer(v1, v2), r = 238, Rule(238).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), writer(v1, v2), Rule(r), Rule(238).
genre_exists(v0, v1, r) :- writer(v0, v2), writer_exists(v1, v2, r), Rule(r), Rule(238).
genre(v0, v1) :- writer(v0, v2), writer(v2, v1), Rule(239).
genre_exists(v0, v1, r) :- writer(v0, v2), writer(v2, v1), r = 239, Rule(239).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), writer(v2, v1), Rule(r), Rule(239).
genre_exists(v0, v1, r) :- writer(v0, v2), writer_exists(v2, v1, r), Rule(r), Rule(239).
genre(v0, v1) :- writer(v2, v1), writer(v2, v0), Rule(240).
genre_exists(v0, v1, r) :- writer(v2, v1), writer(v2, v0), r = 240, Rule(240).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), writer(v2, v0), Rule(r), Rule(240).
genre_exists(v0, v1, r) :- writer(v2, v1), writer_exists(v2, v0, r), Rule(r), Rule(240).
genre(v0, v1) :- writer(v1, v2), writer(v0, v2), Rule(241).
genre_exists(v0, v1, r) :- writer(v1, v2), writer(v0, v2), r = 241, Rule(241).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), writer(v0, v2), Rule(r), Rule(241).
genre_exists(v0, v1, r) :- writer(v1, v2), writer_exists(v0, v2, r), Rule(r), Rule(241).
genre(v0, v1) :- writer(v0, v1), wikisourcelangProperty(v0, v1), Rule(242).
genre_exists(v0, v1, r) :- writer(v0, v1), wikisourcelangProperty(v0, v1), r = 242, Rule(242).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(242).
genre_exists(v0, v1, r) :- writer(v0, v1), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(242).
genre(v0, v1) :- writer(v0, v1), wikisourcelangProperty(v1, v0), Rule(243).
genre_exists(v0, v1, r) :- writer(v0, v1), wikisourcelangProperty(v1, v0), r = 243, Rule(243).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(243).
genre_exists(v0, v1, r) :- writer(v0, v1), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(243).
genre(v0, v1) :- writer(v1, v0), wikisourcelangProperty(v1, v0), Rule(244).
genre_exists(v0, v1, r) :- writer(v1, v0), wikisourcelangProperty(v1, v0), r = 244, Rule(244).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(244).
genre_exists(v0, v1, r) :- writer(v1, v0), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(244).
genre(v0, v1) :- writer(v1, v0), wikisourcelangProperty(v0, v1), Rule(245).
genre_exists(v0, v1, r) :- writer(v1, v0), wikisourcelangProperty(v0, v1), r = 245, Rule(245).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(245).
genre_exists(v0, v1, r) :- writer(v1, v0), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(245).
genre(v0, v1) :- writer(v2, v1), wikisourcelangProperty(v0, v2), Rule(246).
genre_exists(v0, v1, r) :- writer(v2, v1), wikisourcelangProperty(v0, v2), r = 246, Rule(246).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(246).
genre_exists(v0, v1, r) :- writer(v2, v1), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(246).
genre(v0, v1) :- writer(v1, v2), wikisourcelangProperty(v2, v0), Rule(247).
genre_exists(v0, v1, r) :- writer(v1, v2), wikisourcelangProperty(v2, v0), r = 247, Rule(247).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(247).
genre_exists(v0, v1, r) :- writer(v1, v2), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(247).
genre(v0, v1) :- writer(v2, v0), wikisourcelangProperty(v1, v2), Rule(248).
genre_exists(v0, v1, r) :- writer(v2, v0), wikisourcelangProperty(v1, v2), r = 248, Rule(248).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(248).
genre_exists(v0, v1, r) :- writer(v2, v0), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(248).
genre(v0, v1) :- writer(v2, v0), wikisourcelangProperty(v2, v1), Rule(249).
genre_exists(v0, v1, r) :- writer(v2, v0), wikisourcelangProperty(v2, v1), r = 249, Rule(249).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(249).
genre_exists(v0, v1, r) :- writer(v2, v0), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(249).
genre(v0, v1) :- writer(v0, v2), wikisourcelangProperty(v1, v2), Rule(250).
genre_exists(v0, v1, r) :- writer(v0, v2), wikisourcelangProperty(v1, v2), r = 250, Rule(250).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(250).
genre_exists(v0, v1, r) :- writer(v0, v2), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(250).
genre(v0, v1) :- writer(v0, v2), wikisourcelangProperty(v2, v1), Rule(251).
genre_exists(v0, v1, r) :- writer(v0, v2), wikisourcelangProperty(v2, v1), r = 251, Rule(251).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(251).
genre_exists(v0, v1, r) :- writer(v0, v2), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(251).
genre(v0, v1) :- writer(v2, v1), wikisourcelangProperty(v2, v0), Rule(252).
genre_exists(v0, v1, r) :- writer(v2, v1), wikisourcelangProperty(v2, v0), r = 252, Rule(252).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(252).
genre_exists(v0, v1, r) :- writer(v2, v1), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(252).
genre(v0, v1) :- writer(v1, v2), wikisourcelangProperty(v0, v2), Rule(253).
genre_exists(v0, v1, r) :- writer(v1, v2), wikisourcelangProperty(v0, v2), r = 253, Rule(253).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(253).
genre_exists(v0, v1, r) :- writer(v1, v2), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(253).
genre(v0, v1) :- writer(v0, v1), Igenre(v0, v1), Rule(254).
genre_exists(v0, v1, r) :- writer(v0, v1), Igenre(v0, v1), r = 254, Rule(254).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), Igenre(v0, v1), Rule(r), Rule(254).
genre_exists(v0, v1, r) :- writer(v0, v1), Igenre_exists(v0, v1, r), Rule(r), Rule(254).
genre(v0, v1) :- writer(v0, v1), Igenre(v1, v0), Rule(255).
genre_exists(v0, v1, r) :- writer(v0, v1), Igenre(v1, v0), r = 255, Rule(255).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), Igenre(v1, v0), Rule(r), Rule(255).
genre_exists(v0, v1, r) :- writer(v0, v1), Igenre_exists(v1, v0, r), Rule(r), Rule(255).
genre(v0, v1) :- writer(v1, v0), Igenre(v1, v0), Rule(256).
genre_exists(v0, v1, r) :- writer(v1, v0), Igenre(v1, v0), r = 256, Rule(256).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), Igenre(v1, v0), Rule(r), Rule(256).
genre_exists(v0, v1, r) :- writer(v1, v0), Igenre_exists(v1, v0, r), Rule(r), Rule(256).
genre(v0, v1) :- writer(v1, v0), Igenre(v0, v1), Rule(257).
genre_exists(v0, v1, r) :- writer(v1, v0), Igenre(v0, v1), r = 257, Rule(257).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), Igenre(v0, v1), Rule(r), Rule(257).
genre_exists(v0, v1, r) :- writer(v1, v0), Igenre_exists(v0, v1, r), Rule(r), Rule(257).
genre(v0, v1) :- writer(v2, v1), Igenre(v0, v2), Rule(258).
genre_exists(v0, v1, r) :- writer(v2, v1), Igenre(v0, v2), r = 258, Rule(258).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), Igenre(v0, v2), Rule(r), Rule(258).
genre_exists(v0, v1, r) :- writer(v2, v1), Igenre_exists(v0, v2, r), Rule(r), Rule(258).
genre(v0, v1) :- writer(v1, v2), Igenre(v2, v0), Rule(259).
genre_exists(v0, v1, r) :- writer(v1, v2), Igenre(v2, v0), r = 259, Rule(259).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), Igenre(v2, v0), Rule(r), Rule(259).
genre_exists(v0, v1, r) :- writer(v1, v2), Igenre_exists(v2, v0, r), Rule(r), Rule(259).
genre(v0, v1) :- writer(v2, v0), Igenre(v1, v2), Rule(260).
genre_exists(v0, v1, r) :- writer(v2, v0), Igenre(v1, v2), r = 260, Rule(260).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), Igenre(v1, v2), Rule(r), Rule(260).
genre_exists(v0, v1, r) :- writer(v2, v0), Igenre_exists(v1, v2, r), Rule(r), Rule(260).
genre(v0, v1) :- writer(v2, v0), Igenre(v2, v1), Rule(261).
genre_exists(v0, v1, r) :- writer(v2, v0), Igenre(v2, v1), r = 261, Rule(261).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), Igenre(v2, v1), Rule(r), Rule(261).
genre_exists(v0, v1, r) :- writer(v2, v0), Igenre_exists(v2, v1, r), Rule(r), Rule(261).
genre(v0, v1) :- writer(v0, v2), Igenre(v1, v2), Rule(262).
genre_exists(v0, v1, r) :- writer(v0, v2), Igenre(v1, v2), r = 262, Rule(262).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), Igenre(v1, v2), Rule(r), Rule(262).
genre_exists(v0, v1, r) :- writer(v0, v2), Igenre_exists(v1, v2, r), Rule(r), Rule(262).
genre(v0, v1) :- writer(v0, v2), Igenre(v2, v1), Rule(263).
genre_exists(v0, v1, r) :- writer(v0, v2), Igenre(v2, v1), r = 263, Rule(263).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), Igenre(v2, v1), Rule(r), Rule(263).
genre_exists(v0, v1, r) :- writer(v0, v2), Igenre_exists(v2, v1, r), Rule(r), Rule(263).
genre(v0, v1) :- writer(v2, v1), Igenre(v2, v0), Rule(264).
genre_exists(v0, v1, r) :- writer(v2, v1), Igenre(v2, v0), r = 264, Rule(264).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), Igenre(v2, v0), Rule(r), Rule(264).
genre_exists(v0, v1, r) :- writer(v2, v1), Igenre_exists(v2, v0, r), Rule(r), Rule(264).
genre(v0, v1) :- writer(v1, v2), Igenre(v0, v2), Rule(265).
genre_exists(v0, v1, r) :- writer(v1, v2), Igenre(v0, v2), r = 265, Rule(265).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), Igenre(v0, v2), Rule(r), Rule(265).
genre_exists(v0, v1, r) :- writer(v1, v2), Igenre_exists(v0, v2, r), Rule(r), Rule(265).
genre(v0, v1) :- writer(v0, v1), genre(v0, v1), Rule(266).
genre_exists(v0, v1, r) :- writer(v0, v1), genre(v0, v1), r = 266, Rule(266).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), genre(v0, v1), Rule(r), Rule(266).
genre_exists(v0, v1, r) :- writer(v0, v1), genre_exists(v0, v1, r), Rule(r), Rule(266).
genre(v0, v1) :- writer(v0, v1), genre(v1, v0), Rule(267).
genre_exists(v0, v1, r) :- writer(v0, v1), genre(v1, v0), r = 267, Rule(267).
genre_exists(v0, v1, r) :- writer_exists(v0, v1, r), genre(v1, v0), Rule(r), Rule(267).
genre_exists(v0, v1, r) :- writer(v0, v1), genre_exists(v1, v0, r), Rule(r), Rule(267).
genre(v0, v1) :- writer(v1, v0), genre(v1, v0), Rule(268).
genre_exists(v0, v1, r) :- writer(v1, v0), genre(v1, v0), r = 268, Rule(268).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), genre(v1, v0), Rule(r), Rule(268).
genre_exists(v0, v1, r) :- writer(v1, v0), genre_exists(v1, v0, r), Rule(r), Rule(268).
genre(v0, v1) :- writer(v1, v0), genre(v0, v1), Rule(269).
genre_exists(v0, v1, r) :- writer(v1, v0), genre(v0, v1), r = 269, Rule(269).
genre_exists(v0, v1, r) :- writer_exists(v1, v0, r), genre(v0, v1), Rule(r), Rule(269).
genre_exists(v0, v1, r) :- writer(v1, v0), genre_exists(v0, v1, r), Rule(r), Rule(269).
genre(v0, v1) :- writer(v2, v1), genre(v0, v2), Rule(270).
genre_exists(v0, v1, r) :- writer(v2, v1), genre(v0, v2), r = 270, Rule(270).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), genre(v0, v2), Rule(r), Rule(270).
genre_exists(v0, v1, r) :- writer(v2, v1), genre_exists(v0, v2, r), Rule(r), Rule(270).
genre(v0, v1) :- writer(v1, v2), genre(v2, v0), Rule(271).
genre_exists(v0, v1, r) :- writer(v1, v2), genre(v2, v0), r = 271, Rule(271).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), genre(v2, v0), Rule(r), Rule(271).
genre_exists(v0, v1, r) :- writer(v1, v2), genre_exists(v2, v0, r), Rule(r), Rule(271).
genre(v0, v1) :- writer(v2, v0), genre(v1, v2), Rule(272).
genre_exists(v0, v1, r) :- writer(v2, v0), genre(v1, v2), r = 272, Rule(272).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), genre(v1, v2), Rule(r), Rule(272).
genre_exists(v0, v1, r) :- writer(v2, v0), genre_exists(v1, v2, r), Rule(r), Rule(272).
genre(v0, v1) :- writer(v2, v0), genre(v2, v1), Rule(273).
genre_exists(v0, v1, r) :- writer(v2, v0), genre(v2, v1), r = 273, Rule(273).
genre_exists(v0, v1, r) :- writer_exists(v2, v0, r), genre(v2, v1), Rule(r), Rule(273).
genre_exists(v0, v1, r) :- writer(v2, v0), genre_exists(v2, v1, r), Rule(r), Rule(273).
genre(v0, v1) :- writer(v0, v2), genre(v1, v2), Rule(274).
genre_exists(v0, v1, r) :- writer(v0, v2), genre(v1, v2), r = 274, Rule(274).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), genre(v1, v2), Rule(r), Rule(274).
genre_exists(v0, v1, r) :- writer(v0, v2), genre_exists(v1, v2, r), Rule(r), Rule(274).
genre(v0, v1) :- writer(v0, v2), genre(v2, v1), Rule(275).
genre_exists(v0, v1, r) :- writer(v0, v2), genre(v2, v1), r = 275, Rule(275).
genre_exists(v0, v1, r) :- writer_exists(v0, v2, r), genre(v2, v1), Rule(r), Rule(275).
genre_exists(v0, v1, r) :- writer(v0, v2), genre_exists(v2, v1, r), Rule(r), Rule(275).
genre(v0, v1) :- writer(v2, v1), genre(v2, v0), Rule(276).
genre_exists(v0, v1, r) :- writer(v2, v1), genre(v2, v0), r = 276, Rule(276).
genre_exists(v0, v1, r) :- writer_exists(v2, v1, r), genre(v2, v0), Rule(r), Rule(276).
genre_exists(v0, v1, r) :- writer(v2, v1), genre_exists(v2, v0, r), Rule(r), Rule(276).
genre(v0, v1) :- writer(v1, v2), genre(v0, v2), Rule(277).
genre_exists(v0, v1, r) :- writer(v1, v2), genre(v0, v2), r = 277, Rule(277).
genre_exists(v0, v1, r) :- writer_exists(v1, v2, r), genre(v0, v2), Rule(r), Rule(277).
genre_exists(v0, v1, r) :- writer(v1, v2), genre_exists(v0, v2, r), Rule(r), Rule(277).
genre(v0, v1) :- wikisourcelangProperty(v0, v1), wikisourcelangProperty(v0, v1), Rule(278).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), wikisourcelangProperty(v0, v1), r = 278, Rule(278).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v1, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(278).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(278).
genre(v0, v1) :- wikisourcelangProperty(v0, v1), wikisourcelangProperty(v1, v0), Rule(279).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), wikisourcelangProperty(v1, v0), r = 279, Rule(279).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v1, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(279).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(279).
genre(v0, v1) :- wikisourcelangProperty(v1, v0), wikisourcelangProperty(v1, v0), Rule(280).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), wikisourcelangProperty(v1, v0), r = 280, Rule(280).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v0, r), wikisourcelangProperty(v1, v0), Rule(r), Rule(280).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), wikisourcelangProperty_exists(v1, v0, r), Rule(r), Rule(280).
genre(v0, v1) :- wikisourcelangProperty(v1, v0), wikisourcelangProperty(v0, v1), Rule(281).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), wikisourcelangProperty(v0, v1), r = 281, Rule(281).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v0, r), wikisourcelangProperty(v0, v1), Rule(r), Rule(281).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), wikisourcelangProperty_exists(v0, v1, r), Rule(r), Rule(281).
genre(v0, v1) :- wikisourcelangProperty(v2, v1), wikisourcelangProperty(v0, v2), Rule(282).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), wikisourcelangProperty(v0, v2), r = 282, Rule(282).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v1, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(282).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(282).
genre(v0, v1) :- wikisourcelangProperty(v1, v2), wikisourcelangProperty(v2, v0), Rule(283).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), wikisourcelangProperty(v2, v0), r = 283, Rule(283).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v2, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(283).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(283).
genre(v0, v1) :- wikisourcelangProperty(v2, v0), wikisourcelangProperty(v1, v2), Rule(284).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), wikisourcelangProperty(v1, v2), r = 284, Rule(284).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v0, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(284).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(284).
genre(v0, v1) :- wikisourcelangProperty(v2, v0), wikisourcelangProperty(v2, v1), Rule(285).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), wikisourcelangProperty(v2, v1), r = 285, Rule(285).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v0, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(285).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(285).
genre(v0, v1) :- wikisourcelangProperty(v0, v2), wikisourcelangProperty(v1, v2), Rule(286).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), wikisourcelangProperty(v1, v2), r = 286, Rule(286).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v2, r), wikisourcelangProperty(v1, v2), Rule(r), Rule(286).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), wikisourcelangProperty_exists(v1, v2, r), Rule(r), Rule(286).
genre(v0, v1) :- wikisourcelangProperty(v0, v2), wikisourcelangProperty(v2, v1), Rule(287).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), wikisourcelangProperty(v2, v1), r = 287, Rule(287).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v2, r), wikisourcelangProperty(v2, v1), Rule(r), Rule(287).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), wikisourcelangProperty_exists(v2, v1, r), Rule(r), Rule(287).
genre(v0, v1) :- wikisourcelangProperty(v2, v1), wikisourcelangProperty(v2, v0), Rule(288).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), wikisourcelangProperty(v2, v0), r = 288, Rule(288).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v1, r), wikisourcelangProperty(v2, v0), Rule(r), Rule(288).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), wikisourcelangProperty_exists(v2, v0, r), Rule(r), Rule(288).
genre(v0, v1) :- wikisourcelangProperty(v1, v2), wikisourcelangProperty(v0, v2), Rule(289).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), wikisourcelangProperty(v0, v2), r = 289, Rule(289).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v2, r), wikisourcelangProperty(v0, v2), Rule(r), Rule(289).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), wikisourcelangProperty_exists(v0, v2, r), Rule(r), Rule(289).
genre(v0, v1) :- wikisourcelangProperty(v0, v1), Igenre(v0, v1), Rule(290).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), Igenre(v0, v1), r = 290, Rule(290).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v1, r), Igenre(v0, v1), Rule(r), Rule(290).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), Igenre_exists(v0, v1, r), Rule(r), Rule(290).
genre(v0, v1) :- wikisourcelangProperty(v0, v1), Igenre(v1, v0), Rule(291).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), Igenre(v1, v0), r = 291, Rule(291).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v1, r), Igenre(v1, v0), Rule(r), Rule(291).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), Igenre_exists(v1, v0, r), Rule(r), Rule(291).
genre(v0, v1) :- wikisourcelangProperty(v1, v0), Igenre(v1, v0), Rule(292).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), Igenre(v1, v0), r = 292, Rule(292).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v0, r), Igenre(v1, v0), Rule(r), Rule(292).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), Igenre_exists(v1, v0, r), Rule(r), Rule(292).
genre(v0, v1) :- wikisourcelangProperty(v1, v0), Igenre(v0, v1), Rule(293).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), Igenre(v0, v1), r = 293, Rule(293).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v0, r), Igenre(v0, v1), Rule(r), Rule(293).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), Igenre_exists(v0, v1, r), Rule(r), Rule(293).
genre(v0, v1) :- wikisourcelangProperty(v2, v1), Igenre(v0, v2), Rule(294).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), Igenre(v0, v2), r = 294, Rule(294).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v1, r), Igenre(v0, v2), Rule(r), Rule(294).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), Igenre_exists(v0, v2, r), Rule(r), Rule(294).
genre(v0, v1) :- wikisourcelangProperty(v1, v2), Igenre(v2, v0), Rule(295).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), Igenre(v2, v0), r = 295, Rule(295).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v2, r), Igenre(v2, v0), Rule(r), Rule(295).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), Igenre_exists(v2, v0, r), Rule(r), Rule(295).
genre(v0, v1) :- wikisourcelangProperty(v2, v0), Igenre(v1, v2), Rule(296).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), Igenre(v1, v2), r = 296, Rule(296).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v0, r), Igenre(v1, v2), Rule(r), Rule(296).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), Igenre_exists(v1, v2, r), Rule(r), Rule(296).
genre(v0, v1) :- wikisourcelangProperty(v2, v0), Igenre(v2, v1), Rule(297).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), Igenre(v2, v1), r = 297, Rule(297).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v0, r), Igenre(v2, v1), Rule(r), Rule(297).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), Igenre_exists(v2, v1, r), Rule(r), Rule(297).
genre(v0, v1) :- wikisourcelangProperty(v0, v2), Igenre(v1, v2), Rule(298).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), Igenre(v1, v2), r = 298, Rule(298).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v2, r), Igenre(v1, v2), Rule(r), Rule(298).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), Igenre_exists(v1, v2, r), Rule(r), Rule(298).
genre(v0, v1) :- wikisourcelangProperty(v0, v2), Igenre(v2, v1), Rule(299).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), Igenre(v2, v1), r = 299, Rule(299).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v2, r), Igenre(v2, v1), Rule(r), Rule(299).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), Igenre_exists(v2, v1, r), Rule(r), Rule(299).
genre(v0, v1) :- wikisourcelangProperty(v2, v1), Igenre(v2, v0), Rule(300).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), Igenre(v2, v0), r = 300, Rule(300).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v1, r), Igenre(v2, v0), Rule(r), Rule(300).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), Igenre_exists(v2, v0, r), Rule(r), Rule(300).
genre(v0, v1) :- wikisourcelangProperty(v1, v2), Igenre(v0, v2), Rule(301).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), Igenre(v0, v2), r = 301, Rule(301).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v2, r), Igenre(v0, v2), Rule(r), Rule(301).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), Igenre_exists(v0, v2, r), Rule(r), Rule(301).
genre(v0, v1) :- wikisourcelangProperty(v0, v1), genre(v0, v1), Rule(302).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), genre(v0, v1), r = 302, Rule(302).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v1, r), genre(v0, v1), Rule(r), Rule(302).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), genre_exists(v0, v1, r), Rule(r), Rule(302).
genre(v0, v1) :- wikisourcelangProperty(v0, v1), genre(v1, v0), Rule(303).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), genre(v1, v0), r = 303, Rule(303).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v1, r), genre(v1, v0), Rule(r), Rule(303).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v1), genre_exists(v1, v0, r), Rule(r), Rule(303).
genre(v0, v1) :- wikisourcelangProperty(v1, v0), genre(v1, v0), Rule(304).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), genre(v1, v0), r = 304, Rule(304).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v0, r), genre(v1, v0), Rule(r), Rule(304).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), genre_exists(v1, v0, r), Rule(r), Rule(304).
genre(v0, v1) :- wikisourcelangProperty(v1, v0), genre(v0, v1), Rule(305).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), genre(v0, v1), r = 305, Rule(305).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v0, r), genre(v0, v1), Rule(r), Rule(305).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v0), genre_exists(v0, v1, r), Rule(r), Rule(305).
genre(v0, v1) :- wikisourcelangProperty(v2, v1), genre(v0, v2), Rule(306).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), genre(v0, v2), r = 306, Rule(306).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v1, r), genre(v0, v2), Rule(r), Rule(306).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), genre_exists(v0, v2, r), Rule(r), Rule(306).
genre(v0, v1) :- wikisourcelangProperty(v1, v2), genre(v2, v0), Rule(307).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), genre(v2, v0), r = 307, Rule(307).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v2, r), genre(v2, v0), Rule(r), Rule(307).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), genre_exists(v2, v0, r), Rule(r), Rule(307).
genre(v0, v1) :- wikisourcelangProperty(v2, v0), genre(v1, v2), Rule(308).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), genre(v1, v2), r = 308, Rule(308).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v0, r), genre(v1, v2), Rule(r), Rule(308).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), genre_exists(v1, v2, r), Rule(r), Rule(308).
genre(v0, v1) :- wikisourcelangProperty(v2, v0), genre(v2, v1), Rule(309).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), genre(v2, v1), r = 309, Rule(309).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v0, r), genre(v2, v1), Rule(r), Rule(309).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v0), genre_exists(v2, v1, r), Rule(r), Rule(309).
genre(v0, v1) :- wikisourcelangProperty(v0, v2), genre(v1, v2), Rule(310).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), genre(v1, v2), r = 310, Rule(310).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v2, r), genre(v1, v2), Rule(r), Rule(310).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), genre_exists(v1, v2, r), Rule(r), Rule(310).
genre(v0, v1) :- wikisourcelangProperty(v0, v2), genre(v2, v1), Rule(311).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), genre(v2, v1), r = 311, Rule(311).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v0, v2, r), genre(v2, v1), Rule(r), Rule(311).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v0, v2), genre_exists(v2, v1, r), Rule(r), Rule(311).
genre(v0, v1) :- wikisourcelangProperty(v2, v1), genre(v2, v0), Rule(312).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), genre(v2, v0), r = 312, Rule(312).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v2, v1, r), genre(v2, v0), Rule(r), Rule(312).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v2, v1), genre_exists(v2, v0, r), Rule(r), Rule(312).
genre(v0, v1) :- wikisourcelangProperty(v1, v2), genre(v0, v2), Rule(313).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), genre(v0, v2), r = 313, Rule(313).
genre_exists(v0, v1, r) :- wikisourcelangProperty_exists(v1, v2, r), genre(v0, v2), Rule(r), Rule(313).
genre_exists(v0, v1, r) :- wikisourcelangProperty(v1, v2), genre_exists(v0, v2, r), Rule(r), Rule(313).
genre(v0, v1) :- Igenre(v0, v1), Igenre(v0, v1), Rule(314).
genre_exists(v0, v1, r) :- Igenre(v0, v1), Igenre(v0, v1), r = 314, Rule(314).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v1, r), Igenre(v0, v1), Rule(r), Rule(314).
genre_exists(v0, v1, r) :- Igenre(v0, v1), Igenre_exists(v0, v1, r), Rule(r), Rule(314).
genre(v0, v1) :- Igenre(v0, v1), Igenre(v1, v0), Rule(315).
genre_exists(v0, v1, r) :- Igenre(v0, v1), Igenre(v1, v0), r = 315, Rule(315).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v1, r), Igenre(v1, v0), Rule(r), Rule(315).
genre_exists(v0, v1, r) :- Igenre(v0, v1), Igenre_exists(v1, v0, r), Rule(r), Rule(315).
genre(v0, v1) :- Igenre(v1, v0), Igenre(v1, v0), Rule(316).
genre_exists(v0, v1, r) :- Igenre(v1, v0), Igenre(v1, v0), r = 316, Rule(316).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v0, r), Igenre(v1, v0), Rule(r), Rule(316).
genre_exists(v0, v1, r) :- Igenre(v1, v0), Igenre_exists(v1, v0, r), Rule(r), Rule(316).
genre(v0, v1) :- Igenre(v1, v0), Igenre(v0, v1), Rule(317).
genre_exists(v0, v1, r) :- Igenre(v1, v0), Igenre(v0, v1), r = 317, Rule(317).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v0, r), Igenre(v0, v1), Rule(r), Rule(317).
genre_exists(v0, v1, r) :- Igenre(v1, v0), Igenre_exists(v0, v1, r), Rule(r), Rule(317).
genre(v0, v1) :- Igenre(v2, v1), Igenre(v0, v2), Rule(318).
genre_exists(v0, v1, r) :- Igenre(v2, v1), Igenre(v0, v2), r = 318, Rule(318).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v1, r), Igenre(v0, v2), Rule(r), Rule(318).
genre_exists(v0, v1, r) :- Igenre(v2, v1), Igenre_exists(v0, v2, r), Rule(r), Rule(318).
genre(v0, v1) :- Igenre(v1, v2), Igenre(v2, v0), Rule(319).
genre_exists(v0, v1, r) :- Igenre(v1, v2), Igenre(v2, v0), r = 319, Rule(319).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v2, r), Igenre(v2, v0), Rule(r), Rule(319).
genre_exists(v0, v1, r) :- Igenre(v1, v2), Igenre_exists(v2, v0, r), Rule(r), Rule(319).
genre(v0, v1) :- Igenre(v2, v0), Igenre(v1, v2), Rule(320).
genre_exists(v0, v1, r) :- Igenre(v2, v0), Igenre(v1, v2), r = 320, Rule(320).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v0, r), Igenre(v1, v2), Rule(r), Rule(320).
genre_exists(v0, v1, r) :- Igenre(v2, v0), Igenre_exists(v1, v2, r), Rule(r), Rule(320).
genre(v0, v1) :- Igenre(v2, v0), Igenre(v2, v1), Rule(321).
genre_exists(v0, v1, r) :- Igenre(v2, v0), Igenre(v2, v1), r = 321, Rule(321).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v0, r), Igenre(v2, v1), Rule(r), Rule(321).
genre_exists(v0, v1, r) :- Igenre(v2, v0), Igenre_exists(v2, v1, r), Rule(r), Rule(321).
genre(v0, v1) :- Igenre(v0, v2), Igenre(v1, v2), Rule(322).
genre_exists(v0, v1, r) :- Igenre(v0, v2), Igenre(v1, v2), r = 322, Rule(322).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v2, r), Igenre(v1, v2), Rule(r), Rule(322).
genre_exists(v0, v1, r) :- Igenre(v0, v2), Igenre_exists(v1, v2, r), Rule(r), Rule(322).
genre(v0, v1) :- Igenre(v0, v2), Igenre(v2, v1), Rule(323).
genre_exists(v0, v1, r) :- Igenre(v0, v2), Igenre(v2, v1), r = 323, Rule(323).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v2, r), Igenre(v2, v1), Rule(r), Rule(323).
genre_exists(v0, v1, r) :- Igenre(v0, v2), Igenre_exists(v2, v1, r), Rule(r), Rule(323).
genre(v0, v1) :- Igenre(v2, v1), Igenre(v2, v0), Rule(324).
genre_exists(v0, v1, r) :- Igenre(v2, v1), Igenre(v2, v0), r = 324, Rule(324).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v1, r), Igenre(v2, v0), Rule(r), Rule(324).
genre_exists(v0, v1, r) :- Igenre(v2, v1), Igenre_exists(v2, v0, r), Rule(r), Rule(324).
genre(v0, v1) :- Igenre(v1, v2), Igenre(v0, v2), Rule(325).
genre_exists(v0, v1, r) :- Igenre(v1, v2), Igenre(v0, v2), r = 325, Rule(325).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v2, r), Igenre(v0, v2), Rule(r), Rule(325).
genre_exists(v0, v1, r) :- Igenre(v1, v2), Igenre_exists(v0, v2, r), Rule(r), Rule(325).
genre(v0, v1) :- Igenre(v0, v1), genre(v0, v1), Rule(326).
genre_exists(v0, v1, r) :- Igenre(v0, v1), genre(v0, v1), r = 326, Rule(326).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v1, r), genre(v0, v1), Rule(r), Rule(326).
genre_exists(v0, v1, r) :- Igenre(v0, v1), genre_exists(v0, v1, r), Rule(r), Rule(326).
genre(v0, v1) :- Igenre(v0, v1), genre(v1, v0), Rule(327).
genre_exists(v0, v1, r) :- Igenre(v0, v1), genre(v1, v0), r = 327, Rule(327).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v1, r), genre(v1, v0), Rule(r), Rule(327).
genre_exists(v0, v1, r) :- Igenre(v0, v1), genre_exists(v1, v0, r), Rule(r), Rule(327).
genre(v0, v1) :- Igenre(v1, v0), genre(v1, v0), Rule(328).
genre_exists(v0, v1, r) :- Igenre(v1, v0), genre(v1, v0), r = 328, Rule(328).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v0, r), genre(v1, v0), Rule(r), Rule(328).
genre_exists(v0, v1, r) :- Igenre(v1, v0), genre_exists(v1, v0, r), Rule(r), Rule(328).
genre(v0, v1) :- Igenre(v1, v0), genre(v0, v1), Rule(329).
genre_exists(v0, v1, r) :- Igenre(v1, v0), genre(v0, v1), r = 329, Rule(329).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v0, r), genre(v0, v1), Rule(r), Rule(329).
genre_exists(v0, v1, r) :- Igenre(v1, v0), genre_exists(v0, v1, r), Rule(r), Rule(329).
genre(v0, v1) :- Igenre(v2, v1), genre(v0, v2), Rule(330).
genre_exists(v0, v1, r) :- Igenre(v2, v1), genre(v0, v2), r = 330, Rule(330).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v1, r), genre(v0, v2), Rule(r), Rule(330).
genre_exists(v0, v1, r) :- Igenre(v2, v1), genre_exists(v0, v2, r), Rule(r), Rule(330).
genre(v0, v1) :- Igenre(v1, v2), genre(v2, v0), Rule(331).
genre_exists(v0, v1, r) :- Igenre(v1, v2), genre(v2, v0), r = 331, Rule(331).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v2, r), genre(v2, v0), Rule(r), Rule(331).
genre_exists(v0, v1, r) :- Igenre(v1, v2), genre_exists(v2, v0, r), Rule(r), Rule(331).
genre(v0, v1) :- Igenre(v2, v0), genre(v1, v2), Rule(332).
genre_exists(v0, v1, r) :- Igenre(v2, v0), genre(v1, v2), r = 332, Rule(332).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v0, r), genre(v1, v2), Rule(r), Rule(332).
genre_exists(v0, v1, r) :- Igenre(v2, v0), genre_exists(v1, v2, r), Rule(r), Rule(332).
genre(v0, v1) :- Igenre(v2, v0), genre(v2, v1), Rule(333).
genre_exists(v0, v1, r) :- Igenre(v2, v0), genre(v2, v1), r = 333, Rule(333).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v0, r), genre(v2, v1), Rule(r), Rule(333).
genre_exists(v0, v1, r) :- Igenre(v2, v0), genre_exists(v2, v1, r), Rule(r), Rule(333).
genre(v0, v1) :- Igenre(v0, v2), genre(v1, v2), Rule(334).
genre_exists(v0, v1, r) :- Igenre(v0, v2), genre(v1, v2), r = 334, Rule(334).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v2, r), genre(v1, v2), Rule(r), Rule(334).
genre_exists(v0, v1, r) :- Igenre(v0, v2), genre_exists(v1, v2, r), Rule(r), Rule(334).
genre(v0, v1) :- Igenre(v0, v2), genre(v2, v1), Rule(335).
genre_exists(v0, v1, r) :- Igenre(v0, v2), genre(v2, v1), r = 335, Rule(335).
genre_exists(v0, v1, r) :- Igenre_exists(v0, v2, r), genre(v2, v1), Rule(r), Rule(335).
genre_exists(v0, v1, r) :- Igenre(v0, v2), genre_exists(v2, v1, r), Rule(r), Rule(335).
genre(v0, v1) :- Igenre(v2, v1), genre(v2, v0), Rule(336).
genre_exists(v0, v1, r) :- Igenre(v2, v1), genre(v2, v0), r = 336, Rule(336).
genre_exists(v0, v1, r) :- Igenre_exists(v2, v1, r), genre(v2, v0), Rule(r), Rule(336).
genre_exists(v0, v1, r) :- Igenre(v2, v1), genre_exists(v2, v0, r), Rule(r), Rule(336).
genre(v0, v1) :- Igenre(v1, v2), genre(v0, v2), Rule(337).
genre_exists(v0, v1, r) :- Igenre(v1, v2), genre(v0, v2), r = 337, Rule(337).
genre_exists(v0, v1, r) :- Igenre_exists(v1, v2, r), genre(v0, v2), Rule(r), Rule(337).
genre_exists(v0, v1, r) :- Igenre(v1, v2), genre_exists(v0, v2, r), Rule(r), Rule(337).
genre(v0, v1) :- genre(v0, v1), genre(v0, v1), Rule(338).
genre_exists(v0, v1, r) :- genre(v0, v1), genre(v0, v1), r = 338, Rule(338).
genre_exists(v0, v1, r) :- genre_exists(v0, v1, r), genre(v0, v1), Rule(r), Rule(338).
genre_exists(v0, v1, r) :- genre(v0, v1), genre_exists(v0, v1, r), Rule(r), Rule(338).
genre(v0, v1) :- genre(v0, v1), genre(v1, v0), Rule(339).
genre_exists(v0, v1, r) :- genre(v0, v1), genre(v1, v0), r = 339, Rule(339).
genre_exists(v0, v1, r) :- genre_exists(v0, v1, r), genre(v1, v0), Rule(r), Rule(339).
genre_exists(v0, v1, r) :- genre(v0, v1), genre_exists(v1, v0, r), Rule(r), Rule(339).
genre(v0, v1) :- genre(v1, v0), genre(v1, v0), Rule(340).
genre_exists(v0, v1, r) :- genre(v1, v0), genre(v1, v0), r = 340, Rule(340).
genre_exists(v0, v1, r) :- genre_exists(v1, v0, r), genre(v1, v0), Rule(r), Rule(340).
genre_exists(v0, v1, r) :- genre(v1, v0), genre_exists(v1, v0, r), Rule(r), Rule(340).
genre(v0, v1) :- genre(v1, v0), genre(v0, v1), Rule(341).
genre_exists(v0, v1, r) :- genre(v1, v0), genre(v0, v1), r = 341, Rule(341).
genre_exists(v0, v1, r) :- genre_exists(v1, v0, r), genre(v0, v1), Rule(r), Rule(341).
genre_exists(v0, v1, r) :- genre(v1, v0), genre_exists(v0, v1, r), Rule(r), Rule(341).
genre(v0, v1) :- genre(v2, v1), genre(v0, v2), Rule(342).
genre_exists(v0, v1, r) :- genre(v2, v1), genre(v0, v2), r = 342, Rule(342).
genre_exists(v0, v1, r) :- genre_exists(v2, v1, r), genre(v0, v2), Rule(r), Rule(342).
genre_exists(v0, v1, r) :- genre(v2, v1), genre_exists(v0, v2, r), Rule(r), Rule(342).
genre(v0, v1) :- genre(v1, v2), genre(v2, v0), Rule(343).
genre_exists(v0, v1, r) :- genre(v1, v2), genre(v2, v0), r = 343, Rule(343).
genre_exists(v0, v1, r) :- genre_exists(v1, v2, r), genre(v2, v0), Rule(r), Rule(343).
genre_exists(v0, v1, r) :- genre(v1, v2), genre_exists(v2, v0, r), Rule(r), Rule(343).
genre(v0, v1) :- genre(v2, v0), genre(v1, v2), Rule(344).
genre_exists(v0, v1, r) :- genre(v2, v0), genre(v1, v2), r = 344, Rule(344).
genre_exists(v0, v1, r) :- genre_exists(v2, v0, r), genre(v1, v2), Rule(r), Rule(344).
genre_exists(v0, v1, r) :- genre(v2, v0), genre_exists(v1, v2, r), Rule(r), Rule(344).
genre(v0, v1) :- genre(v2, v0), genre(v2, v1), Rule(345).
genre_exists(v0, v1, r) :- genre(v2, v0), genre(v2, v1), r = 345, Rule(345).
genre_exists(v0, v1, r) :- genre_exists(v2, v0, r), genre(v2, v1), Rule(r), Rule(345).
genre_exists(v0, v1, r) :- genre(v2, v0), genre_exists(v2, v1, r), Rule(r), Rule(345).
genre(v0, v1) :- genre(v0, v2), genre(v1, v2), Rule(346).
genre_exists(v0, v1, r) :- genre(v0, v2), genre(v1, v2), r = 346, Rule(346).
genre_exists(v0, v1, r) :- genre_exists(v0, v2, r), genre(v1, v2), Rule(r), Rule(346).
genre_exists(v0, v1, r) :- genre(v0, v2), genre_exists(v1, v2, r), Rule(r), Rule(346).
genre(v0, v1) :- genre(v0, v2), genre(v2, v1), Rule(347).
genre_exists(v0, v1, r) :- genre(v0, v2), genre(v2, v1), r = 347, Rule(347).
genre_exists(v0, v1, r) :- genre_exists(v0, v2, r), genre(v2, v1), Rule(r), Rule(347).
genre_exists(v0, v1, r) :- genre(v0, v2), genre_exists(v2, v1, r), Rule(r), Rule(347).
genre(v0, v1) :- genre(v2, v1), genre(v2, v0), Rule(348).
genre_exists(v0, v1, r) :- genre(v2, v1), genre(v2, v0), r = 348, Rule(348).
genre_exists(v0, v1, r) :- genre_exists(v2, v1, r), genre(v2, v0), Rule(r), Rule(348).
genre_exists(v0, v1, r) :- genre(v2, v1), genre_exists(v2, v0, r), Rule(r), Rule(348).
genre(v0, v1) :- genre(v1, v2), genre(v0, v2), Rule(349).
genre_exists(v0, v1, r) :- genre(v1, v2), genre(v0, v2), r = 349, Rule(349).
genre_exists(v0, v1, r) :- genre_exists(v1, v2, r), genre(v0, v2), Rule(r), Rule(349).
genre_exists(v0, v1, r) :- genre(v1, v2), genre_exists(v0, v2, r), Rule(r), Rule(349).
