invent_error
inv_0(v0, v1) :- Ilivesin(v0, v1), Rule(24).
input prevent
inv_0(v0, v1) :- Ilivesin(v1, v0), Rule(25).
Head twice 
inv_0(v0, v1) :- inv_0(v0, v1), Rule(26).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), islocatedin(v1, v0), Rule(29).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), islocatedin(v0, v1), Rule(31).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), islocatedin(v0, v2), Rule(32).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), islocatedin(v2, v0), Rule(33).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), islocatedin(v1, v2), Rule(34).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), islocatedin(v2, v1), Rule(37).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), ismarriedto(v0, v1), Rule(40).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), ismarriedto(v1, v0), Rule(41).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), ismarriedto(v1, v0), Rule(42).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), ismarriedto(v0, v1), Rule(43).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), ismarriedto(v0, v2), Rule(44).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), ismarriedto(v2, v0), Rule(45).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), ismarriedto(v1, v2), Rule(46).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), ismarriedto(v2, v1), Rule(47).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), ismarriedto(v1, v2), Rule(48).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), ismarriedto(v2, v1), Rule(49).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), ismarriedto(v2, v0), Rule(50).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), ismarriedto(v0, v2), Rule(51).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), created(v0, v1), Rule(52).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), created(v1, v0), Rule(53).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), created(v1, v0), Rule(54).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), created(v0, v1), Rule(55).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), created(v2, v0), Rule(57).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), created(v2, v1), Rule(59).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), created(v1, v2), Rule(60).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), created(v2, v1), Rule(61).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), created(v2, v0), Rule(62).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), created(v0, v2), Rule(63).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), influences(v0, v1), Rule(76).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), influences(v1, v0), Rule(77).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), influences(v1, v0), Rule(78).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), influences(v0, v1), Rule(79).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), influences(v0, v2), Rule(80).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), influences(v2, v0), Rule(81).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), influences(v1, v2), Rule(82).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), influences(v2, v1), Rule(83).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), influences(v1, v2), Rule(84).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), influences(v2, v1), Rule(85).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), influences(v2, v0), Rule(86).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), influences(v0, v2), Rule(87).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), actedin(v0, v1), Rule(88).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), actedin(v1, v0), Rule(89).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), actedin(v1, v0), Rule(90).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), actedin(v0, v1), Rule(91).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), actedin(v0, v2), Rule(92).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), actedin(v2, v0), Rule(93).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), actedin(v1, v2), Rule(94).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), actedin(v2, v1), Rule(95).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), actedin(v1, v2), Rule(96).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), actedin(v2, v1), Rule(97).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), actedin(v2, v0), Rule(98).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), actedin(v0, v2), Rule(99).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), diedin(v0, v1), Rule(100).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), diedin(v1, v0), Rule(101).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), diedin(v1, v0), Rule(102).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), diedin(v0, v1), Rule(103).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), diedin(v0, v2), Rule(104).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), diedin(v2, v0), Rule(105).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), diedin(v1, v2), Rule(106).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), diedin(v2, v1), Rule(107).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), diedin(v2, v1), Rule(109).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), diedin(v2, v0), Rule(110).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), wasbornin(v0, v1), Rule(112).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), wasbornin(v1, v0), Rule(113).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), wasbornin(v1, v0), Rule(114).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), wasbornin(v0, v1), Rule(115).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), wasbornin(v0, v2), Rule(116).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), wasbornin(v2, v0), Rule(117).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), wasbornin(v1, v2), Rule(118).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), wasbornin(v2, v1), Rule(119).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), wasbornin(v2, v1), Rule(121).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), wasbornin(v2, v0), Rule(122).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), hasgeonamesid(v0, v1), Rule(124).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), hasgeonamesid(v1, v0), Rule(126).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), hasgeonamesid(v2, v1), Rule(131).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), hasgeonamesid(v1, v2), Rule(132).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), hasgeonamesid(v2, v0), Rule(134).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), hasgeonamesid(v0, v2), Rule(135).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), haswonprize(v0, v1), Rule(136).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), haswonprize(v1, v0), Rule(137).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), haswonprize(v1, v0), Rule(138).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), haswonprize(v0, v1), Rule(139).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), haswonprize(v0, v2), Rule(140).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), haswonprize(v2, v0), Rule(141).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), haswonprize(v1, v2), Rule(142).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), haswonprize(v1, v2), Rule(144).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), haswonprize(v2, v1), Rule(145).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), haswonprize(v0, v2), Rule(147).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), directed(v0, v1), Rule(148).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), directed(v1, v0), Rule(149).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), directed(v1, v0), Rule(150).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), directed(v0, v1), Rule(151).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), directed(v0, v2), Rule(152).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), directed(v2, v0), Rule(153).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), directed(v1, v2), Rule(154).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), directed(v2, v1), Rule(155).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), directed(v1, v2), Rule(156).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), directed(v2, v1), Rule(157).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), directed(v2, v0), Rule(158).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), directed(v0, v2), Rule(159).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), haschild(v0, v1), Rule(160).
type error
inv_0(v0, v1) :- islocatedin(v0, v1), haschild(v1, v0), Rule(161).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), haschild(v1, v0), Rule(162).
type error
inv_0(v0, v1) :- islocatedin(v1, v0), haschild(v0, v1), Rule(163).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), haschild(v0, v2), Rule(164).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), haschild(v2, v0), Rule(165).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), haschild(v1, v2), Rule(166).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), haschild(v2, v1), Rule(167).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), haschild(v1, v2), Rule(168).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), haschild(v2, v1), Rule(169).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), haschild(v2, v0), Rule(170).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), haschild(v0, v2), Rule(171).
invent_error
inv_0(v0, v1) :- islocatedin(v0, v1), Ilivesin(v0, v1), Rule(172).
input prevent
inv_0(v0, v1) :- islocatedin(v0, v1), Ilivesin(v1, v0), Rule(173).
input prevent
inv_0(v0, v1) :- islocatedin(v1, v0), Ilivesin(v1, v0), Rule(174).
invent_error
inv_0(v0, v1) :- islocatedin(v1, v0), Ilivesin(v0, v1), Rule(175).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), Ilivesin(v0, v2), Rule(176).
type error
inv_0(v0, v1) :- islocatedin(v1, v2), Ilivesin(v2, v0), Rule(177).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), Ilivesin(v1, v2), Rule(178).
type error
inv_0(v0, v1) :- islocatedin(v2, v0), Ilivesin(v2, v1), Rule(179).
type error
inv_0(v0, v1) :- islocatedin(v0, v2), Ilivesin(v2, v1), Rule(181).
type error
inv_0(v0, v1) :- islocatedin(v2, v1), Ilivesin(v2, v0), Rule(182).
Head twice 
inv_0(v0, v1) :- islocatedin(v0, v1), inv_0(v0, v1), Rule(184).
Head twice 
inv_0(v0, v1) :- islocatedin(v1, v0), inv_0(v0, v1), Rule(187).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), created(v0, v1), Rule(208).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), created(v1, v0), Rule(209).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), created(v1, v0), Rule(210).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), created(v0, v1), Rule(211).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), created(v0, v2), Rule(212).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), created(v1, v2), Rule(214).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), created(v1, v2), Rule(216).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), created(v0, v2), Rule(219).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), actedin(v0, v1), Rule(244).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), actedin(v1, v0), Rule(245).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), actedin(v1, v0), Rule(246).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), actedin(v0, v1), Rule(247).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), actedin(v0, v2), Rule(248).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), actedin(v1, v2), Rule(250).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), actedin(v1, v2), Rule(252).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), actedin(v0, v2), Rule(255).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), diedin(v0, v1), Rule(256).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), diedin(v1, v0), Rule(257).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), diedin(v1, v0), Rule(258).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), diedin(v0, v1), Rule(259).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), diedin(v0, v2), Rule(260).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), diedin(v1, v2), Rule(262).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), diedin(v1, v2), Rule(264).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), diedin(v0, v2), Rule(267).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), wasbornin(v0, v1), Rule(268).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), wasbornin(v1, v0), Rule(269).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), wasbornin(v1, v0), Rule(270).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), wasbornin(v0, v1), Rule(271).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), wasbornin(v0, v2), Rule(272).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), wasbornin(v1, v2), Rule(274).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), wasbornin(v1, v2), Rule(276).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), wasbornin(v0, v2), Rule(279).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), hasgeonamesid(v0, v1), Rule(280).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), hasgeonamesid(v1, v0), Rule(281).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), hasgeonamesid(v1, v0), Rule(282).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), hasgeonamesid(v0, v1), Rule(283).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), hasgeonamesid(v0, v2), Rule(284).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), hasgeonamesid(v2, v0), Rule(285).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), hasgeonamesid(v1, v2), Rule(286).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), hasgeonamesid(v2, v1), Rule(287).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), hasgeonamesid(v1, v2), Rule(288).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), hasgeonamesid(v2, v1), Rule(289).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), hasgeonamesid(v2, v0), Rule(290).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), hasgeonamesid(v0, v2), Rule(291).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), haswonprize(v0, v1), Rule(292).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), haswonprize(v1, v0), Rule(293).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), haswonprize(v1, v0), Rule(294).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), haswonprize(v0, v1), Rule(295).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), haswonprize(v0, v2), Rule(296).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), haswonprize(v2, v0), Rule(297).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), haswonprize(v1, v2), Rule(298).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), haswonprize(v2, v1), Rule(299).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), haswonprize(v1, v2), Rule(300).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), haswonprize(v2, v1), Rule(301).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), haswonprize(v2, v0), Rule(302).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), haswonprize(v0, v2), Rule(303).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), directed(v0, v1), Rule(304).
type error
inv_0(v0, v1) :- ismarriedto(v0, v1), directed(v1, v0), Rule(305).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), directed(v1, v0), Rule(306).
type error
inv_0(v0, v1) :- ismarriedto(v1, v0), directed(v0, v1), Rule(307).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), directed(v0, v2), Rule(308).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), directed(v1, v2), Rule(310).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), directed(v1, v2), Rule(312).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), directed(v0, v2), Rule(315).
invent_error
inv_0(v0, v1) :- ismarriedto(v0, v1), Ilivesin(v0, v1), Rule(328).
input prevent
inv_0(v0, v1) :- ismarriedto(v0, v1), Ilivesin(v1, v0), Rule(329).
input prevent
inv_0(v0, v1) :- ismarriedto(v1, v0), Ilivesin(v1, v0), Rule(330).
invent_error
inv_0(v0, v1) :- ismarriedto(v1, v0), Ilivesin(v0, v1), Rule(331).
type error
inv_0(v0, v1) :- ismarriedto(v2, v1), Ilivesin(v0, v2), Rule(332).
type error
inv_0(v0, v1) :- ismarriedto(v2, v0), Ilivesin(v1, v2), Rule(334).
type error
inv_0(v0, v1) :- ismarriedto(v0, v2), Ilivesin(v1, v2), Rule(336).
type error
inv_0(v0, v1) :- ismarriedto(v1, v2), Ilivesin(v0, v2), Rule(339).
Head twice 
inv_0(v0, v1) :- ismarriedto(v0, v1), inv_0(v0, v1), Rule(340).
Head twice 
inv_0(v0, v1) :- ismarriedto(v1, v0), inv_0(v0, v1), Rule(343).
type error
inv_0(v0, v1) :- created(v0, v1), created(v1, v0), Rule(353).
type error
inv_0(v0, v1) :- created(v1, v0), created(v0, v1), Rule(355).
type error
inv_0(v0, v1) :- created(v2, v1), created(v0, v2), Rule(356).
type error
inv_0(v0, v1) :- created(v1, v2), created(v2, v0), Rule(357).
type error
inv_0(v0, v1) :- created(v2, v0), created(v1, v2), Rule(358).
type error
inv_0(v0, v1) :- created(v0, v2), created(v2, v1), Rule(361).
type error
inv_0(v0, v1) :- created(v0, v1), influences(v0, v1), Rule(376).
type error
inv_0(v0, v1) :- created(v0, v1), influences(v1, v0), Rule(377).
type error
inv_0(v0, v1) :- created(v1, v0), influences(v1, v0), Rule(378).
type error
inv_0(v0, v1) :- created(v1, v0), influences(v0, v1), Rule(379).
type error
inv_0(v0, v1) :- created(v1, v2), influences(v2, v0), Rule(381).
type error
inv_0(v0, v1) :- created(v0, v2), influences(v1, v2), Rule(384).
type error
inv_0(v0, v1) :- created(v0, v2), influences(v2, v1), Rule(385).
type error
inv_0(v0, v1) :- created(v1, v2), influences(v0, v2), Rule(387).
type error
inv_0(v0, v1) :- created(v0, v1), actedin(v0, v1), Rule(388).
type error
inv_0(v0, v1) :- created(v0, v1), actedin(v1, v0), Rule(389).
type error
inv_0(v0, v1) :- created(v1, v0), actedin(v1, v0), Rule(390).
type error
inv_0(v0, v1) :- created(v1, v0), actedin(v0, v1), Rule(391).
type error
inv_0(v0, v1) :- created(v2, v1), actedin(v0, v2), Rule(392).
type error
inv_0(v0, v1) :- created(v1, v2), actedin(v2, v0), Rule(393).
type error
inv_0(v0, v1) :- created(v2, v0), actedin(v1, v2), Rule(394).
type error
inv_0(v0, v1) :- created(v0, v2), actedin(v1, v2), Rule(396).
type error
inv_0(v0, v1) :- created(v0, v2), actedin(v2, v1), Rule(397).
type error
inv_0(v0, v1) :- created(v1, v2), actedin(v0, v2), Rule(399).
type error
inv_0(v0, v1) :- created(v0, v1), diedin(v0, v1), Rule(400).
type error
inv_0(v0, v1) :- created(v0, v1), diedin(v1, v0), Rule(401).
type error
inv_0(v0, v1) :- created(v1, v0), diedin(v1, v0), Rule(402).
type error
inv_0(v0, v1) :- created(v1, v0), diedin(v0, v1), Rule(403).
type error
inv_0(v0, v1) :- created(v2, v1), diedin(v0, v2), Rule(404).
type error
inv_0(v0, v1) :- created(v1, v2), diedin(v2, v0), Rule(405).
type error
inv_0(v0, v1) :- created(v2, v0), diedin(v1, v2), Rule(406).
type error
inv_0(v0, v1) :- created(v0, v2), diedin(v1, v2), Rule(408).
type error
inv_0(v0, v1) :- created(v0, v2), diedin(v2, v1), Rule(409).
type error
inv_0(v0, v1) :- created(v1, v2), diedin(v0, v2), Rule(411).
type error
inv_0(v0, v1) :- created(v0, v1), wasbornin(v0, v1), Rule(412).
type error
inv_0(v0, v1) :- created(v0, v1), wasbornin(v1, v0), Rule(413).
type error
inv_0(v0, v1) :- created(v1, v0), wasbornin(v1, v0), Rule(414).
type error
inv_0(v0, v1) :- created(v1, v0), wasbornin(v0, v1), Rule(415).
type error
inv_0(v0, v1) :- created(v2, v1), wasbornin(v0, v2), Rule(416).
type error
inv_0(v0, v1) :- created(v1, v2), wasbornin(v2, v0), Rule(417).
type error
inv_0(v0, v1) :- created(v2, v0), wasbornin(v1, v2), Rule(418).
type error
inv_0(v0, v1) :- created(v0, v2), wasbornin(v1, v2), Rule(420).
type error
inv_0(v0, v1) :- created(v0, v2), wasbornin(v2, v1), Rule(421).
type error
inv_0(v0, v1) :- created(v1, v2), wasbornin(v0, v2), Rule(423).
type error
inv_0(v0, v1) :- created(v0, v1), hasgeonamesid(v0, v1), Rule(424).
type error
inv_0(v0, v1) :- created(v0, v1), hasgeonamesid(v1, v0), Rule(425).
type error
inv_0(v0, v1) :- created(v1, v0), hasgeonamesid(v1, v0), Rule(426).
type error
inv_0(v0, v1) :- created(v1, v0), hasgeonamesid(v0, v1), Rule(427).
type error
inv_0(v0, v1) :- created(v2, v1), hasgeonamesid(v0, v2), Rule(428).
type error
inv_0(v0, v1) :- created(v1, v2), hasgeonamesid(v2, v0), Rule(429).
type error
inv_0(v0, v1) :- created(v2, v0), hasgeonamesid(v1, v2), Rule(430).
type error
inv_0(v0, v1) :- created(v2, v0), hasgeonamesid(v2, v1), Rule(431).
type error
inv_0(v0, v1) :- created(v0, v2), hasgeonamesid(v2, v1), Rule(433).
type error
inv_0(v0, v1) :- created(v2, v1), hasgeonamesid(v2, v0), Rule(434).
type error
inv_0(v0, v1) :- created(v0, v1), haswonprize(v0, v1), Rule(436).
type error
inv_0(v0, v1) :- created(v0, v1), haswonprize(v1, v0), Rule(437).
type error
inv_0(v0, v1) :- created(v1, v0), haswonprize(v1, v0), Rule(438).
type error
inv_0(v0, v1) :- created(v1, v0), haswonprize(v0, v1), Rule(439).
type error
inv_0(v0, v1) :- created(v2, v1), haswonprize(v0, v2), Rule(440).
type error
inv_0(v0, v1) :- created(v2, v0), haswonprize(v1, v2), Rule(442).
type error
inv_0(v0, v1) :- created(v2, v0), haswonprize(v2, v1), Rule(443).
type error
inv_0(v0, v1) :- created(v0, v2), haswonprize(v1, v2), Rule(444).
type error
inv_0(v0, v1) :- created(v2, v1), haswonprize(v2, v0), Rule(446).
type error
inv_0(v0, v1) :- created(v1, v2), haswonprize(v0, v2), Rule(447).
type error
inv_0(v0, v1) :- created(v0, v1), directed(v0, v1), Rule(448).
type error
inv_0(v0, v1) :- created(v0, v1), directed(v1, v0), Rule(449).
type error
inv_0(v0, v1) :- created(v1, v0), directed(v1, v0), Rule(450).
type error
inv_0(v0, v1) :- created(v1, v0), directed(v0, v1), Rule(451).
type error
inv_0(v0, v1) :- created(v2, v1), directed(v0, v2), Rule(452).
type error
inv_0(v0, v1) :- created(v1, v2), directed(v2, v0), Rule(453).
type error
inv_0(v0, v1) :- created(v2, v0), directed(v1, v2), Rule(454).
type error
inv_0(v0, v1) :- created(v0, v2), directed(v1, v2), Rule(456).
type error
inv_0(v0, v1) :- created(v0, v2), directed(v2, v1), Rule(457).
type error
inv_0(v0, v1) :- created(v1, v2), directed(v0, v2), Rule(459).
type error
inv_0(v0, v1) :- created(v0, v1), haschild(v0, v1), Rule(460).
type error
inv_0(v0, v1) :- created(v0, v1), haschild(v1, v0), Rule(461).
type error
inv_0(v0, v1) :- created(v1, v0), haschild(v1, v0), Rule(462).
type error
inv_0(v0, v1) :- created(v1, v0), haschild(v0, v1), Rule(463).
type error
inv_0(v0, v1) :- created(v1, v2), haschild(v2, v0), Rule(465).
type error
inv_0(v0, v1) :- created(v0, v2), haschild(v1, v2), Rule(468).
type error
inv_0(v0, v1) :- created(v0, v2), haschild(v2, v1), Rule(469).
type error
inv_0(v0, v1) :- created(v1, v2), haschild(v0, v2), Rule(471).
invent_error
inv_0(v0, v1) :- created(v0, v1), Ilivesin(v0, v1), Rule(472).
input prevent
inv_0(v0, v1) :- created(v0, v1), Ilivesin(v1, v0), Rule(473).
input prevent
inv_0(v0, v1) :- created(v1, v0), Ilivesin(v1, v0), Rule(474).
invent_error
inv_0(v0, v1) :- created(v1, v0), Ilivesin(v0, v1), Rule(475).
type error
inv_0(v0, v1) :- created(v2, v1), Ilivesin(v0, v2), Rule(476).
type error
inv_0(v0, v1) :- created(v1, v2), Ilivesin(v2, v0), Rule(477).
type error
inv_0(v0, v1) :- created(v2, v0), Ilivesin(v1, v2), Rule(478).
type error
inv_0(v0, v1) :- created(v0, v2), Ilivesin(v1, v2), Rule(480).
type error
inv_0(v0, v1) :- created(v0, v2), Ilivesin(v2, v1), Rule(481).
type error
inv_0(v0, v1) :- created(v1, v2), Ilivesin(v0, v2), Rule(483).
Head twice 
inv_0(v0, v1) :- created(v0, v1), inv_0(v0, v1), Rule(484).
Head twice 
inv_0(v0, v1) :- created(v1, v0), inv_0(v0, v1), Rule(487).
invent_error
inv_0(v0, v1) :- participatedin(v0, v1), Ilivesin(v0, v1), Rule(604).
input prevent
inv_0(v0, v1) :- participatedin(v0, v1), Ilivesin(v1, v0), Rule(605).
input prevent
inv_0(v0, v1) :- participatedin(v1, v0), Ilivesin(v1, v0), Rule(606).
invent_error
inv_0(v0, v1) :- participatedin(v1, v0), Ilivesin(v0, v1), Rule(607).
Head twice 
inv_0(v0, v1) :- participatedin(v0, v1), inv_0(v0, v1), Rule(616).
Head twice 
inv_0(v0, v1) :- participatedin(v1, v0), inv_0(v0, v1), Rule(619).
type error
inv_0(v0, v1) :- influences(v0, v1), actedin(v0, v1), Rule(640).
type error
inv_0(v0, v1) :- influences(v0, v1), actedin(v1, v0), Rule(641).
type error
inv_0(v0, v1) :- influences(v1, v0), actedin(v1, v0), Rule(642).
type error
inv_0(v0, v1) :- influences(v1, v0), actedin(v0, v1), Rule(643).
type error
inv_0(v0, v1) :- influences(v2, v1), actedin(v0, v2), Rule(644).
type error
inv_0(v0, v1) :- influences(v2, v0), actedin(v1, v2), Rule(646).
type error
inv_0(v0, v1) :- influences(v0, v2), actedin(v1, v2), Rule(648).
type error
inv_0(v0, v1) :- influences(v1, v2), actedin(v0, v2), Rule(651).
type error
inv_0(v0, v1) :- influences(v0, v1), diedin(v0, v1), Rule(652).
type error
inv_0(v0, v1) :- influences(v0, v1), diedin(v1, v0), Rule(653).
type error
inv_0(v0, v1) :- influences(v1, v0), diedin(v1, v0), Rule(654).
type error
inv_0(v0, v1) :- influences(v1, v0), diedin(v0, v1), Rule(655).
type error
inv_0(v0, v1) :- influences(v2, v1), diedin(v0, v2), Rule(656).
type error
inv_0(v0, v1) :- influences(v2, v0), diedin(v1, v2), Rule(658).
type error
inv_0(v0, v1) :- influences(v0, v2), diedin(v1, v2), Rule(660).
type error
inv_0(v0, v1) :- influences(v1, v2), diedin(v0, v2), Rule(663).
type error
inv_0(v0, v1) :- influences(v0, v1), wasbornin(v0, v1), Rule(664).
type error
inv_0(v0, v1) :- influences(v0, v1), wasbornin(v1, v0), Rule(665).
type error
inv_0(v0, v1) :- influences(v1, v0), wasbornin(v1, v0), Rule(666).
type error
inv_0(v0, v1) :- influences(v1, v0), wasbornin(v0, v1), Rule(667).
type error
inv_0(v0, v1) :- influences(v2, v1), wasbornin(v0, v2), Rule(668).
type error
inv_0(v0, v1) :- influences(v2, v0), wasbornin(v1, v2), Rule(670).
type error
inv_0(v0, v1) :- influences(v0, v2), wasbornin(v1, v2), Rule(672).
type error
inv_0(v0, v1) :- influences(v1, v2), wasbornin(v0, v2), Rule(675).
type error
inv_0(v0, v1) :- influences(v0, v1), hasgeonamesid(v0, v1), Rule(676).
type error
inv_0(v0, v1) :- influences(v0, v1), hasgeonamesid(v1, v0), Rule(677).
type error
inv_0(v0, v1) :- influences(v1, v0), hasgeonamesid(v1, v0), Rule(678).
type error
inv_0(v0, v1) :- influences(v1, v0), hasgeonamesid(v0, v1), Rule(679).
type error
inv_0(v0, v1) :- influences(v2, v1), hasgeonamesid(v0, v2), Rule(680).
type error
inv_0(v0, v1) :- influences(v1, v2), hasgeonamesid(v2, v0), Rule(681).
type error
inv_0(v0, v1) :- influences(v2, v0), hasgeonamesid(v1, v2), Rule(682).
type error
inv_0(v0, v1) :- influences(v2, v0), hasgeonamesid(v2, v1), Rule(683).
type error
inv_0(v0, v1) :- influences(v0, v2), hasgeonamesid(v1, v2), Rule(684).
type error
inv_0(v0, v1) :- influences(v0, v2), hasgeonamesid(v2, v1), Rule(685).
type error
inv_0(v0, v1) :- influences(v2, v1), hasgeonamesid(v2, v0), Rule(686).
type error
inv_0(v0, v1) :- influences(v1, v2), hasgeonamesid(v0, v2), Rule(687).
type error
inv_0(v0, v1) :- influences(v0, v1), haswonprize(v0, v1), Rule(688).
type error
inv_0(v0, v1) :- influences(v0, v1), haswonprize(v1, v0), Rule(689).
type error
inv_0(v0, v1) :- influences(v1, v0), haswonprize(v1, v0), Rule(690).
type error
inv_0(v0, v1) :- influences(v1, v0), haswonprize(v0, v1), Rule(691).
type error
inv_0(v0, v1) :- influences(v2, v1), haswonprize(v0, v2), Rule(692).
type error
inv_0(v0, v1) :- influences(v1, v2), haswonprize(v2, v0), Rule(693).
type error
inv_0(v0, v1) :- influences(v2, v0), haswonprize(v1, v2), Rule(694).
type error
inv_0(v0, v1) :- influences(v2, v0), haswonprize(v2, v1), Rule(695).
type error
inv_0(v0, v1) :- influences(v0, v2), haswonprize(v1, v2), Rule(696).
type error
inv_0(v0, v1) :- influences(v0, v2), haswonprize(v2, v1), Rule(697).
type error
inv_0(v0, v1) :- influences(v2, v1), haswonprize(v2, v0), Rule(698).
type error
inv_0(v0, v1) :- influences(v1, v2), haswonprize(v0, v2), Rule(699).
type error
inv_0(v0, v1) :- influences(v0, v1), directed(v0, v1), Rule(700).
type error
inv_0(v0, v1) :- influences(v0, v1), directed(v1, v0), Rule(701).
type error
inv_0(v0, v1) :- influences(v1, v0), directed(v1, v0), Rule(702).
type error
inv_0(v0, v1) :- influences(v1, v0), directed(v0, v1), Rule(703).
type error
inv_0(v0, v1) :- influences(v2, v1), directed(v0, v2), Rule(704).
type error
inv_0(v0, v1) :- influences(v2, v0), directed(v1, v2), Rule(706).
type error
inv_0(v0, v1) :- influences(v0, v2), directed(v1, v2), Rule(708).
type error
inv_0(v0, v1) :- influences(v1, v2), directed(v0, v2), Rule(711).
invent_error
inv_0(v0, v1) :- influences(v0, v1), Ilivesin(v0, v1), Rule(724).
input prevent
inv_0(v0, v1) :- influences(v0, v1), Ilivesin(v1, v0), Rule(725).
input prevent
inv_0(v0, v1) :- influences(v1, v0), Ilivesin(v1, v0), Rule(726).
invent_error
inv_0(v0, v1) :- influences(v1, v0), Ilivesin(v0, v1), Rule(727).
type error
inv_0(v0, v1) :- influences(v2, v1), Ilivesin(v0, v2), Rule(728).
type error
inv_0(v0, v1) :- influences(v2, v0), Ilivesin(v1, v2), Rule(730).
type error
inv_0(v0, v1) :- influences(v0, v2), Ilivesin(v1, v2), Rule(732).
type error
inv_0(v0, v1) :- influences(v1, v2), Ilivesin(v0, v2), Rule(735).
Head twice 
inv_0(v0, v1) :- influences(v0, v1), inv_0(v0, v1), Rule(736).
Head twice 
inv_0(v0, v1) :- influences(v1, v0), inv_0(v0, v1), Rule(739).
type error
inv_0(v0, v1) :- actedin(v0, v1), actedin(v1, v0), Rule(749).
type error
inv_0(v0, v1) :- actedin(v1, v0), actedin(v0, v1), Rule(751).
type error
inv_0(v0, v1) :- actedin(v2, v1), actedin(v0, v2), Rule(752).
type error
inv_0(v0, v1) :- actedin(v1, v2), actedin(v2, v0), Rule(753).
type error
inv_0(v0, v1) :- actedin(v2, v0), actedin(v1, v2), Rule(754).
type error
inv_0(v0, v1) :- actedin(v0, v2), actedin(v2, v1), Rule(757).
type error
inv_0(v0, v1) :- actedin(v0, v1), diedin(v0, v1), Rule(760).
type error
inv_0(v0, v1) :- actedin(v0, v1), diedin(v1, v0), Rule(761).
type error
inv_0(v0, v1) :- actedin(v1, v0), diedin(v1, v0), Rule(762).
type error
inv_0(v0, v1) :- actedin(v1, v0), diedin(v0, v1), Rule(763).
type error
inv_0(v0, v1) :- actedin(v2, v1), diedin(v0, v2), Rule(764).
type error
inv_0(v0, v1) :- actedin(v1, v2), diedin(v2, v0), Rule(765).
type error
inv_0(v0, v1) :- actedin(v2, v0), diedin(v1, v2), Rule(766).
type error
inv_0(v0, v1) :- actedin(v0, v2), diedin(v1, v2), Rule(768).
type error
inv_0(v0, v1) :- actedin(v0, v2), diedin(v2, v1), Rule(769).
type error
inv_0(v0, v1) :- actedin(v1, v2), diedin(v0, v2), Rule(771).
type error
inv_0(v0, v1) :- actedin(v0, v1), wasbornin(v0, v1), Rule(772).
type error
inv_0(v0, v1) :- actedin(v0, v1), wasbornin(v1, v0), Rule(773).
type error
inv_0(v0, v1) :- actedin(v1, v0), wasbornin(v1, v0), Rule(774).
type error
inv_0(v0, v1) :- actedin(v1, v0), wasbornin(v0, v1), Rule(775).
type error
inv_0(v0, v1) :- actedin(v2, v1), wasbornin(v0, v2), Rule(776).
type error
inv_0(v0, v1) :- actedin(v1, v2), wasbornin(v2, v0), Rule(777).
type error
inv_0(v0, v1) :- actedin(v2, v0), wasbornin(v1, v2), Rule(778).
type error
inv_0(v0, v1) :- actedin(v0, v2), wasbornin(v1, v2), Rule(780).
type error
inv_0(v0, v1) :- actedin(v0, v2), wasbornin(v2, v1), Rule(781).
type error
inv_0(v0, v1) :- actedin(v1, v2), wasbornin(v0, v2), Rule(783).
type error
inv_0(v0, v1) :- actedin(v0, v1), hasgeonamesid(v0, v1), Rule(784).
type error
inv_0(v0, v1) :- actedin(v0, v1), hasgeonamesid(v1, v0), Rule(785).
type error
inv_0(v0, v1) :- actedin(v1, v0), hasgeonamesid(v1, v0), Rule(786).
type error
inv_0(v0, v1) :- actedin(v1, v0), hasgeonamesid(v0, v1), Rule(787).
type error
inv_0(v0, v1) :- actedin(v2, v1), hasgeonamesid(v0, v2), Rule(788).
type error
inv_0(v0, v1) :- actedin(v1, v2), hasgeonamesid(v2, v0), Rule(789).
type error
inv_0(v0, v1) :- actedin(v2, v0), hasgeonamesid(v1, v2), Rule(790).
type error
inv_0(v0, v1) :- actedin(v2, v0), hasgeonamesid(v2, v1), Rule(791).
type error
inv_0(v0, v1) :- actedin(v0, v2), hasgeonamesid(v1, v2), Rule(792).
type error
inv_0(v0, v1) :- actedin(v0, v2), hasgeonamesid(v2, v1), Rule(793).
type error
inv_0(v0, v1) :- actedin(v2, v1), hasgeonamesid(v2, v0), Rule(794).
type error
inv_0(v0, v1) :- actedin(v1, v2), hasgeonamesid(v0, v2), Rule(795).
type error
inv_0(v0, v1) :- actedin(v0, v1), haswonprize(v0, v1), Rule(796).
type error
inv_0(v0, v1) :- actedin(v0, v1), haswonprize(v1, v0), Rule(797).
type error
inv_0(v0, v1) :- actedin(v1, v0), haswonprize(v1, v0), Rule(798).
type error
inv_0(v0, v1) :- actedin(v1, v0), haswonprize(v0, v1), Rule(799).
type error
inv_0(v0, v1) :- actedin(v2, v1), haswonprize(v0, v2), Rule(800).
type error
inv_0(v0, v1) :- actedin(v1, v2), haswonprize(v2, v0), Rule(801).
type error
inv_0(v0, v1) :- actedin(v2, v0), haswonprize(v1, v2), Rule(802).
type error
inv_0(v0, v1) :- actedin(v2, v0), haswonprize(v2, v1), Rule(803).
type error
inv_0(v0, v1) :- actedin(v0, v2), haswonprize(v1, v2), Rule(804).
type error
inv_0(v0, v1) :- actedin(v0, v2), haswonprize(v2, v1), Rule(805).
type error
inv_0(v0, v1) :- actedin(v2, v1), haswonprize(v2, v0), Rule(806).
type error
inv_0(v0, v1) :- actedin(v1, v2), haswonprize(v0, v2), Rule(807).
type error
inv_0(v0, v1) :- actedin(v0, v1), directed(v1, v0), Rule(809).
type error
inv_0(v0, v1) :- actedin(v1, v0), directed(v0, v1), Rule(811).
type error
inv_0(v0, v1) :- actedin(v2, v1), directed(v0, v2), Rule(812).
type error
inv_0(v0, v1) :- actedin(v1, v2), directed(v2, v0), Rule(813).
type error
inv_0(v0, v1) :- actedin(v2, v0), directed(v1, v2), Rule(814).
type error
inv_0(v0, v1) :- actedin(v0, v2), directed(v2, v1), Rule(817).
type error
inv_0(v0, v1) :- actedin(v0, v1), haschild(v0, v1), Rule(820).
type error
inv_0(v0, v1) :- actedin(v0, v1), haschild(v1, v0), Rule(821).
type error
inv_0(v0, v1) :- actedin(v1, v0), haschild(v1, v0), Rule(822).
type error
inv_0(v0, v1) :- actedin(v1, v0), haschild(v0, v1), Rule(823).
type error
inv_0(v0, v1) :- actedin(v1, v2), haschild(v2, v0), Rule(825).
type error
inv_0(v0, v1) :- actedin(v0, v2), haschild(v1, v2), Rule(828).
type error
inv_0(v0, v1) :- actedin(v0, v2), haschild(v2, v1), Rule(829).
type error
inv_0(v0, v1) :- actedin(v1, v2), haschild(v0, v2), Rule(831).
invent_error
inv_0(v0, v1) :- actedin(v0, v1), Ilivesin(v0, v1), Rule(832).
input prevent
inv_0(v0, v1) :- actedin(v0, v1), Ilivesin(v1, v0), Rule(833).
input prevent
inv_0(v0, v1) :- actedin(v1, v0), Ilivesin(v1, v0), Rule(834).
invent_error
inv_0(v0, v1) :- actedin(v1, v0), Ilivesin(v0, v1), Rule(835).
type error
inv_0(v0, v1) :- actedin(v2, v1), Ilivesin(v0, v2), Rule(836).
type error
inv_0(v0, v1) :- actedin(v1, v2), Ilivesin(v2, v0), Rule(837).
type error
inv_0(v0, v1) :- actedin(v2, v0), Ilivesin(v1, v2), Rule(838).
type error
inv_0(v0, v1) :- actedin(v0, v2), Ilivesin(v1, v2), Rule(840).
type error
inv_0(v0, v1) :- actedin(v0, v2), Ilivesin(v2, v1), Rule(841).
type error
inv_0(v0, v1) :- actedin(v1, v2), Ilivesin(v0, v2), Rule(843).
Head twice 
inv_0(v0, v1) :- actedin(v0, v1), inv_0(v0, v1), Rule(844).
Head twice 
inv_0(v0, v1) :- actedin(v1, v0), inv_0(v0, v1), Rule(847).
type error
inv_0(v0, v1) :- diedin(v0, v1), diedin(v1, v0), Rule(857).
type error
inv_0(v0, v1) :- diedin(v1, v0), diedin(v0, v1), Rule(859).
type error
inv_0(v0, v1) :- diedin(v2, v1), diedin(v0, v2), Rule(860).
type error
inv_0(v0, v1) :- diedin(v1, v2), diedin(v2, v0), Rule(861).
type error
inv_0(v0, v1) :- diedin(v2, v0), diedin(v1, v2), Rule(862).
type error
inv_0(v0, v1) :- diedin(v0, v2), diedin(v2, v1), Rule(865).
type error
inv_0(v0, v1) :- diedin(v0, v1), wasbornin(v1, v0), Rule(869).
type error
inv_0(v0, v1) :- diedin(v1, v0), wasbornin(v0, v1), Rule(871).
type error
inv_0(v0, v1) :- diedin(v2, v1), wasbornin(v0, v2), Rule(872).
type error
inv_0(v0, v1) :- diedin(v1, v2), wasbornin(v2, v0), Rule(873).
type error
inv_0(v0, v1) :- diedin(v2, v0), wasbornin(v1, v2), Rule(874).
type error
inv_0(v0, v1) :- diedin(v0, v2), wasbornin(v2, v1), Rule(877).
type error
inv_0(v0, v1) :- diedin(v0, v1), hasgeonamesid(v0, v1), Rule(880).
type error
inv_0(v0, v1) :- diedin(v0, v1), hasgeonamesid(v1, v0), Rule(881).
type error
inv_0(v0, v1) :- diedin(v1, v0), hasgeonamesid(v1, v0), Rule(882).
type error
inv_0(v0, v1) :- diedin(v1, v0), hasgeonamesid(v0, v1), Rule(883).
type error
inv_0(v0, v1) :- diedin(v2, v1), hasgeonamesid(v0, v2), Rule(884).
type error
inv_0(v0, v1) :- diedin(v2, v0), hasgeonamesid(v1, v2), Rule(886).
type error
inv_0(v0, v1) :- diedin(v2, v0), hasgeonamesid(v2, v1), Rule(887).
type error
inv_0(v0, v1) :- diedin(v0, v2), hasgeonamesid(v1, v2), Rule(888).
type error
inv_0(v0, v1) :- diedin(v2, v1), hasgeonamesid(v2, v0), Rule(890).
type error
inv_0(v0, v1) :- diedin(v1, v2), hasgeonamesid(v0, v2), Rule(891).
type error
inv_0(v0, v1) :- diedin(v0, v1), haswonprize(v0, v1), Rule(892).
type error
inv_0(v0, v1) :- diedin(v0, v1), haswonprize(v1, v0), Rule(893).
type error
inv_0(v0, v1) :- diedin(v1, v0), haswonprize(v1, v0), Rule(894).
type error
inv_0(v0, v1) :- diedin(v1, v0), haswonprize(v0, v1), Rule(895).
type error
inv_0(v0, v1) :- diedin(v2, v1), haswonprize(v0, v2), Rule(896).
type error
inv_0(v0, v1) :- diedin(v1, v2), haswonprize(v2, v0), Rule(897).
type error
inv_0(v0, v1) :- diedin(v2, v0), haswonprize(v1, v2), Rule(898).
type error
inv_0(v0, v1) :- diedin(v2, v0), haswonprize(v2, v1), Rule(899).
type error
inv_0(v0, v1) :- diedin(v0, v2), haswonprize(v1, v2), Rule(900).
type error
inv_0(v0, v1) :- diedin(v0, v2), haswonprize(v2, v1), Rule(901).
type error
inv_0(v0, v1) :- diedin(v2, v1), haswonprize(v2, v0), Rule(902).
type error
inv_0(v0, v1) :- diedin(v1, v2), haswonprize(v0, v2), Rule(903).
type error
inv_0(v0, v1) :- diedin(v0, v1), directed(v0, v1), Rule(904).
type error
inv_0(v0, v1) :- diedin(v0, v1), directed(v1, v0), Rule(905).
type error
inv_0(v0, v1) :- diedin(v1, v0), directed(v1, v0), Rule(906).
type error
inv_0(v0, v1) :- diedin(v1, v0), directed(v0, v1), Rule(907).
type error
inv_0(v0, v1) :- diedin(v2, v1), directed(v0, v2), Rule(908).
type error
inv_0(v0, v1) :- diedin(v1, v2), directed(v2, v0), Rule(909).
type error
inv_0(v0, v1) :- diedin(v2, v0), directed(v1, v2), Rule(910).
type error
inv_0(v0, v1) :- diedin(v0, v2), directed(v1, v2), Rule(912).
type error
inv_0(v0, v1) :- diedin(v0, v2), directed(v2, v1), Rule(913).
type error
inv_0(v0, v1) :- diedin(v1, v2), directed(v0, v2), Rule(915).
type error
inv_0(v0, v1) :- diedin(v0, v1), haschild(v0, v1), Rule(916).
type error
inv_0(v0, v1) :- diedin(v0, v1), haschild(v1, v0), Rule(917).
type error
inv_0(v0, v1) :- diedin(v1, v0), haschild(v1, v0), Rule(918).
type error
inv_0(v0, v1) :- diedin(v1, v0), haschild(v0, v1), Rule(919).
type error
inv_0(v0, v1) :- diedin(v1, v2), haschild(v2, v0), Rule(921).
type error
inv_0(v0, v1) :- diedin(v0, v2), haschild(v1, v2), Rule(924).
type error
inv_0(v0, v1) :- diedin(v0, v2), haschild(v2, v1), Rule(925).
type error
inv_0(v0, v1) :- diedin(v1, v2), haschild(v0, v2), Rule(927).
invent_error
inv_0(v0, v1) :- diedin(v0, v1), Ilivesin(v0, v1), Rule(928).
input prevent
inv_0(v0, v1) :- diedin(v0, v1), Ilivesin(v1, v0), Rule(929).
input prevent
inv_0(v0, v1) :- diedin(v1, v0), Ilivesin(v1, v0), Rule(930).
invent_error
inv_0(v0, v1) :- diedin(v1, v0), Ilivesin(v0, v1), Rule(931).
type error
inv_0(v0, v1) :- diedin(v2, v1), Ilivesin(v0, v2), Rule(932).
type error
inv_0(v0, v1) :- diedin(v1, v2), Ilivesin(v2, v0), Rule(933).
type error
inv_0(v0, v1) :- diedin(v2, v0), Ilivesin(v1, v2), Rule(934).
type error
inv_0(v0, v1) :- diedin(v0, v2), Ilivesin(v2, v1), Rule(937).
Head twice 
inv_0(v0, v1) :- diedin(v0, v1), inv_0(v0, v1), Rule(940).
Head twice 
inv_0(v0, v1) :- diedin(v1, v0), inv_0(v0, v1), Rule(943).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), wasbornin(v1, v0), Rule(953).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), wasbornin(v0, v1), Rule(955).
type error
inv_0(v0, v1) :- wasbornin(v2, v1), wasbornin(v0, v2), Rule(956).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), wasbornin(v2, v0), Rule(957).
type error
inv_0(v0, v1) :- wasbornin(v2, v0), wasbornin(v1, v2), Rule(958).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), wasbornin(v2, v1), Rule(961).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), hasgeonamesid(v0, v1), Rule(964).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), hasgeonamesid(v1, v0), Rule(965).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), hasgeonamesid(v1, v0), Rule(966).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), hasgeonamesid(v0, v1), Rule(967).
type error
inv_0(v0, v1) :- wasbornin(v2, v1), hasgeonamesid(v0, v2), Rule(968).
type error
inv_0(v0, v1) :- wasbornin(v2, v0), hasgeonamesid(v1, v2), Rule(970).
type error
inv_0(v0, v1) :- wasbornin(v2, v0), hasgeonamesid(v2, v1), Rule(971).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), hasgeonamesid(v1, v2), Rule(972).
type error
inv_0(v0, v1) :- wasbornin(v2, v1), hasgeonamesid(v2, v0), Rule(974).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), hasgeonamesid(v0, v2), Rule(975).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), haswonprize(v0, v1), Rule(976).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), haswonprize(v1, v0), Rule(977).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), haswonprize(v1, v0), Rule(978).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), haswonprize(v0, v1), Rule(979).
type error
inv_0(v0, v1) :- wasbornin(v2, v1), haswonprize(v0, v2), Rule(980).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), haswonprize(v2, v0), Rule(981).
type error
inv_0(v0, v1) :- wasbornin(v2, v0), haswonprize(v1, v2), Rule(982).
type error
inv_0(v0, v1) :- wasbornin(v2, v0), haswonprize(v2, v1), Rule(983).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), haswonprize(v1, v2), Rule(984).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), haswonprize(v2, v1), Rule(985).
type error
inv_0(v0, v1) :- wasbornin(v2, v1), haswonprize(v2, v0), Rule(986).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), haswonprize(v0, v2), Rule(987).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), directed(v0, v1), Rule(988).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), directed(v1, v0), Rule(989).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), directed(v1, v0), Rule(990).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), directed(v0, v1), Rule(991).
type error
inv_0(v0, v1) :- wasbornin(v2, v1), directed(v0, v2), Rule(992).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), directed(v2, v0), Rule(993).
type error
inv_0(v0, v1) :- wasbornin(v2, v0), directed(v1, v2), Rule(994).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), directed(v1, v2), Rule(996).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), directed(v2, v1), Rule(997).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), directed(v0, v2), Rule(999).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), haschild(v0, v1), Rule(1000).
type error
inv_0(v0, v1) :- wasbornin(v0, v1), haschild(v1, v0), Rule(1001).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), haschild(v1, v0), Rule(1002).
type error
inv_0(v0, v1) :- wasbornin(v1, v0), haschild(v0, v1), Rule(1003).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), haschild(v2, v0), Rule(1005).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), haschild(v1, v2), Rule(1008).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), haschild(v2, v1), Rule(1009).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), haschild(v0, v2), Rule(1011).
invent_error
inv_0(v0, v1) :- wasbornin(v0, v1), Ilivesin(v0, v1), Rule(1012).
input prevent
inv_0(v0, v1) :- wasbornin(v0, v1), Ilivesin(v1, v0), Rule(1013).
input prevent
inv_0(v0, v1) :- wasbornin(v1, v0), Ilivesin(v1, v0), Rule(1014).
invent_error
inv_0(v0, v1) :- wasbornin(v1, v0), Ilivesin(v0, v1), Rule(1015).
type error
inv_0(v0, v1) :- wasbornin(v2, v1), Ilivesin(v0, v2), Rule(1016).
type error
inv_0(v0, v1) :- wasbornin(v1, v2), Ilivesin(v2, v0), Rule(1017).
type error
inv_0(v0, v1) :- wasbornin(v2, v0), Ilivesin(v1, v2), Rule(1018).
type error
inv_0(v0, v1) :- wasbornin(v0, v2), Ilivesin(v2, v1), Rule(1021).
Head twice 
inv_0(v0, v1) :- wasbornin(v0, v1), inv_0(v0, v1), Rule(1024).
Head twice 
inv_0(v0, v1) :- wasbornin(v1, v0), inv_0(v0, v1), Rule(1027).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), hasgeonamesid(v1, v0), Rule(1037).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), hasgeonamesid(v0, v1), Rule(1039).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), hasgeonamesid(v0, v2), Rule(1040).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), hasgeonamesid(v2, v0), Rule(1041).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), hasgeonamesid(v1, v2), Rule(1042).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), hasgeonamesid(v2, v1), Rule(1045).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), haswonprize(v0, v1), Rule(1048).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), haswonprize(v1, v0), Rule(1049).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), haswonprize(v1, v0), Rule(1050).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), haswonprize(v0, v1), Rule(1051).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), haswonprize(v0, v2), Rule(1052).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), haswonprize(v1, v2), Rule(1054).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), haswonprize(v2, v1), Rule(1055).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), haswonprize(v1, v2), Rule(1056).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), haswonprize(v2, v0), Rule(1058).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), haswonprize(v0, v2), Rule(1059).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), directed(v0, v1), Rule(1060).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), directed(v1, v0), Rule(1061).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), directed(v1, v0), Rule(1062).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), directed(v0, v1), Rule(1063).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), directed(v0, v2), Rule(1064).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), directed(v2, v0), Rule(1065).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), directed(v1, v2), Rule(1066).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), directed(v2, v1), Rule(1067).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), directed(v1, v2), Rule(1068).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), directed(v2, v1), Rule(1069).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), directed(v2, v0), Rule(1070).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), directed(v0, v2), Rule(1071).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), haschild(v0, v1), Rule(1072).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), haschild(v1, v0), Rule(1073).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), haschild(v1, v0), Rule(1074).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), haschild(v0, v1), Rule(1075).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), haschild(v0, v2), Rule(1076).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), haschild(v2, v0), Rule(1077).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), haschild(v1, v2), Rule(1078).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), haschild(v2, v1), Rule(1079).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), haschild(v1, v2), Rule(1080).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), haschild(v2, v1), Rule(1081).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), haschild(v2, v0), Rule(1082).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), haschild(v0, v2), Rule(1083).
invent_error
inv_0(v0, v1) :- hasgeonamesid(v0, v1), Ilivesin(v0, v1), Rule(1084).
input prevent
inv_0(v0, v1) :- hasgeonamesid(v0, v1), Ilivesin(v1, v0), Rule(1085).
input prevent
inv_0(v0, v1) :- hasgeonamesid(v1, v0), Ilivesin(v1, v0), Rule(1086).
invent_error
inv_0(v0, v1) :- hasgeonamesid(v1, v0), Ilivesin(v0, v1), Rule(1087).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), Ilivesin(v2, v0), Rule(1089).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v0), Ilivesin(v2, v1), Rule(1091).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), Ilivesin(v1, v2), Rule(1092).
type error
inv_0(v0, v1) :- hasgeonamesid(v0, v2), Ilivesin(v2, v1), Rule(1093).
type error
inv_0(v0, v1) :- hasgeonamesid(v2, v1), Ilivesin(v2, v0), Rule(1094).
type error
inv_0(v0, v1) :- hasgeonamesid(v1, v2), Ilivesin(v0, v2), Rule(1095).
Head twice 
inv_0(v0, v1) :- hasgeonamesid(v0, v1), inv_0(v0, v1), Rule(1096).
Head twice 
inv_0(v0, v1) :- hasgeonamesid(v1, v0), inv_0(v0, v1), Rule(1099).
type error
inv_0(v0, v1) :- haswonprize(v0, v1), haswonprize(v1, v0), Rule(1109).
type error
inv_0(v0, v1) :- haswonprize(v1, v0), haswonprize(v0, v1), Rule(1111).
type error
inv_0(v0, v1) :- haswonprize(v2, v1), haswonprize(v0, v2), Rule(1112).
type error
inv_0(v0, v1) :- haswonprize(v1, v2), haswonprize(v2, v0), Rule(1113).
type error
inv_0(v0, v1) :- haswonprize(v2, v0), haswonprize(v1, v2), Rule(1114).
type error
inv_0(v0, v1) :- haswonprize(v0, v2), haswonprize(v2, v1), Rule(1117).
type error
inv_0(v0, v1) :- haswonprize(v0, v1), directed(v0, v1), Rule(1120).
type error
inv_0(v0, v1) :- haswonprize(v0, v1), directed(v1, v0), Rule(1121).
type error
inv_0(v0, v1) :- haswonprize(v1, v0), directed(v1, v0), Rule(1122).
type error
inv_0(v0, v1) :- haswonprize(v1, v0), directed(v0, v1), Rule(1123).
type error
inv_0(v0, v1) :- haswonprize(v2, v1), directed(v0, v2), Rule(1124).
type error
inv_0(v0, v1) :- haswonprize(v1, v2), directed(v2, v0), Rule(1125).
type error
inv_0(v0, v1) :- haswonprize(v2, v0), directed(v1, v2), Rule(1126).
type error
inv_0(v0, v1) :- haswonprize(v2, v0), directed(v2, v1), Rule(1127).
type error
inv_0(v0, v1) :- haswonprize(v0, v2), directed(v1, v2), Rule(1128).
type error
inv_0(v0, v1) :- haswonprize(v0, v2), directed(v2, v1), Rule(1129).
type error
inv_0(v0, v1) :- haswonprize(v2, v1), directed(v2, v0), Rule(1130).
type error
inv_0(v0, v1) :- haswonprize(v1, v2), directed(v0, v2), Rule(1131).
type error
inv_0(v0, v1) :- haswonprize(v0, v1), haschild(v0, v1), Rule(1132).
type error
inv_0(v0, v1) :- haswonprize(v0, v1), haschild(v1, v0), Rule(1133).
type error
inv_0(v0, v1) :- haswonprize(v1, v0), haschild(v1, v0), Rule(1134).
type error
inv_0(v0, v1) :- haswonprize(v1, v0), haschild(v0, v1), Rule(1135).
type error
inv_0(v0, v1) :- haswonprize(v2, v1), haschild(v0, v2), Rule(1136).
type error
inv_0(v0, v1) :- haswonprize(v1, v2), haschild(v2, v0), Rule(1137).
type error
inv_0(v0, v1) :- haswonprize(v2, v0), haschild(v1, v2), Rule(1138).
type error
inv_0(v0, v1) :- haswonprize(v2, v0), haschild(v2, v1), Rule(1139).
type error
inv_0(v0, v1) :- haswonprize(v0, v2), haschild(v1, v2), Rule(1140).
type error
inv_0(v0, v1) :- haswonprize(v0, v2), haschild(v2, v1), Rule(1141).
type error
inv_0(v0, v1) :- haswonprize(v2, v1), haschild(v2, v0), Rule(1142).
type error
inv_0(v0, v1) :- haswonprize(v1, v2), haschild(v0, v2), Rule(1143).
invent_error
inv_0(v0, v1) :- haswonprize(v0, v1), Ilivesin(v0, v1), Rule(1144).
input prevent
inv_0(v0, v1) :- haswonprize(v0, v1), Ilivesin(v1, v0), Rule(1145).
input prevent
inv_0(v0, v1) :- haswonprize(v1, v0), Ilivesin(v1, v0), Rule(1146).
invent_error
inv_0(v0, v1) :- haswonprize(v1, v0), Ilivesin(v0, v1), Rule(1147).
type error
inv_0(v0, v1) :- haswonprize(v2, v1), Ilivesin(v0, v2), Rule(1148).
type error
inv_0(v0, v1) :- haswonprize(v1, v2), Ilivesin(v2, v0), Rule(1149).
type error
inv_0(v0, v1) :- haswonprize(v2, v0), Ilivesin(v1, v2), Rule(1150).
type error
inv_0(v0, v1) :- haswonprize(v2, v0), Ilivesin(v2, v1), Rule(1151).
type error
inv_0(v0, v1) :- haswonprize(v0, v2), Ilivesin(v1, v2), Rule(1152).
type error
inv_0(v0, v1) :- haswonprize(v0, v2), Ilivesin(v2, v1), Rule(1153).
type error
inv_0(v0, v1) :- haswonprize(v2, v1), Ilivesin(v2, v0), Rule(1154).
type error
inv_0(v0, v1) :- haswonprize(v1, v2), Ilivesin(v0, v2), Rule(1155).
Head twice 
inv_0(v0, v1) :- haswonprize(v0, v1), inv_0(v0, v1), Rule(1156).
Head twice 
inv_0(v0, v1) :- haswonprize(v1, v0), inv_0(v0, v1), Rule(1159).
type error
inv_0(v0, v1) :- directed(v0, v1), directed(v1, v0), Rule(1169).
type error
inv_0(v0, v1) :- directed(v1, v0), directed(v0, v1), Rule(1171).
type error
inv_0(v0, v1) :- directed(v2, v1), directed(v0, v2), Rule(1172).
type error
inv_0(v0, v1) :- directed(v1, v2), directed(v2, v0), Rule(1173).
type error
inv_0(v0, v1) :- directed(v2, v0), directed(v1, v2), Rule(1174).
type error
inv_0(v0, v1) :- directed(v0, v2), directed(v2, v1), Rule(1177).
type error
inv_0(v0, v1) :- directed(v0, v1), haschild(v0, v1), Rule(1180).
type error
inv_0(v0, v1) :- directed(v0, v1), haschild(v1, v0), Rule(1181).
type error
inv_0(v0, v1) :- directed(v1, v0), haschild(v1, v0), Rule(1182).
type error
inv_0(v0, v1) :- directed(v1, v0), haschild(v0, v1), Rule(1183).
type error
inv_0(v0, v1) :- directed(v1, v2), haschild(v2, v0), Rule(1185).
type error
inv_0(v0, v1) :- directed(v0, v2), haschild(v1, v2), Rule(1188).
type error
inv_0(v0, v1) :- directed(v0, v2), haschild(v2, v1), Rule(1189).
type error
inv_0(v0, v1) :- directed(v1, v2), haschild(v0, v2), Rule(1191).
invent_error
inv_0(v0, v1) :- directed(v0, v1), Ilivesin(v0, v1), Rule(1192).
input prevent
inv_0(v0, v1) :- directed(v0, v1), Ilivesin(v1, v0), Rule(1193).
input prevent
inv_0(v0, v1) :- directed(v1, v0), Ilivesin(v1, v0), Rule(1194).
invent_error
inv_0(v0, v1) :- directed(v1, v0), Ilivesin(v0, v1), Rule(1195).
type error
inv_0(v0, v1) :- directed(v2, v1), Ilivesin(v0, v2), Rule(1196).
type error
inv_0(v0, v1) :- directed(v1, v2), Ilivesin(v2, v0), Rule(1197).
type error
inv_0(v0, v1) :- directed(v2, v0), Ilivesin(v1, v2), Rule(1198).
type error
inv_0(v0, v1) :- directed(v0, v2), Ilivesin(v1, v2), Rule(1200).
type error
inv_0(v0, v1) :- directed(v0, v2), Ilivesin(v2, v1), Rule(1201).
type error
inv_0(v0, v1) :- directed(v1, v2), Ilivesin(v0, v2), Rule(1203).
Head twice 
inv_0(v0, v1) :- directed(v0, v1), inv_0(v0, v1), Rule(1204).
Head twice 
inv_0(v0, v1) :- directed(v1, v0), inv_0(v0, v1), Rule(1207).
invent_error
inv_0(v0, v1) :- haschild(v0, v1), Ilivesin(v0, v1), Rule(1228).
input prevent
inv_0(v0, v1) :- haschild(v0, v1), Ilivesin(v1, v0), Rule(1229).
input prevent
inv_0(v0, v1) :- haschild(v1, v0), Ilivesin(v1, v0), Rule(1230).
invent_error
inv_0(v0, v1) :- haschild(v1, v0), Ilivesin(v0, v1), Rule(1231).
type error
inv_0(v0, v1) :- haschild(v2, v1), Ilivesin(v0, v2), Rule(1232).
type error
inv_0(v0, v1) :- haschild(v2, v0), Ilivesin(v1, v2), Rule(1234).
type error
inv_0(v0, v1) :- haschild(v0, v2), Ilivesin(v1, v2), Rule(1236).
type error
inv_0(v0, v1) :- haschild(v1, v2), Ilivesin(v0, v2), Rule(1239).
Head twice 
inv_0(v0, v1) :- haschild(v0, v1), inv_0(v0, v1), Rule(1240).
Head twice 
inv_0(v0, v1) :- haschild(v1, v0), inv_0(v0, v1), Rule(1243).
invent_error
inv_0(v0, v1) :- Ilivesin(v0, v1), Ilivesin(v0, v1), Rule(1252).
input prevent
inv_0(v0, v1) :- Ilivesin(v0, v1), Ilivesin(v1, v0), Rule(1253).
input prevent
inv_0(v0, v1) :- Ilivesin(v1, v0), Ilivesin(v1, v0), Rule(1254).
input prevent
inv_0(v0, v1) :- Ilivesin(v1, v0), Ilivesin(v0, v1), Rule(1255).
type error
inv_0(v0, v1) :- Ilivesin(v2, v1), Ilivesin(v0, v2), Rule(1256).
type error
inv_0(v0, v1) :- Ilivesin(v1, v2), Ilivesin(v2, v0), Rule(1257).
type error
inv_0(v0, v1) :- Ilivesin(v2, v0), Ilivesin(v1, v2), Rule(1258).
type error
inv_0(v0, v1) :- Ilivesin(v0, v2), Ilivesin(v2, v1), Rule(1261).
Head twice 
inv_0(v0, v1) :- Ilivesin(v0, v1), inv_0(v0, v1), Rule(1264).
invent_error
inv_0(v0, v1) :- Ilivesin(v0, v1), inv_0(v1, v0), Rule(1265).
input prevent
inv_0(v0, v1) :- Ilivesin(v1, v0), inv_0(v1, v0), Rule(1266).
Head twice 
inv_0(v0, v1) :- Ilivesin(v1, v0), inv_0(v0, v1), Rule(1267).
Head twice 
inv_0(v0, v1) :- inv_0(v0, v1), inv_0(v0, v1), Rule(1276).
Head twice 
inv_0(v0, v1) :- inv_0(v0, v1), inv_0(v1, v0), Rule(1277).
Head twice 
inv_0(v0, v1) :- inv_0(v1, v0), inv_0(v0, v1), Rule(1279).
type error
livesin(v0, v1) :- islocatedin(v0, v1), Rule(1288).
type error
livesin(v0, v1) :- islocatedin(v1, v0), Rule(1289).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), Rule(1290).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), Rule(1291).
type error
livesin(v0, v1) :- created(v0, v1), Rule(1292).
type error
livesin(v0, v1) :- created(v1, v0), Rule(1293).
type error
livesin(v0, v1) :- influences(v0, v1), Rule(1296).
type error
livesin(v0, v1) :- influences(v1, v0), Rule(1297).
type error
livesin(v0, v1) :- actedin(v0, v1), Rule(1298).
type error
livesin(v0, v1) :- actedin(v1, v0), Rule(1299).
type error
livesin(v0, v1) :- diedin(v1, v0), Rule(1301).
type error
livesin(v0, v1) :- wasbornin(v1, v0), Rule(1303).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), Rule(1304).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), Rule(1305).
type error
livesin(v0, v1) :- haswonprize(v0, v1), Rule(1306).
type error
livesin(v0, v1) :- haswonprize(v1, v0), Rule(1307).
type error
livesin(v0, v1) :- directed(v0, v1), Rule(1308).
type error
livesin(v0, v1) :- directed(v1, v0), Rule(1309).
type error
livesin(v0, v1) :- haschild(v0, v1), Rule(1310).
type error
livesin(v0, v1) :- haschild(v1, v0), Rule(1311).
Head twice 
livesin(v0, v1) :- Ilivesin(v0, v1), Rule(1312).
input prevent
livesin(v0, v1) :- Ilivesin(v1, v0), Rule(1313).
Head twice 
livesin(v0, v1) :- livesin(v0, v1), Rule(1316).
type error
livesin(v0, v1) :- livesin(v1, v0), Rule(1317).
type error
livesin(v0, v1) :- islocatedin(v0, v1), islocatedin(v0, v1), Rule(1318).
type error
livesin(v0, v1) :- islocatedin(v0, v1), islocatedin(v1, v0), Rule(1319).
type error
livesin(v0, v1) :- islocatedin(v1, v0), islocatedin(v1, v0), Rule(1320).
type error
livesin(v0, v1) :- islocatedin(v1, v0), islocatedin(v0, v1), Rule(1321).
type error
livesin(v0, v1) :- islocatedin(v2, v1), islocatedin(v0, v2), Rule(1322).
type error
livesin(v0, v1) :- islocatedin(v1, v2), islocatedin(v2, v0), Rule(1323).
type error
livesin(v0, v1) :- islocatedin(v2, v0), islocatedin(v1, v2), Rule(1324).
type error
livesin(v0, v1) :- islocatedin(v2, v0), islocatedin(v2, v1), Rule(1325).
type error
livesin(v0, v1) :- islocatedin(v0, v2), islocatedin(v1, v2), Rule(1326).
type error
livesin(v0, v1) :- islocatedin(v0, v2), islocatedin(v2, v1), Rule(1327).
type error
livesin(v0, v1) :- islocatedin(v2, v1), islocatedin(v2, v0), Rule(1328).
type error
livesin(v0, v1) :- islocatedin(v1, v2), islocatedin(v0, v2), Rule(1329).
type error
livesin(v0, v1) :- islocatedin(v0, v1), ismarriedto(v0, v1), Rule(1330).
type error
livesin(v0, v1) :- islocatedin(v0, v1), ismarriedto(v1, v0), Rule(1331).
type error
livesin(v0, v1) :- islocatedin(v1, v0), ismarriedto(v1, v0), Rule(1332).
type error
livesin(v0, v1) :- islocatedin(v1, v0), ismarriedto(v0, v1), Rule(1333).
type error
livesin(v0, v1) :- islocatedin(v2, v1), ismarriedto(v0, v2), Rule(1334).
type error
livesin(v0, v1) :- islocatedin(v1, v2), ismarriedto(v2, v0), Rule(1335).
type error
livesin(v0, v1) :- islocatedin(v2, v0), ismarriedto(v1, v2), Rule(1336).
type error
livesin(v0, v1) :- islocatedin(v2, v0), ismarriedto(v2, v1), Rule(1337).
type error
livesin(v0, v1) :- islocatedin(v0, v2), ismarriedto(v1, v2), Rule(1338).
type error
livesin(v0, v1) :- islocatedin(v0, v2), ismarriedto(v2, v1), Rule(1339).
type error
livesin(v0, v1) :- islocatedin(v2, v1), ismarriedto(v2, v0), Rule(1340).
type error
livesin(v0, v1) :- islocatedin(v1, v2), ismarriedto(v0, v2), Rule(1341).
type error
livesin(v0, v1) :- islocatedin(v0, v1), created(v0, v1), Rule(1342).
type error
livesin(v0, v1) :- islocatedin(v0, v1), created(v1, v0), Rule(1343).
type error
livesin(v0, v1) :- islocatedin(v1, v0), created(v1, v0), Rule(1344).
type error
livesin(v0, v1) :- islocatedin(v1, v0), created(v0, v1), Rule(1345).
type error
livesin(v0, v1) :- islocatedin(v1, v2), created(v2, v0), Rule(1347).
type error
livesin(v0, v1) :- islocatedin(v2, v0), created(v1, v2), Rule(1348).
type error
livesin(v0, v1) :- islocatedin(v2, v0), created(v2, v1), Rule(1349).
type error
livesin(v0, v1) :- islocatedin(v0, v2), created(v1, v2), Rule(1350).
type error
livesin(v0, v1) :- islocatedin(v0, v2), created(v2, v1), Rule(1351).
type error
livesin(v0, v1) :- islocatedin(v2, v1), created(v2, v0), Rule(1352).
type error
livesin(v0, v1) :- islocatedin(v1, v2), created(v0, v2), Rule(1353).
type error
livesin(v0, v1) :- islocatedin(v0, v1), participatedin(v0, v1), Rule(1354).
type error
livesin(v0, v1) :- islocatedin(v0, v1), participatedin(v1, v0), Rule(1355).
type error
livesin(v0, v1) :- islocatedin(v1, v0), participatedin(v1, v0), Rule(1356).
type error
livesin(v0, v1) :- islocatedin(v1, v0), participatedin(v0, v1), Rule(1357).
type error
livesin(v0, v1) :- islocatedin(v1, v2), participatedin(v2, v0), Rule(1359).
type error
livesin(v0, v1) :- islocatedin(v2, v0), participatedin(v1, v2), Rule(1360).
type error
livesin(v0, v1) :- islocatedin(v2, v0), participatedin(v2, v1), Rule(1361).
type error
livesin(v0, v1) :- islocatedin(v0, v2), participatedin(v1, v2), Rule(1362).
type error
livesin(v0, v1) :- islocatedin(v0, v2), participatedin(v2, v1), Rule(1363).
type error
livesin(v0, v1) :- islocatedin(v1, v2), participatedin(v0, v2), Rule(1365).
type error
livesin(v0, v1) :- islocatedin(v0, v1), influences(v0, v1), Rule(1366).
type error
livesin(v0, v1) :- islocatedin(v0, v1), influences(v1, v0), Rule(1367).
type error
livesin(v0, v1) :- islocatedin(v1, v0), influences(v1, v0), Rule(1368).
type error
livesin(v0, v1) :- islocatedin(v1, v0), influences(v0, v1), Rule(1369).
type error
livesin(v0, v1) :- islocatedin(v2, v1), influences(v0, v2), Rule(1370).
type error
livesin(v0, v1) :- islocatedin(v1, v2), influences(v2, v0), Rule(1371).
type error
livesin(v0, v1) :- islocatedin(v2, v0), influences(v1, v2), Rule(1372).
type error
livesin(v0, v1) :- islocatedin(v2, v0), influences(v2, v1), Rule(1373).
type error
livesin(v0, v1) :- islocatedin(v0, v2), influences(v1, v2), Rule(1374).
type error
livesin(v0, v1) :- islocatedin(v0, v2), influences(v2, v1), Rule(1375).
type error
livesin(v0, v1) :- islocatedin(v2, v1), influences(v2, v0), Rule(1376).
type error
livesin(v0, v1) :- islocatedin(v1, v2), influences(v0, v2), Rule(1377).
type error
livesin(v0, v1) :- islocatedin(v0, v1), actedin(v0, v1), Rule(1378).
type error
livesin(v0, v1) :- islocatedin(v0, v1), actedin(v1, v0), Rule(1379).
type error
livesin(v0, v1) :- islocatedin(v1, v0), actedin(v1, v0), Rule(1380).
type error
livesin(v0, v1) :- islocatedin(v1, v0), actedin(v0, v1), Rule(1381).
type error
livesin(v0, v1) :- islocatedin(v2, v1), actedin(v0, v2), Rule(1382).
type error
livesin(v0, v1) :- islocatedin(v1, v2), actedin(v2, v0), Rule(1383).
type error
livesin(v0, v1) :- islocatedin(v2, v0), actedin(v1, v2), Rule(1384).
type error
livesin(v0, v1) :- islocatedin(v2, v0), actedin(v2, v1), Rule(1385).
type error
livesin(v0, v1) :- islocatedin(v0, v2), actedin(v1, v2), Rule(1386).
type error
livesin(v0, v1) :- islocatedin(v0, v2), actedin(v2, v1), Rule(1387).
type error
livesin(v0, v1) :- islocatedin(v2, v1), actedin(v2, v0), Rule(1388).
type error
livesin(v0, v1) :- islocatedin(v1, v2), actedin(v0, v2), Rule(1389).
type error
livesin(v0, v1) :- islocatedin(v0, v1), diedin(v0, v1), Rule(1390).
type error
livesin(v0, v1) :- islocatedin(v0, v1), diedin(v1, v0), Rule(1391).
type error
livesin(v0, v1) :- islocatedin(v1, v0), diedin(v1, v0), Rule(1392).
type error
livesin(v0, v1) :- islocatedin(v1, v0), diedin(v0, v1), Rule(1393).
type error
livesin(v0, v1) :- islocatedin(v2, v1), diedin(v0, v2), Rule(1394).
type error
livesin(v0, v1) :- islocatedin(v1, v2), diedin(v2, v0), Rule(1395).
type error
livesin(v0, v1) :- islocatedin(v2, v0), diedin(v1, v2), Rule(1396).
type error
livesin(v0, v1) :- islocatedin(v2, v0), diedin(v2, v1), Rule(1397).
type error
livesin(v0, v1) :- islocatedin(v0, v2), diedin(v1, v2), Rule(1398).
type error
livesin(v0, v1) :- islocatedin(v0, v2), diedin(v2, v1), Rule(1399).
type error
livesin(v0, v1) :- islocatedin(v2, v1), diedin(v2, v0), Rule(1400).
type error
livesin(v0, v1) :- islocatedin(v1, v2), diedin(v0, v2), Rule(1401).
type error
livesin(v0, v1) :- islocatedin(v0, v1), wasbornin(v0, v1), Rule(1402).
type error
livesin(v0, v1) :- islocatedin(v0, v1), wasbornin(v1, v0), Rule(1403).
type error
livesin(v0, v1) :- islocatedin(v1, v0), wasbornin(v1, v0), Rule(1404).
type error
livesin(v0, v1) :- islocatedin(v1, v0), wasbornin(v0, v1), Rule(1405).
type error
livesin(v0, v1) :- islocatedin(v2, v1), wasbornin(v0, v2), Rule(1406).
type error
livesin(v0, v1) :- islocatedin(v1, v2), wasbornin(v2, v0), Rule(1407).
type error
livesin(v0, v1) :- islocatedin(v2, v0), wasbornin(v1, v2), Rule(1408).
type error
livesin(v0, v1) :- islocatedin(v2, v0), wasbornin(v2, v1), Rule(1409).
type error
livesin(v0, v1) :- islocatedin(v0, v2), wasbornin(v1, v2), Rule(1410).
type error
livesin(v0, v1) :- islocatedin(v0, v2), wasbornin(v2, v1), Rule(1411).
type error
livesin(v0, v1) :- islocatedin(v2, v1), wasbornin(v2, v0), Rule(1412).
type error
livesin(v0, v1) :- islocatedin(v1, v2), wasbornin(v0, v2), Rule(1413).
type error
livesin(v0, v1) :- islocatedin(v0, v1), hasgeonamesid(v0, v1), Rule(1414).
type error
livesin(v0, v1) :- islocatedin(v0, v1), hasgeonamesid(v1, v0), Rule(1415).
type error
livesin(v0, v1) :- islocatedin(v1, v0), hasgeonamesid(v1, v0), Rule(1416).
type error
livesin(v0, v1) :- islocatedin(v1, v0), hasgeonamesid(v0, v1), Rule(1417).
type error
livesin(v0, v1) :- islocatedin(v2, v1), hasgeonamesid(v0, v2), Rule(1418).
type error
livesin(v0, v1) :- islocatedin(v1, v2), hasgeonamesid(v2, v0), Rule(1419).
type error
livesin(v0, v1) :- islocatedin(v2, v0), hasgeonamesid(v1, v2), Rule(1420).
type error
livesin(v0, v1) :- islocatedin(v2, v0), hasgeonamesid(v2, v1), Rule(1421).
type error
livesin(v0, v1) :- islocatedin(v0, v2), hasgeonamesid(v1, v2), Rule(1422).
type error
livesin(v0, v1) :- islocatedin(v0, v2), hasgeonamesid(v2, v1), Rule(1423).
type error
livesin(v0, v1) :- islocatedin(v2, v1), hasgeonamesid(v2, v0), Rule(1424).
type error
livesin(v0, v1) :- islocatedin(v1, v2), hasgeonamesid(v0, v2), Rule(1425).
type error
livesin(v0, v1) :- islocatedin(v0, v1), haswonprize(v0, v1), Rule(1426).
type error
livesin(v0, v1) :- islocatedin(v0, v1), haswonprize(v1, v0), Rule(1427).
type error
livesin(v0, v1) :- islocatedin(v1, v0), haswonprize(v1, v0), Rule(1428).
type error
livesin(v0, v1) :- islocatedin(v1, v0), haswonprize(v0, v1), Rule(1429).
type error
livesin(v0, v1) :- islocatedin(v2, v1), haswonprize(v0, v2), Rule(1430).
type error
livesin(v0, v1) :- islocatedin(v1, v2), haswonprize(v2, v0), Rule(1431).
type error
livesin(v0, v1) :- islocatedin(v2, v0), haswonprize(v1, v2), Rule(1432).
type error
livesin(v0, v1) :- islocatedin(v2, v0), haswonprize(v2, v1), Rule(1433).
type error
livesin(v0, v1) :- islocatedin(v0, v2), haswonprize(v1, v2), Rule(1434).
type error
livesin(v0, v1) :- islocatedin(v0, v2), haswonprize(v2, v1), Rule(1435).
type error
livesin(v0, v1) :- islocatedin(v2, v1), haswonprize(v2, v0), Rule(1436).
type error
livesin(v0, v1) :- islocatedin(v1, v2), haswonprize(v0, v2), Rule(1437).
type error
livesin(v0, v1) :- islocatedin(v0, v1), directed(v0, v1), Rule(1438).
type error
livesin(v0, v1) :- islocatedin(v0, v1), directed(v1, v0), Rule(1439).
type error
livesin(v0, v1) :- islocatedin(v1, v0), directed(v1, v0), Rule(1440).
type error
livesin(v0, v1) :- islocatedin(v1, v0), directed(v0, v1), Rule(1441).
type error
livesin(v0, v1) :- islocatedin(v2, v1), directed(v0, v2), Rule(1442).
type error
livesin(v0, v1) :- islocatedin(v1, v2), directed(v2, v0), Rule(1443).
type error
livesin(v0, v1) :- islocatedin(v2, v0), directed(v1, v2), Rule(1444).
type error
livesin(v0, v1) :- islocatedin(v2, v0), directed(v2, v1), Rule(1445).
type error
livesin(v0, v1) :- islocatedin(v0, v2), directed(v1, v2), Rule(1446).
type error
livesin(v0, v1) :- islocatedin(v0, v2), directed(v2, v1), Rule(1447).
type error
livesin(v0, v1) :- islocatedin(v2, v1), directed(v2, v0), Rule(1448).
type error
livesin(v0, v1) :- islocatedin(v1, v2), directed(v0, v2), Rule(1449).
type error
livesin(v0, v1) :- islocatedin(v0, v1), haschild(v0, v1), Rule(1450).
type error
livesin(v0, v1) :- islocatedin(v0, v1), haschild(v1, v0), Rule(1451).
type error
livesin(v0, v1) :- islocatedin(v1, v0), haschild(v1, v0), Rule(1452).
type error
livesin(v0, v1) :- islocatedin(v1, v0), haschild(v0, v1), Rule(1453).
type error
livesin(v0, v1) :- islocatedin(v2, v1), haschild(v0, v2), Rule(1454).
type error
livesin(v0, v1) :- islocatedin(v1, v2), haschild(v2, v0), Rule(1455).
type error
livesin(v0, v1) :- islocatedin(v2, v0), haschild(v1, v2), Rule(1456).
type error
livesin(v0, v1) :- islocatedin(v2, v0), haschild(v2, v1), Rule(1457).
type error
livesin(v0, v1) :- islocatedin(v0, v2), haschild(v1, v2), Rule(1458).
type error
livesin(v0, v1) :- islocatedin(v0, v2), haschild(v2, v1), Rule(1459).
type error
livesin(v0, v1) :- islocatedin(v2, v1), haschild(v2, v0), Rule(1460).
type error
livesin(v0, v1) :- islocatedin(v1, v2), haschild(v0, v2), Rule(1461).
Head twice 
livesin(v0, v1) :- islocatedin(v0, v1), Ilivesin(v0, v1), Rule(1462).
input prevent
livesin(v0, v1) :- islocatedin(v0, v1), Ilivesin(v1, v0), Rule(1463).
input prevent
livesin(v0, v1) :- islocatedin(v1, v0), Ilivesin(v1, v0), Rule(1464).
Head twice 
livesin(v0, v1) :- islocatedin(v1, v0), Ilivesin(v0, v1), Rule(1465).
type error
livesin(v0, v1) :- islocatedin(v2, v1), Ilivesin(v0, v2), Rule(1466).
type error
livesin(v0, v1) :- islocatedin(v1, v2), Ilivesin(v2, v0), Rule(1467).
type error
livesin(v0, v1) :- islocatedin(v2, v0), Ilivesin(v1, v2), Rule(1468).
type error
livesin(v0, v1) :- islocatedin(v2, v0), Ilivesin(v2, v1), Rule(1469).
type error
livesin(v0, v1) :- islocatedin(v0, v2), Ilivesin(v1, v2), Rule(1470).
type error
livesin(v0, v1) :- islocatedin(v0, v2), Ilivesin(v2, v1), Rule(1471).
type error
livesin(v0, v1) :- islocatedin(v2, v1), Ilivesin(v2, v0), Rule(1472).
type error
livesin(v0, v1) :- islocatedin(v1, v2), Ilivesin(v0, v2), Rule(1473).
type error
livesin(v0, v1) :- islocatedin(v0, v1), inv_0(v0, v1), Rule(1474).
type error
livesin(v0, v1) :- islocatedin(v0, v1), inv_0(v1, v0), Rule(1475).
type error
livesin(v0, v1) :- islocatedin(v1, v0), inv_0(v1, v0), Rule(1476).
type error
livesin(v0, v1) :- islocatedin(v1, v0), inv_0(v0, v1), Rule(1477).
type error
livesin(v0, v1) :- islocatedin(v1, v2), inv_0(v2, v0), Rule(1479).
type error
livesin(v0, v1) :- islocatedin(v2, v0), inv_0(v1, v2), Rule(1480).
type error
livesin(v0, v1) :- islocatedin(v2, v0), inv_0(v2, v1), Rule(1481).
type error
livesin(v0, v1) :- islocatedin(v0, v2), inv_0(v1, v2), Rule(1482).
type error
livesin(v0, v1) :- islocatedin(v0, v2), inv_0(v2, v1), Rule(1483).
type error
livesin(v0, v1) :- islocatedin(v1, v2), inv_0(v0, v2), Rule(1485).
Head twice 
livesin(v0, v1) :- islocatedin(v0, v1), livesin(v0, v1), Rule(1486).
type error
livesin(v0, v1) :- islocatedin(v0, v1), livesin(v1, v0), Rule(1487).
type error
livesin(v0, v1) :- islocatedin(v1, v0), livesin(v1, v0), Rule(1488).
Head twice 
livesin(v0, v1) :- islocatedin(v1, v0), livesin(v0, v1), Rule(1489).
type error
livesin(v0, v1) :- islocatedin(v2, v1), livesin(v0, v2), Rule(1490).
type error
livesin(v0, v1) :- islocatedin(v1, v2), livesin(v2, v0), Rule(1491).
type error
livesin(v0, v1) :- islocatedin(v2, v0), livesin(v1, v2), Rule(1492).
type error
livesin(v0, v1) :- islocatedin(v2, v0), livesin(v2, v1), Rule(1493).
type error
livesin(v0, v1) :- islocatedin(v0, v2), livesin(v1, v2), Rule(1494).
type error
livesin(v0, v1) :- islocatedin(v0, v2), livesin(v2, v1), Rule(1495).
type error
livesin(v0, v1) :- islocatedin(v2, v1), livesin(v2, v0), Rule(1496).
type error
livesin(v0, v1) :- islocatedin(v1, v2), livesin(v0, v2), Rule(1497).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), ismarriedto(v0, v1), Rule(1498).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), ismarriedto(v1, v0), Rule(1499).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), ismarriedto(v1, v0), Rule(1500).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), ismarriedto(v0, v1), Rule(1501).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), ismarriedto(v0, v2), Rule(1502).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), ismarriedto(v2, v0), Rule(1503).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), ismarriedto(v1, v2), Rule(1504).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), ismarriedto(v2, v1), Rule(1505).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), ismarriedto(v1, v2), Rule(1506).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), ismarriedto(v2, v1), Rule(1507).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), ismarriedto(v2, v0), Rule(1508).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), ismarriedto(v0, v2), Rule(1509).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), created(v0, v1), Rule(1510).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), created(v1, v0), Rule(1511).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), created(v1, v0), Rule(1512).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), created(v0, v1), Rule(1513).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), created(v0, v2), Rule(1514).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), created(v2, v0), Rule(1515).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), created(v1, v2), Rule(1516).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), created(v2, v1), Rule(1517).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), created(v1, v2), Rule(1518).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), created(v2, v1), Rule(1519).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), created(v2, v0), Rule(1520).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), created(v0, v2), Rule(1521).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), participatedin(v0, v1), Rule(1522).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), participatedin(v1, v0), Rule(1523).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), participatedin(v1, v0), Rule(1524).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), participatedin(v0, v1), Rule(1525).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), participatedin(v0, v2), Rule(1526).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), participatedin(v2, v0), Rule(1527).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), participatedin(v2, v0), Rule(1532).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), participatedin(v0, v2), Rule(1533).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), influences(v0, v1), Rule(1534).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), influences(v1, v0), Rule(1535).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), influences(v1, v0), Rule(1536).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), influences(v0, v1), Rule(1537).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), influences(v0, v2), Rule(1538).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), influences(v2, v0), Rule(1539).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), influences(v1, v2), Rule(1540).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), influences(v2, v1), Rule(1541).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), influences(v1, v2), Rule(1542).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), influences(v2, v1), Rule(1543).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), influences(v2, v0), Rule(1544).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), influences(v0, v2), Rule(1545).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), actedin(v0, v1), Rule(1546).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), actedin(v1, v0), Rule(1547).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), actedin(v1, v0), Rule(1548).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), actedin(v0, v1), Rule(1549).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), actedin(v0, v2), Rule(1550).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), actedin(v2, v0), Rule(1551).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), actedin(v1, v2), Rule(1552).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), actedin(v2, v1), Rule(1553).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), actedin(v1, v2), Rule(1554).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), actedin(v2, v1), Rule(1555).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), actedin(v2, v0), Rule(1556).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), actedin(v0, v2), Rule(1557).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), diedin(v0, v1), Rule(1558).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), diedin(v1, v0), Rule(1559).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), diedin(v1, v0), Rule(1560).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), diedin(v0, v1), Rule(1561).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), diedin(v0, v2), Rule(1562).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), diedin(v2, v0), Rule(1563).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), diedin(v1, v2), Rule(1564).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), diedin(v1, v2), Rule(1566).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), diedin(v2, v0), Rule(1568).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), diedin(v0, v2), Rule(1569).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), wasbornin(v0, v1), Rule(1570).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), wasbornin(v1, v0), Rule(1571).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), wasbornin(v1, v0), Rule(1572).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), wasbornin(v0, v1), Rule(1573).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), wasbornin(v0, v2), Rule(1574).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), wasbornin(v2, v0), Rule(1575).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), wasbornin(v1, v2), Rule(1576).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), wasbornin(v1, v2), Rule(1578).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), wasbornin(v2, v0), Rule(1580).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), wasbornin(v0, v2), Rule(1581).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), hasgeonamesid(v0, v1), Rule(1582).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), hasgeonamesid(v1, v0), Rule(1583).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), hasgeonamesid(v1, v0), Rule(1584).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), hasgeonamesid(v0, v1), Rule(1585).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), hasgeonamesid(v0, v2), Rule(1586).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), hasgeonamesid(v2, v0), Rule(1587).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), hasgeonamesid(v1, v2), Rule(1588).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), hasgeonamesid(v2, v1), Rule(1589).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), hasgeonamesid(v1, v2), Rule(1590).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), hasgeonamesid(v2, v1), Rule(1591).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), hasgeonamesid(v2, v0), Rule(1592).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), hasgeonamesid(v0, v2), Rule(1593).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), haswonprize(v0, v1), Rule(1594).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), haswonprize(v1, v0), Rule(1595).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), haswonprize(v1, v0), Rule(1596).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), haswonprize(v0, v1), Rule(1597).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), haswonprize(v0, v2), Rule(1598).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), haswonprize(v2, v0), Rule(1599).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), haswonprize(v1, v2), Rule(1600).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), haswonprize(v2, v1), Rule(1601).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), haswonprize(v1, v2), Rule(1602).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), haswonprize(v2, v1), Rule(1603).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), haswonprize(v2, v0), Rule(1604).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), haswonprize(v0, v2), Rule(1605).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), directed(v0, v1), Rule(1606).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), directed(v1, v0), Rule(1607).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), directed(v1, v0), Rule(1608).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), directed(v0, v1), Rule(1609).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), directed(v0, v2), Rule(1610).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), directed(v2, v0), Rule(1611).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), directed(v1, v2), Rule(1612).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), directed(v2, v1), Rule(1613).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), directed(v1, v2), Rule(1614).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), directed(v2, v1), Rule(1615).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), directed(v2, v0), Rule(1616).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), directed(v0, v2), Rule(1617).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), haschild(v0, v1), Rule(1618).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), haschild(v1, v0), Rule(1619).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), haschild(v1, v0), Rule(1620).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), haschild(v0, v1), Rule(1621).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), haschild(v0, v2), Rule(1622).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), haschild(v2, v0), Rule(1623).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), haschild(v1, v2), Rule(1624).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), haschild(v2, v1), Rule(1625).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), haschild(v1, v2), Rule(1626).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), haschild(v2, v1), Rule(1627).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), haschild(v2, v0), Rule(1628).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), haschild(v0, v2), Rule(1629).
Head twice 
livesin(v0, v1) :- ismarriedto(v0, v1), Ilivesin(v0, v1), Rule(1630).
input prevent
livesin(v0, v1) :- ismarriedto(v0, v1), Ilivesin(v1, v0), Rule(1631).
input prevent
livesin(v0, v1) :- ismarriedto(v1, v0), Ilivesin(v1, v0), Rule(1632).
Head twice 
livesin(v0, v1) :- ismarriedto(v1, v0), Ilivesin(v0, v1), Rule(1633).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), Ilivesin(v0, v2), Rule(1634).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), Ilivesin(v2, v0), Rule(1635).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), Ilivesin(v1, v2), Rule(1636).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), Ilivesin(v1, v2), Rule(1638).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), Ilivesin(v2, v0), Rule(1640).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), Ilivesin(v0, v2), Rule(1641).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), inv_0(v0, v1), Rule(1642).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), inv_0(v1, v0), Rule(1643).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), inv_0(v1, v0), Rule(1644).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), inv_0(v0, v1), Rule(1645).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), inv_0(v0, v2), Rule(1646).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), inv_0(v2, v0), Rule(1647).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), inv_0(v2, v0), Rule(1652).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), inv_0(v0, v2), Rule(1653).
Head twice 
livesin(v0, v1) :- ismarriedto(v0, v1), livesin(v0, v1), Rule(1654).
type error
livesin(v0, v1) :- ismarriedto(v0, v1), livesin(v1, v0), Rule(1655).
type error
livesin(v0, v1) :- ismarriedto(v1, v0), livesin(v1, v0), Rule(1656).
Head twice 
livesin(v0, v1) :- ismarriedto(v1, v0), livesin(v0, v1), Rule(1657).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), livesin(v0, v2), Rule(1658).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), livesin(v2, v0), Rule(1659).
type error
livesin(v0, v1) :- ismarriedto(v2, v0), livesin(v1, v2), Rule(1660).
type error
livesin(v0, v1) :- ismarriedto(v0, v2), livesin(v1, v2), Rule(1662).
type error
livesin(v0, v1) :- ismarriedto(v2, v1), livesin(v2, v0), Rule(1664).
type error
livesin(v0, v1) :- ismarriedto(v1, v2), livesin(v0, v2), Rule(1665).
type error
livesin(v0, v1) :- created(v0, v1), created(v0, v1), Rule(1666).
type error
livesin(v0, v1) :- created(v0, v1), created(v1, v0), Rule(1667).
type error
livesin(v0, v1) :- created(v1, v0), created(v1, v0), Rule(1668).
type error
livesin(v0, v1) :- created(v1, v0), created(v0, v1), Rule(1669).
type error
livesin(v0, v1) :- created(v2, v1), created(v0, v2), Rule(1670).
type error
livesin(v0, v1) :- created(v1, v2), created(v2, v0), Rule(1671).
type error
livesin(v0, v1) :- created(v2, v0), created(v1, v2), Rule(1672).
type error
livesin(v0, v1) :- created(v2, v0), created(v2, v1), Rule(1673).
type error
livesin(v0, v1) :- created(v0, v2), created(v1, v2), Rule(1674).
type error
livesin(v0, v1) :- created(v0, v2), created(v2, v1), Rule(1675).
type error
livesin(v0, v1) :- created(v2, v1), created(v2, v0), Rule(1676).
type error
livesin(v0, v1) :- created(v1, v2), created(v0, v2), Rule(1677).
type error
livesin(v0, v1) :- created(v0, v1), participatedin(v0, v1), Rule(1678).
type error
livesin(v0, v1) :- created(v0, v1), participatedin(v1, v0), Rule(1679).
type error
livesin(v0, v1) :- created(v1, v0), participatedin(v1, v0), Rule(1680).
type error
livesin(v0, v1) :- created(v1, v0), participatedin(v0, v1), Rule(1681).
type error
livesin(v0, v1) :- created(v2, v1), participatedin(v0, v2), Rule(1682).
type error
livesin(v0, v1) :- created(v1, v2), participatedin(v2, v0), Rule(1683).
type error
livesin(v0, v1) :- created(v2, v0), participatedin(v1, v2), Rule(1684).
type error
livesin(v0, v1) :- created(v2, v0), participatedin(v2, v1), Rule(1685).
type error
livesin(v0, v1) :- created(v2, v1), participatedin(v2, v0), Rule(1688).
type error
livesin(v0, v1) :- created(v1, v2), participatedin(v0, v2), Rule(1689).
type error
livesin(v0, v1) :- created(v0, v1), influences(v0, v1), Rule(1690).
type error
livesin(v0, v1) :- created(v0, v1), influences(v1, v0), Rule(1691).
type error
livesin(v0, v1) :- created(v1, v0), influences(v1, v0), Rule(1692).
type error
livesin(v0, v1) :- created(v1, v0), influences(v0, v1), Rule(1693).
type error
livesin(v0, v1) :- created(v2, v1), influences(v0, v2), Rule(1694).
type error
livesin(v0, v1) :- created(v1, v2), influences(v2, v0), Rule(1695).
type error
livesin(v0, v1) :- created(v2, v0), influences(v1, v2), Rule(1696).
type error
livesin(v0, v1) :- created(v2, v0), influences(v2, v1), Rule(1697).
type error
livesin(v0, v1) :- created(v0, v2), influences(v1, v2), Rule(1698).
type error
livesin(v0, v1) :- created(v0, v2), influences(v2, v1), Rule(1699).
type error
livesin(v0, v1) :- created(v2, v1), influences(v2, v0), Rule(1700).
type error
livesin(v0, v1) :- created(v1, v2), influences(v0, v2), Rule(1701).
type error
livesin(v0, v1) :- created(v0, v1), actedin(v0, v1), Rule(1702).
type error
livesin(v0, v1) :- created(v0, v1), actedin(v1, v0), Rule(1703).
type error
livesin(v0, v1) :- created(v1, v0), actedin(v1, v0), Rule(1704).
type error
livesin(v0, v1) :- created(v1, v0), actedin(v0, v1), Rule(1705).
type error
livesin(v0, v1) :- created(v2, v1), actedin(v0, v2), Rule(1706).
type error
livesin(v0, v1) :- created(v1, v2), actedin(v2, v0), Rule(1707).
type error
livesin(v0, v1) :- created(v2, v0), actedin(v1, v2), Rule(1708).
type error
livesin(v0, v1) :- created(v2, v0), actedin(v2, v1), Rule(1709).
type error
livesin(v0, v1) :- created(v0, v2), actedin(v1, v2), Rule(1710).
type error
livesin(v0, v1) :- created(v0, v2), actedin(v2, v1), Rule(1711).
type error
livesin(v0, v1) :- created(v2, v1), actedin(v2, v0), Rule(1712).
type error
livesin(v0, v1) :- created(v1, v2), actedin(v0, v2), Rule(1713).
type error
livesin(v0, v1) :- created(v0, v1), diedin(v0, v1), Rule(1714).
type error
livesin(v0, v1) :- created(v0, v1), diedin(v1, v0), Rule(1715).
type error
livesin(v0, v1) :- created(v1, v0), diedin(v1, v0), Rule(1716).
type error
livesin(v0, v1) :- created(v1, v0), diedin(v0, v1), Rule(1717).
type error
livesin(v0, v1) :- created(v2, v1), diedin(v0, v2), Rule(1718).
type error
livesin(v0, v1) :- created(v1, v2), diedin(v2, v0), Rule(1719).
type error
livesin(v0, v1) :- created(v2, v0), diedin(v1, v2), Rule(1720).
type error
livesin(v0, v1) :- created(v2, v0), diedin(v2, v1), Rule(1721).
type error
livesin(v0, v1) :- created(v0, v2), diedin(v1, v2), Rule(1722).
type error
livesin(v0, v1) :- created(v0, v2), diedin(v2, v1), Rule(1723).
type error
livesin(v0, v1) :- created(v2, v1), diedin(v2, v0), Rule(1724).
type error
livesin(v0, v1) :- created(v1, v2), diedin(v0, v2), Rule(1725).
type error
livesin(v0, v1) :- created(v0, v1), wasbornin(v0, v1), Rule(1726).
type error
livesin(v0, v1) :- created(v0, v1), wasbornin(v1, v0), Rule(1727).
type error
livesin(v0, v1) :- created(v1, v0), wasbornin(v1, v0), Rule(1728).
type error
livesin(v0, v1) :- created(v1, v0), wasbornin(v0, v1), Rule(1729).
type error
livesin(v0, v1) :- created(v2, v1), wasbornin(v0, v2), Rule(1730).
type error
livesin(v0, v1) :- created(v1, v2), wasbornin(v2, v0), Rule(1731).
type error
livesin(v0, v1) :- created(v2, v0), wasbornin(v1, v2), Rule(1732).
type error
livesin(v0, v1) :- created(v2, v0), wasbornin(v2, v1), Rule(1733).
type error
livesin(v0, v1) :- created(v0, v2), wasbornin(v1, v2), Rule(1734).
type error
livesin(v0, v1) :- created(v0, v2), wasbornin(v2, v1), Rule(1735).
type error
livesin(v0, v1) :- created(v2, v1), wasbornin(v2, v0), Rule(1736).
type error
livesin(v0, v1) :- created(v1, v2), wasbornin(v0, v2), Rule(1737).
type error
livesin(v0, v1) :- created(v0, v1), hasgeonamesid(v0, v1), Rule(1738).
type error
livesin(v0, v1) :- created(v0, v1), hasgeonamesid(v1, v0), Rule(1739).
type error
livesin(v0, v1) :- created(v1, v0), hasgeonamesid(v1, v0), Rule(1740).
type error
livesin(v0, v1) :- created(v1, v0), hasgeonamesid(v0, v1), Rule(1741).
type error
livesin(v0, v1) :- created(v2, v1), hasgeonamesid(v0, v2), Rule(1742).
type error
livesin(v0, v1) :- created(v1, v2), hasgeonamesid(v2, v0), Rule(1743).
type error
livesin(v0, v1) :- created(v2, v0), hasgeonamesid(v1, v2), Rule(1744).
type error
livesin(v0, v1) :- created(v2, v0), hasgeonamesid(v2, v1), Rule(1745).
type error
livesin(v0, v1) :- created(v0, v2), hasgeonamesid(v2, v1), Rule(1747).
type error
livesin(v0, v1) :- created(v2, v1), hasgeonamesid(v2, v0), Rule(1748).
type error
livesin(v0, v1) :- created(v1, v2), hasgeonamesid(v0, v2), Rule(1749).
type error
livesin(v0, v1) :- created(v0, v1), haswonprize(v0, v1), Rule(1750).
type error
livesin(v0, v1) :- created(v0, v1), haswonprize(v1, v0), Rule(1751).
type error
livesin(v0, v1) :- created(v1, v0), haswonprize(v1, v0), Rule(1752).
type error
livesin(v0, v1) :- created(v1, v0), haswonprize(v0, v1), Rule(1753).
type error
livesin(v0, v1) :- created(v2, v1), haswonprize(v0, v2), Rule(1754).
type error
livesin(v0, v1) :- created(v1, v2), haswonprize(v2, v0), Rule(1755).
type error
livesin(v0, v1) :- created(v2, v0), haswonprize(v1, v2), Rule(1756).
type error
livesin(v0, v1) :- created(v2, v0), haswonprize(v2, v1), Rule(1757).
type error
livesin(v0, v1) :- created(v0, v2), haswonprize(v1, v2), Rule(1758).
type error
livesin(v0, v1) :- created(v0, v2), haswonprize(v2, v1), Rule(1759).
type error
livesin(v0, v1) :- created(v2, v1), haswonprize(v2, v0), Rule(1760).
type error
livesin(v0, v1) :- created(v1, v2), haswonprize(v0, v2), Rule(1761).
type error
livesin(v0, v1) :- created(v0, v1), directed(v0, v1), Rule(1762).
type error
livesin(v0, v1) :- created(v0, v1), directed(v1, v0), Rule(1763).
type error
livesin(v0, v1) :- created(v1, v0), directed(v1, v0), Rule(1764).
type error
livesin(v0, v1) :- created(v1, v0), directed(v0, v1), Rule(1765).
type error
livesin(v0, v1) :- created(v2, v1), directed(v0, v2), Rule(1766).
type error
livesin(v0, v1) :- created(v1, v2), directed(v2, v0), Rule(1767).
type error
livesin(v0, v1) :- created(v2, v0), directed(v1, v2), Rule(1768).
type error
livesin(v0, v1) :- created(v2, v0), directed(v2, v1), Rule(1769).
type error
livesin(v0, v1) :- created(v0, v2), directed(v1, v2), Rule(1770).
type error
livesin(v0, v1) :- created(v0, v2), directed(v2, v1), Rule(1771).
type error
livesin(v0, v1) :- created(v2, v1), directed(v2, v0), Rule(1772).
type error
livesin(v0, v1) :- created(v1, v2), directed(v0, v2), Rule(1773).
type error
livesin(v0, v1) :- created(v0, v1), haschild(v0, v1), Rule(1774).
type error
livesin(v0, v1) :- created(v0, v1), haschild(v1, v0), Rule(1775).
type error
livesin(v0, v1) :- created(v1, v0), haschild(v1, v0), Rule(1776).
type error
livesin(v0, v1) :- created(v1, v0), haschild(v0, v1), Rule(1777).
type error
livesin(v0, v1) :- created(v2, v1), haschild(v0, v2), Rule(1778).
type error
livesin(v0, v1) :- created(v1, v2), haschild(v2, v0), Rule(1779).
type error
livesin(v0, v1) :- created(v2, v0), haschild(v1, v2), Rule(1780).
type error
livesin(v0, v1) :- created(v2, v0), haschild(v2, v1), Rule(1781).
type error
livesin(v0, v1) :- created(v0, v2), haschild(v1, v2), Rule(1782).
type error
livesin(v0, v1) :- created(v0, v2), haschild(v2, v1), Rule(1783).
type error
livesin(v0, v1) :- created(v2, v1), haschild(v2, v0), Rule(1784).
type error
livesin(v0, v1) :- created(v1, v2), haschild(v0, v2), Rule(1785).
Head twice 
livesin(v0, v1) :- created(v0, v1), Ilivesin(v0, v1), Rule(1786).
input prevent
livesin(v0, v1) :- created(v0, v1), Ilivesin(v1, v0), Rule(1787).
input prevent
livesin(v0, v1) :- created(v1, v0), Ilivesin(v1, v0), Rule(1788).
Head twice 
livesin(v0, v1) :- created(v1, v0), Ilivesin(v0, v1), Rule(1789).
type error
livesin(v0, v1) :- created(v2, v1), Ilivesin(v0, v2), Rule(1790).
type error
livesin(v0, v1) :- created(v1, v2), Ilivesin(v2, v0), Rule(1791).
type error
livesin(v0, v1) :- created(v2, v0), Ilivesin(v1, v2), Rule(1792).
type error
livesin(v0, v1) :- created(v2, v0), Ilivesin(v2, v1), Rule(1793).
type error
livesin(v0, v1) :- created(v0, v2), Ilivesin(v1, v2), Rule(1794).
type error
livesin(v0, v1) :- created(v0, v2), Ilivesin(v2, v1), Rule(1795).
type error
livesin(v0, v1) :- created(v2, v1), Ilivesin(v2, v0), Rule(1796).
type error
livesin(v0, v1) :- created(v1, v2), Ilivesin(v0, v2), Rule(1797).
type error
livesin(v0, v1) :- created(v0, v1), inv_0(v0, v1), Rule(1798).
type error
livesin(v0, v1) :- created(v0, v1), inv_0(v1, v0), Rule(1799).
type error
livesin(v0, v1) :- created(v1, v0), inv_0(v1, v0), Rule(1800).
type error
livesin(v0, v1) :- created(v1, v0), inv_0(v0, v1), Rule(1801).
type error
livesin(v0, v1) :- created(v2, v1), inv_0(v0, v2), Rule(1802).
type error
livesin(v0, v1) :- created(v1, v2), inv_0(v2, v0), Rule(1803).
type error
livesin(v0, v1) :- created(v2, v0), inv_0(v1, v2), Rule(1804).
type error
livesin(v0, v1) :- created(v2, v0), inv_0(v2, v1), Rule(1805).
type error
livesin(v0, v1) :- created(v2, v1), inv_0(v2, v0), Rule(1808).
type error
livesin(v0, v1) :- created(v1, v2), inv_0(v0, v2), Rule(1809).
Head twice 
livesin(v0, v1) :- created(v0, v1), livesin(v0, v1), Rule(1810).
type error
livesin(v0, v1) :- created(v0, v1), livesin(v1, v0), Rule(1811).
type error
livesin(v0, v1) :- created(v1, v0), livesin(v1, v0), Rule(1812).
Head twice 
livesin(v0, v1) :- created(v1, v0), livesin(v0, v1), Rule(1813).
type error
livesin(v0, v1) :- created(v2, v1), livesin(v0, v2), Rule(1814).
type error
livesin(v0, v1) :- created(v1, v2), livesin(v2, v0), Rule(1815).
type error
livesin(v0, v1) :- created(v2, v0), livesin(v1, v2), Rule(1816).
type error
livesin(v0, v1) :- created(v2, v0), livesin(v2, v1), Rule(1817).
type error
livesin(v0, v1) :- created(v0, v2), livesin(v1, v2), Rule(1818).
type error
livesin(v0, v1) :- created(v0, v2), livesin(v2, v1), Rule(1819).
type error
livesin(v0, v1) :- created(v2, v1), livesin(v2, v0), Rule(1820).
type error
livesin(v0, v1) :- created(v1, v2), livesin(v0, v2), Rule(1821).
type error
livesin(v0, v1) :- participatedin(v0, v1), influences(v0, v1), Rule(1834).
type error
livesin(v0, v1) :- participatedin(v0, v1), influences(v1, v0), Rule(1835).
type error
livesin(v0, v1) :- participatedin(v1, v0), influences(v1, v0), Rule(1836).
type error
livesin(v0, v1) :- participatedin(v1, v0), influences(v0, v1), Rule(1837).
type error
livesin(v0, v1) :- participatedin(v2, v0), influences(v1, v2), Rule(1840).
type error
livesin(v0, v1) :- participatedin(v2, v0), influences(v2, v1), Rule(1841).
type error
livesin(v0, v1) :- participatedin(v0, v2), influences(v1, v2), Rule(1842).
type error
livesin(v0, v1) :- participatedin(v0, v2), influences(v2, v1), Rule(1843).
type error
livesin(v0, v1) :- participatedin(v0, v1), actedin(v0, v1), Rule(1846).
type error
livesin(v0, v1) :- participatedin(v0, v1), actedin(v1, v0), Rule(1847).
type error
livesin(v0, v1) :- participatedin(v1, v0), actedin(v1, v0), Rule(1848).
type error
livesin(v0, v1) :- participatedin(v1, v0), actedin(v0, v1), Rule(1849).
type error
livesin(v0, v1) :- participatedin(v1, v2), actedin(v2, v0), Rule(1851).
type error
livesin(v0, v1) :- participatedin(v2, v0), actedin(v1, v2), Rule(1852).
type error
livesin(v0, v1) :- participatedin(v2, v0), actedin(v2, v1), Rule(1853).
type error
livesin(v0, v1) :- participatedin(v0, v2), actedin(v1, v2), Rule(1854).
type error
livesin(v0, v1) :- participatedin(v0, v2), actedin(v2, v1), Rule(1855).
type error
livesin(v0, v1) :- participatedin(v2, v1), actedin(v2, v0), Rule(1856).
type error
livesin(v0, v1) :- participatedin(v0, v1), diedin(v1, v0), Rule(1859).
type error
livesin(v0, v1) :- participatedin(v1, v0), diedin(v1, v0), Rule(1860).
type error
livesin(v0, v1) :- participatedin(v1, v2), diedin(v2, v0), Rule(1863).
type error
livesin(v0, v1) :- participatedin(v2, v0), diedin(v1, v2), Rule(1864).
type error
livesin(v0, v1) :- participatedin(v0, v2), diedin(v1, v2), Rule(1866).
type error
livesin(v0, v1) :- participatedin(v2, v1), diedin(v2, v0), Rule(1868).
type error
livesin(v0, v1) :- participatedin(v0, v1), wasbornin(v1, v0), Rule(1871).
type error
livesin(v0, v1) :- participatedin(v1, v0), wasbornin(v1, v0), Rule(1872).
type error
livesin(v0, v1) :- participatedin(v1, v2), wasbornin(v2, v0), Rule(1875).
type error
livesin(v0, v1) :- participatedin(v2, v0), wasbornin(v1, v2), Rule(1876).
type error
livesin(v0, v1) :- participatedin(v0, v2), wasbornin(v1, v2), Rule(1878).
type error
livesin(v0, v1) :- participatedin(v2, v1), wasbornin(v2, v0), Rule(1880).
type error
livesin(v0, v1) :- participatedin(v0, v1), hasgeonamesid(v0, v1), Rule(1882).
type error
livesin(v0, v1) :- participatedin(v0, v1), hasgeonamesid(v1, v0), Rule(1883).
type error
livesin(v0, v1) :- participatedin(v1, v0), hasgeonamesid(v1, v0), Rule(1884).
type error
livesin(v0, v1) :- participatedin(v1, v0), hasgeonamesid(v0, v1), Rule(1885).
type error
livesin(v0, v1) :- participatedin(v2, v1), hasgeonamesid(v0, v2), Rule(1886).
type error
livesin(v0, v1) :- participatedin(v1, v2), hasgeonamesid(v2, v0), Rule(1887).
type error
livesin(v0, v1) :- participatedin(v2, v0), hasgeonamesid(v2, v1), Rule(1889).
type error
livesin(v0, v1) :- participatedin(v0, v2), hasgeonamesid(v2, v1), Rule(1891).
type error
livesin(v0, v1) :- participatedin(v2, v1), hasgeonamesid(v2, v0), Rule(1892).
type error
livesin(v0, v1) :- participatedin(v1, v2), hasgeonamesid(v0, v2), Rule(1893).
type error
livesin(v0, v1) :- participatedin(v0, v1), haswonprize(v0, v1), Rule(1894).
type error
livesin(v0, v1) :- participatedin(v0, v1), haswonprize(v1, v0), Rule(1895).
type error
livesin(v0, v1) :- participatedin(v1, v0), haswonprize(v1, v0), Rule(1896).
type error
livesin(v0, v1) :- participatedin(v1, v0), haswonprize(v0, v1), Rule(1897).
type error
livesin(v0, v1) :- participatedin(v2, v1), haswonprize(v0, v2), Rule(1898).
type error
livesin(v0, v1) :- participatedin(v1, v2), haswonprize(v2, v0), Rule(1899).
type error
livesin(v0, v1) :- participatedin(v2, v0), haswonprize(v1, v2), Rule(1900).
type error
livesin(v0, v1) :- participatedin(v2, v0), haswonprize(v2, v1), Rule(1901).
type error
livesin(v0, v1) :- participatedin(v0, v2), haswonprize(v1, v2), Rule(1902).
type error
livesin(v0, v1) :- participatedin(v0, v2), haswonprize(v2, v1), Rule(1903).
type error
livesin(v0, v1) :- participatedin(v2, v1), haswonprize(v2, v0), Rule(1904).
type error
livesin(v0, v1) :- participatedin(v1, v2), haswonprize(v0, v2), Rule(1905).
type error
livesin(v0, v1) :- participatedin(v0, v1), directed(v0, v1), Rule(1906).
type error
livesin(v0, v1) :- participatedin(v0, v1), directed(v1, v0), Rule(1907).
type error
livesin(v0, v1) :- participatedin(v1, v0), directed(v1, v0), Rule(1908).
type error
livesin(v0, v1) :- participatedin(v1, v0), directed(v0, v1), Rule(1909).
type error
livesin(v0, v1) :- participatedin(v1, v2), directed(v2, v0), Rule(1911).
type error
livesin(v0, v1) :- participatedin(v2, v0), directed(v1, v2), Rule(1912).
type error
livesin(v0, v1) :- participatedin(v2, v0), directed(v2, v1), Rule(1913).
type error
livesin(v0, v1) :- participatedin(v0, v2), directed(v1, v2), Rule(1914).
type error
livesin(v0, v1) :- participatedin(v0, v2), directed(v2, v1), Rule(1915).
type error
livesin(v0, v1) :- participatedin(v2, v1), directed(v2, v0), Rule(1916).
type error
livesin(v0, v1) :- participatedin(v0, v1), haschild(v0, v1), Rule(1918).
type error
livesin(v0, v1) :- participatedin(v0, v1), haschild(v1, v0), Rule(1919).
type error
livesin(v0, v1) :- participatedin(v1, v0), haschild(v1, v0), Rule(1920).
type error
livesin(v0, v1) :- participatedin(v1, v0), haschild(v0, v1), Rule(1921).
type error
livesin(v0, v1) :- participatedin(v2, v0), haschild(v1, v2), Rule(1924).
type error
livesin(v0, v1) :- participatedin(v2, v0), haschild(v2, v1), Rule(1925).
type error
livesin(v0, v1) :- participatedin(v0, v2), haschild(v1, v2), Rule(1926).
type error
livesin(v0, v1) :- participatedin(v0, v2), haschild(v2, v1), Rule(1927).
Head twice 
livesin(v0, v1) :- participatedin(v0, v1), Ilivesin(v0, v1), Rule(1930).
input prevent
livesin(v0, v1) :- participatedin(v0, v1), Ilivesin(v1, v0), Rule(1931).
input prevent
livesin(v0, v1) :- participatedin(v1, v0), Ilivesin(v1, v0), Rule(1932).
Head twice 
livesin(v0, v1) :- participatedin(v1, v0), Ilivesin(v0, v1), Rule(1933).
type error
livesin(v0, v1) :- participatedin(v1, v2), Ilivesin(v2, v0), Rule(1935).
type error
livesin(v0, v1) :- participatedin(v2, v0), Ilivesin(v1, v2), Rule(1936).
type error
livesin(v0, v1) :- participatedin(v0, v2), Ilivesin(v1, v2), Rule(1938).
type error
livesin(v0, v1) :- participatedin(v2, v1), Ilivesin(v2, v0), Rule(1940).
Head twice 
livesin(v0, v1) :- participatedin(v0, v1), livesin(v0, v1), Rule(1954).
type error
livesin(v0, v1) :- participatedin(v0, v1), livesin(v1, v0), Rule(1955).
type error
livesin(v0, v1) :- participatedin(v1, v0), livesin(v1, v0), Rule(1956).
Head twice 
livesin(v0, v1) :- participatedin(v1, v0), livesin(v0, v1), Rule(1957).
type error
livesin(v0, v1) :- participatedin(v1, v2), livesin(v2, v0), Rule(1959).
type error
livesin(v0, v1) :- participatedin(v2, v0), livesin(v1, v2), Rule(1960).
type error
livesin(v0, v1) :- participatedin(v0, v2), livesin(v1, v2), Rule(1962).
type error
livesin(v0, v1) :- participatedin(v2, v1), livesin(v2, v0), Rule(1964).
type error
livesin(v0, v1) :- influences(v0, v1), influences(v0, v1), Rule(1966).
type error
livesin(v0, v1) :- influences(v0, v1), influences(v1, v0), Rule(1967).
type error
livesin(v0, v1) :- influences(v1, v0), influences(v1, v0), Rule(1968).
type error
livesin(v0, v1) :- influences(v1, v0), influences(v0, v1), Rule(1969).
type error
livesin(v0, v1) :- influences(v2, v1), influences(v0, v2), Rule(1970).
type error
livesin(v0, v1) :- influences(v1, v2), influences(v2, v0), Rule(1971).
type error
livesin(v0, v1) :- influences(v2, v0), influences(v1, v2), Rule(1972).
type error
livesin(v0, v1) :- influences(v2, v0), influences(v2, v1), Rule(1973).
type error
livesin(v0, v1) :- influences(v0, v2), influences(v1, v2), Rule(1974).
type error
livesin(v0, v1) :- influences(v0, v2), influences(v2, v1), Rule(1975).
type error
livesin(v0, v1) :- influences(v2, v1), influences(v2, v0), Rule(1976).
type error
livesin(v0, v1) :- influences(v1, v2), influences(v0, v2), Rule(1977).
type error
livesin(v0, v1) :- influences(v0, v1), actedin(v0, v1), Rule(1978).
type error
livesin(v0, v1) :- influences(v0, v1), actedin(v1, v0), Rule(1979).
type error
livesin(v0, v1) :- influences(v1, v0), actedin(v1, v0), Rule(1980).
type error
livesin(v0, v1) :- influences(v1, v0), actedin(v0, v1), Rule(1981).
type error
livesin(v0, v1) :- influences(v2, v1), actedin(v0, v2), Rule(1982).
type error
livesin(v0, v1) :- influences(v1, v2), actedin(v2, v0), Rule(1983).
type error
livesin(v0, v1) :- influences(v2, v0), actedin(v1, v2), Rule(1984).
type error
livesin(v0, v1) :- influences(v2, v0), actedin(v2, v1), Rule(1985).
type error
livesin(v0, v1) :- influences(v0, v2), actedin(v1, v2), Rule(1986).
type error
livesin(v0, v1) :- influences(v0, v2), actedin(v2, v1), Rule(1987).
type error
livesin(v0, v1) :- influences(v2, v1), actedin(v2, v0), Rule(1988).
type error
livesin(v0, v1) :- influences(v1, v2), actedin(v0, v2), Rule(1989).
type error
livesin(v0, v1) :- influences(v0, v1), diedin(v0, v1), Rule(1990).
type error
livesin(v0, v1) :- influences(v0, v1), diedin(v1, v0), Rule(1991).
type error
livesin(v0, v1) :- influences(v1, v0), diedin(v1, v0), Rule(1992).
type error
livesin(v0, v1) :- influences(v1, v0), diedin(v0, v1), Rule(1993).
type error
livesin(v0, v1) :- influences(v2, v1), diedin(v0, v2), Rule(1994).
type error
livesin(v0, v1) :- influences(v1, v2), diedin(v2, v0), Rule(1995).
type error
livesin(v0, v1) :- influences(v2, v0), diedin(v1, v2), Rule(1996).
type error
livesin(v0, v1) :- influences(v0, v2), diedin(v1, v2), Rule(1998).
type error
livesin(v0, v1) :- influences(v2, v1), diedin(v2, v0), Rule(2000).
type error
livesin(v0, v1) :- influences(v1, v2), diedin(v0, v2), Rule(2001).
type error
livesin(v0, v1) :- influences(v0, v1), wasbornin(v0, v1), Rule(2002).
type error
livesin(v0, v1) :- influences(v0, v1), wasbornin(v1, v0), Rule(2003).
type error
livesin(v0, v1) :- influences(v1, v0), wasbornin(v1, v0), Rule(2004).
type error
livesin(v0, v1) :- influences(v1, v0), wasbornin(v0, v1), Rule(2005).
type error
livesin(v0, v1) :- influences(v2, v1), wasbornin(v0, v2), Rule(2006).
type error
livesin(v0, v1) :- influences(v1, v2), wasbornin(v2, v0), Rule(2007).
type error
livesin(v0, v1) :- influences(v2, v0), wasbornin(v1, v2), Rule(2008).
type error
livesin(v0, v1) :- influences(v0, v2), wasbornin(v1, v2), Rule(2010).
type error
livesin(v0, v1) :- influences(v2, v1), wasbornin(v2, v0), Rule(2012).
type error
livesin(v0, v1) :- influences(v1, v2), wasbornin(v0, v2), Rule(2013).
type error
livesin(v0, v1) :- influences(v0, v1), hasgeonamesid(v0, v1), Rule(2014).
type error
livesin(v0, v1) :- influences(v0, v1), hasgeonamesid(v1, v0), Rule(2015).
type error
livesin(v0, v1) :- influences(v1, v0), hasgeonamesid(v1, v0), Rule(2016).
type error
livesin(v0, v1) :- influences(v1, v0), hasgeonamesid(v0, v1), Rule(2017).
type error
livesin(v0, v1) :- influences(v2, v1), hasgeonamesid(v0, v2), Rule(2018).
type error
livesin(v0, v1) :- influences(v1, v2), hasgeonamesid(v2, v0), Rule(2019).
type error
livesin(v0, v1) :- influences(v2, v0), hasgeonamesid(v1, v2), Rule(2020).
type error
livesin(v0, v1) :- influences(v2, v0), hasgeonamesid(v2, v1), Rule(2021).
type error
livesin(v0, v1) :- influences(v0, v2), hasgeonamesid(v1, v2), Rule(2022).
type error
livesin(v0, v1) :- influences(v0, v2), hasgeonamesid(v2, v1), Rule(2023).
type error
livesin(v0, v1) :- influences(v2, v1), hasgeonamesid(v2, v0), Rule(2024).
type error
livesin(v0, v1) :- influences(v1, v2), hasgeonamesid(v0, v2), Rule(2025).
type error
livesin(v0, v1) :- influences(v0, v1), haswonprize(v0, v1), Rule(2026).
type error
livesin(v0, v1) :- influences(v0, v1), haswonprize(v1, v0), Rule(2027).
type error
livesin(v0, v1) :- influences(v1, v0), haswonprize(v1, v0), Rule(2028).
type error
livesin(v0, v1) :- influences(v1, v0), haswonprize(v0, v1), Rule(2029).
type error
livesin(v0, v1) :- influences(v2, v1), haswonprize(v0, v2), Rule(2030).
type error
livesin(v0, v1) :- influences(v1, v2), haswonprize(v2, v0), Rule(2031).
type error
livesin(v0, v1) :- influences(v2, v0), haswonprize(v1, v2), Rule(2032).
type error
livesin(v0, v1) :- influences(v2, v0), haswonprize(v2, v1), Rule(2033).
type error
livesin(v0, v1) :- influences(v0, v2), haswonprize(v1, v2), Rule(2034).
type error
livesin(v0, v1) :- influences(v0, v2), haswonprize(v2, v1), Rule(2035).
type error
livesin(v0, v1) :- influences(v2, v1), haswonprize(v2, v0), Rule(2036).
type error
livesin(v0, v1) :- influences(v1, v2), haswonprize(v0, v2), Rule(2037).
type error
livesin(v0, v1) :- influences(v0, v1), directed(v0, v1), Rule(2038).
type error
livesin(v0, v1) :- influences(v0, v1), directed(v1, v0), Rule(2039).
type error
livesin(v0, v1) :- influences(v1, v0), directed(v1, v0), Rule(2040).
type error
livesin(v0, v1) :- influences(v1, v0), directed(v0, v1), Rule(2041).
type error
livesin(v0, v1) :- influences(v2, v1), directed(v0, v2), Rule(2042).
type error
livesin(v0, v1) :- influences(v1, v2), directed(v2, v0), Rule(2043).
type error
livesin(v0, v1) :- influences(v2, v0), directed(v1, v2), Rule(2044).
type error
livesin(v0, v1) :- influences(v2, v0), directed(v2, v1), Rule(2045).
type error
livesin(v0, v1) :- influences(v0, v2), directed(v1, v2), Rule(2046).
type error
livesin(v0, v1) :- influences(v0, v2), directed(v2, v1), Rule(2047).
type error
livesin(v0, v1) :- influences(v2, v1), directed(v2, v0), Rule(2048).
type error
livesin(v0, v1) :- influences(v1, v2), directed(v0, v2), Rule(2049).
type error
livesin(v0, v1) :- influences(v0, v1), haschild(v0, v1), Rule(2050).
type error
livesin(v0, v1) :- influences(v0, v1), haschild(v1, v0), Rule(2051).
type error
livesin(v0, v1) :- influences(v1, v0), haschild(v1, v0), Rule(2052).
type error
livesin(v0, v1) :- influences(v1, v0), haschild(v0, v1), Rule(2053).
type error
livesin(v0, v1) :- influences(v2, v1), haschild(v0, v2), Rule(2054).
type error
livesin(v0, v1) :- influences(v1, v2), haschild(v2, v0), Rule(2055).
type error
livesin(v0, v1) :- influences(v2, v0), haschild(v1, v2), Rule(2056).
type error
livesin(v0, v1) :- influences(v2, v0), haschild(v2, v1), Rule(2057).
type error
livesin(v0, v1) :- influences(v0, v2), haschild(v1, v2), Rule(2058).
type error
livesin(v0, v1) :- influences(v0, v2), haschild(v2, v1), Rule(2059).
type error
livesin(v0, v1) :- influences(v2, v1), haschild(v2, v0), Rule(2060).
type error
livesin(v0, v1) :- influences(v1, v2), haschild(v0, v2), Rule(2061).
Head twice 
livesin(v0, v1) :- influences(v0, v1), Ilivesin(v0, v1), Rule(2062).
input prevent
livesin(v0, v1) :- influences(v0, v1), Ilivesin(v1, v0), Rule(2063).
input prevent
livesin(v0, v1) :- influences(v1, v0), Ilivesin(v1, v0), Rule(2064).
Head twice 
livesin(v0, v1) :- influences(v1, v0), Ilivesin(v0, v1), Rule(2065).
type error
livesin(v0, v1) :- influences(v2, v1), Ilivesin(v0, v2), Rule(2066).
type error
livesin(v0, v1) :- influences(v1, v2), Ilivesin(v2, v0), Rule(2067).
type error
livesin(v0, v1) :- influences(v2, v0), Ilivesin(v1, v2), Rule(2068).
type error
livesin(v0, v1) :- influences(v0, v2), Ilivesin(v1, v2), Rule(2070).
type error
livesin(v0, v1) :- influences(v2, v1), Ilivesin(v2, v0), Rule(2072).
type error
livesin(v0, v1) :- influences(v1, v2), Ilivesin(v0, v2), Rule(2073).
type error
livesin(v0, v1) :- influences(v0, v1), inv_0(v0, v1), Rule(2074).
type error
livesin(v0, v1) :- influences(v0, v1), inv_0(v1, v0), Rule(2075).
type error
livesin(v0, v1) :- influences(v1, v0), inv_0(v1, v0), Rule(2076).
type error
livesin(v0, v1) :- influences(v1, v0), inv_0(v0, v1), Rule(2077).
type error
livesin(v0, v1) :- influences(v2, v1), inv_0(v0, v2), Rule(2078).
type error
livesin(v0, v1) :- influences(v1, v2), inv_0(v2, v0), Rule(2079).
type error
livesin(v0, v1) :- influences(v2, v1), inv_0(v2, v0), Rule(2084).
type error
livesin(v0, v1) :- influences(v1, v2), inv_0(v0, v2), Rule(2085).
Head twice 
livesin(v0, v1) :- influences(v0, v1), livesin(v0, v1), Rule(2086).
type error
livesin(v0, v1) :- influences(v0, v1), livesin(v1, v0), Rule(2087).
type error
livesin(v0, v1) :- influences(v1, v0), livesin(v1, v0), Rule(2088).
Head twice 
livesin(v0, v1) :- influences(v1, v0), livesin(v0, v1), Rule(2089).
type error
livesin(v0, v1) :- influences(v2, v1), livesin(v0, v2), Rule(2090).
type error
livesin(v0, v1) :- influences(v1, v2), livesin(v2, v0), Rule(2091).
type error
livesin(v0, v1) :- influences(v2, v0), livesin(v1, v2), Rule(2092).
type error
livesin(v0, v1) :- influences(v0, v2), livesin(v1, v2), Rule(2094).
type error
livesin(v0, v1) :- influences(v2, v1), livesin(v2, v0), Rule(2096).
type error
livesin(v0, v1) :- influences(v1, v2), livesin(v0, v2), Rule(2097).
type error
livesin(v0, v1) :- actedin(v0, v1), actedin(v0, v1), Rule(2098).
type error
livesin(v0, v1) :- actedin(v0, v1), actedin(v1, v0), Rule(2099).
type error
livesin(v0, v1) :- actedin(v1, v0), actedin(v1, v0), Rule(2100).
type error
livesin(v0, v1) :- actedin(v1, v0), actedin(v0, v1), Rule(2101).
type error
livesin(v0, v1) :- actedin(v2, v1), actedin(v0, v2), Rule(2102).
type error
livesin(v0, v1) :- actedin(v1, v2), actedin(v2, v0), Rule(2103).
type error
livesin(v0, v1) :- actedin(v2, v0), actedin(v1, v2), Rule(2104).
type error
livesin(v0, v1) :- actedin(v2, v0), actedin(v2, v1), Rule(2105).
type error
livesin(v0, v1) :- actedin(v0, v2), actedin(v1, v2), Rule(2106).
type error
livesin(v0, v1) :- actedin(v0, v2), actedin(v2, v1), Rule(2107).
type error
livesin(v0, v1) :- actedin(v2, v1), actedin(v2, v0), Rule(2108).
type error
livesin(v0, v1) :- actedin(v1, v2), actedin(v0, v2), Rule(2109).
type error
livesin(v0, v1) :- actedin(v0, v1), diedin(v0, v1), Rule(2110).
type error
livesin(v0, v1) :- actedin(v0, v1), diedin(v1, v0), Rule(2111).
type error
livesin(v0, v1) :- actedin(v1, v0), diedin(v1, v0), Rule(2112).
type error
livesin(v0, v1) :- actedin(v1, v0), diedin(v0, v1), Rule(2113).
type error
livesin(v0, v1) :- actedin(v2, v1), diedin(v0, v2), Rule(2114).
type error
livesin(v0, v1) :- actedin(v1, v2), diedin(v2, v0), Rule(2115).
type error
livesin(v0, v1) :- actedin(v2, v0), diedin(v1, v2), Rule(2116).
type error
livesin(v0, v1) :- actedin(v2, v0), diedin(v2, v1), Rule(2117).
type error
livesin(v0, v1) :- actedin(v0, v2), diedin(v1, v2), Rule(2118).
type error
livesin(v0, v1) :- actedin(v0, v2), diedin(v2, v1), Rule(2119).
type error
livesin(v0, v1) :- actedin(v2, v1), diedin(v2, v0), Rule(2120).
type error
livesin(v0, v1) :- actedin(v1, v2), diedin(v0, v2), Rule(2121).
type error
livesin(v0, v1) :- actedin(v0, v1), wasbornin(v0, v1), Rule(2122).
type error
livesin(v0, v1) :- actedin(v0, v1), wasbornin(v1, v0), Rule(2123).
type error
livesin(v0, v1) :- actedin(v1, v0), wasbornin(v1, v0), Rule(2124).
type error
livesin(v0, v1) :- actedin(v1, v0), wasbornin(v0, v1), Rule(2125).
type error
livesin(v0, v1) :- actedin(v2, v1), wasbornin(v0, v2), Rule(2126).
type error
livesin(v0, v1) :- actedin(v1, v2), wasbornin(v2, v0), Rule(2127).
type error
livesin(v0, v1) :- actedin(v2, v0), wasbornin(v1, v2), Rule(2128).
type error
livesin(v0, v1) :- actedin(v2, v0), wasbornin(v2, v1), Rule(2129).
type error
livesin(v0, v1) :- actedin(v0, v2), wasbornin(v1, v2), Rule(2130).
type error
livesin(v0, v1) :- actedin(v0, v2), wasbornin(v2, v1), Rule(2131).
type error
livesin(v0, v1) :- actedin(v2, v1), wasbornin(v2, v0), Rule(2132).
type error
livesin(v0, v1) :- actedin(v1, v2), wasbornin(v0, v2), Rule(2133).
type error
livesin(v0, v1) :- actedin(v0, v1), hasgeonamesid(v0, v1), Rule(2134).
type error
livesin(v0, v1) :- actedin(v0, v1), hasgeonamesid(v1, v0), Rule(2135).
type error
livesin(v0, v1) :- actedin(v1, v0), hasgeonamesid(v1, v0), Rule(2136).
type error
livesin(v0, v1) :- actedin(v1, v0), hasgeonamesid(v0, v1), Rule(2137).
type error
livesin(v0, v1) :- actedin(v2, v1), hasgeonamesid(v0, v2), Rule(2138).
type error
livesin(v0, v1) :- actedin(v1, v2), hasgeonamesid(v2, v0), Rule(2139).
type error
livesin(v0, v1) :- actedin(v2, v0), hasgeonamesid(v1, v2), Rule(2140).
type error
livesin(v0, v1) :- actedin(v2, v0), hasgeonamesid(v2, v1), Rule(2141).
type error
livesin(v0, v1) :- actedin(v0, v2), hasgeonamesid(v1, v2), Rule(2142).
type error
livesin(v0, v1) :- actedin(v0, v2), hasgeonamesid(v2, v1), Rule(2143).
type error
livesin(v0, v1) :- actedin(v2, v1), hasgeonamesid(v2, v0), Rule(2144).
type error
livesin(v0, v1) :- actedin(v1, v2), hasgeonamesid(v0, v2), Rule(2145).
type error
livesin(v0, v1) :- actedin(v0, v1), haswonprize(v0, v1), Rule(2146).
type error
livesin(v0, v1) :- actedin(v0, v1), haswonprize(v1, v0), Rule(2147).
type error
livesin(v0, v1) :- actedin(v1, v0), haswonprize(v1, v0), Rule(2148).
type error
livesin(v0, v1) :- actedin(v1, v0), haswonprize(v0, v1), Rule(2149).
type error
livesin(v0, v1) :- actedin(v2, v1), haswonprize(v0, v2), Rule(2150).
type error
livesin(v0, v1) :- actedin(v1, v2), haswonprize(v2, v0), Rule(2151).
type error
livesin(v0, v1) :- actedin(v2, v0), haswonprize(v1, v2), Rule(2152).
type error
livesin(v0, v1) :- actedin(v2, v0), haswonprize(v2, v1), Rule(2153).
type error
livesin(v0, v1) :- actedin(v0, v2), haswonprize(v1, v2), Rule(2154).
type error
livesin(v0, v1) :- actedin(v0, v2), haswonprize(v2, v1), Rule(2155).
type error
livesin(v0, v1) :- actedin(v2, v1), haswonprize(v2, v0), Rule(2156).
type error
livesin(v0, v1) :- actedin(v1, v2), haswonprize(v0, v2), Rule(2157).
type error
livesin(v0, v1) :- actedin(v0, v1), directed(v0, v1), Rule(2158).
type error
livesin(v0, v1) :- actedin(v0, v1), directed(v1, v0), Rule(2159).
type error
livesin(v0, v1) :- actedin(v1, v0), directed(v1, v0), Rule(2160).
type error
livesin(v0, v1) :- actedin(v1, v0), directed(v0, v1), Rule(2161).
type error
livesin(v0, v1) :- actedin(v2, v1), directed(v0, v2), Rule(2162).
type error
livesin(v0, v1) :- actedin(v1, v2), directed(v2, v0), Rule(2163).
type error
livesin(v0, v1) :- actedin(v2, v0), directed(v1, v2), Rule(2164).
type error
livesin(v0, v1) :- actedin(v2, v0), directed(v2, v1), Rule(2165).
type error
livesin(v0, v1) :- actedin(v0, v2), directed(v1, v2), Rule(2166).
type error
livesin(v0, v1) :- actedin(v0, v2), directed(v2, v1), Rule(2167).
type error
livesin(v0, v1) :- actedin(v2, v1), directed(v2, v0), Rule(2168).
type error
livesin(v0, v1) :- actedin(v1, v2), directed(v0, v2), Rule(2169).
type error
livesin(v0, v1) :- actedin(v0, v1), haschild(v0, v1), Rule(2170).
type error
livesin(v0, v1) :- actedin(v0, v1), haschild(v1, v0), Rule(2171).
type error
livesin(v0, v1) :- actedin(v1, v0), haschild(v1, v0), Rule(2172).
type error
livesin(v0, v1) :- actedin(v1, v0), haschild(v0, v1), Rule(2173).
type error
livesin(v0, v1) :- actedin(v2, v1), haschild(v0, v2), Rule(2174).
type error
livesin(v0, v1) :- actedin(v1, v2), haschild(v2, v0), Rule(2175).
type error
livesin(v0, v1) :- actedin(v2, v0), haschild(v1, v2), Rule(2176).
type error
livesin(v0, v1) :- actedin(v2, v0), haschild(v2, v1), Rule(2177).
type error
livesin(v0, v1) :- actedin(v0, v2), haschild(v1, v2), Rule(2178).
type error
livesin(v0, v1) :- actedin(v0, v2), haschild(v2, v1), Rule(2179).
type error
livesin(v0, v1) :- actedin(v2, v1), haschild(v2, v0), Rule(2180).
type error
livesin(v0, v1) :- actedin(v1, v2), haschild(v0, v2), Rule(2181).
Head twice 
livesin(v0, v1) :- actedin(v0, v1), Ilivesin(v0, v1), Rule(2182).
input prevent
livesin(v0, v1) :- actedin(v0, v1), Ilivesin(v1, v0), Rule(2183).
input prevent
livesin(v0, v1) :- actedin(v1, v0), Ilivesin(v1, v0), Rule(2184).
Head twice 
livesin(v0, v1) :- actedin(v1, v0), Ilivesin(v0, v1), Rule(2185).
type error
livesin(v0, v1) :- actedin(v2, v1), Ilivesin(v0, v2), Rule(2186).
type error
livesin(v0, v1) :- actedin(v1, v2), Ilivesin(v2, v0), Rule(2187).
type error
livesin(v0, v1) :- actedin(v2, v0), Ilivesin(v1, v2), Rule(2188).
type error
livesin(v0, v1) :- actedin(v2, v0), Ilivesin(v2, v1), Rule(2189).
type error
livesin(v0, v1) :- actedin(v0, v2), Ilivesin(v1, v2), Rule(2190).
type error
livesin(v0, v1) :- actedin(v0, v2), Ilivesin(v2, v1), Rule(2191).
type error
livesin(v0, v1) :- actedin(v2, v1), Ilivesin(v2, v0), Rule(2192).
type error
livesin(v0, v1) :- actedin(v1, v2), Ilivesin(v0, v2), Rule(2193).
type error
livesin(v0, v1) :- actedin(v0, v1), inv_0(v0, v1), Rule(2194).
type error
livesin(v0, v1) :- actedin(v0, v1), inv_0(v1, v0), Rule(2195).
type error
livesin(v0, v1) :- actedin(v1, v0), inv_0(v1, v0), Rule(2196).
type error
livesin(v0, v1) :- actedin(v1, v0), inv_0(v0, v1), Rule(2197).
type error
livesin(v0, v1) :- actedin(v2, v1), inv_0(v0, v2), Rule(2198).
type error
livesin(v0, v1) :- actedin(v1, v2), inv_0(v2, v0), Rule(2199).
type error
livesin(v0, v1) :- actedin(v2, v0), inv_0(v1, v2), Rule(2200).
type error
livesin(v0, v1) :- actedin(v2, v0), inv_0(v2, v1), Rule(2201).
type error
livesin(v0, v1) :- actedin(v2, v1), inv_0(v2, v0), Rule(2204).
type error
livesin(v0, v1) :- actedin(v1, v2), inv_0(v0, v2), Rule(2205).
Head twice 
livesin(v0, v1) :- actedin(v0, v1), livesin(v0, v1), Rule(2206).
type error
livesin(v0, v1) :- actedin(v0, v1), livesin(v1, v0), Rule(2207).
type error
livesin(v0, v1) :- actedin(v1, v0), livesin(v1, v0), Rule(2208).
Head twice 
livesin(v0, v1) :- actedin(v1, v0), livesin(v0, v1), Rule(2209).
type error
livesin(v0, v1) :- actedin(v2, v1), livesin(v0, v2), Rule(2210).
type error
livesin(v0, v1) :- actedin(v1, v2), livesin(v2, v0), Rule(2211).
type error
livesin(v0, v1) :- actedin(v2, v0), livesin(v1, v2), Rule(2212).
type error
livesin(v0, v1) :- actedin(v2, v0), livesin(v2, v1), Rule(2213).
type error
livesin(v0, v1) :- actedin(v0, v2), livesin(v1, v2), Rule(2214).
type error
livesin(v0, v1) :- actedin(v0, v2), livesin(v2, v1), Rule(2215).
type error
livesin(v0, v1) :- actedin(v2, v1), livesin(v2, v0), Rule(2216).
type error
livesin(v0, v1) :- actedin(v1, v2), livesin(v0, v2), Rule(2217).
type error
livesin(v0, v1) :- diedin(v0, v1), diedin(v1, v0), Rule(2219).
type error
livesin(v0, v1) :- diedin(v1, v0), diedin(v1, v0), Rule(2220).
type error
livesin(v0, v1) :- diedin(v1, v0), diedin(v0, v1), Rule(2221).
type error
livesin(v0, v1) :- diedin(v2, v1), diedin(v0, v2), Rule(2222).
type error
livesin(v0, v1) :- diedin(v1, v2), diedin(v2, v0), Rule(2223).
type error
livesin(v0, v1) :- diedin(v2, v0), diedin(v1, v2), Rule(2224).
type error
livesin(v0, v1) :- diedin(v2, v0), diedin(v2, v1), Rule(2225).
type error
livesin(v0, v1) :- diedin(v0, v2), diedin(v1, v2), Rule(2226).
type error
livesin(v0, v1) :- diedin(v0, v2), diedin(v2, v1), Rule(2227).
type error
livesin(v0, v1) :- diedin(v2, v1), diedin(v2, v0), Rule(2228).
type error
livesin(v0, v1) :- diedin(v1, v2), diedin(v0, v2), Rule(2229).
type error
livesin(v0, v1) :- diedin(v0, v1), wasbornin(v1, v0), Rule(2231).
type error
livesin(v0, v1) :- diedin(v1, v0), wasbornin(v1, v0), Rule(2232).
type error
livesin(v0, v1) :- diedin(v1, v0), wasbornin(v0, v1), Rule(2233).
type error
livesin(v0, v1) :- diedin(v2, v1), wasbornin(v0, v2), Rule(2234).
type error
livesin(v0, v1) :- diedin(v1, v2), wasbornin(v2, v0), Rule(2235).
type error
livesin(v0, v1) :- diedin(v2, v0), wasbornin(v1, v2), Rule(2236).
type error
livesin(v0, v1) :- diedin(v2, v0), wasbornin(v2, v1), Rule(2237).
type error
livesin(v0, v1) :- diedin(v0, v2), wasbornin(v1, v2), Rule(2238).
type error
livesin(v0, v1) :- diedin(v0, v2), wasbornin(v2, v1), Rule(2239).
type error
livesin(v0, v1) :- diedin(v2, v1), wasbornin(v2, v0), Rule(2240).
type error
livesin(v0, v1) :- diedin(v1, v2), wasbornin(v0, v2), Rule(2241).
type error
livesin(v0, v1) :- diedin(v0, v1), hasgeonamesid(v0, v1), Rule(2242).
type error
livesin(v0, v1) :- diedin(v0, v1), hasgeonamesid(v1, v0), Rule(2243).
type error
livesin(v0, v1) :- diedin(v1, v0), hasgeonamesid(v1, v0), Rule(2244).
type error
livesin(v0, v1) :- diedin(v1, v0), hasgeonamesid(v0, v1), Rule(2245).
type error
livesin(v0, v1) :- diedin(v2, v1), hasgeonamesid(v0, v2), Rule(2246).
type error
livesin(v0, v1) :- diedin(v1, v2), hasgeonamesid(v2, v0), Rule(2247).
type error
livesin(v0, v1) :- diedin(v2, v0), hasgeonamesid(v1, v2), Rule(2248).
type error
livesin(v0, v1) :- diedin(v2, v0), hasgeonamesid(v2, v1), Rule(2249).
type error
livesin(v0, v1) :- diedin(v0, v2), hasgeonamesid(v1, v2), Rule(2250).
type error
livesin(v0, v1) :- diedin(v0, v2), hasgeonamesid(v2, v1), Rule(2251).
type error
livesin(v0, v1) :- diedin(v2, v1), hasgeonamesid(v2, v0), Rule(2252).
type error
livesin(v0, v1) :- diedin(v1, v2), hasgeonamesid(v0, v2), Rule(2253).
type error
livesin(v0, v1) :- diedin(v0, v1), haswonprize(v0, v1), Rule(2254).
type error
livesin(v0, v1) :- diedin(v0, v1), haswonprize(v1, v0), Rule(2255).
type error
livesin(v0, v1) :- diedin(v1, v0), haswonprize(v1, v0), Rule(2256).
type error
livesin(v0, v1) :- diedin(v1, v0), haswonprize(v0, v1), Rule(2257).
type error
livesin(v0, v1) :- diedin(v2, v1), haswonprize(v0, v2), Rule(2258).
type error
livesin(v0, v1) :- diedin(v1, v2), haswonprize(v2, v0), Rule(2259).
type error
livesin(v0, v1) :- diedin(v2, v0), haswonprize(v1, v2), Rule(2260).
type error
livesin(v0, v1) :- diedin(v2, v0), haswonprize(v2, v1), Rule(2261).
type error
livesin(v0, v1) :- diedin(v0, v2), haswonprize(v1, v2), Rule(2262).
type error
livesin(v0, v1) :- diedin(v0, v2), haswonprize(v2, v1), Rule(2263).
type error
livesin(v0, v1) :- diedin(v2, v1), haswonprize(v2, v0), Rule(2264).
type error
livesin(v0, v1) :- diedin(v1, v2), haswonprize(v0, v2), Rule(2265).
type error
livesin(v0, v1) :- diedin(v0, v1), directed(v0, v1), Rule(2266).
type error
livesin(v0, v1) :- diedin(v0, v1), directed(v1, v0), Rule(2267).
type error
livesin(v0, v1) :- diedin(v1, v0), directed(v1, v0), Rule(2268).
type error
livesin(v0, v1) :- diedin(v1, v0), directed(v0, v1), Rule(2269).
type error
livesin(v0, v1) :- diedin(v2, v1), directed(v0, v2), Rule(2270).
type error
livesin(v0, v1) :- diedin(v1, v2), directed(v2, v0), Rule(2271).
type error
livesin(v0, v1) :- diedin(v2, v0), directed(v1, v2), Rule(2272).
type error
livesin(v0, v1) :- diedin(v2, v0), directed(v2, v1), Rule(2273).
type error
livesin(v0, v1) :- diedin(v0, v2), directed(v1, v2), Rule(2274).
type error
livesin(v0, v1) :- diedin(v0, v2), directed(v2, v1), Rule(2275).
type error
livesin(v0, v1) :- diedin(v2, v1), directed(v2, v0), Rule(2276).
type error
livesin(v0, v1) :- diedin(v1, v2), directed(v0, v2), Rule(2277).
type error
livesin(v0, v1) :- diedin(v0, v1), haschild(v0, v1), Rule(2278).
type error
livesin(v0, v1) :- diedin(v0, v1), haschild(v1, v0), Rule(2279).
type error
livesin(v0, v1) :- diedin(v1, v0), haschild(v1, v0), Rule(2280).
type error
livesin(v0, v1) :- diedin(v1, v0), haschild(v0, v1), Rule(2281).
type error
livesin(v0, v1) :- diedin(v1, v2), haschild(v2, v0), Rule(2283).
type error
livesin(v0, v1) :- diedin(v2, v0), haschild(v1, v2), Rule(2284).
type error
livesin(v0, v1) :- diedin(v2, v0), haschild(v2, v1), Rule(2285).
type error
livesin(v0, v1) :- diedin(v0, v2), haschild(v1, v2), Rule(2286).
type error
livesin(v0, v1) :- diedin(v0, v2), haschild(v2, v1), Rule(2287).
type error
livesin(v0, v1) :- diedin(v1, v2), haschild(v0, v2), Rule(2289).
Head twice 
livesin(v0, v1) :- diedin(v0, v1), Ilivesin(v0, v1), Rule(2290).
input prevent
livesin(v0, v1) :- diedin(v0, v1), Ilivesin(v1, v0), Rule(2291).
input prevent
livesin(v0, v1) :- diedin(v1, v0), Ilivesin(v1, v0), Rule(2292).
Head twice 
livesin(v0, v1) :- diedin(v1, v0), Ilivesin(v0, v1), Rule(2293).
type error
livesin(v0, v1) :- diedin(v2, v1), Ilivesin(v0, v2), Rule(2294).
type error
livesin(v0, v1) :- diedin(v1, v2), Ilivesin(v2, v0), Rule(2295).
type error
livesin(v0, v1) :- diedin(v2, v0), Ilivesin(v1, v2), Rule(2296).
type error
livesin(v0, v1) :- diedin(v2, v0), Ilivesin(v2, v1), Rule(2297).
type error
livesin(v0, v1) :- diedin(v0, v2), Ilivesin(v1, v2), Rule(2298).
type error
livesin(v0, v1) :- diedin(v0, v2), Ilivesin(v2, v1), Rule(2299).
type error
livesin(v0, v1) :- diedin(v2, v1), Ilivesin(v2, v0), Rule(2300).
type error
livesin(v0, v1) :- diedin(v1, v2), Ilivesin(v0, v2), Rule(2301).
type error
livesin(v0, v1) :- diedin(v1, v0), inv_0(v1, v0), Rule(2304).
type error
livesin(v0, v1) :- diedin(v1, v0), inv_0(v0, v1), Rule(2305).
type error
livesin(v0, v1) :- diedin(v1, v2), inv_0(v2, v0), Rule(2307).
type error
livesin(v0, v1) :- diedin(v2, v0), inv_0(v1, v2), Rule(2308).
type error
livesin(v0, v1) :- diedin(v2, v0), inv_0(v2, v1), Rule(2309).
type error
livesin(v0, v1) :- diedin(v1, v2), inv_0(v0, v2), Rule(2313).
Head twice 
livesin(v0, v1) :- diedin(v0, v1), livesin(v0, v1), Rule(2314).
type error
livesin(v0, v1) :- diedin(v0, v1), livesin(v1, v0), Rule(2315).
type error
livesin(v0, v1) :- diedin(v1, v0), livesin(v1, v0), Rule(2316).
Head twice 
livesin(v0, v1) :- diedin(v1, v0), livesin(v0, v1), Rule(2317).
type error
livesin(v0, v1) :- diedin(v2, v1), livesin(v0, v2), Rule(2318).
type error
livesin(v0, v1) :- diedin(v1, v2), livesin(v2, v0), Rule(2319).
type error
livesin(v0, v1) :- diedin(v2, v0), livesin(v1, v2), Rule(2320).
type error
livesin(v0, v1) :- diedin(v2, v0), livesin(v2, v1), Rule(2321).
type error
livesin(v0, v1) :- diedin(v0, v2), livesin(v1, v2), Rule(2322).
type error
livesin(v0, v1) :- diedin(v0, v2), livesin(v2, v1), Rule(2323).
type error
livesin(v0, v1) :- diedin(v2, v1), livesin(v2, v0), Rule(2324).
type error
livesin(v0, v1) :- diedin(v1, v2), livesin(v0, v2), Rule(2325).
type error
livesin(v0, v1) :- wasbornin(v0, v1), wasbornin(v1, v0), Rule(2327).
type error
livesin(v0, v1) :- wasbornin(v1, v0), wasbornin(v1, v0), Rule(2328).
type error
livesin(v0, v1) :- wasbornin(v1, v0), wasbornin(v0, v1), Rule(2329).
type error
livesin(v0, v1) :- wasbornin(v2, v1), wasbornin(v0, v2), Rule(2330).
type error
livesin(v0, v1) :- wasbornin(v1, v2), wasbornin(v2, v0), Rule(2331).
type error
livesin(v0, v1) :- wasbornin(v2, v0), wasbornin(v1, v2), Rule(2332).
type error
livesin(v0, v1) :- wasbornin(v2, v0), wasbornin(v2, v1), Rule(2333).
type error
livesin(v0, v1) :- wasbornin(v0, v2), wasbornin(v1, v2), Rule(2334).
type error
livesin(v0, v1) :- wasbornin(v0, v2), wasbornin(v2, v1), Rule(2335).
type error
livesin(v0, v1) :- wasbornin(v2, v1), wasbornin(v2, v0), Rule(2336).
type error
livesin(v0, v1) :- wasbornin(v1, v2), wasbornin(v0, v2), Rule(2337).
type error
livesin(v0, v1) :- wasbornin(v0, v1), hasgeonamesid(v0, v1), Rule(2338).
type error
livesin(v0, v1) :- wasbornin(v0, v1), hasgeonamesid(v1, v0), Rule(2339).
type error
livesin(v0, v1) :- wasbornin(v1, v0), hasgeonamesid(v1, v0), Rule(2340).
type error
livesin(v0, v1) :- wasbornin(v1, v0), hasgeonamesid(v0, v1), Rule(2341).
type error
livesin(v0, v1) :- wasbornin(v2, v1), hasgeonamesid(v0, v2), Rule(2342).
type error
livesin(v0, v1) :- wasbornin(v1, v2), hasgeonamesid(v2, v0), Rule(2343).
type error
livesin(v0, v1) :- wasbornin(v2, v0), hasgeonamesid(v1, v2), Rule(2344).
type error
livesin(v0, v1) :- wasbornin(v2, v0), hasgeonamesid(v2, v1), Rule(2345).
type error
livesin(v0, v1) :- wasbornin(v0, v2), hasgeonamesid(v1, v2), Rule(2346).
type error
livesin(v0, v1) :- wasbornin(v0, v2), hasgeonamesid(v2, v1), Rule(2347).
type error
livesin(v0, v1) :- wasbornin(v2, v1), hasgeonamesid(v2, v0), Rule(2348).
type error
livesin(v0, v1) :- wasbornin(v1, v2), hasgeonamesid(v0, v2), Rule(2349).
type error
livesin(v0, v1) :- wasbornin(v0, v1), haswonprize(v0, v1), Rule(2350).
type error
livesin(v0, v1) :- wasbornin(v0, v1), haswonprize(v1, v0), Rule(2351).
type error
livesin(v0, v1) :- wasbornin(v1, v0), haswonprize(v1, v0), Rule(2352).
type error
livesin(v0, v1) :- wasbornin(v1, v0), haswonprize(v0, v1), Rule(2353).
type error
livesin(v0, v1) :- wasbornin(v2, v1), haswonprize(v0, v2), Rule(2354).
type error
livesin(v0, v1) :- wasbornin(v1, v2), haswonprize(v2, v0), Rule(2355).
type error
livesin(v0, v1) :- wasbornin(v2, v0), haswonprize(v1, v2), Rule(2356).
type error
livesin(v0, v1) :- wasbornin(v2, v0), haswonprize(v2, v1), Rule(2357).
type error
livesin(v0, v1) :- wasbornin(v0, v2), haswonprize(v1, v2), Rule(2358).
type error
livesin(v0, v1) :- wasbornin(v0, v2), haswonprize(v2, v1), Rule(2359).
type error
livesin(v0, v1) :- wasbornin(v2, v1), haswonprize(v2, v0), Rule(2360).
type error
livesin(v0, v1) :- wasbornin(v1, v2), haswonprize(v0, v2), Rule(2361).
type error
livesin(v0, v1) :- wasbornin(v0, v1), directed(v0, v1), Rule(2362).
type error
livesin(v0, v1) :- wasbornin(v0, v1), directed(v1, v0), Rule(2363).
type error
livesin(v0, v1) :- wasbornin(v1, v0), directed(v1, v0), Rule(2364).
type error
livesin(v0, v1) :- wasbornin(v1, v0), directed(v0, v1), Rule(2365).
type error
livesin(v0, v1) :- wasbornin(v2, v1), directed(v0, v2), Rule(2366).
type error
livesin(v0, v1) :- wasbornin(v1, v2), directed(v2, v0), Rule(2367).
type error
livesin(v0, v1) :- wasbornin(v2, v0), directed(v1, v2), Rule(2368).
type error
livesin(v0, v1) :- wasbornin(v2, v0), directed(v2, v1), Rule(2369).
type error
livesin(v0, v1) :- wasbornin(v0, v2), directed(v1, v2), Rule(2370).
type error
livesin(v0, v1) :- wasbornin(v0, v2), directed(v2, v1), Rule(2371).
type error
livesin(v0, v1) :- wasbornin(v2, v1), directed(v2, v0), Rule(2372).
type error
livesin(v0, v1) :- wasbornin(v1, v2), directed(v0, v2), Rule(2373).
type error
livesin(v0, v1) :- wasbornin(v0, v1), haschild(v0, v1), Rule(2374).
type error
livesin(v0, v1) :- wasbornin(v0, v1), haschild(v1, v0), Rule(2375).
type error
livesin(v0, v1) :- wasbornin(v1, v0), haschild(v1, v0), Rule(2376).
type error
livesin(v0, v1) :- wasbornin(v1, v0), haschild(v0, v1), Rule(2377).
type error
livesin(v0, v1) :- wasbornin(v1, v2), haschild(v2, v0), Rule(2379).
type error
livesin(v0, v1) :- wasbornin(v2, v0), haschild(v1, v2), Rule(2380).
type error
livesin(v0, v1) :- wasbornin(v2, v0), haschild(v2, v1), Rule(2381).
type error
livesin(v0, v1) :- wasbornin(v0, v2), haschild(v1, v2), Rule(2382).
type error
livesin(v0, v1) :- wasbornin(v0, v2), haschild(v2, v1), Rule(2383).
type error
livesin(v0, v1) :- wasbornin(v1, v2), haschild(v0, v2), Rule(2385).
Head twice 
livesin(v0, v1) :- wasbornin(v0, v1), Ilivesin(v0, v1), Rule(2386).
input prevent
livesin(v0, v1) :- wasbornin(v0, v1), Ilivesin(v1, v0), Rule(2387).
input prevent
livesin(v0, v1) :- wasbornin(v1, v0), Ilivesin(v1, v0), Rule(2388).
Head twice 
livesin(v0, v1) :- wasbornin(v1, v0), Ilivesin(v0, v1), Rule(2389).
type error
livesin(v0, v1) :- wasbornin(v2, v1), Ilivesin(v0, v2), Rule(2390).
type error
livesin(v0, v1) :- wasbornin(v1, v2), Ilivesin(v2, v0), Rule(2391).
type error
livesin(v0, v1) :- wasbornin(v2, v0), Ilivesin(v1, v2), Rule(2392).
type error
livesin(v0, v1) :- wasbornin(v2, v0), Ilivesin(v2, v1), Rule(2393).
type error
livesin(v0, v1) :- wasbornin(v0, v2), Ilivesin(v1, v2), Rule(2394).
type error
livesin(v0, v1) :- wasbornin(v0, v2), Ilivesin(v2, v1), Rule(2395).
type error
livesin(v0, v1) :- wasbornin(v2, v1), Ilivesin(v2, v0), Rule(2396).
type error
livesin(v0, v1) :- wasbornin(v1, v2), Ilivesin(v0, v2), Rule(2397).
type error
livesin(v0, v1) :- wasbornin(v1, v0), inv_0(v1, v0), Rule(2400).
type error
livesin(v0, v1) :- wasbornin(v1, v0), inv_0(v0, v1), Rule(2401).
type error
livesin(v0, v1) :- wasbornin(v1, v2), inv_0(v2, v0), Rule(2403).
type error
livesin(v0, v1) :- wasbornin(v2, v0), inv_0(v1, v2), Rule(2404).
type error
livesin(v0, v1) :- wasbornin(v2, v0), inv_0(v2, v1), Rule(2405).
type error
livesin(v0, v1) :- wasbornin(v1, v2), inv_0(v0, v2), Rule(2409).
Head twice 
livesin(v0, v1) :- wasbornin(v0, v1), livesin(v0, v1), Rule(2410).
type error
livesin(v0, v1) :- wasbornin(v0, v1), livesin(v1, v0), Rule(2411).
type error
livesin(v0, v1) :- wasbornin(v1, v0), livesin(v1, v0), Rule(2412).
Head twice 
livesin(v0, v1) :- wasbornin(v1, v0), livesin(v0, v1), Rule(2413).
type error
livesin(v0, v1) :- wasbornin(v2, v1), livesin(v0, v2), Rule(2414).
type error
livesin(v0, v1) :- wasbornin(v1, v2), livesin(v2, v0), Rule(2415).
type error
livesin(v0, v1) :- wasbornin(v2, v0), livesin(v1, v2), Rule(2416).
type error
livesin(v0, v1) :- wasbornin(v2, v0), livesin(v2, v1), Rule(2417).
type error
livesin(v0, v1) :- wasbornin(v0, v2), livesin(v1, v2), Rule(2418).
type error
livesin(v0, v1) :- wasbornin(v0, v2), livesin(v2, v1), Rule(2419).
type error
livesin(v0, v1) :- wasbornin(v2, v1), livesin(v2, v0), Rule(2420).
type error
livesin(v0, v1) :- wasbornin(v1, v2), livesin(v0, v2), Rule(2421).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), hasgeonamesid(v0, v1), Rule(2422).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), hasgeonamesid(v1, v0), Rule(2423).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), hasgeonamesid(v1, v0), Rule(2424).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), hasgeonamesid(v0, v1), Rule(2425).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), hasgeonamesid(v0, v2), Rule(2426).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), hasgeonamesid(v2, v0), Rule(2427).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), hasgeonamesid(v1, v2), Rule(2428).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), hasgeonamesid(v2, v1), Rule(2429).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), hasgeonamesid(v1, v2), Rule(2430).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), hasgeonamesid(v2, v1), Rule(2431).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), hasgeonamesid(v2, v0), Rule(2432).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), hasgeonamesid(v0, v2), Rule(2433).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), haswonprize(v0, v1), Rule(2434).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), haswonprize(v1, v0), Rule(2435).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), haswonprize(v1, v0), Rule(2436).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), haswonprize(v0, v1), Rule(2437).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), haswonprize(v0, v2), Rule(2438).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), haswonprize(v2, v0), Rule(2439).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), haswonprize(v1, v2), Rule(2440).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), haswonprize(v2, v1), Rule(2441).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), haswonprize(v1, v2), Rule(2442).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), haswonprize(v2, v1), Rule(2443).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), haswonprize(v2, v0), Rule(2444).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), haswonprize(v0, v2), Rule(2445).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), directed(v0, v1), Rule(2446).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), directed(v1, v0), Rule(2447).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), directed(v1, v0), Rule(2448).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), directed(v0, v1), Rule(2449).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), directed(v0, v2), Rule(2450).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), directed(v2, v0), Rule(2451).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), directed(v1, v2), Rule(2452).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), directed(v2, v1), Rule(2453).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), directed(v1, v2), Rule(2454).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), directed(v2, v1), Rule(2455).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), directed(v2, v0), Rule(2456).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), directed(v0, v2), Rule(2457).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), haschild(v0, v1), Rule(2458).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), haschild(v1, v0), Rule(2459).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), haschild(v1, v0), Rule(2460).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), haschild(v0, v1), Rule(2461).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), haschild(v0, v2), Rule(2462).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), haschild(v2, v0), Rule(2463).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), haschild(v1, v2), Rule(2464).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), haschild(v2, v1), Rule(2465).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), haschild(v1, v2), Rule(2466).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), haschild(v2, v1), Rule(2467).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), haschild(v2, v0), Rule(2468).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), haschild(v0, v2), Rule(2469).
Head twice 
livesin(v0, v1) :- hasgeonamesid(v0, v1), Ilivesin(v0, v1), Rule(2470).
input prevent
livesin(v0, v1) :- hasgeonamesid(v0, v1), Ilivesin(v1, v0), Rule(2471).
input prevent
livesin(v0, v1) :- hasgeonamesid(v1, v0), Ilivesin(v1, v0), Rule(2472).
Head twice 
livesin(v0, v1) :- hasgeonamesid(v1, v0), Ilivesin(v0, v1), Rule(2473).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), Ilivesin(v0, v2), Rule(2474).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), Ilivesin(v2, v0), Rule(2475).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), Ilivesin(v1, v2), Rule(2476).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), Ilivesin(v2, v1), Rule(2477).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), Ilivesin(v1, v2), Rule(2478).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), Ilivesin(v2, v1), Rule(2479).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), Ilivesin(v2, v0), Rule(2480).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), Ilivesin(v0, v2), Rule(2481).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), inv_0(v0, v1), Rule(2482).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), inv_0(v1, v0), Rule(2483).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), inv_0(v1, v0), Rule(2484).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), inv_0(v0, v1), Rule(2485).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), inv_0(v0, v2), Rule(2486).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), inv_0(v1, v2), Rule(2488).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), inv_0(v2, v1), Rule(2489).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), inv_0(v1, v2), Rule(2490).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), inv_0(v2, v1), Rule(2491).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), inv_0(v2, v0), Rule(2492).
Head twice 
livesin(v0, v1) :- hasgeonamesid(v0, v1), livesin(v0, v1), Rule(2494).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v1), livesin(v1, v0), Rule(2495).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v0), livesin(v1, v0), Rule(2496).
Head twice 
livesin(v0, v1) :- hasgeonamesid(v1, v0), livesin(v0, v1), Rule(2497).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), livesin(v0, v2), Rule(2498).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), livesin(v2, v0), Rule(2499).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), livesin(v1, v2), Rule(2500).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v0), livesin(v2, v1), Rule(2501).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), livesin(v1, v2), Rule(2502).
type error
livesin(v0, v1) :- hasgeonamesid(v0, v2), livesin(v2, v1), Rule(2503).
type error
livesin(v0, v1) :- hasgeonamesid(v2, v1), livesin(v2, v0), Rule(2504).
type error
livesin(v0, v1) :- hasgeonamesid(v1, v2), livesin(v0, v2), Rule(2505).
type error
livesin(v0, v1) :- haswonprize(v0, v1), haswonprize(v0, v1), Rule(2506).
type error
livesin(v0, v1) :- haswonprize(v0, v1), haswonprize(v1, v0), Rule(2507).
type error
livesin(v0, v1) :- haswonprize(v1, v0), haswonprize(v1, v0), Rule(2508).
type error
livesin(v0, v1) :- haswonprize(v1, v0), haswonprize(v0, v1), Rule(2509).
type error
livesin(v0, v1) :- haswonprize(v2, v1), haswonprize(v0, v2), Rule(2510).
type error
livesin(v0, v1) :- haswonprize(v1, v2), haswonprize(v2, v0), Rule(2511).
type error
livesin(v0, v1) :- haswonprize(v2, v0), haswonprize(v1, v2), Rule(2512).
type error
livesin(v0, v1) :- haswonprize(v2, v0), haswonprize(v2, v1), Rule(2513).
type error
livesin(v0, v1) :- haswonprize(v0, v2), haswonprize(v1, v2), Rule(2514).
type error
livesin(v0, v1) :- haswonprize(v0, v2), haswonprize(v2, v1), Rule(2515).
type error
livesin(v0, v1) :- haswonprize(v2, v1), haswonprize(v2, v0), Rule(2516).
type error
livesin(v0, v1) :- haswonprize(v1, v2), haswonprize(v0, v2), Rule(2517).
type error
livesin(v0, v1) :- haswonprize(v0, v1), directed(v0, v1), Rule(2518).
type error
livesin(v0, v1) :- haswonprize(v0, v1), directed(v1, v0), Rule(2519).
type error
livesin(v0, v1) :- haswonprize(v1, v0), directed(v1, v0), Rule(2520).
type error
livesin(v0, v1) :- haswonprize(v1, v0), directed(v0, v1), Rule(2521).
type error
livesin(v0, v1) :- haswonprize(v2, v1), directed(v0, v2), Rule(2522).
type error
livesin(v0, v1) :- haswonprize(v1, v2), directed(v2, v0), Rule(2523).
type error
livesin(v0, v1) :- haswonprize(v2, v0), directed(v1, v2), Rule(2524).
type error
livesin(v0, v1) :- haswonprize(v2, v0), directed(v2, v1), Rule(2525).
type error
livesin(v0, v1) :- haswonprize(v0, v2), directed(v1, v2), Rule(2526).
type error
livesin(v0, v1) :- haswonprize(v0, v2), directed(v2, v1), Rule(2527).
type error
livesin(v0, v1) :- haswonprize(v2, v1), directed(v2, v0), Rule(2528).
type error
livesin(v0, v1) :- haswonprize(v1, v2), directed(v0, v2), Rule(2529).
type error
livesin(v0, v1) :- haswonprize(v0, v1), haschild(v0, v1), Rule(2530).
type error
livesin(v0, v1) :- haswonprize(v0, v1), haschild(v1, v0), Rule(2531).
type error
livesin(v0, v1) :- haswonprize(v1, v0), haschild(v1, v0), Rule(2532).
type error
livesin(v0, v1) :- haswonprize(v1, v0), haschild(v0, v1), Rule(2533).
type error
livesin(v0, v1) :- haswonprize(v2, v1), haschild(v0, v2), Rule(2534).
type error
livesin(v0, v1) :- haswonprize(v1, v2), haschild(v2, v0), Rule(2535).
type error
livesin(v0, v1) :- haswonprize(v2, v0), haschild(v1, v2), Rule(2536).
type error
livesin(v0, v1) :- haswonprize(v2, v0), haschild(v2, v1), Rule(2537).
type error
livesin(v0, v1) :- haswonprize(v0, v2), haschild(v1, v2), Rule(2538).
type error
livesin(v0, v1) :- haswonprize(v0, v2), haschild(v2, v1), Rule(2539).
type error
livesin(v0, v1) :- haswonprize(v2, v1), haschild(v2, v0), Rule(2540).
type error
livesin(v0, v1) :- haswonprize(v1, v2), haschild(v0, v2), Rule(2541).
Head twice 
livesin(v0, v1) :- haswonprize(v0, v1), Ilivesin(v0, v1), Rule(2542).
input prevent
livesin(v0, v1) :- haswonprize(v0, v1), Ilivesin(v1, v0), Rule(2543).
input prevent
livesin(v0, v1) :- haswonprize(v1, v0), Ilivesin(v1, v0), Rule(2544).
Head twice 
livesin(v0, v1) :- haswonprize(v1, v0), Ilivesin(v0, v1), Rule(2545).
type error
livesin(v0, v1) :- haswonprize(v2, v1), Ilivesin(v0, v2), Rule(2546).
type error
livesin(v0, v1) :- haswonprize(v1, v2), Ilivesin(v2, v0), Rule(2547).
type error
livesin(v0, v1) :- haswonprize(v2, v0), Ilivesin(v1, v2), Rule(2548).
type error
livesin(v0, v1) :- haswonprize(v2, v0), Ilivesin(v2, v1), Rule(2549).
type error
livesin(v0, v1) :- haswonprize(v0, v2), Ilivesin(v1, v2), Rule(2550).
type error
livesin(v0, v1) :- haswonprize(v0, v2), Ilivesin(v2, v1), Rule(2551).
type error
livesin(v0, v1) :- haswonprize(v2, v1), Ilivesin(v2, v0), Rule(2552).
type error
livesin(v0, v1) :- haswonprize(v1, v2), Ilivesin(v0, v2), Rule(2553).
type error
livesin(v0, v1) :- haswonprize(v0, v1), inv_0(v0, v1), Rule(2554).
type error
livesin(v0, v1) :- haswonprize(v0, v1), inv_0(v1, v0), Rule(2555).
type error
livesin(v0, v1) :- haswonprize(v1, v0), inv_0(v1, v0), Rule(2556).
type error
livesin(v0, v1) :- haswonprize(v1, v0), inv_0(v0, v1), Rule(2557).
type error
livesin(v0, v1) :- haswonprize(v2, v1), inv_0(v0, v2), Rule(2558).
type error
livesin(v0, v1) :- haswonprize(v1, v2), inv_0(v2, v0), Rule(2559).
type error
livesin(v0, v1) :- haswonprize(v2, v0), inv_0(v1, v2), Rule(2560).
type error
livesin(v0, v1) :- haswonprize(v2, v0), inv_0(v2, v1), Rule(2561).
type error
livesin(v0, v1) :- haswonprize(v0, v2), inv_0(v1, v2), Rule(2562).
type error
livesin(v0, v1) :- haswonprize(v0, v2), inv_0(v2, v1), Rule(2563).
type error
livesin(v0, v1) :- haswonprize(v2, v1), inv_0(v2, v0), Rule(2564).
type error
livesin(v0, v1) :- haswonprize(v1, v2), inv_0(v0, v2), Rule(2565).
Head twice 
livesin(v0, v1) :- haswonprize(v0, v1), livesin(v0, v1), Rule(2566).
type error
livesin(v0, v1) :- haswonprize(v0, v1), livesin(v1, v0), Rule(2567).
type error
livesin(v0, v1) :- haswonprize(v1, v0), livesin(v1, v0), Rule(2568).
Head twice 
livesin(v0, v1) :- haswonprize(v1, v0), livesin(v0, v1), Rule(2569).
type error
livesin(v0, v1) :- haswonprize(v2, v1), livesin(v0, v2), Rule(2570).
type error
livesin(v0, v1) :- haswonprize(v1, v2), livesin(v2, v0), Rule(2571).
type error
livesin(v0, v1) :- haswonprize(v2, v0), livesin(v1, v2), Rule(2572).
type error
livesin(v0, v1) :- haswonprize(v2, v0), livesin(v2, v1), Rule(2573).
type error
livesin(v0, v1) :- haswonprize(v0, v2), livesin(v1, v2), Rule(2574).
type error
livesin(v0, v1) :- haswonprize(v0, v2), livesin(v2, v1), Rule(2575).
type error
livesin(v0, v1) :- haswonprize(v2, v1), livesin(v2, v0), Rule(2576).
type error
livesin(v0, v1) :- haswonprize(v1, v2), livesin(v0, v2), Rule(2577).
type error
livesin(v0, v1) :- directed(v0, v1), directed(v0, v1), Rule(2578).
type error
livesin(v0, v1) :- directed(v0, v1), directed(v1, v0), Rule(2579).
type error
livesin(v0, v1) :- directed(v1, v0), directed(v1, v0), Rule(2580).
type error
livesin(v0, v1) :- directed(v1, v0), directed(v0, v1), Rule(2581).
type error
livesin(v0, v1) :- directed(v2, v1), directed(v0, v2), Rule(2582).
type error
livesin(v0, v1) :- directed(v1, v2), directed(v2, v0), Rule(2583).
type error
livesin(v0, v1) :- directed(v2, v0), directed(v1, v2), Rule(2584).
type error
livesin(v0, v1) :- directed(v2, v0), directed(v2, v1), Rule(2585).
type error
livesin(v0, v1) :- directed(v0, v2), directed(v1, v2), Rule(2586).
type error
livesin(v0, v1) :- directed(v0, v2), directed(v2, v1), Rule(2587).
type error
livesin(v0, v1) :- directed(v2, v1), directed(v2, v0), Rule(2588).
type error
livesin(v0, v1) :- directed(v1, v2), directed(v0, v2), Rule(2589).
type error
livesin(v0, v1) :- directed(v0, v1), haschild(v0, v1), Rule(2590).
type error
livesin(v0, v1) :- directed(v0, v1), haschild(v1, v0), Rule(2591).
type error
livesin(v0, v1) :- directed(v1, v0), haschild(v1, v0), Rule(2592).
type error
livesin(v0, v1) :- directed(v1, v0), haschild(v0, v1), Rule(2593).
type error
livesin(v0, v1) :- directed(v2, v1), haschild(v0, v2), Rule(2594).
type error
livesin(v0, v1) :- directed(v1, v2), haschild(v2, v0), Rule(2595).
type error
livesin(v0, v1) :- directed(v2, v0), haschild(v1, v2), Rule(2596).
type error
livesin(v0, v1) :- directed(v2, v0), haschild(v2, v1), Rule(2597).
type error
livesin(v0, v1) :- directed(v0, v2), haschild(v1, v2), Rule(2598).
type error
livesin(v0, v1) :- directed(v0, v2), haschild(v2, v1), Rule(2599).
type error
livesin(v0, v1) :- directed(v2, v1), haschild(v2, v0), Rule(2600).
type error
livesin(v0, v1) :- directed(v1, v2), haschild(v0, v2), Rule(2601).
Head twice 
livesin(v0, v1) :- directed(v0, v1), Ilivesin(v0, v1), Rule(2602).
input prevent
livesin(v0, v1) :- directed(v0, v1), Ilivesin(v1, v0), Rule(2603).
input prevent
livesin(v0, v1) :- directed(v1, v0), Ilivesin(v1, v0), Rule(2604).
Head twice 
livesin(v0, v1) :- directed(v1, v0), Ilivesin(v0, v1), Rule(2605).
type error
livesin(v0, v1) :- directed(v2, v1), Ilivesin(v0, v2), Rule(2606).
type error
livesin(v0, v1) :- directed(v1, v2), Ilivesin(v2, v0), Rule(2607).
type error
livesin(v0, v1) :- directed(v2, v0), Ilivesin(v1, v2), Rule(2608).
type error
livesin(v0, v1) :- directed(v2, v0), Ilivesin(v2, v1), Rule(2609).
type error
livesin(v0, v1) :- directed(v0, v2), Ilivesin(v1, v2), Rule(2610).
type error
livesin(v0, v1) :- directed(v0, v2), Ilivesin(v2, v1), Rule(2611).
type error
livesin(v0, v1) :- directed(v2, v1), Ilivesin(v2, v0), Rule(2612).
type error
livesin(v0, v1) :- directed(v1, v2), Ilivesin(v0, v2), Rule(2613).
type error
livesin(v0, v1) :- directed(v0, v1), inv_0(v0, v1), Rule(2614).
type error
livesin(v0, v1) :- directed(v0, v1), inv_0(v1, v0), Rule(2615).
type error
livesin(v0, v1) :- directed(v1, v0), inv_0(v1, v0), Rule(2616).
type error
livesin(v0, v1) :- directed(v1, v0), inv_0(v0, v1), Rule(2617).
type error
livesin(v0, v1) :- directed(v2, v1), inv_0(v0, v2), Rule(2618).
type error
livesin(v0, v1) :- directed(v1, v2), inv_0(v2, v0), Rule(2619).
type error
livesin(v0, v1) :- directed(v2, v0), inv_0(v1, v2), Rule(2620).
type error
livesin(v0, v1) :- directed(v2, v0), inv_0(v2, v1), Rule(2621).
type error
livesin(v0, v1) :- directed(v2, v1), inv_0(v2, v0), Rule(2624).
type error
livesin(v0, v1) :- directed(v1, v2), inv_0(v0, v2), Rule(2625).
Head twice 
livesin(v0, v1) :- directed(v0, v1), livesin(v0, v1), Rule(2626).
type error
livesin(v0, v1) :- directed(v0, v1), livesin(v1, v0), Rule(2627).
type error
livesin(v0, v1) :- directed(v1, v0), livesin(v1, v0), Rule(2628).
Head twice 
livesin(v0, v1) :- directed(v1, v0), livesin(v0, v1), Rule(2629).
type error
livesin(v0, v1) :- directed(v2, v1), livesin(v0, v2), Rule(2630).
type error
livesin(v0, v1) :- directed(v1, v2), livesin(v2, v0), Rule(2631).
type error
livesin(v0, v1) :- directed(v2, v0), livesin(v1, v2), Rule(2632).
type error
livesin(v0, v1) :- directed(v2, v0), livesin(v2, v1), Rule(2633).
type error
livesin(v0, v1) :- directed(v0, v2), livesin(v1, v2), Rule(2634).
type error
livesin(v0, v1) :- directed(v0, v2), livesin(v2, v1), Rule(2635).
type error
livesin(v0, v1) :- directed(v2, v1), livesin(v2, v0), Rule(2636).
type error
livesin(v0, v1) :- directed(v1, v2), livesin(v0, v2), Rule(2637).
type error
livesin(v0, v1) :- haschild(v0, v1), haschild(v0, v1), Rule(2638).
type error
livesin(v0, v1) :- haschild(v0, v1), haschild(v1, v0), Rule(2639).
type error
livesin(v0, v1) :- haschild(v1, v0), haschild(v1, v0), Rule(2640).
type error
livesin(v0, v1) :- haschild(v1, v0), haschild(v0, v1), Rule(2641).
type error
livesin(v0, v1) :- haschild(v2, v1), haschild(v0, v2), Rule(2642).
type error
livesin(v0, v1) :- haschild(v1, v2), haschild(v2, v0), Rule(2643).
type error
livesin(v0, v1) :- haschild(v2, v0), haschild(v1, v2), Rule(2644).
type error
livesin(v0, v1) :- haschild(v2, v0), haschild(v2, v1), Rule(2645).
type error
livesin(v0, v1) :- haschild(v0, v2), haschild(v1, v2), Rule(2646).
type error
livesin(v0, v1) :- haschild(v0, v2), haschild(v2, v1), Rule(2647).
type error
livesin(v0, v1) :- haschild(v2, v1), haschild(v2, v0), Rule(2648).
type error
livesin(v0, v1) :- haschild(v1, v2), haschild(v0, v2), Rule(2649).
Head twice 
livesin(v0, v1) :- haschild(v0, v1), Ilivesin(v0, v1), Rule(2650).
input prevent
livesin(v0, v1) :- haschild(v0, v1), Ilivesin(v1, v0), Rule(2651).
input prevent
livesin(v0, v1) :- haschild(v1, v0), Ilivesin(v1, v0), Rule(2652).
Head twice 
livesin(v0, v1) :- haschild(v1, v0), Ilivesin(v0, v1), Rule(2653).
type error
livesin(v0, v1) :- haschild(v2, v1), Ilivesin(v0, v2), Rule(2654).
type error
livesin(v0, v1) :- haschild(v1, v2), Ilivesin(v2, v0), Rule(2655).
type error
livesin(v0, v1) :- haschild(v2, v0), Ilivesin(v1, v2), Rule(2656).
type error
livesin(v0, v1) :- haschild(v0, v2), Ilivesin(v1, v2), Rule(2658).
type error
livesin(v0, v1) :- haschild(v2, v1), Ilivesin(v2, v0), Rule(2660).
type error
livesin(v0, v1) :- haschild(v1, v2), Ilivesin(v0, v2), Rule(2661).
type error
livesin(v0, v1) :- haschild(v0, v1), inv_0(v0, v1), Rule(2662).
type error
livesin(v0, v1) :- haschild(v0, v1), inv_0(v1, v0), Rule(2663).
type error
livesin(v0, v1) :- haschild(v1, v0), inv_0(v1, v0), Rule(2664).
type error
livesin(v0, v1) :- haschild(v1, v0), inv_0(v0, v1), Rule(2665).
type error
livesin(v0, v1) :- haschild(v2, v1), inv_0(v0, v2), Rule(2666).
type error
livesin(v0, v1) :- haschild(v1, v2), inv_0(v2, v0), Rule(2667).
type error
livesin(v0, v1) :- haschild(v2, v1), inv_0(v2, v0), Rule(2672).
type error
livesin(v0, v1) :- haschild(v1, v2), inv_0(v0, v2), Rule(2673).
Head twice 
livesin(v0, v1) :- haschild(v0, v1), livesin(v0, v1), Rule(2674).
type error
livesin(v0, v1) :- haschild(v0, v1), livesin(v1, v0), Rule(2675).
type error
livesin(v0, v1) :- haschild(v1, v0), livesin(v1, v0), Rule(2676).
Head twice 
livesin(v0, v1) :- haschild(v1, v0), livesin(v0, v1), Rule(2677).
type error
livesin(v0, v1) :- haschild(v2, v1), livesin(v0, v2), Rule(2678).
type error
livesin(v0, v1) :- haschild(v1, v2), livesin(v2, v0), Rule(2679).
type error
livesin(v0, v1) :- haschild(v2, v0), livesin(v1, v2), Rule(2680).
type error
livesin(v0, v1) :- haschild(v0, v2), livesin(v1, v2), Rule(2682).
type error
livesin(v0, v1) :- haschild(v2, v1), livesin(v2, v0), Rule(2684).
type error
livesin(v0, v1) :- haschild(v1, v2), livesin(v0, v2), Rule(2685).
Head twice 
livesin(v0, v1) :- Ilivesin(v0, v1), Ilivesin(v0, v1), Rule(2686).
Head twice 
livesin(v0, v1) :- Ilivesin(v0, v1), Ilivesin(v1, v0), Rule(2687).
input prevent
livesin(v0, v1) :- Ilivesin(v1, v0), Ilivesin(v1, v0), Rule(2688).
Head twice 
livesin(v0, v1) :- Ilivesin(v1, v0), Ilivesin(v0, v1), Rule(2689).
type error
livesin(v0, v1) :- Ilivesin(v2, v1), Ilivesin(v0, v2), Rule(2690).
type error
livesin(v0, v1) :- Ilivesin(v1, v2), Ilivesin(v2, v0), Rule(2691).
type error
livesin(v0, v1) :- Ilivesin(v2, v0), Ilivesin(v1, v2), Rule(2692).
type error
livesin(v0, v1) :- Ilivesin(v2, v0), Ilivesin(v2, v1), Rule(2693).
type error
livesin(v0, v1) :- Ilivesin(v0, v2), Ilivesin(v1, v2), Rule(2694).
type error
livesin(v0, v1) :- Ilivesin(v0, v2), Ilivesin(v2, v1), Rule(2695).
type error
livesin(v0, v1) :- Ilivesin(v2, v1), Ilivesin(v2, v0), Rule(2696).
type error
livesin(v0, v1) :- Ilivesin(v1, v2), Ilivesin(v0, v2), Rule(2697).
Head twice 
livesin(v0, v1) :- Ilivesin(v0, v1), inv_0(v0, v1), Rule(2698).
Head twice 
livesin(v0, v1) :- Ilivesin(v0, v1), inv_0(v1, v0), Rule(2699).
input prevent
livesin(v0, v1) :- Ilivesin(v1, v0), inv_0(v1, v0), Rule(2700).
input prevent
livesin(v0, v1) :- Ilivesin(v1, v0), inv_0(v0, v1), Rule(2701).
type error
livesin(v0, v1) :- Ilivesin(v1, v2), inv_0(v2, v0), Rule(2703).
type error
livesin(v0, v1) :- Ilivesin(v2, v0), inv_0(v1, v2), Rule(2704).
type error
livesin(v0, v1) :- Ilivesin(v2, v0), inv_0(v2, v1), Rule(2705).
type error
livesin(v0, v1) :- Ilivesin(v1, v2), inv_0(v0, v2), Rule(2709).
Head twice 
livesin(v0, v1) :- Ilivesin(v0, v1), livesin(v0, v1), Rule(2710).
Head twice 
livesin(v0, v1) :- Ilivesin(v0, v1), livesin(v1, v0), Rule(2711).
input prevent
livesin(v0, v1) :- Ilivesin(v1, v0), livesin(v1, v0), Rule(2712).
Head twice 
livesin(v0, v1) :- Ilivesin(v1, v0), livesin(v0, v1), Rule(2713).
type error
livesin(v0, v1) :- Ilivesin(v2, v1), livesin(v0, v2), Rule(2714).
type error
livesin(v0, v1) :- Ilivesin(v1, v2), livesin(v2, v0), Rule(2715).
type error
livesin(v0, v1) :- Ilivesin(v2, v0), livesin(v1, v2), Rule(2716).
type error
livesin(v0, v1) :- Ilivesin(v2, v0), livesin(v2, v1), Rule(2717).
type error
livesin(v0, v1) :- Ilivesin(v0, v2), livesin(v1, v2), Rule(2718).
type error
livesin(v0, v1) :- Ilivesin(v0, v2), livesin(v2, v1), Rule(2719).
type error
livesin(v0, v1) :- Ilivesin(v2, v1), livesin(v2, v0), Rule(2720).
type error
livesin(v0, v1) :- Ilivesin(v1, v2), livesin(v0, v2), Rule(2721).
Head twice 
livesin(v0, v1) :- inv_0(v0, v1), livesin(v0, v1), Rule(2734).
type error
livesin(v0, v1) :- inv_0(v0, v1), livesin(v1, v0), Rule(2735).
type error
livesin(v0, v1) :- inv_0(v1, v0), livesin(v1, v0), Rule(2736).
Head twice 
livesin(v0, v1) :- inv_0(v1, v0), livesin(v0, v1), Rule(2737).
type error
livesin(v0, v1) :- inv_0(v1, v2), livesin(v2, v0), Rule(2739).
type error
livesin(v0, v1) :- inv_0(v2, v0), livesin(v1, v2), Rule(2740).
type error
livesin(v0, v1) :- inv_0(v0, v2), livesin(v1, v2), Rule(2742).
type error
livesin(v0, v1) :- inv_0(v2, v1), livesin(v2, v0), Rule(2744).
Head twice 
livesin(v0, v1) :- livesin(v0, v1), livesin(v0, v1), Rule(2746).
Head twice 
livesin(v0, v1) :- livesin(v0, v1), livesin(v1, v0), Rule(2747).
type error
livesin(v0, v1) :- livesin(v1, v0), livesin(v1, v0), Rule(2748).
Head twice 
livesin(v0, v1) :- livesin(v1, v0), livesin(v0, v1), Rule(2749).
type error
livesin(v0, v1) :- livesin(v2, v1), livesin(v0, v2), Rule(2750).
type error
livesin(v0, v1) :- livesin(v1, v2), livesin(v2, v0), Rule(2751).
type error
livesin(v0, v1) :- livesin(v2, v0), livesin(v1, v2), Rule(2752).
type error
livesin(v0, v1) :- livesin(v2, v0), livesin(v2, v1), Rule(2753).
type error
livesin(v0, v1) :- livesin(v0, v2), livesin(v1, v2), Rule(2754).
type error
livesin(v0, v1) :- livesin(v0, v2), livesin(v2, v1), Rule(2755).
type error
livesin(v0, v1) :- livesin(v2, v1), livesin(v2, v0), Rule(2756).
type error
livesin(v0, v1) :- livesin(v1, v2), livesin(v0, v2), Rule(2757).
