.type V

.decl Rule(n: number)
.input Rule

.decl Rule(v0: V, v1: V)
.input Rule

.decl livesin(v0: V, v1: V)
.input livesin

.decl wasbornin(v0: V, v1: V)
.input wasbornin

.decl IIlivesin(v0: V, v1: V)
.input IIlivesin

.decl inv_0(v0: V, v1: V)
.decl Ilivesin(v0: V, v1: V)
.decl Rule_exists(v0: V, v1: V, r: number)
.output Rule_exists

.decl livesin_exists(v0: V, v1: V, r: number)
.output livesin_exists

.decl wasbornin_exists(v0: V, v1: V, r: number)
.output wasbornin_exists

.decl IIlivesin_exists(v0: V, v1: V, r: number)
.output IIlivesin_exists

.decl inv_0_exists(v0: V, v1: V, r: number)
.output inv_0_exists

.decl Ilivesin_exists(v0: V, v1: V, r: number)
.output Ilivesin_exists



inv_0(v0, v1) :- Rule(v0, v1), Rule(0).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), r = 0, Rule(0).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Rule(r), Rule(0).
inv_0(v0, v1) :- Rule(v1, v0), Rule(1).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), r = 1, Rule(1).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Rule(r), Rule(1).
inv_0(v0, v1) :- livesin(v0, v1), Rule(2).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), r = 2, Rule(2).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), Rule(r), Rule(2).
inv_0(v0, v1) :- livesin(v1, v0), Rule(3).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), r = 3, Rule(3).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), Rule(r), Rule(3).
inv_0(v0, v1) :- wasbornin(v0, v1), Rule(4).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), r = 4, Rule(4).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), Rule(r), Rule(4).
inv_0(v0, v1) :- wasbornin(v1, v0), Rule(5).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), r = 5, Rule(5).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), Rule(r), Rule(5).
inv_0(v0, v1) :- IIlivesin(v0, v1), Rule(6).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), r = 6, Rule(6).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), Rule(r), Rule(6).
inv_0(v0, v1) :- IIlivesin(v1, v0), Rule(7).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), r = 7, Rule(7).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), Rule(r), Rule(7).
inv_0(v0, v1) :- inv_0(v0, v1), Rule(8).
inv_0_exists(v0, v1, r) :- inv_0(v0, v1), r = 8, Rule(8).
inv_0_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), Rule(r), Rule(8).
inv_0(v0, v1) :- inv_0(v1, v0), Rule(9).
inv_0_exists(v0, v1, r) :- inv_0(v1, v0), r = 9, Rule(9).
inv_0_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), Rule(r), Rule(9).
inv_0(v0, v1) :- Rule(v0, v1), Rule(v0, v1), Rule(10).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), Rule(v0, v1), r = 10, Rule(10).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Rule(v0, v1), Rule(r), Rule(10).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), Rule_exists(v0, v1, r), Rule(r), Rule(10).
inv_0(v0, v1) :- Rule(v0, v1), Rule(v1, v0), Rule(11).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), Rule(v1, v0), r = 11, Rule(11).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Rule(v1, v0), Rule(r), Rule(11).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), Rule_exists(v1, v0, r), Rule(r), Rule(11).
inv_0(v0, v1) :- Rule(v1, v0), Rule(v1, v0), Rule(12).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), Rule(v1, v0), r = 12, Rule(12).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Rule(v1, v0), Rule(r), Rule(12).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), Rule_exists(v1, v0, r), Rule(r), Rule(12).
inv_0(v0, v1) :- Rule(v1, v0), Rule(v0, v1), Rule(13).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), Rule(v0, v1), r = 13, Rule(13).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Rule(v0, v1), Rule(r), Rule(13).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), Rule_exists(v0, v1, r), Rule(r), Rule(13).
inv_0(v0, v1) :- Rule(v2, v1), Rule(v0, v2), Rule(14).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), Rule(v0, v2), r = 14, Rule(14).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), Rule(v0, v2), Rule(r), Rule(14).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), Rule_exists(v0, v2, r), Rule(r), Rule(14).
inv_0(v0, v1) :- Rule(v1, v2), Rule(v2, v0), Rule(15).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), Rule(v2, v0), r = 15, Rule(15).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), Rule(v2, v0), Rule(r), Rule(15).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), Rule_exists(v2, v0, r), Rule(r), Rule(15).
inv_0(v0, v1) :- Rule(v2, v0), Rule(v1, v2), Rule(16).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), Rule(v1, v2), r = 16, Rule(16).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), Rule(v1, v2), Rule(r), Rule(16).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), Rule_exists(v1, v2, r), Rule(r), Rule(16).
inv_0(v0, v1) :- Rule(v2, v0), Rule(v2, v1), Rule(17).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), Rule(v2, v1), r = 17, Rule(17).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), Rule(v2, v1), Rule(r), Rule(17).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), Rule_exists(v2, v1, r), Rule(r), Rule(17).
inv_0(v0, v1) :- Rule(v0, v2), Rule(v1, v2), Rule(18).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), Rule(v1, v2), r = 18, Rule(18).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), Rule(v1, v2), Rule(r), Rule(18).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), Rule_exists(v1, v2, r), Rule(r), Rule(18).
inv_0(v0, v1) :- Rule(v0, v2), Rule(v2, v1), Rule(19).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), Rule(v2, v1), r = 19, Rule(19).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), Rule(v2, v1), Rule(r), Rule(19).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), Rule_exists(v2, v1, r), Rule(r), Rule(19).
inv_0(v0, v1) :- Rule(v2, v1), Rule(v2, v0), Rule(20).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), Rule(v2, v0), r = 20, Rule(20).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), Rule(v2, v0), Rule(r), Rule(20).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), Rule_exists(v2, v0, r), Rule(r), Rule(20).
inv_0(v0, v1) :- Rule(v1, v2), Rule(v0, v2), Rule(21).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), Rule(v0, v2), r = 21, Rule(21).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), Rule(v0, v2), Rule(r), Rule(21).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), Rule_exists(v0, v2, r), Rule(r), Rule(21).
inv_0(v0, v1) :- Rule(v0, v1), livesin(v0, v1), Rule(22).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), livesin(v0, v1), r = 22, Rule(22).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), livesin(v0, v1), Rule(r), Rule(22).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), livesin_exists(v0, v1, r), Rule(r), Rule(22).
inv_0(v0, v1) :- Rule(v0, v1), livesin(v1, v0), Rule(23).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), livesin(v1, v0), r = 23, Rule(23).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), livesin(v1, v0), Rule(r), Rule(23).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), livesin_exists(v1, v0, r), Rule(r), Rule(23).
inv_0(v0, v1) :- Rule(v1, v0), livesin(v1, v0), Rule(24).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), livesin(v1, v0), r = 24, Rule(24).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), livesin(v1, v0), Rule(r), Rule(24).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), livesin_exists(v1, v0, r), Rule(r), Rule(24).
inv_0(v0, v1) :- Rule(v1, v0), livesin(v0, v1), Rule(25).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), livesin(v0, v1), r = 25, Rule(25).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), livesin(v0, v1), Rule(r), Rule(25).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), livesin_exists(v0, v1, r), Rule(r), Rule(25).
inv_0(v0, v1) :- Rule(v2, v1), livesin(v0, v2), Rule(26).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), livesin(v0, v2), r = 26, Rule(26).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), livesin(v0, v2), Rule(r), Rule(26).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), livesin_exists(v0, v2, r), Rule(r), Rule(26).
inv_0(v0, v1) :- Rule(v1, v2), livesin(v2, v0), Rule(27).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), livesin(v2, v0), r = 27, Rule(27).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), livesin(v2, v0), Rule(r), Rule(27).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), livesin_exists(v2, v0, r), Rule(r), Rule(27).
inv_0(v0, v1) :- Rule(v2, v0), livesin(v1, v2), Rule(28).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), livesin(v1, v2), r = 28, Rule(28).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), livesin(v1, v2), Rule(r), Rule(28).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), livesin_exists(v1, v2, r), Rule(r), Rule(28).
inv_0(v0, v1) :- Rule(v2, v0), livesin(v2, v1), Rule(29).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), livesin(v2, v1), r = 29, Rule(29).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), livesin(v2, v1), Rule(r), Rule(29).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), livesin_exists(v2, v1, r), Rule(r), Rule(29).
inv_0(v0, v1) :- Rule(v0, v2), livesin(v1, v2), Rule(30).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), livesin(v1, v2), r = 30, Rule(30).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), livesin(v1, v2), Rule(r), Rule(30).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), livesin_exists(v1, v2, r), Rule(r), Rule(30).
inv_0(v0, v1) :- Rule(v0, v2), livesin(v2, v1), Rule(31).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), livesin(v2, v1), r = 31, Rule(31).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), livesin(v2, v1), Rule(r), Rule(31).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), livesin_exists(v2, v1, r), Rule(r), Rule(31).
inv_0(v0, v1) :- Rule(v2, v1), livesin(v2, v0), Rule(32).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), livesin(v2, v0), r = 32, Rule(32).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), livesin(v2, v0), Rule(r), Rule(32).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), livesin_exists(v2, v0, r), Rule(r), Rule(32).
inv_0(v0, v1) :- Rule(v1, v2), livesin(v0, v2), Rule(33).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), livesin(v0, v2), r = 33, Rule(33).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), livesin(v0, v2), Rule(r), Rule(33).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), livesin_exists(v0, v2, r), Rule(r), Rule(33).
inv_0(v0, v1) :- Rule(v0, v1), wasbornin(v0, v1), Rule(34).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), wasbornin(v0, v1), r = 34, Rule(34).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), wasbornin(v0, v1), Rule(r), Rule(34).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), wasbornin_exists(v0, v1, r), Rule(r), Rule(34).
inv_0(v0, v1) :- Rule(v0, v1), wasbornin(v1, v0), Rule(35).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), wasbornin(v1, v0), r = 35, Rule(35).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), wasbornin(v1, v0), Rule(r), Rule(35).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), wasbornin_exists(v1, v0, r), Rule(r), Rule(35).
inv_0(v0, v1) :- Rule(v1, v0), wasbornin(v1, v0), Rule(36).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), wasbornin(v1, v0), r = 36, Rule(36).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), wasbornin(v1, v0), Rule(r), Rule(36).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), wasbornin_exists(v1, v0, r), Rule(r), Rule(36).
inv_0(v0, v1) :- Rule(v1, v0), wasbornin(v0, v1), Rule(37).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), wasbornin(v0, v1), r = 37, Rule(37).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), wasbornin(v0, v1), Rule(r), Rule(37).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), wasbornin_exists(v0, v1, r), Rule(r), Rule(37).
inv_0(v0, v1) :- Rule(v2, v1), wasbornin(v0, v2), Rule(38).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), wasbornin(v0, v2), r = 38, Rule(38).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), wasbornin(v0, v2), Rule(r), Rule(38).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), wasbornin_exists(v0, v2, r), Rule(r), Rule(38).
inv_0(v0, v1) :- Rule(v1, v2), wasbornin(v2, v0), Rule(39).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), wasbornin(v2, v0), r = 39, Rule(39).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), wasbornin(v2, v0), Rule(r), Rule(39).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), wasbornin_exists(v2, v0, r), Rule(r), Rule(39).
inv_0(v0, v1) :- Rule(v2, v0), wasbornin(v1, v2), Rule(40).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), wasbornin(v1, v2), r = 40, Rule(40).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), wasbornin(v1, v2), Rule(r), Rule(40).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), wasbornin_exists(v1, v2, r), Rule(r), Rule(40).
inv_0(v0, v1) :- Rule(v2, v0), wasbornin(v2, v1), Rule(41).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), wasbornin(v2, v1), r = 41, Rule(41).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), wasbornin(v2, v1), Rule(r), Rule(41).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), wasbornin_exists(v2, v1, r), Rule(r), Rule(41).
inv_0(v0, v1) :- Rule(v0, v2), wasbornin(v1, v2), Rule(42).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), wasbornin(v1, v2), r = 42, Rule(42).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), wasbornin(v1, v2), Rule(r), Rule(42).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), wasbornin_exists(v1, v2, r), Rule(r), Rule(42).
inv_0(v0, v1) :- Rule(v0, v2), wasbornin(v2, v1), Rule(43).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), wasbornin(v2, v1), r = 43, Rule(43).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), wasbornin(v2, v1), Rule(r), Rule(43).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), wasbornin_exists(v2, v1, r), Rule(r), Rule(43).
inv_0(v0, v1) :- Rule(v2, v1), wasbornin(v2, v0), Rule(44).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), wasbornin(v2, v0), r = 44, Rule(44).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), wasbornin(v2, v0), Rule(r), Rule(44).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), wasbornin_exists(v2, v0, r), Rule(r), Rule(44).
inv_0(v0, v1) :- Rule(v1, v2), wasbornin(v0, v2), Rule(45).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), wasbornin(v0, v2), r = 45, Rule(45).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), wasbornin(v0, v2), Rule(r), Rule(45).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), wasbornin_exists(v0, v2, r), Rule(r), Rule(45).
inv_0(v0, v1) :- Rule(v0, v1), IIlivesin(v0, v1), Rule(46).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin(v0, v1), r = 46, Rule(46).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(46).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(46).
inv_0(v0, v1) :- Rule(v0, v1), IIlivesin(v1, v0), Rule(47).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin(v1, v0), r = 47, Rule(47).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(47).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(47).
inv_0(v0, v1) :- Rule(v1, v0), IIlivesin(v1, v0), Rule(48).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin(v1, v0), r = 48, Rule(48).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(48).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(48).
inv_0(v0, v1) :- Rule(v1, v0), IIlivesin(v0, v1), Rule(49).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin(v0, v1), r = 49, Rule(49).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(49).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(49).
inv_0(v0, v1) :- Rule(v2, v1), IIlivesin(v0, v2), Rule(50).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin(v0, v2), r = 50, Rule(50).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(50).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(50).
inv_0(v0, v1) :- Rule(v1, v2), IIlivesin(v2, v0), Rule(51).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin(v2, v0), r = 51, Rule(51).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(51).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(51).
inv_0(v0, v1) :- Rule(v2, v0), IIlivesin(v1, v2), Rule(52).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin(v1, v2), r = 52, Rule(52).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(52).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(52).
inv_0(v0, v1) :- Rule(v2, v0), IIlivesin(v2, v1), Rule(53).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin(v2, v1), r = 53, Rule(53).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(53).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(53).
inv_0(v0, v1) :- Rule(v0, v2), IIlivesin(v1, v2), Rule(54).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin(v1, v2), r = 54, Rule(54).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(54).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(54).
inv_0(v0, v1) :- Rule(v0, v2), IIlivesin(v2, v1), Rule(55).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin(v2, v1), r = 55, Rule(55).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(55).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(55).
inv_0(v0, v1) :- Rule(v2, v1), IIlivesin(v2, v0), Rule(56).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin(v2, v0), r = 56, Rule(56).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(56).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(56).
inv_0(v0, v1) :- Rule(v1, v2), IIlivesin(v0, v2), Rule(57).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin(v0, v2), r = 57, Rule(57).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(57).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(57).
inv_0(v0, v1) :- Rule(v0, v1), inv_0(v0, v1), Rule(58).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), inv_0(v0, v1), r = 58, Rule(58).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(58).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(58).
inv_0(v0, v1) :- Rule(v0, v1), inv_0(v1, v0), Rule(59).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), inv_0(v1, v0), r = 59, Rule(59).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(59).
inv_0_exists(v0, v1, r) :- Rule(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(59).
inv_0(v0, v1) :- Rule(v1, v0), inv_0(v1, v0), Rule(60).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), inv_0(v1, v0), r = 60, Rule(60).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(60).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(60).
inv_0(v0, v1) :- Rule(v1, v0), inv_0(v0, v1), Rule(61).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), inv_0(v0, v1), r = 61, Rule(61).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(61).
inv_0_exists(v0, v1, r) :- Rule(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(61).
inv_0(v0, v1) :- Rule(v2, v1), inv_0(v0, v2), Rule(62).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), inv_0(v0, v2), r = 62, Rule(62).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(62).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(62).
inv_0(v0, v1) :- Rule(v1, v2), inv_0(v2, v0), Rule(63).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), inv_0(v2, v0), r = 63, Rule(63).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(63).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(63).
inv_0(v0, v1) :- Rule(v2, v0), inv_0(v1, v2), Rule(64).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), inv_0(v1, v2), r = 64, Rule(64).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(64).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(64).
inv_0(v0, v1) :- Rule(v2, v0), inv_0(v2, v1), Rule(65).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), inv_0(v2, v1), r = 65, Rule(65).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(65).
inv_0_exists(v0, v1, r) :- Rule(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(65).
inv_0(v0, v1) :- Rule(v0, v2), inv_0(v1, v2), Rule(66).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), inv_0(v1, v2), r = 66, Rule(66).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(66).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(66).
inv_0(v0, v1) :- Rule(v0, v2), inv_0(v2, v1), Rule(67).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), inv_0(v2, v1), r = 67, Rule(67).
inv_0_exists(v0, v1, r) :- Rule_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(67).
inv_0_exists(v0, v1, r) :- Rule(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(67).
inv_0(v0, v1) :- Rule(v2, v1), inv_0(v2, v0), Rule(68).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), inv_0(v2, v0), r = 68, Rule(68).
inv_0_exists(v0, v1, r) :- Rule_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(68).
inv_0_exists(v0, v1, r) :- Rule(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(68).
inv_0(v0, v1) :- Rule(v1, v2), inv_0(v0, v2), Rule(69).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), inv_0(v0, v2), r = 69, Rule(69).
inv_0_exists(v0, v1, r) :- Rule_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(69).
inv_0_exists(v0, v1, r) :- Rule(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(69).
inv_0(v0, v1) :- livesin(v0, v1), livesin(v0, v1), Rule(70).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), livesin(v0, v1), r = 70, Rule(70).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), livesin(v0, v1), Rule(r), Rule(70).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), livesin_exists(v0, v1, r), Rule(r), Rule(70).
inv_0(v0, v1) :- livesin(v0, v1), livesin(v1, v0), Rule(71).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), livesin(v1, v0), r = 71, Rule(71).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), livesin(v1, v0), Rule(r), Rule(71).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), livesin_exists(v1, v0, r), Rule(r), Rule(71).
inv_0(v0, v1) :- livesin(v1, v0), livesin(v1, v0), Rule(72).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), livesin(v1, v0), r = 72, Rule(72).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), livesin(v1, v0), Rule(r), Rule(72).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), livesin_exists(v1, v0, r), Rule(r), Rule(72).
inv_0(v0, v1) :- livesin(v1, v0), livesin(v0, v1), Rule(73).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), livesin(v0, v1), r = 73, Rule(73).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), livesin(v0, v1), Rule(r), Rule(73).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), livesin_exists(v0, v1, r), Rule(r), Rule(73).
inv_0(v0, v1) :- livesin(v2, v1), livesin(v0, v2), Rule(74).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), livesin(v0, v2), r = 74, Rule(74).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), livesin(v0, v2), Rule(r), Rule(74).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), livesin_exists(v0, v2, r), Rule(r), Rule(74).
inv_0(v0, v1) :- livesin(v1, v2), livesin(v2, v0), Rule(75).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), livesin(v2, v0), r = 75, Rule(75).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), livesin(v2, v0), Rule(r), Rule(75).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), livesin_exists(v2, v0, r), Rule(r), Rule(75).
inv_0(v0, v1) :- livesin(v2, v0), livesin(v1, v2), Rule(76).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), livesin(v1, v2), r = 76, Rule(76).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), livesin(v1, v2), Rule(r), Rule(76).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), livesin_exists(v1, v2, r), Rule(r), Rule(76).
inv_0(v0, v1) :- livesin(v2, v0), livesin(v2, v1), Rule(77).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), livesin(v2, v1), r = 77, Rule(77).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), livesin(v2, v1), Rule(r), Rule(77).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), livesin_exists(v2, v1, r), Rule(r), Rule(77).
inv_0(v0, v1) :- livesin(v0, v2), livesin(v1, v2), Rule(78).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), livesin(v1, v2), r = 78, Rule(78).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), livesin(v1, v2), Rule(r), Rule(78).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), livesin_exists(v1, v2, r), Rule(r), Rule(78).
inv_0(v0, v1) :- livesin(v0, v2), livesin(v2, v1), Rule(79).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), livesin(v2, v1), r = 79, Rule(79).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), livesin(v2, v1), Rule(r), Rule(79).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), livesin_exists(v2, v1, r), Rule(r), Rule(79).
inv_0(v0, v1) :- livesin(v2, v1), livesin(v2, v0), Rule(80).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), livesin(v2, v0), r = 80, Rule(80).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), livesin(v2, v0), Rule(r), Rule(80).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), livesin_exists(v2, v0, r), Rule(r), Rule(80).
inv_0(v0, v1) :- livesin(v1, v2), livesin(v0, v2), Rule(81).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), livesin(v0, v2), r = 81, Rule(81).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), livesin(v0, v2), Rule(r), Rule(81).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), livesin_exists(v0, v2, r), Rule(r), Rule(81).
inv_0(v0, v1) :- livesin(v0, v1), wasbornin(v0, v1), Rule(82).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), wasbornin(v0, v1), r = 82, Rule(82).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), wasbornin(v0, v1), Rule(r), Rule(82).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), wasbornin_exists(v0, v1, r), Rule(r), Rule(82).
inv_0(v0, v1) :- livesin(v0, v1), wasbornin(v1, v0), Rule(83).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), wasbornin(v1, v0), r = 83, Rule(83).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), wasbornin(v1, v0), Rule(r), Rule(83).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), wasbornin_exists(v1, v0, r), Rule(r), Rule(83).
inv_0(v0, v1) :- livesin(v1, v0), wasbornin(v1, v0), Rule(84).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), wasbornin(v1, v0), r = 84, Rule(84).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), wasbornin(v1, v0), Rule(r), Rule(84).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), wasbornin_exists(v1, v0, r), Rule(r), Rule(84).
inv_0(v0, v1) :- livesin(v1, v0), wasbornin(v0, v1), Rule(85).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), wasbornin(v0, v1), r = 85, Rule(85).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), wasbornin(v0, v1), Rule(r), Rule(85).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), wasbornin_exists(v0, v1, r), Rule(r), Rule(85).
inv_0(v0, v1) :- livesin(v2, v1), wasbornin(v0, v2), Rule(86).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), wasbornin(v0, v2), r = 86, Rule(86).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), wasbornin(v0, v2), Rule(r), Rule(86).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), wasbornin_exists(v0, v2, r), Rule(r), Rule(86).
inv_0(v0, v1) :- livesin(v1, v2), wasbornin(v2, v0), Rule(87).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), wasbornin(v2, v0), r = 87, Rule(87).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), wasbornin(v2, v0), Rule(r), Rule(87).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), wasbornin_exists(v2, v0, r), Rule(r), Rule(87).
inv_0(v0, v1) :- livesin(v2, v0), wasbornin(v1, v2), Rule(88).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), wasbornin(v1, v2), r = 88, Rule(88).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), wasbornin(v1, v2), Rule(r), Rule(88).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), wasbornin_exists(v1, v2, r), Rule(r), Rule(88).
inv_0(v0, v1) :- livesin(v2, v0), wasbornin(v2, v1), Rule(89).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), wasbornin(v2, v1), r = 89, Rule(89).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), wasbornin(v2, v1), Rule(r), Rule(89).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), wasbornin_exists(v2, v1, r), Rule(r), Rule(89).
inv_0(v0, v1) :- livesin(v0, v2), wasbornin(v1, v2), Rule(90).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), wasbornin(v1, v2), r = 90, Rule(90).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), wasbornin(v1, v2), Rule(r), Rule(90).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), wasbornin_exists(v1, v2, r), Rule(r), Rule(90).
inv_0(v0, v1) :- livesin(v0, v2), wasbornin(v2, v1), Rule(91).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), wasbornin(v2, v1), r = 91, Rule(91).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), wasbornin(v2, v1), Rule(r), Rule(91).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), wasbornin_exists(v2, v1, r), Rule(r), Rule(91).
inv_0(v0, v1) :- livesin(v2, v1), wasbornin(v2, v0), Rule(92).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), wasbornin(v2, v0), r = 92, Rule(92).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), wasbornin(v2, v0), Rule(r), Rule(92).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), wasbornin_exists(v2, v0, r), Rule(r), Rule(92).
inv_0(v0, v1) :- livesin(v1, v2), wasbornin(v0, v2), Rule(93).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), wasbornin(v0, v2), r = 93, Rule(93).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), wasbornin(v0, v2), Rule(r), Rule(93).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), wasbornin_exists(v0, v2, r), Rule(r), Rule(93).
inv_0(v0, v1) :- livesin(v0, v1), IIlivesin(v0, v1), Rule(94).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin(v0, v1), r = 94, Rule(94).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(94).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(94).
inv_0(v0, v1) :- livesin(v0, v1), IIlivesin(v1, v0), Rule(95).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin(v1, v0), r = 95, Rule(95).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(95).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(95).
inv_0(v0, v1) :- livesin(v1, v0), IIlivesin(v1, v0), Rule(96).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin(v1, v0), r = 96, Rule(96).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(96).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(96).
inv_0(v0, v1) :- livesin(v1, v0), IIlivesin(v0, v1), Rule(97).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin(v0, v1), r = 97, Rule(97).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(97).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(97).
inv_0(v0, v1) :- livesin(v2, v1), IIlivesin(v0, v2), Rule(98).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin(v0, v2), r = 98, Rule(98).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(98).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(98).
inv_0(v0, v1) :- livesin(v1, v2), IIlivesin(v2, v0), Rule(99).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin(v2, v0), r = 99, Rule(99).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(99).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(99).
inv_0(v0, v1) :- livesin(v2, v0), IIlivesin(v1, v2), Rule(100).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin(v1, v2), r = 100, Rule(100).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(100).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(100).
inv_0(v0, v1) :- livesin(v2, v0), IIlivesin(v2, v1), Rule(101).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin(v2, v1), r = 101, Rule(101).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(101).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(101).
inv_0(v0, v1) :- livesin(v0, v2), IIlivesin(v1, v2), Rule(102).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin(v1, v2), r = 102, Rule(102).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(102).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(102).
inv_0(v0, v1) :- livesin(v0, v2), IIlivesin(v2, v1), Rule(103).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin(v2, v1), r = 103, Rule(103).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(103).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(103).
inv_0(v0, v1) :- livesin(v2, v1), IIlivesin(v2, v0), Rule(104).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin(v2, v0), r = 104, Rule(104).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(104).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(104).
inv_0(v0, v1) :- livesin(v1, v2), IIlivesin(v0, v2), Rule(105).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin(v0, v2), r = 105, Rule(105).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(105).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(105).
inv_0(v0, v1) :- livesin(v0, v1), inv_0(v0, v1), Rule(106).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), inv_0(v0, v1), r = 106, Rule(106).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(106).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(106).
inv_0(v0, v1) :- livesin(v0, v1), inv_0(v1, v0), Rule(107).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), inv_0(v1, v0), r = 107, Rule(107).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(107).
inv_0_exists(v0, v1, r) :- livesin(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(107).
inv_0(v0, v1) :- livesin(v1, v0), inv_0(v1, v0), Rule(108).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), inv_0(v1, v0), r = 108, Rule(108).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(108).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(108).
inv_0(v0, v1) :- livesin(v1, v0), inv_0(v0, v1), Rule(109).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), inv_0(v0, v1), r = 109, Rule(109).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(109).
inv_0_exists(v0, v1, r) :- livesin(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(109).
inv_0(v0, v1) :- livesin(v2, v1), inv_0(v0, v2), Rule(110).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), inv_0(v0, v2), r = 110, Rule(110).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(110).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(110).
inv_0(v0, v1) :- livesin(v1, v2), inv_0(v2, v0), Rule(111).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), inv_0(v2, v0), r = 111, Rule(111).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(111).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(111).
inv_0(v0, v1) :- livesin(v2, v0), inv_0(v1, v2), Rule(112).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), inv_0(v1, v2), r = 112, Rule(112).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(112).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(112).
inv_0(v0, v1) :- livesin(v2, v0), inv_0(v2, v1), Rule(113).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), inv_0(v2, v1), r = 113, Rule(113).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(113).
inv_0_exists(v0, v1, r) :- livesin(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(113).
inv_0(v0, v1) :- livesin(v0, v2), inv_0(v1, v2), Rule(114).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), inv_0(v1, v2), r = 114, Rule(114).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(114).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(114).
inv_0(v0, v1) :- livesin(v0, v2), inv_0(v2, v1), Rule(115).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), inv_0(v2, v1), r = 115, Rule(115).
inv_0_exists(v0, v1, r) :- livesin_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(115).
inv_0_exists(v0, v1, r) :- livesin(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(115).
inv_0(v0, v1) :- livesin(v2, v1), inv_0(v2, v0), Rule(116).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), inv_0(v2, v0), r = 116, Rule(116).
inv_0_exists(v0, v1, r) :- livesin_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(116).
inv_0_exists(v0, v1, r) :- livesin(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(116).
inv_0(v0, v1) :- livesin(v1, v2), inv_0(v0, v2), Rule(117).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), inv_0(v0, v2), r = 117, Rule(117).
inv_0_exists(v0, v1, r) :- livesin_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(117).
inv_0_exists(v0, v1, r) :- livesin(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(117).
inv_0(v0, v1) :- wasbornin(v0, v1), wasbornin(v0, v1), Rule(118).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin(v0, v1), r = 118, Rule(118).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), wasbornin(v0, v1), Rule(r), Rule(118).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin_exists(v0, v1, r), Rule(r), Rule(118).
inv_0(v0, v1) :- wasbornin(v0, v1), wasbornin(v1, v0), Rule(119).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin(v1, v0), r = 119, Rule(119).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), wasbornin(v1, v0), Rule(r), Rule(119).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin_exists(v1, v0, r), Rule(r), Rule(119).
inv_0(v0, v1) :- wasbornin(v1, v0), wasbornin(v1, v0), Rule(120).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin(v1, v0), r = 120, Rule(120).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), wasbornin(v1, v0), Rule(r), Rule(120).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin_exists(v1, v0, r), Rule(r), Rule(120).
inv_0(v0, v1) :- wasbornin(v1, v0), wasbornin(v0, v1), Rule(121).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin(v0, v1), r = 121, Rule(121).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), wasbornin(v0, v1), Rule(r), Rule(121).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin_exists(v0, v1, r), Rule(r), Rule(121).
inv_0(v0, v1) :- wasbornin(v2, v1), wasbornin(v0, v2), Rule(122).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin(v0, v2), r = 122, Rule(122).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), wasbornin(v0, v2), Rule(r), Rule(122).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin_exists(v0, v2, r), Rule(r), Rule(122).
inv_0(v0, v1) :- wasbornin(v1, v2), wasbornin(v2, v0), Rule(123).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin(v2, v0), r = 123, Rule(123).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), wasbornin(v2, v0), Rule(r), Rule(123).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin_exists(v2, v0, r), Rule(r), Rule(123).
inv_0(v0, v1) :- wasbornin(v2, v0), wasbornin(v1, v2), Rule(124).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin(v1, v2), r = 124, Rule(124).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), wasbornin(v1, v2), Rule(r), Rule(124).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin_exists(v1, v2, r), Rule(r), Rule(124).
inv_0(v0, v1) :- wasbornin(v2, v0), wasbornin(v2, v1), Rule(125).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin(v2, v1), r = 125, Rule(125).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), wasbornin(v2, v1), Rule(r), Rule(125).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin_exists(v2, v1, r), Rule(r), Rule(125).
inv_0(v0, v1) :- wasbornin(v0, v2), wasbornin(v1, v2), Rule(126).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin(v1, v2), r = 126, Rule(126).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), wasbornin(v1, v2), Rule(r), Rule(126).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin_exists(v1, v2, r), Rule(r), Rule(126).
inv_0(v0, v1) :- wasbornin(v0, v2), wasbornin(v2, v1), Rule(127).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin(v2, v1), r = 127, Rule(127).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), wasbornin(v2, v1), Rule(r), Rule(127).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin_exists(v2, v1, r), Rule(r), Rule(127).
inv_0(v0, v1) :- wasbornin(v2, v1), wasbornin(v2, v0), Rule(128).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin(v2, v0), r = 128, Rule(128).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), wasbornin(v2, v0), Rule(r), Rule(128).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin_exists(v2, v0, r), Rule(r), Rule(128).
inv_0(v0, v1) :- wasbornin(v1, v2), wasbornin(v0, v2), Rule(129).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin(v0, v2), r = 129, Rule(129).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), wasbornin(v0, v2), Rule(r), Rule(129).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin_exists(v0, v2, r), Rule(r), Rule(129).
inv_0(v0, v1) :- wasbornin(v0, v1), IIlivesin(v0, v1), Rule(130).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin(v0, v1), r = 130, Rule(130).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(130).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(130).
inv_0(v0, v1) :- wasbornin(v0, v1), IIlivesin(v1, v0), Rule(131).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin(v1, v0), r = 131, Rule(131).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(131).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(131).
inv_0(v0, v1) :- wasbornin(v1, v0), IIlivesin(v1, v0), Rule(132).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin(v1, v0), r = 132, Rule(132).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(132).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(132).
inv_0(v0, v1) :- wasbornin(v1, v0), IIlivesin(v0, v1), Rule(133).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin(v0, v1), r = 133, Rule(133).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(133).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(133).
inv_0(v0, v1) :- wasbornin(v2, v1), IIlivesin(v0, v2), Rule(134).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin(v0, v2), r = 134, Rule(134).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(134).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(134).
inv_0(v0, v1) :- wasbornin(v1, v2), IIlivesin(v2, v0), Rule(135).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin(v2, v0), r = 135, Rule(135).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(135).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(135).
inv_0(v0, v1) :- wasbornin(v2, v0), IIlivesin(v1, v2), Rule(136).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin(v1, v2), r = 136, Rule(136).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(136).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(136).
inv_0(v0, v1) :- wasbornin(v2, v0), IIlivesin(v2, v1), Rule(137).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin(v2, v1), r = 137, Rule(137).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(137).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(137).
inv_0(v0, v1) :- wasbornin(v0, v2), IIlivesin(v1, v2), Rule(138).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin(v1, v2), r = 138, Rule(138).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(138).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(138).
inv_0(v0, v1) :- wasbornin(v0, v2), IIlivesin(v2, v1), Rule(139).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin(v2, v1), r = 139, Rule(139).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(139).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(139).
inv_0(v0, v1) :- wasbornin(v2, v1), IIlivesin(v2, v0), Rule(140).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin(v2, v0), r = 140, Rule(140).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(140).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(140).
inv_0(v0, v1) :- wasbornin(v1, v2), IIlivesin(v0, v2), Rule(141).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin(v0, v2), r = 141, Rule(141).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(141).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(141).
inv_0(v0, v1) :- wasbornin(v0, v1), inv_0(v0, v1), Rule(142).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0(v0, v1), r = 142, Rule(142).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(142).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(142).
inv_0(v0, v1) :- wasbornin(v0, v1), inv_0(v1, v0), Rule(143).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0(v1, v0), r = 143, Rule(143).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(143).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(143).
inv_0(v0, v1) :- wasbornin(v1, v0), inv_0(v1, v0), Rule(144).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0(v1, v0), r = 144, Rule(144).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(144).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(144).
inv_0(v0, v1) :- wasbornin(v1, v0), inv_0(v0, v1), Rule(145).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0(v0, v1), r = 145, Rule(145).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(145).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(145).
inv_0(v0, v1) :- wasbornin(v2, v1), inv_0(v0, v2), Rule(146).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0(v0, v2), r = 146, Rule(146).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(146).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(146).
inv_0(v0, v1) :- wasbornin(v1, v2), inv_0(v2, v0), Rule(147).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0(v2, v0), r = 147, Rule(147).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(147).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(147).
inv_0(v0, v1) :- wasbornin(v2, v0), inv_0(v1, v2), Rule(148).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0(v1, v2), r = 148, Rule(148).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(148).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(148).
inv_0(v0, v1) :- wasbornin(v2, v0), inv_0(v2, v1), Rule(149).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0(v2, v1), r = 149, Rule(149).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(149).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(149).
inv_0(v0, v1) :- wasbornin(v0, v2), inv_0(v1, v2), Rule(150).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0(v1, v2), r = 150, Rule(150).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(150).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(150).
inv_0(v0, v1) :- wasbornin(v0, v2), inv_0(v2, v1), Rule(151).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0(v2, v1), r = 151, Rule(151).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(151).
inv_0_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(151).
inv_0(v0, v1) :- wasbornin(v2, v1), inv_0(v2, v0), Rule(152).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0(v2, v0), r = 152, Rule(152).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(152).
inv_0_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(152).
inv_0(v0, v1) :- wasbornin(v1, v2), inv_0(v0, v2), Rule(153).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0(v0, v2), r = 153, Rule(153).
inv_0_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(153).
inv_0_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(153).
inv_0(v0, v1) :- IIlivesin(v0, v1), IIlivesin(v0, v1), Rule(154).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin(v0, v1), r = 154, Rule(154).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(154).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(154).
inv_0(v0, v1) :- IIlivesin(v0, v1), IIlivesin(v1, v0), Rule(155).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin(v1, v0), r = 155, Rule(155).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(155).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(155).
inv_0(v0, v1) :- IIlivesin(v1, v0), IIlivesin(v1, v0), Rule(156).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin(v1, v0), r = 156, Rule(156).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(156).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(156).
inv_0(v0, v1) :- IIlivesin(v1, v0), IIlivesin(v0, v1), Rule(157).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin(v0, v1), r = 157, Rule(157).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(157).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(157).
inv_0(v0, v1) :- IIlivesin(v2, v1), IIlivesin(v0, v2), Rule(158).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin(v0, v2), r = 158, Rule(158).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(158).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(158).
inv_0(v0, v1) :- IIlivesin(v1, v2), IIlivesin(v2, v0), Rule(159).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin(v2, v0), r = 159, Rule(159).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(159).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(159).
inv_0(v0, v1) :- IIlivesin(v2, v0), IIlivesin(v1, v2), Rule(160).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin(v1, v2), r = 160, Rule(160).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(160).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(160).
inv_0(v0, v1) :- IIlivesin(v2, v0), IIlivesin(v2, v1), Rule(161).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin(v2, v1), r = 161, Rule(161).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(161).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(161).
inv_0(v0, v1) :- IIlivesin(v0, v2), IIlivesin(v1, v2), Rule(162).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin(v1, v2), r = 162, Rule(162).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(162).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(162).
inv_0(v0, v1) :- IIlivesin(v0, v2), IIlivesin(v2, v1), Rule(163).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin(v2, v1), r = 163, Rule(163).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(163).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(163).
inv_0(v0, v1) :- IIlivesin(v2, v1), IIlivesin(v2, v0), Rule(164).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin(v2, v0), r = 164, Rule(164).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(164).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(164).
inv_0(v0, v1) :- IIlivesin(v1, v2), IIlivesin(v0, v2), Rule(165).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin(v0, v2), r = 165, Rule(165).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(165).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(165).
inv_0(v0, v1) :- IIlivesin(v0, v1), inv_0(v0, v1), Rule(166).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0(v0, v1), r = 166, Rule(166).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(166).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(166).
inv_0(v0, v1) :- IIlivesin(v0, v1), inv_0(v1, v0), Rule(167).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0(v1, v0), r = 167, Rule(167).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(167).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(167).
inv_0(v0, v1) :- IIlivesin(v1, v0), inv_0(v1, v0), Rule(168).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0(v1, v0), r = 168, Rule(168).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(168).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(168).
inv_0(v0, v1) :- IIlivesin(v1, v0), inv_0(v0, v1), Rule(169).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0(v0, v1), r = 169, Rule(169).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(169).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(169).
inv_0(v0, v1) :- IIlivesin(v2, v1), inv_0(v0, v2), Rule(170).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0(v0, v2), r = 170, Rule(170).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(170).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(170).
inv_0(v0, v1) :- IIlivesin(v1, v2), inv_0(v2, v0), Rule(171).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0(v2, v0), r = 171, Rule(171).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(171).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(171).
inv_0(v0, v1) :- IIlivesin(v2, v0), inv_0(v1, v2), Rule(172).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0(v1, v2), r = 172, Rule(172).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(172).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(172).
inv_0(v0, v1) :- IIlivesin(v2, v0), inv_0(v2, v1), Rule(173).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0(v2, v1), r = 173, Rule(173).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(173).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(173).
inv_0(v0, v1) :- IIlivesin(v0, v2), inv_0(v1, v2), Rule(174).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0(v1, v2), r = 174, Rule(174).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(174).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(174).
inv_0(v0, v1) :- IIlivesin(v0, v2), inv_0(v2, v1), Rule(175).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0(v2, v1), r = 175, Rule(175).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(175).
inv_0_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(175).
inv_0(v0, v1) :- IIlivesin(v2, v1), inv_0(v2, v0), Rule(176).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0(v2, v0), r = 176, Rule(176).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(176).
inv_0_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(176).
inv_0(v0, v1) :- IIlivesin(v1, v2), inv_0(v0, v2), Rule(177).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0(v0, v2), r = 177, Rule(177).
inv_0_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(177).
inv_0_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(177).
inv_0(v0, v1) :- inv_0(v0, v1), inv_0(v0, v1), Rule(178).
inv_0_exists(v0, v1, r) :- inv_0(v0, v1), inv_0(v0, v1), r = 178, Rule(178).
inv_0_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(178).
inv_0_exists(v0, v1, r) :- inv_0(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(178).
inv_0(v0, v1) :- inv_0(v0, v1), inv_0(v1, v0), Rule(179).
inv_0_exists(v0, v1, r) :- inv_0(v0, v1), inv_0(v1, v0), r = 179, Rule(179).
inv_0_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(179).
inv_0_exists(v0, v1, r) :- inv_0(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(179).
inv_0(v0, v1) :- inv_0(v1, v0), inv_0(v1, v0), Rule(180).
inv_0_exists(v0, v1, r) :- inv_0(v1, v0), inv_0(v1, v0), r = 180, Rule(180).
inv_0_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(180).
inv_0_exists(v0, v1, r) :- inv_0(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(180).
inv_0(v0, v1) :- inv_0(v1, v0), inv_0(v0, v1), Rule(181).
inv_0_exists(v0, v1, r) :- inv_0(v1, v0), inv_0(v0, v1), r = 181, Rule(181).
inv_0_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(181).
inv_0_exists(v0, v1, r) :- inv_0(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(181).
inv_0(v0, v1) :- inv_0(v2, v1), inv_0(v0, v2), Rule(182).
inv_0_exists(v0, v1, r) :- inv_0(v2, v1), inv_0(v0, v2), r = 182, Rule(182).
inv_0_exists(v0, v1, r) :- inv_0_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(182).
inv_0_exists(v0, v1, r) :- inv_0(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(182).
inv_0(v0, v1) :- inv_0(v1, v2), inv_0(v2, v0), Rule(183).
inv_0_exists(v0, v1, r) :- inv_0(v1, v2), inv_0(v2, v0), r = 183, Rule(183).
inv_0_exists(v0, v1, r) :- inv_0_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(183).
inv_0_exists(v0, v1, r) :- inv_0(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(183).
inv_0(v0, v1) :- inv_0(v2, v0), inv_0(v1, v2), Rule(184).
inv_0_exists(v0, v1, r) :- inv_0(v2, v0), inv_0(v1, v2), r = 184, Rule(184).
inv_0_exists(v0, v1, r) :- inv_0_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(184).
inv_0_exists(v0, v1, r) :- inv_0(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(184).
inv_0(v0, v1) :- inv_0(v2, v0), inv_0(v2, v1), Rule(185).
inv_0_exists(v0, v1, r) :- inv_0(v2, v0), inv_0(v2, v1), r = 185, Rule(185).
inv_0_exists(v0, v1, r) :- inv_0_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(185).
inv_0_exists(v0, v1, r) :- inv_0(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(185).
inv_0(v0, v1) :- inv_0(v0, v2), inv_0(v1, v2), Rule(186).
inv_0_exists(v0, v1, r) :- inv_0(v0, v2), inv_0(v1, v2), r = 186, Rule(186).
inv_0_exists(v0, v1, r) :- inv_0_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(186).
inv_0_exists(v0, v1, r) :- inv_0(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(186).
inv_0(v0, v1) :- inv_0(v0, v2), inv_0(v2, v1), Rule(187).
inv_0_exists(v0, v1, r) :- inv_0(v0, v2), inv_0(v2, v1), r = 187, Rule(187).
inv_0_exists(v0, v1, r) :- inv_0_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(187).
inv_0_exists(v0, v1, r) :- inv_0(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(187).
inv_0(v0, v1) :- inv_0(v2, v1), inv_0(v2, v0), Rule(188).
inv_0_exists(v0, v1, r) :- inv_0(v2, v1), inv_0(v2, v0), r = 188, Rule(188).
inv_0_exists(v0, v1, r) :- inv_0_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(188).
inv_0_exists(v0, v1, r) :- inv_0(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(188).
inv_0(v0, v1) :- inv_0(v1, v2), inv_0(v0, v2), Rule(189).
inv_0_exists(v0, v1, r) :- inv_0(v1, v2), inv_0(v0, v2), r = 189, Rule(189).
inv_0_exists(v0, v1, r) :- inv_0_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(189).
inv_0_exists(v0, v1, r) :- inv_0(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(189).
Ilivesin(v0, v1) :- Rule(v0, v1), Rule(190).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), r = 190, Rule(190).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Rule(r), Rule(190).
Ilivesin(v0, v1) :- Rule(v1, v0), Rule(191).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), r = 191, Rule(191).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Rule(r), Rule(191).
Ilivesin(v0, v1) :- livesin(v0, v1), Rule(192).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), r = 192, Rule(192).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), Rule(r), Rule(192).
Ilivesin(v0, v1) :- livesin(v1, v0), Rule(193).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), r = 193, Rule(193).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), Rule(r), Rule(193).
Ilivesin(v0, v1) :- wasbornin(v0, v1), Rule(194).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), r = 194, Rule(194).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), Rule(r), Rule(194).
Ilivesin(v0, v1) :- wasbornin(v1, v0), Rule(195).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), r = 195, Rule(195).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), Rule(r), Rule(195).
Ilivesin(v0, v1) :- IIlivesin(v0, v1), Rule(196).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), r = 196, Rule(196).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), Rule(r), Rule(196).
Ilivesin(v0, v1) :- IIlivesin(v1, v0), Rule(197).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), r = 197, Rule(197).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), Rule(r), Rule(197).
Ilivesin(v0, v1) :- inv_0(v0, v1), Rule(198).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), r = 198, Rule(198).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), Rule(r), Rule(198).
Ilivesin(v0, v1) :- inv_0(v1, v0), Rule(199).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), r = 199, Rule(199).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), Rule(r), Rule(199).
Ilivesin(v0, v1) :- Ilivesin(v0, v1), Rule(200).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v1), r = 200, Rule(200).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v0, v1, r), Rule(r), Rule(200).
Ilivesin(v0, v1) :- Ilivesin(v1, v0), Rule(201).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v0), r = 201, Rule(201).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v1, v0, r), Rule(r), Rule(201).
Ilivesin(v0, v1) :- Rule(v0, v1), Rule(v0, v1), Rule(202).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Rule(v0, v1), r = 202, Rule(202).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Rule(v0, v1), Rule(r), Rule(202).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Rule_exists(v0, v1, r), Rule(r), Rule(202).
Ilivesin(v0, v1) :- Rule(v0, v1), Rule(v1, v0), Rule(203).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Rule(v1, v0), r = 203, Rule(203).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Rule(v1, v0), Rule(r), Rule(203).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Rule_exists(v1, v0, r), Rule(r), Rule(203).
Ilivesin(v0, v1) :- Rule(v1, v0), Rule(v1, v0), Rule(204).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Rule(v1, v0), r = 204, Rule(204).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Rule(v1, v0), Rule(r), Rule(204).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Rule_exists(v1, v0, r), Rule(r), Rule(204).
Ilivesin(v0, v1) :- Rule(v1, v0), Rule(v0, v1), Rule(205).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Rule(v0, v1), r = 205, Rule(205).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Rule(v0, v1), Rule(r), Rule(205).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Rule_exists(v0, v1, r), Rule(r), Rule(205).
Ilivesin(v0, v1) :- Rule(v2, v1), Rule(v0, v2), Rule(206).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Rule(v0, v2), r = 206, Rule(206).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), Rule(v0, v2), Rule(r), Rule(206).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Rule_exists(v0, v2, r), Rule(r), Rule(206).
Ilivesin(v0, v1) :- Rule(v1, v2), Rule(v2, v0), Rule(207).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Rule(v2, v0), r = 207, Rule(207).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), Rule(v2, v0), Rule(r), Rule(207).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Rule_exists(v2, v0, r), Rule(r), Rule(207).
Ilivesin(v0, v1) :- Rule(v2, v0), Rule(v1, v2), Rule(208).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Rule(v1, v2), r = 208, Rule(208).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), Rule(v1, v2), Rule(r), Rule(208).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Rule_exists(v1, v2, r), Rule(r), Rule(208).
Ilivesin(v0, v1) :- Rule(v2, v0), Rule(v2, v1), Rule(209).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Rule(v2, v1), r = 209, Rule(209).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), Rule(v2, v1), Rule(r), Rule(209).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Rule_exists(v2, v1, r), Rule(r), Rule(209).
Ilivesin(v0, v1) :- Rule(v0, v2), Rule(v1, v2), Rule(210).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Rule(v1, v2), r = 210, Rule(210).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), Rule(v1, v2), Rule(r), Rule(210).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Rule_exists(v1, v2, r), Rule(r), Rule(210).
Ilivesin(v0, v1) :- Rule(v0, v2), Rule(v2, v1), Rule(211).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Rule(v2, v1), r = 211, Rule(211).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), Rule(v2, v1), Rule(r), Rule(211).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Rule_exists(v2, v1, r), Rule(r), Rule(211).
Ilivesin(v0, v1) :- Rule(v2, v1), Rule(v2, v0), Rule(212).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Rule(v2, v0), r = 212, Rule(212).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), Rule(v2, v0), Rule(r), Rule(212).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Rule_exists(v2, v0, r), Rule(r), Rule(212).
Ilivesin(v0, v1) :- Rule(v1, v2), Rule(v0, v2), Rule(213).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Rule(v0, v2), r = 213, Rule(213).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), Rule(v0, v2), Rule(r), Rule(213).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Rule_exists(v0, v2, r), Rule(r), Rule(213).
Ilivesin(v0, v1) :- Rule(v0, v1), livesin(v0, v1), Rule(214).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), livesin(v0, v1), r = 214, Rule(214).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), livesin(v0, v1), Rule(r), Rule(214).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), livesin_exists(v0, v1, r), Rule(r), Rule(214).
Ilivesin(v0, v1) :- Rule(v0, v1), livesin(v1, v0), Rule(215).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), livesin(v1, v0), r = 215, Rule(215).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), livesin(v1, v0), Rule(r), Rule(215).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), livesin_exists(v1, v0, r), Rule(r), Rule(215).
Ilivesin(v0, v1) :- Rule(v1, v0), livesin(v1, v0), Rule(216).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), livesin(v1, v0), r = 216, Rule(216).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), livesin(v1, v0), Rule(r), Rule(216).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), livesin_exists(v1, v0, r), Rule(r), Rule(216).
Ilivesin(v0, v1) :- Rule(v1, v0), livesin(v0, v1), Rule(217).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), livesin(v0, v1), r = 217, Rule(217).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), livesin(v0, v1), Rule(r), Rule(217).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), livesin_exists(v0, v1, r), Rule(r), Rule(217).
Ilivesin(v0, v1) :- Rule(v2, v1), livesin(v0, v2), Rule(218).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), livesin(v0, v2), r = 218, Rule(218).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), livesin(v0, v2), Rule(r), Rule(218).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), livesin_exists(v0, v2, r), Rule(r), Rule(218).
Ilivesin(v0, v1) :- Rule(v1, v2), livesin(v2, v0), Rule(219).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), livesin(v2, v0), r = 219, Rule(219).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), livesin(v2, v0), Rule(r), Rule(219).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), livesin_exists(v2, v0, r), Rule(r), Rule(219).
Ilivesin(v0, v1) :- Rule(v2, v0), livesin(v1, v2), Rule(220).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), livesin(v1, v2), r = 220, Rule(220).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), livesin(v1, v2), Rule(r), Rule(220).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), livesin_exists(v1, v2, r), Rule(r), Rule(220).
Ilivesin(v0, v1) :- Rule(v2, v0), livesin(v2, v1), Rule(221).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), livesin(v2, v1), r = 221, Rule(221).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), livesin(v2, v1), Rule(r), Rule(221).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), livesin_exists(v2, v1, r), Rule(r), Rule(221).
Ilivesin(v0, v1) :- Rule(v0, v2), livesin(v1, v2), Rule(222).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), livesin(v1, v2), r = 222, Rule(222).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), livesin(v1, v2), Rule(r), Rule(222).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), livesin_exists(v1, v2, r), Rule(r), Rule(222).
Ilivesin(v0, v1) :- Rule(v0, v2), livesin(v2, v1), Rule(223).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), livesin(v2, v1), r = 223, Rule(223).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), livesin(v2, v1), Rule(r), Rule(223).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), livesin_exists(v2, v1, r), Rule(r), Rule(223).
Ilivesin(v0, v1) :- Rule(v2, v1), livesin(v2, v0), Rule(224).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), livesin(v2, v0), r = 224, Rule(224).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), livesin(v2, v0), Rule(r), Rule(224).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), livesin_exists(v2, v0, r), Rule(r), Rule(224).
Ilivesin(v0, v1) :- Rule(v1, v2), livesin(v0, v2), Rule(225).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), livesin(v0, v2), r = 225, Rule(225).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), livesin(v0, v2), Rule(r), Rule(225).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), livesin_exists(v0, v2, r), Rule(r), Rule(225).
Ilivesin(v0, v1) :- Rule(v0, v1), wasbornin(v0, v1), Rule(226).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), wasbornin(v0, v1), r = 226, Rule(226).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), wasbornin(v0, v1), Rule(r), Rule(226).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), wasbornin_exists(v0, v1, r), Rule(r), Rule(226).
Ilivesin(v0, v1) :- Rule(v0, v1), wasbornin(v1, v0), Rule(227).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), wasbornin(v1, v0), r = 227, Rule(227).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), wasbornin(v1, v0), Rule(r), Rule(227).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), wasbornin_exists(v1, v0, r), Rule(r), Rule(227).
Ilivesin(v0, v1) :- Rule(v1, v0), wasbornin(v1, v0), Rule(228).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), wasbornin(v1, v0), r = 228, Rule(228).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), wasbornin(v1, v0), Rule(r), Rule(228).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), wasbornin_exists(v1, v0, r), Rule(r), Rule(228).
Ilivesin(v0, v1) :- Rule(v1, v0), wasbornin(v0, v1), Rule(229).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), wasbornin(v0, v1), r = 229, Rule(229).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), wasbornin(v0, v1), Rule(r), Rule(229).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), wasbornin_exists(v0, v1, r), Rule(r), Rule(229).
Ilivesin(v0, v1) :- Rule(v2, v1), wasbornin(v0, v2), Rule(230).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), wasbornin(v0, v2), r = 230, Rule(230).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), wasbornin(v0, v2), Rule(r), Rule(230).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), wasbornin_exists(v0, v2, r), Rule(r), Rule(230).
Ilivesin(v0, v1) :- Rule(v1, v2), wasbornin(v2, v0), Rule(231).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), wasbornin(v2, v0), r = 231, Rule(231).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), wasbornin(v2, v0), Rule(r), Rule(231).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), wasbornin_exists(v2, v0, r), Rule(r), Rule(231).
Ilivesin(v0, v1) :- Rule(v2, v0), wasbornin(v1, v2), Rule(232).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), wasbornin(v1, v2), r = 232, Rule(232).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), wasbornin(v1, v2), Rule(r), Rule(232).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), wasbornin_exists(v1, v2, r), Rule(r), Rule(232).
Ilivesin(v0, v1) :- Rule(v2, v0), wasbornin(v2, v1), Rule(233).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), wasbornin(v2, v1), r = 233, Rule(233).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), wasbornin(v2, v1), Rule(r), Rule(233).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), wasbornin_exists(v2, v1, r), Rule(r), Rule(233).
Ilivesin(v0, v1) :- Rule(v0, v2), wasbornin(v1, v2), Rule(234).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), wasbornin(v1, v2), r = 234, Rule(234).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), wasbornin(v1, v2), Rule(r), Rule(234).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), wasbornin_exists(v1, v2, r), Rule(r), Rule(234).
Ilivesin(v0, v1) :- Rule(v0, v2), wasbornin(v2, v1), Rule(235).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), wasbornin(v2, v1), r = 235, Rule(235).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), wasbornin(v2, v1), Rule(r), Rule(235).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), wasbornin_exists(v2, v1, r), Rule(r), Rule(235).
Ilivesin(v0, v1) :- Rule(v2, v1), wasbornin(v2, v0), Rule(236).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), wasbornin(v2, v0), r = 236, Rule(236).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), wasbornin(v2, v0), Rule(r), Rule(236).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), wasbornin_exists(v2, v0, r), Rule(r), Rule(236).
Ilivesin(v0, v1) :- Rule(v1, v2), wasbornin(v0, v2), Rule(237).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), wasbornin(v0, v2), r = 237, Rule(237).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), wasbornin(v0, v2), Rule(r), Rule(237).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), wasbornin_exists(v0, v2, r), Rule(r), Rule(237).
Ilivesin(v0, v1) :- Rule(v0, v1), IIlivesin(v0, v1), Rule(238).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin(v0, v1), r = 238, Rule(238).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(238).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(238).
Ilivesin(v0, v1) :- Rule(v0, v1), IIlivesin(v1, v0), Rule(239).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin(v1, v0), r = 239, Rule(239).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(239).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(239).
Ilivesin(v0, v1) :- Rule(v1, v0), IIlivesin(v1, v0), Rule(240).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin(v1, v0), r = 240, Rule(240).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(240).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(240).
Ilivesin(v0, v1) :- Rule(v1, v0), IIlivesin(v0, v1), Rule(241).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin(v0, v1), r = 241, Rule(241).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(241).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(241).
Ilivesin(v0, v1) :- Rule(v2, v1), IIlivesin(v0, v2), Rule(242).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin(v0, v2), r = 242, Rule(242).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(242).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(242).
Ilivesin(v0, v1) :- Rule(v1, v2), IIlivesin(v2, v0), Rule(243).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin(v2, v0), r = 243, Rule(243).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(243).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(243).
Ilivesin(v0, v1) :- Rule(v2, v0), IIlivesin(v1, v2), Rule(244).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin(v1, v2), r = 244, Rule(244).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(244).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(244).
Ilivesin(v0, v1) :- Rule(v2, v0), IIlivesin(v2, v1), Rule(245).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin(v2, v1), r = 245, Rule(245).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(245).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(245).
Ilivesin(v0, v1) :- Rule(v0, v2), IIlivesin(v1, v2), Rule(246).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin(v1, v2), r = 246, Rule(246).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(246).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(246).
Ilivesin(v0, v1) :- Rule(v0, v2), IIlivesin(v2, v1), Rule(247).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin(v2, v1), r = 247, Rule(247).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(247).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(247).
Ilivesin(v0, v1) :- Rule(v2, v1), IIlivesin(v2, v0), Rule(248).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin(v2, v0), r = 248, Rule(248).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(248).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(248).
Ilivesin(v0, v1) :- Rule(v1, v2), IIlivesin(v0, v2), Rule(249).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin(v0, v2), r = 249, Rule(249).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(249).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(249).
Ilivesin(v0, v1) :- Rule(v0, v1), inv_0(v0, v1), Rule(250).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), inv_0(v0, v1), r = 250, Rule(250).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(250).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(250).
Ilivesin(v0, v1) :- Rule(v0, v1), inv_0(v1, v0), Rule(251).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), inv_0(v1, v0), r = 251, Rule(251).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(251).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(251).
Ilivesin(v0, v1) :- Rule(v1, v0), inv_0(v1, v0), Rule(252).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), inv_0(v1, v0), r = 252, Rule(252).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(252).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(252).
Ilivesin(v0, v1) :- Rule(v1, v0), inv_0(v0, v1), Rule(253).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), inv_0(v0, v1), r = 253, Rule(253).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(253).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(253).
Ilivesin(v0, v1) :- Rule(v2, v1), inv_0(v0, v2), Rule(254).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), inv_0(v0, v2), r = 254, Rule(254).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(254).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(254).
Ilivesin(v0, v1) :- Rule(v1, v2), inv_0(v2, v0), Rule(255).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), inv_0(v2, v0), r = 255, Rule(255).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(255).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(255).
Ilivesin(v0, v1) :- Rule(v2, v0), inv_0(v1, v2), Rule(256).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), inv_0(v1, v2), r = 256, Rule(256).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(256).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(256).
Ilivesin(v0, v1) :- Rule(v2, v0), inv_0(v2, v1), Rule(257).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), inv_0(v2, v1), r = 257, Rule(257).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(257).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(257).
Ilivesin(v0, v1) :- Rule(v0, v2), inv_0(v1, v2), Rule(258).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), inv_0(v1, v2), r = 258, Rule(258).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(258).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(258).
Ilivesin(v0, v1) :- Rule(v0, v2), inv_0(v2, v1), Rule(259).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), inv_0(v2, v1), r = 259, Rule(259).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(259).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(259).
Ilivesin(v0, v1) :- Rule(v2, v1), inv_0(v2, v0), Rule(260).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), inv_0(v2, v0), r = 260, Rule(260).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(260).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(260).
Ilivesin(v0, v1) :- Rule(v1, v2), inv_0(v0, v2), Rule(261).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), inv_0(v0, v2), r = 261, Rule(261).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(261).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(261).
Ilivesin(v0, v1) :- Rule(v0, v1), Ilivesin(v0, v1), Rule(262).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Ilivesin(v0, v1), r = 262, Rule(262).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Ilivesin(v0, v1), Rule(r), Rule(262).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Ilivesin_exists(v0, v1, r), Rule(r), Rule(262).
Ilivesin(v0, v1) :- Rule(v0, v1), Ilivesin(v1, v0), Rule(263).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Ilivesin(v1, v0), r = 263, Rule(263).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v1, r), Ilivesin(v1, v0), Rule(r), Rule(263).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v1), Ilivesin_exists(v1, v0, r), Rule(r), Rule(263).
Ilivesin(v0, v1) :- Rule(v1, v0), Ilivesin(v1, v0), Rule(264).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Ilivesin(v1, v0), r = 264, Rule(264).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Ilivesin(v1, v0), Rule(r), Rule(264).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Ilivesin_exists(v1, v0, r), Rule(r), Rule(264).
Ilivesin(v0, v1) :- Rule(v1, v0), Ilivesin(v0, v1), Rule(265).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Ilivesin(v0, v1), r = 265, Rule(265).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v0, r), Ilivesin(v0, v1), Rule(r), Rule(265).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v0), Ilivesin_exists(v0, v1, r), Rule(r), Rule(265).
Ilivesin(v0, v1) :- Rule(v2, v1), Ilivesin(v0, v2), Rule(266).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Ilivesin(v0, v2), r = 266, Rule(266).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), Ilivesin(v0, v2), Rule(r), Rule(266).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Ilivesin_exists(v0, v2, r), Rule(r), Rule(266).
Ilivesin(v0, v1) :- Rule(v1, v2), Ilivesin(v2, v0), Rule(267).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Ilivesin(v2, v0), r = 267, Rule(267).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), Ilivesin(v2, v0), Rule(r), Rule(267).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Ilivesin_exists(v2, v0, r), Rule(r), Rule(267).
Ilivesin(v0, v1) :- Rule(v2, v0), Ilivesin(v1, v2), Rule(268).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Ilivesin(v1, v2), r = 268, Rule(268).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), Ilivesin(v1, v2), Rule(r), Rule(268).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Ilivesin_exists(v1, v2, r), Rule(r), Rule(268).
Ilivesin(v0, v1) :- Rule(v2, v0), Ilivesin(v2, v1), Rule(269).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Ilivesin(v2, v1), r = 269, Rule(269).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v0, r), Ilivesin(v2, v1), Rule(r), Rule(269).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v0), Ilivesin_exists(v2, v1, r), Rule(r), Rule(269).
Ilivesin(v0, v1) :- Rule(v0, v2), Ilivesin(v1, v2), Rule(270).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Ilivesin(v1, v2), r = 270, Rule(270).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), Ilivesin(v1, v2), Rule(r), Rule(270).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Ilivesin_exists(v1, v2, r), Rule(r), Rule(270).
Ilivesin(v0, v1) :- Rule(v0, v2), Ilivesin(v2, v1), Rule(271).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Ilivesin(v2, v1), r = 271, Rule(271).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v0, v2, r), Ilivesin(v2, v1), Rule(r), Rule(271).
Ilivesin_exists(v0, v1, r) :- Rule(v0, v2), Ilivesin_exists(v2, v1, r), Rule(r), Rule(271).
Ilivesin(v0, v1) :- Rule(v2, v1), Ilivesin(v2, v0), Rule(272).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Ilivesin(v2, v0), r = 272, Rule(272).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v2, v1, r), Ilivesin(v2, v0), Rule(r), Rule(272).
Ilivesin_exists(v0, v1, r) :- Rule(v2, v1), Ilivesin_exists(v2, v0, r), Rule(r), Rule(272).
Ilivesin(v0, v1) :- Rule(v1, v2), Ilivesin(v0, v2), Rule(273).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Ilivesin(v0, v2), r = 273, Rule(273).
Ilivesin_exists(v0, v1, r) :- Rule_exists(v1, v2, r), Ilivesin(v0, v2), Rule(r), Rule(273).
Ilivesin_exists(v0, v1, r) :- Rule(v1, v2), Ilivesin_exists(v0, v2, r), Rule(r), Rule(273).
Ilivesin(v0, v1) :- livesin(v0, v1), livesin(v0, v1), Rule(274).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), livesin(v0, v1), r = 274, Rule(274).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), livesin(v0, v1), Rule(r), Rule(274).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), livesin_exists(v0, v1, r), Rule(r), Rule(274).
Ilivesin(v0, v1) :- livesin(v0, v1), livesin(v1, v0), Rule(275).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), livesin(v1, v0), r = 275, Rule(275).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), livesin(v1, v0), Rule(r), Rule(275).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), livesin_exists(v1, v0, r), Rule(r), Rule(275).
Ilivesin(v0, v1) :- livesin(v1, v0), livesin(v1, v0), Rule(276).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), livesin(v1, v0), r = 276, Rule(276).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), livesin(v1, v0), Rule(r), Rule(276).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), livesin_exists(v1, v0, r), Rule(r), Rule(276).
Ilivesin(v0, v1) :- livesin(v1, v0), livesin(v0, v1), Rule(277).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), livesin(v0, v1), r = 277, Rule(277).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), livesin(v0, v1), Rule(r), Rule(277).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), livesin_exists(v0, v1, r), Rule(r), Rule(277).
Ilivesin(v0, v1) :- livesin(v2, v1), livesin(v0, v2), Rule(278).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), livesin(v0, v2), r = 278, Rule(278).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), livesin(v0, v2), Rule(r), Rule(278).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), livesin_exists(v0, v2, r), Rule(r), Rule(278).
Ilivesin(v0, v1) :- livesin(v1, v2), livesin(v2, v0), Rule(279).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), livesin(v2, v0), r = 279, Rule(279).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), livesin(v2, v0), Rule(r), Rule(279).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), livesin_exists(v2, v0, r), Rule(r), Rule(279).
Ilivesin(v0, v1) :- livesin(v2, v0), livesin(v1, v2), Rule(280).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), livesin(v1, v2), r = 280, Rule(280).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), livesin(v1, v2), Rule(r), Rule(280).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), livesin_exists(v1, v2, r), Rule(r), Rule(280).
Ilivesin(v0, v1) :- livesin(v2, v0), livesin(v2, v1), Rule(281).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), livesin(v2, v1), r = 281, Rule(281).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), livesin(v2, v1), Rule(r), Rule(281).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), livesin_exists(v2, v1, r), Rule(r), Rule(281).
Ilivesin(v0, v1) :- livesin(v0, v2), livesin(v1, v2), Rule(282).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), livesin(v1, v2), r = 282, Rule(282).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), livesin(v1, v2), Rule(r), Rule(282).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), livesin_exists(v1, v2, r), Rule(r), Rule(282).
Ilivesin(v0, v1) :- livesin(v0, v2), livesin(v2, v1), Rule(283).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), livesin(v2, v1), r = 283, Rule(283).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), livesin(v2, v1), Rule(r), Rule(283).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), livesin_exists(v2, v1, r), Rule(r), Rule(283).
Ilivesin(v0, v1) :- livesin(v2, v1), livesin(v2, v0), Rule(284).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), livesin(v2, v0), r = 284, Rule(284).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), livesin(v2, v0), Rule(r), Rule(284).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), livesin_exists(v2, v0, r), Rule(r), Rule(284).
Ilivesin(v0, v1) :- livesin(v1, v2), livesin(v0, v2), Rule(285).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), livesin(v0, v2), r = 285, Rule(285).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), livesin(v0, v2), Rule(r), Rule(285).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), livesin_exists(v0, v2, r), Rule(r), Rule(285).
Ilivesin(v0, v1) :- livesin(v0, v1), wasbornin(v0, v1), Rule(286).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), wasbornin(v0, v1), r = 286, Rule(286).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), wasbornin(v0, v1), Rule(r), Rule(286).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), wasbornin_exists(v0, v1, r), Rule(r), Rule(286).
Ilivesin(v0, v1) :- livesin(v0, v1), wasbornin(v1, v0), Rule(287).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), wasbornin(v1, v0), r = 287, Rule(287).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), wasbornin(v1, v0), Rule(r), Rule(287).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), wasbornin_exists(v1, v0, r), Rule(r), Rule(287).
Ilivesin(v0, v1) :- livesin(v1, v0), wasbornin(v1, v0), Rule(288).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), wasbornin(v1, v0), r = 288, Rule(288).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), wasbornin(v1, v0), Rule(r), Rule(288).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), wasbornin_exists(v1, v0, r), Rule(r), Rule(288).
Ilivesin(v0, v1) :- livesin(v1, v0), wasbornin(v0, v1), Rule(289).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), wasbornin(v0, v1), r = 289, Rule(289).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), wasbornin(v0, v1), Rule(r), Rule(289).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), wasbornin_exists(v0, v1, r), Rule(r), Rule(289).
Ilivesin(v0, v1) :- livesin(v2, v1), wasbornin(v0, v2), Rule(290).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), wasbornin(v0, v2), r = 290, Rule(290).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), wasbornin(v0, v2), Rule(r), Rule(290).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), wasbornin_exists(v0, v2, r), Rule(r), Rule(290).
Ilivesin(v0, v1) :- livesin(v1, v2), wasbornin(v2, v0), Rule(291).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), wasbornin(v2, v0), r = 291, Rule(291).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), wasbornin(v2, v0), Rule(r), Rule(291).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), wasbornin_exists(v2, v0, r), Rule(r), Rule(291).
Ilivesin(v0, v1) :- livesin(v2, v0), wasbornin(v1, v2), Rule(292).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), wasbornin(v1, v2), r = 292, Rule(292).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), wasbornin(v1, v2), Rule(r), Rule(292).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), wasbornin_exists(v1, v2, r), Rule(r), Rule(292).
Ilivesin(v0, v1) :- livesin(v2, v0), wasbornin(v2, v1), Rule(293).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), wasbornin(v2, v1), r = 293, Rule(293).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), wasbornin(v2, v1), Rule(r), Rule(293).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), wasbornin_exists(v2, v1, r), Rule(r), Rule(293).
Ilivesin(v0, v1) :- livesin(v0, v2), wasbornin(v1, v2), Rule(294).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), wasbornin(v1, v2), r = 294, Rule(294).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), wasbornin(v1, v2), Rule(r), Rule(294).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), wasbornin_exists(v1, v2, r), Rule(r), Rule(294).
Ilivesin(v0, v1) :- livesin(v0, v2), wasbornin(v2, v1), Rule(295).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), wasbornin(v2, v1), r = 295, Rule(295).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), wasbornin(v2, v1), Rule(r), Rule(295).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), wasbornin_exists(v2, v1, r), Rule(r), Rule(295).
Ilivesin(v0, v1) :- livesin(v2, v1), wasbornin(v2, v0), Rule(296).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), wasbornin(v2, v0), r = 296, Rule(296).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), wasbornin(v2, v0), Rule(r), Rule(296).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), wasbornin_exists(v2, v0, r), Rule(r), Rule(296).
Ilivesin(v0, v1) :- livesin(v1, v2), wasbornin(v0, v2), Rule(297).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), wasbornin(v0, v2), r = 297, Rule(297).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), wasbornin(v0, v2), Rule(r), Rule(297).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), wasbornin_exists(v0, v2, r), Rule(r), Rule(297).
Ilivesin(v0, v1) :- livesin(v0, v1), IIlivesin(v0, v1), Rule(298).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin(v0, v1), r = 298, Rule(298).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(298).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(298).
Ilivesin(v0, v1) :- livesin(v0, v1), IIlivesin(v1, v0), Rule(299).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin(v1, v0), r = 299, Rule(299).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(299).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(299).
Ilivesin(v0, v1) :- livesin(v1, v0), IIlivesin(v1, v0), Rule(300).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin(v1, v0), r = 300, Rule(300).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(300).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(300).
Ilivesin(v0, v1) :- livesin(v1, v0), IIlivesin(v0, v1), Rule(301).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin(v0, v1), r = 301, Rule(301).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(301).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(301).
Ilivesin(v0, v1) :- livesin(v2, v1), IIlivesin(v0, v2), Rule(302).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin(v0, v2), r = 302, Rule(302).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(302).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(302).
Ilivesin(v0, v1) :- livesin(v1, v2), IIlivesin(v2, v0), Rule(303).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin(v2, v0), r = 303, Rule(303).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(303).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(303).
Ilivesin(v0, v1) :- livesin(v2, v0), IIlivesin(v1, v2), Rule(304).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin(v1, v2), r = 304, Rule(304).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(304).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(304).
Ilivesin(v0, v1) :- livesin(v2, v0), IIlivesin(v2, v1), Rule(305).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin(v2, v1), r = 305, Rule(305).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(305).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(305).
Ilivesin(v0, v1) :- livesin(v0, v2), IIlivesin(v1, v2), Rule(306).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin(v1, v2), r = 306, Rule(306).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(306).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(306).
Ilivesin(v0, v1) :- livesin(v0, v2), IIlivesin(v2, v1), Rule(307).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin(v2, v1), r = 307, Rule(307).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(307).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(307).
Ilivesin(v0, v1) :- livesin(v2, v1), IIlivesin(v2, v0), Rule(308).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin(v2, v0), r = 308, Rule(308).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(308).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(308).
Ilivesin(v0, v1) :- livesin(v1, v2), IIlivesin(v0, v2), Rule(309).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin(v0, v2), r = 309, Rule(309).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(309).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(309).
Ilivesin(v0, v1) :- livesin(v0, v1), inv_0(v0, v1), Rule(310).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), inv_0(v0, v1), r = 310, Rule(310).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(310).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(310).
Ilivesin(v0, v1) :- livesin(v0, v1), inv_0(v1, v0), Rule(311).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), inv_0(v1, v0), r = 311, Rule(311).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(311).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(311).
Ilivesin(v0, v1) :- livesin(v1, v0), inv_0(v1, v0), Rule(312).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), inv_0(v1, v0), r = 312, Rule(312).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(312).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(312).
Ilivesin(v0, v1) :- livesin(v1, v0), inv_0(v0, v1), Rule(313).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), inv_0(v0, v1), r = 313, Rule(313).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(313).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(313).
Ilivesin(v0, v1) :- livesin(v2, v1), inv_0(v0, v2), Rule(314).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), inv_0(v0, v2), r = 314, Rule(314).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(314).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(314).
Ilivesin(v0, v1) :- livesin(v1, v2), inv_0(v2, v0), Rule(315).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), inv_0(v2, v0), r = 315, Rule(315).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(315).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(315).
Ilivesin(v0, v1) :- livesin(v2, v0), inv_0(v1, v2), Rule(316).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), inv_0(v1, v2), r = 316, Rule(316).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(316).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(316).
Ilivesin(v0, v1) :- livesin(v2, v0), inv_0(v2, v1), Rule(317).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), inv_0(v2, v1), r = 317, Rule(317).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(317).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(317).
Ilivesin(v0, v1) :- livesin(v0, v2), inv_0(v1, v2), Rule(318).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), inv_0(v1, v2), r = 318, Rule(318).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(318).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(318).
Ilivesin(v0, v1) :- livesin(v0, v2), inv_0(v2, v1), Rule(319).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), inv_0(v2, v1), r = 319, Rule(319).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(319).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(319).
Ilivesin(v0, v1) :- livesin(v2, v1), inv_0(v2, v0), Rule(320).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), inv_0(v2, v0), r = 320, Rule(320).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(320).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(320).
Ilivesin(v0, v1) :- livesin(v1, v2), inv_0(v0, v2), Rule(321).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), inv_0(v0, v2), r = 321, Rule(321).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(321).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(321).
Ilivesin(v0, v1) :- livesin(v0, v1), Ilivesin(v0, v1), Rule(322).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), Ilivesin(v0, v1), r = 322, Rule(322).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), Ilivesin(v0, v1), Rule(r), Rule(322).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), Ilivesin_exists(v0, v1, r), Rule(r), Rule(322).
Ilivesin(v0, v1) :- livesin(v0, v1), Ilivesin(v1, v0), Rule(323).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), Ilivesin(v1, v0), r = 323, Rule(323).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v1, r), Ilivesin(v1, v0), Rule(r), Rule(323).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v1), Ilivesin_exists(v1, v0, r), Rule(r), Rule(323).
Ilivesin(v0, v1) :- livesin(v1, v0), Ilivesin(v1, v0), Rule(324).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), Ilivesin(v1, v0), r = 324, Rule(324).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), Ilivesin(v1, v0), Rule(r), Rule(324).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), Ilivesin_exists(v1, v0, r), Rule(r), Rule(324).
Ilivesin(v0, v1) :- livesin(v1, v0), Ilivesin(v0, v1), Rule(325).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), Ilivesin(v0, v1), r = 325, Rule(325).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v0, r), Ilivesin(v0, v1), Rule(r), Rule(325).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v0), Ilivesin_exists(v0, v1, r), Rule(r), Rule(325).
Ilivesin(v0, v1) :- livesin(v2, v1), Ilivesin(v0, v2), Rule(326).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), Ilivesin(v0, v2), r = 326, Rule(326).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), Ilivesin(v0, v2), Rule(r), Rule(326).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), Ilivesin_exists(v0, v2, r), Rule(r), Rule(326).
Ilivesin(v0, v1) :- livesin(v1, v2), Ilivesin(v2, v0), Rule(327).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), Ilivesin(v2, v0), r = 327, Rule(327).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), Ilivesin(v2, v0), Rule(r), Rule(327).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), Ilivesin_exists(v2, v0, r), Rule(r), Rule(327).
Ilivesin(v0, v1) :- livesin(v2, v0), Ilivesin(v1, v2), Rule(328).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), Ilivesin(v1, v2), r = 328, Rule(328).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), Ilivesin(v1, v2), Rule(r), Rule(328).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), Ilivesin_exists(v1, v2, r), Rule(r), Rule(328).
Ilivesin(v0, v1) :- livesin(v2, v0), Ilivesin(v2, v1), Rule(329).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), Ilivesin(v2, v1), r = 329, Rule(329).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v0, r), Ilivesin(v2, v1), Rule(r), Rule(329).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v0), Ilivesin_exists(v2, v1, r), Rule(r), Rule(329).
Ilivesin(v0, v1) :- livesin(v0, v2), Ilivesin(v1, v2), Rule(330).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), Ilivesin(v1, v2), r = 330, Rule(330).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), Ilivesin(v1, v2), Rule(r), Rule(330).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), Ilivesin_exists(v1, v2, r), Rule(r), Rule(330).
Ilivesin(v0, v1) :- livesin(v0, v2), Ilivesin(v2, v1), Rule(331).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), Ilivesin(v2, v1), r = 331, Rule(331).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v0, v2, r), Ilivesin(v2, v1), Rule(r), Rule(331).
Ilivesin_exists(v0, v1, r) :- livesin(v0, v2), Ilivesin_exists(v2, v1, r), Rule(r), Rule(331).
Ilivesin(v0, v1) :- livesin(v2, v1), Ilivesin(v2, v0), Rule(332).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), Ilivesin(v2, v0), r = 332, Rule(332).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v2, v1, r), Ilivesin(v2, v0), Rule(r), Rule(332).
Ilivesin_exists(v0, v1, r) :- livesin(v2, v1), Ilivesin_exists(v2, v0, r), Rule(r), Rule(332).
Ilivesin(v0, v1) :- livesin(v1, v2), Ilivesin(v0, v2), Rule(333).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), Ilivesin(v0, v2), r = 333, Rule(333).
Ilivesin_exists(v0, v1, r) :- livesin_exists(v1, v2, r), Ilivesin(v0, v2), Rule(r), Rule(333).
Ilivesin_exists(v0, v1, r) :- livesin(v1, v2), Ilivesin_exists(v0, v2, r), Rule(r), Rule(333).
Ilivesin(v0, v1) :- wasbornin(v0, v1), wasbornin(v0, v1), Rule(334).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin(v0, v1), r = 334, Rule(334).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), wasbornin(v0, v1), Rule(r), Rule(334).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin_exists(v0, v1, r), Rule(r), Rule(334).
Ilivesin(v0, v1) :- wasbornin(v0, v1), wasbornin(v1, v0), Rule(335).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin(v1, v0), r = 335, Rule(335).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), wasbornin(v1, v0), Rule(r), Rule(335).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), wasbornin_exists(v1, v0, r), Rule(r), Rule(335).
Ilivesin(v0, v1) :- wasbornin(v1, v0), wasbornin(v1, v0), Rule(336).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin(v1, v0), r = 336, Rule(336).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), wasbornin(v1, v0), Rule(r), Rule(336).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin_exists(v1, v0, r), Rule(r), Rule(336).
Ilivesin(v0, v1) :- wasbornin(v1, v0), wasbornin(v0, v1), Rule(337).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin(v0, v1), r = 337, Rule(337).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), wasbornin(v0, v1), Rule(r), Rule(337).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), wasbornin_exists(v0, v1, r), Rule(r), Rule(337).
Ilivesin(v0, v1) :- wasbornin(v2, v1), wasbornin(v0, v2), Rule(338).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin(v0, v2), r = 338, Rule(338).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), wasbornin(v0, v2), Rule(r), Rule(338).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin_exists(v0, v2, r), Rule(r), Rule(338).
Ilivesin(v0, v1) :- wasbornin(v1, v2), wasbornin(v2, v0), Rule(339).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin(v2, v0), r = 339, Rule(339).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), wasbornin(v2, v0), Rule(r), Rule(339).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin_exists(v2, v0, r), Rule(r), Rule(339).
Ilivesin(v0, v1) :- wasbornin(v2, v0), wasbornin(v1, v2), Rule(340).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin(v1, v2), r = 340, Rule(340).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), wasbornin(v1, v2), Rule(r), Rule(340).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin_exists(v1, v2, r), Rule(r), Rule(340).
Ilivesin(v0, v1) :- wasbornin(v2, v0), wasbornin(v2, v1), Rule(341).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin(v2, v1), r = 341, Rule(341).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), wasbornin(v2, v1), Rule(r), Rule(341).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), wasbornin_exists(v2, v1, r), Rule(r), Rule(341).
Ilivesin(v0, v1) :- wasbornin(v0, v2), wasbornin(v1, v2), Rule(342).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin(v1, v2), r = 342, Rule(342).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), wasbornin(v1, v2), Rule(r), Rule(342).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin_exists(v1, v2, r), Rule(r), Rule(342).
Ilivesin(v0, v1) :- wasbornin(v0, v2), wasbornin(v2, v1), Rule(343).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin(v2, v1), r = 343, Rule(343).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), wasbornin(v2, v1), Rule(r), Rule(343).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), wasbornin_exists(v2, v1, r), Rule(r), Rule(343).
Ilivesin(v0, v1) :- wasbornin(v2, v1), wasbornin(v2, v0), Rule(344).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin(v2, v0), r = 344, Rule(344).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), wasbornin(v2, v0), Rule(r), Rule(344).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), wasbornin_exists(v2, v0, r), Rule(r), Rule(344).
Ilivesin(v0, v1) :- wasbornin(v1, v2), wasbornin(v0, v2), Rule(345).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin(v0, v2), r = 345, Rule(345).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), wasbornin(v0, v2), Rule(r), Rule(345).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), wasbornin_exists(v0, v2, r), Rule(r), Rule(345).
Ilivesin(v0, v1) :- wasbornin(v0, v1), IIlivesin(v0, v1), Rule(346).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin(v0, v1), r = 346, Rule(346).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(346).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(346).
Ilivesin(v0, v1) :- wasbornin(v0, v1), IIlivesin(v1, v0), Rule(347).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin(v1, v0), r = 347, Rule(347).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(347).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(347).
Ilivesin(v0, v1) :- wasbornin(v1, v0), IIlivesin(v1, v0), Rule(348).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin(v1, v0), r = 348, Rule(348).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(348).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(348).
Ilivesin(v0, v1) :- wasbornin(v1, v0), IIlivesin(v0, v1), Rule(349).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin(v0, v1), r = 349, Rule(349).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(349).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(349).
Ilivesin(v0, v1) :- wasbornin(v2, v1), IIlivesin(v0, v2), Rule(350).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin(v0, v2), r = 350, Rule(350).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(350).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(350).
Ilivesin(v0, v1) :- wasbornin(v1, v2), IIlivesin(v2, v0), Rule(351).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin(v2, v0), r = 351, Rule(351).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(351).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(351).
Ilivesin(v0, v1) :- wasbornin(v2, v0), IIlivesin(v1, v2), Rule(352).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin(v1, v2), r = 352, Rule(352).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(352).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(352).
Ilivesin(v0, v1) :- wasbornin(v2, v0), IIlivesin(v2, v1), Rule(353).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin(v2, v1), r = 353, Rule(353).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(353).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(353).
Ilivesin(v0, v1) :- wasbornin(v0, v2), IIlivesin(v1, v2), Rule(354).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin(v1, v2), r = 354, Rule(354).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(354).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(354).
Ilivesin(v0, v1) :- wasbornin(v0, v2), IIlivesin(v2, v1), Rule(355).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin(v2, v1), r = 355, Rule(355).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(355).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(355).
Ilivesin(v0, v1) :- wasbornin(v2, v1), IIlivesin(v2, v0), Rule(356).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin(v2, v0), r = 356, Rule(356).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(356).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(356).
Ilivesin(v0, v1) :- wasbornin(v1, v2), IIlivesin(v0, v2), Rule(357).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin(v0, v2), r = 357, Rule(357).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(357).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(357).
Ilivesin(v0, v1) :- wasbornin(v0, v1), inv_0(v0, v1), Rule(358).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0(v0, v1), r = 358, Rule(358).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(358).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(358).
Ilivesin(v0, v1) :- wasbornin(v0, v1), inv_0(v1, v0), Rule(359).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0(v1, v0), r = 359, Rule(359).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(359).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(359).
Ilivesin(v0, v1) :- wasbornin(v1, v0), inv_0(v1, v0), Rule(360).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0(v1, v0), r = 360, Rule(360).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(360).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(360).
Ilivesin(v0, v1) :- wasbornin(v1, v0), inv_0(v0, v1), Rule(361).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0(v0, v1), r = 361, Rule(361).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(361).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(361).
Ilivesin(v0, v1) :- wasbornin(v2, v1), inv_0(v0, v2), Rule(362).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0(v0, v2), r = 362, Rule(362).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(362).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(362).
Ilivesin(v0, v1) :- wasbornin(v1, v2), inv_0(v2, v0), Rule(363).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0(v2, v0), r = 363, Rule(363).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(363).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(363).
Ilivesin(v0, v1) :- wasbornin(v2, v0), inv_0(v1, v2), Rule(364).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0(v1, v2), r = 364, Rule(364).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(364).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(364).
Ilivesin(v0, v1) :- wasbornin(v2, v0), inv_0(v2, v1), Rule(365).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0(v2, v1), r = 365, Rule(365).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(365).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(365).
Ilivesin(v0, v1) :- wasbornin(v0, v2), inv_0(v1, v2), Rule(366).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0(v1, v2), r = 366, Rule(366).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(366).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(366).
Ilivesin(v0, v1) :- wasbornin(v0, v2), inv_0(v2, v1), Rule(367).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0(v2, v1), r = 367, Rule(367).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(367).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(367).
Ilivesin(v0, v1) :- wasbornin(v2, v1), inv_0(v2, v0), Rule(368).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0(v2, v0), r = 368, Rule(368).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(368).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(368).
Ilivesin(v0, v1) :- wasbornin(v1, v2), inv_0(v0, v2), Rule(369).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0(v0, v2), r = 369, Rule(369).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(369).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(369).
Ilivesin(v0, v1) :- wasbornin(v0, v1), Ilivesin(v0, v1), Rule(370).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), Ilivesin(v0, v1), r = 370, Rule(370).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), Ilivesin(v0, v1), Rule(r), Rule(370).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), Ilivesin_exists(v0, v1, r), Rule(r), Rule(370).
Ilivesin(v0, v1) :- wasbornin(v0, v1), Ilivesin(v1, v0), Rule(371).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), Ilivesin(v1, v0), r = 371, Rule(371).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v1, r), Ilivesin(v1, v0), Rule(r), Rule(371).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v1), Ilivesin_exists(v1, v0, r), Rule(r), Rule(371).
Ilivesin(v0, v1) :- wasbornin(v1, v0), Ilivesin(v1, v0), Rule(372).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), Ilivesin(v1, v0), r = 372, Rule(372).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), Ilivesin(v1, v0), Rule(r), Rule(372).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), Ilivesin_exists(v1, v0, r), Rule(r), Rule(372).
Ilivesin(v0, v1) :- wasbornin(v1, v0), Ilivesin(v0, v1), Rule(373).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), Ilivesin(v0, v1), r = 373, Rule(373).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v0, r), Ilivesin(v0, v1), Rule(r), Rule(373).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v0), Ilivesin_exists(v0, v1, r), Rule(r), Rule(373).
Ilivesin(v0, v1) :- wasbornin(v2, v1), Ilivesin(v0, v2), Rule(374).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), Ilivesin(v0, v2), r = 374, Rule(374).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), Ilivesin(v0, v2), Rule(r), Rule(374).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), Ilivesin_exists(v0, v2, r), Rule(r), Rule(374).
Ilivesin(v0, v1) :- wasbornin(v1, v2), Ilivesin(v2, v0), Rule(375).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), Ilivesin(v2, v0), r = 375, Rule(375).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), Ilivesin(v2, v0), Rule(r), Rule(375).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), Ilivesin_exists(v2, v0, r), Rule(r), Rule(375).
Ilivesin(v0, v1) :- wasbornin(v2, v0), Ilivesin(v1, v2), Rule(376).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), Ilivesin(v1, v2), r = 376, Rule(376).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), Ilivesin(v1, v2), Rule(r), Rule(376).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), Ilivesin_exists(v1, v2, r), Rule(r), Rule(376).
Ilivesin(v0, v1) :- wasbornin(v2, v0), Ilivesin(v2, v1), Rule(377).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), Ilivesin(v2, v1), r = 377, Rule(377).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v0, r), Ilivesin(v2, v1), Rule(r), Rule(377).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v0), Ilivesin_exists(v2, v1, r), Rule(r), Rule(377).
Ilivesin(v0, v1) :- wasbornin(v0, v2), Ilivesin(v1, v2), Rule(378).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), Ilivesin(v1, v2), r = 378, Rule(378).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), Ilivesin(v1, v2), Rule(r), Rule(378).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), Ilivesin_exists(v1, v2, r), Rule(r), Rule(378).
Ilivesin(v0, v1) :- wasbornin(v0, v2), Ilivesin(v2, v1), Rule(379).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), Ilivesin(v2, v1), r = 379, Rule(379).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v0, v2, r), Ilivesin(v2, v1), Rule(r), Rule(379).
Ilivesin_exists(v0, v1, r) :- wasbornin(v0, v2), Ilivesin_exists(v2, v1, r), Rule(r), Rule(379).
Ilivesin(v0, v1) :- wasbornin(v2, v1), Ilivesin(v2, v0), Rule(380).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), Ilivesin(v2, v0), r = 380, Rule(380).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v2, v1, r), Ilivesin(v2, v0), Rule(r), Rule(380).
Ilivesin_exists(v0, v1, r) :- wasbornin(v2, v1), Ilivesin_exists(v2, v0, r), Rule(r), Rule(380).
Ilivesin(v0, v1) :- wasbornin(v1, v2), Ilivesin(v0, v2), Rule(381).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), Ilivesin(v0, v2), r = 381, Rule(381).
Ilivesin_exists(v0, v1, r) :- wasbornin_exists(v1, v2, r), Ilivesin(v0, v2), Rule(r), Rule(381).
Ilivesin_exists(v0, v1, r) :- wasbornin(v1, v2), Ilivesin_exists(v0, v2, r), Rule(r), Rule(381).
Ilivesin(v0, v1) :- IIlivesin(v0, v1), IIlivesin(v0, v1), Rule(382).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin(v0, v1), r = 382, Rule(382).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), IIlivesin(v0, v1), Rule(r), Rule(382).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin_exists(v0, v1, r), Rule(r), Rule(382).
Ilivesin(v0, v1) :- IIlivesin(v0, v1), IIlivesin(v1, v0), Rule(383).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin(v1, v0), r = 383, Rule(383).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), IIlivesin(v1, v0), Rule(r), Rule(383).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), IIlivesin_exists(v1, v0, r), Rule(r), Rule(383).
Ilivesin(v0, v1) :- IIlivesin(v1, v0), IIlivesin(v1, v0), Rule(384).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin(v1, v0), r = 384, Rule(384).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), IIlivesin(v1, v0), Rule(r), Rule(384).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin_exists(v1, v0, r), Rule(r), Rule(384).
Ilivesin(v0, v1) :- IIlivesin(v1, v0), IIlivesin(v0, v1), Rule(385).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin(v0, v1), r = 385, Rule(385).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), IIlivesin(v0, v1), Rule(r), Rule(385).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), IIlivesin_exists(v0, v1, r), Rule(r), Rule(385).
Ilivesin(v0, v1) :- IIlivesin(v2, v1), IIlivesin(v0, v2), Rule(386).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin(v0, v2), r = 386, Rule(386).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), IIlivesin(v0, v2), Rule(r), Rule(386).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin_exists(v0, v2, r), Rule(r), Rule(386).
Ilivesin(v0, v1) :- IIlivesin(v1, v2), IIlivesin(v2, v0), Rule(387).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin(v2, v0), r = 387, Rule(387).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), IIlivesin(v2, v0), Rule(r), Rule(387).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin_exists(v2, v0, r), Rule(r), Rule(387).
Ilivesin(v0, v1) :- IIlivesin(v2, v0), IIlivesin(v1, v2), Rule(388).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin(v1, v2), r = 388, Rule(388).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), IIlivesin(v1, v2), Rule(r), Rule(388).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin_exists(v1, v2, r), Rule(r), Rule(388).
Ilivesin(v0, v1) :- IIlivesin(v2, v0), IIlivesin(v2, v1), Rule(389).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin(v2, v1), r = 389, Rule(389).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), IIlivesin(v2, v1), Rule(r), Rule(389).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), IIlivesin_exists(v2, v1, r), Rule(r), Rule(389).
Ilivesin(v0, v1) :- IIlivesin(v0, v2), IIlivesin(v1, v2), Rule(390).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin(v1, v2), r = 390, Rule(390).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), IIlivesin(v1, v2), Rule(r), Rule(390).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin_exists(v1, v2, r), Rule(r), Rule(390).
Ilivesin(v0, v1) :- IIlivesin(v0, v2), IIlivesin(v2, v1), Rule(391).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin(v2, v1), r = 391, Rule(391).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), IIlivesin(v2, v1), Rule(r), Rule(391).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), IIlivesin_exists(v2, v1, r), Rule(r), Rule(391).
Ilivesin(v0, v1) :- IIlivesin(v2, v1), IIlivesin(v2, v0), Rule(392).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin(v2, v0), r = 392, Rule(392).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), IIlivesin(v2, v0), Rule(r), Rule(392).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), IIlivesin_exists(v2, v0, r), Rule(r), Rule(392).
Ilivesin(v0, v1) :- IIlivesin(v1, v2), IIlivesin(v0, v2), Rule(393).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin(v0, v2), r = 393, Rule(393).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), IIlivesin(v0, v2), Rule(r), Rule(393).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), IIlivesin_exists(v0, v2, r), Rule(r), Rule(393).
Ilivesin(v0, v1) :- IIlivesin(v0, v1), inv_0(v0, v1), Rule(394).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0(v0, v1), r = 394, Rule(394).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(394).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(394).
Ilivesin(v0, v1) :- IIlivesin(v0, v1), inv_0(v1, v0), Rule(395).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0(v1, v0), r = 395, Rule(395).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(395).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(395).
Ilivesin(v0, v1) :- IIlivesin(v1, v0), inv_0(v1, v0), Rule(396).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0(v1, v0), r = 396, Rule(396).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(396).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(396).
Ilivesin(v0, v1) :- IIlivesin(v1, v0), inv_0(v0, v1), Rule(397).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0(v0, v1), r = 397, Rule(397).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(397).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(397).
Ilivesin(v0, v1) :- IIlivesin(v2, v1), inv_0(v0, v2), Rule(398).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0(v0, v2), r = 398, Rule(398).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(398).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(398).
Ilivesin(v0, v1) :- IIlivesin(v1, v2), inv_0(v2, v0), Rule(399).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0(v2, v0), r = 399, Rule(399).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(399).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(399).
Ilivesin(v0, v1) :- IIlivesin(v2, v0), inv_0(v1, v2), Rule(400).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0(v1, v2), r = 400, Rule(400).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(400).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(400).
Ilivesin(v0, v1) :- IIlivesin(v2, v0), inv_0(v2, v1), Rule(401).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0(v2, v1), r = 401, Rule(401).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(401).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(401).
Ilivesin(v0, v1) :- IIlivesin(v0, v2), inv_0(v1, v2), Rule(402).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0(v1, v2), r = 402, Rule(402).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(402).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(402).
Ilivesin(v0, v1) :- IIlivesin(v0, v2), inv_0(v2, v1), Rule(403).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0(v2, v1), r = 403, Rule(403).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(403).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(403).
Ilivesin(v0, v1) :- IIlivesin(v2, v1), inv_0(v2, v0), Rule(404).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0(v2, v0), r = 404, Rule(404).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(404).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(404).
Ilivesin(v0, v1) :- IIlivesin(v1, v2), inv_0(v0, v2), Rule(405).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0(v0, v2), r = 405, Rule(405).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(405).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(405).
Ilivesin(v0, v1) :- IIlivesin(v0, v1), Ilivesin(v0, v1), Rule(406).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), Ilivesin(v0, v1), r = 406, Rule(406).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), Ilivesin(v0, v1), Rule(r), Rule(406).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), Ilivesin_exists(v0, v1, r), Rule(r), Rule(406).
Ilivesin(v0, v1) :- IIlivesin(v0, v1), Ilivesin(v1, v0), Rule(407).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), Ilivesin(v1, v0), r = 407, Rule(407).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v1, r), Ilivesin(v1, v0), Rule(r), Rule(407).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v1), Ilivesin_exists(v1, v0, r), Rule(r), Rule(407).
Ilivesin(v0, v1) :- IIlivesin(v1, v0), Ilivesin(v1, v0), Rule(408).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), Ilivesin(v1, v0), r = 408, Rule(408).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), Ilivesin(v1, v0), Rule(r), Rule(408).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), Ilivesin_exists(v1, v0, r), Rule(r), Rule(408).
Ilivesin(v0, v1) :- IIlivesin(v1, v0), Ilivesin(v0, v1), Rule(409).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), Ilivesin(v0, v1), r = 409, Rule(409).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v0, r), Ilivesin(v0, v1), Rule(r), Rule(409).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v0), Ilivesin_exists(v0, v1, r), Rule(r), Rule(409).
Ilivesin(v0, v1) :- IIlivesin(v2, v1), Ilivesin(v0, v2), Rule(410).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), Ilivesin(v0, v2), r = 410, Rule(410).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), Ilivesin(v0, v2), Rule(r), Rule(410).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), Ilivesin_exists(v0, v2, r), Rule(r), Rule(410).
Ilivesin(v0, v1) :- IIlivesin(v1, v2), Ilivesin(v2, v0), Rule(411).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), Ilivesin(v2, v0), r = 411, Rule(411).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), Ilivesin(v2, v0), Rule(r), Rule(411).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), Ilivesin_exists(v2, v0, r), Rule(r), Rule(411).
Ilivesin(v0, v1) :- IIlivesin(v2, v0), Ilivesin(v1, v2), Rule(412).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), Ilivesin(v1, v2), r = 412, Rule(412).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), Ilivesin(v1, v2), Rule(r), Rule(412).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), Ilivesin_exists(v1, v2, r), Rule(r), Rule(412).
Ilivesin(v0, v1) :- IIlivesin(v2, v0), Ilivesin(v2, v1), Rule(413).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), Ilivesin(v2, v1), r = 413, Rule(413).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v0, r), Ilivesin(v2, v1), Rule(r), Rule(413).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v0), Ilivesin_exists(v2, v1, r), Rule(r), Rule(413).
Ilivesin(v0, v1) :- IIlivesin(v0, v2), Ilivesin(v1, v2), Rule(414).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), Ilivesin(v1, v2), r = 414, Rule(414).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), Ilivesin(v1, v2), Rule(r), Rule(414).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), Ilivesin_exists(v1, v2, r), Rule(r), Rule(414).
Ilivesin(v0, v1) :- IIlivesin(v0, v2), Ilivesin(v2, v1), Rule(415).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), Ilivesin(v2, v1), r = 415, Rule(415).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v0, v2, r), Ilivesin(v2, v1), Rule(r), Rule(415).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v0, v2), Ilivesin_exists(v2, v1, r), Rule(r), Rule(415).
Ilivesin(v0, v1) :- IIlivesin(v2, v1), Ilivesin(v2, v0), Rule(416).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), Ilivesin(v2, v0), r = 416, Rule(416).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v2, v1, r), Ilivesin(v2, v0), Rule(r), Rule(416).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v2, v1), Ilivesin_exists(v2, v0, r), Rule(r), Rule(416).
Ilivesin(v0, v1) :- IIlivesin(v1, v2), Ilivesin(v0, v2), Rule(417).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), Ilivesin(v0, v2), r = 417, Rule(417).
Ilivesin_exists(v0, v1, r) :- IIlivesin_exists(v1, v2, r), Ilivesin(v0, v2), Rule(r), Rule(417).
Ilivesin_exists(v0, v1, r) :- IIlivesin(v1, v2), Ilivesin_exists(v0, v2, r), Rule(r), Rule(417).
Ilivesin(v0, v1) :- inv_0(v0, v1), inv_0(v0, v1), Rule(418).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), inv_0(v0, v1), r = 418, Rule(418).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), inv_0(v0, v1), Rule(r), Rule(418).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), inv_0_exists(v0, v1, r), Rule(r), Rule(418).
Ilivesin(v0, v1) :- inv_0(v0, v1), inv_0(v1, v0), Rule(419).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), inv_0(v1, v0), r = 419, Rule(419).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), inv_0(v1, v0), Rule(r), Rule(419).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), inv_0_exists(v1, v0, r), Rule(r), Rule(419).
Ilivesin(v0, v1) :- inv_0(v1, v0), inv_0(v1, v0), Rule(420).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), inv_0(v1, v0), r = 420, Rule(420).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), inv_0(v1, v0), Rule(r), Rule(420).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), inv_0_exists(v1, v0, r), Rule(r), Rule(420).
Ilivesin(v0, v1) :- inv_0(v1, v0), inv_0(v0, v1), Rule(421).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), inv_0(v0, v1), r = 421, Rule(421).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), inv_0(v0, v1), Rule(r), Rule(421).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), inv_0_exists(v0, v1, r), Rule(r), Rule(421).
Ilivesin(v0, v1) :- inv_0(v2, v1), inv_0(v0, v2), Rule(422).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), inv_0(v0, v2), r = 422, Rule(422).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v1, r), inv_0(v0, v2), Rule(r), Rule(422).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), inv_0_exists(v0, v2, r), Rule(r), Rule(422).
Ilivesin(v0, v1) :- inv_0(v1, v2), inv_0(v2, v0), Rule(423).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), inv_0(v2, v0), r = 423, Rule(423).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v2, r), inv_0(v2, v0), Rule(r), Rule(423).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), inv_0_exists(v2, v0, r), Rule(r), Rule(423).
Ilivesin(v0, v1) :- inv_0(v2, v0), inv_0(v1, v2), Rule(424).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), inv_0(v1, v2), r = 424, Rule(424).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v0, r), inv_0(v1, v2), Rule(r), Rule(424).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), inv_0_exists(v1, v2, r), Rule(r), Rule(424).
Ilivesin(v0, v1) :- inv_0(v2, v0), inv_0(v2, v1), Rule(425).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), inv_0(v2, v1), r = 425, Rule(425).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v0, r), inv_0(v2, v1), Rule(r), Rule(425).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), inv_0_exists(v2, v1, r), Rule(r), Rule(425).
Ilivesin(v0, v1) :- inv_0(v0, v2), inv_0(v1, v2), Rule(426).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), inv_0(v1, v2), r = 426, Rule(426).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v2, r), inv_0(v1, v2), Rule(r), Rule(426).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), inv_0_exists(v1, v2, r), Rule(r), Rule(426).
Ilivesin(v0, v1) :- inv_0(v0, v2), inv_0(v2, v1), Rule(427).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), inv_0(v2, v1), r = 427, Rule(427).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v2, r), inv_0(v2, v1), Rule(r), Rule(427).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), inv_0_exists(v2, v1, r), Rule(r), Rule(427).
Ilivesin(v0, v1) :- inv_0(v2, v1), inv_0(v2, v0), Rule(428).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), inv_0(v2, v0), r = 428, Rule(428).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v1, r), inv_0(v2, v0), Rule(r), Rule(428).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), inv_0_exists(v2, v0, r), Rule(r), Rule(428).
Ilivesin(v0, v1) :- inv_0(v1, v2), inv_0(v0, v2), Rule(429).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), inv_0(v0, v2), r = 429, Rule(429).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v2, r), inv_0(v0, v2), Rule(r), Rule(429).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), inv_0_exists(v0, v2, r), Rule(r), Rule(429).
Ilivesin(v0, v1) :- inv_0(v0, v1), Ilivesin(v0, v1), Rule(430).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), Ilivesin(v0, v1), r = 430, Rule(430).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), Ilivesin(v0, v1), Rule(r), Rule(430).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), Ilivesin_exists(v0, v1, r), Rule(r), Rule(430).
Ilivesin(v0, v1) :- inv_0(v0, v1), Ilivesin(v1, v0), Rule(431).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), Ilivesin(v1, v0), r = 431, Rule(431).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v1, r), Ilivesin(v1, v0), Rule(r), Rule(431).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v1), Ilivesin_exists(v1, v0, r), Rule(r), Rule(431).
Ilivesin(v0, v1) :- inv_0(v1, v0), Ilivesin(v1, v0), Rule(432).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), Ilivesin(v1, v0), r = 432, Rule(432).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), Ilivesin(v1, v0), Rule(r), Rule(432).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), Ilivesin_exists(v1, v0, r), Rule(r), Rule(432).
Ilivesin(v0, v1) :- inv_0(v1, v0), Ilivesin(v0, v1), Rule(433).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), Ilivesin(v0, v1), r = 433, Rule(433).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v0, r), Ilivesin(v0, v1), Rule(r), Rule(433).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v0), Ilivesin_exists(v0, v1, r), Rule(r), Rule(433).
Ilivesin(v0, v1) :- inv_0(v2, v1), Ilivesin(v0, v2), Rule(434).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), Ilivesin(v0, v2), r = 434, Rule(434).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v1, r), Ilivesin(v0, v2), Rule(r), Rule(434).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), Ilivesin_exists(v0, v2, r), Rule(r), Rule(434).
Ilivesin(v0, v1) :- inv_0(v1, v2), Ilivesin(v2, v0), Rule(435).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), Ilivesin(v2, v0), r = 435, Rule(435).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v2, r), Ilivesin(v2, v0), Rule(r), Rule(435).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), Ilivesin_exists(v2, v0, r), Rule(r), Rule(435).
Ilivesin(v0, v1) :- inv_0(v2, v0), Ilivesin(v1, v2), Rule(436).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), Ilivesin(v1, v2), r = 436, Rule(436).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v0, r), Ilivesin(v1, v2), Rule(r), Rule(436).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), Ilivesin_exists(v1, v2, r), Rule(r), Rule(436).
Ilivesin(v0, v1) :- inv_0(v2, v0), Ilivesin(v2, v1), Rule(437).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), Ilivesin(v2, v1), r = 437, Rule(437).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v0, r), Ilivesin(v2, v1), Rule(r), Rule(437).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v0), Ilivesin_exists(v2, v1, r), Rule(r), Rule(437).
Ilivesin(v0, v1) :- inv_0(v0, v2), Ilivesin(v1, v2), Rule(438).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), Ilivesin(v1, v2), r = 438, Rule(438).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v2, r), Ilivesin(v1, v2), Rule(r), Rule(438).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), Ilivesin_exists(v1, v2, r), Rule(r), Rule(438).
Ilivesin(v0, v1) :- inv_0(v0, v2), Ilivesin(v2, v1), Rule(439).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), Ilivesin(v2, v1), r = 439, Rule(439).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v0, v2, r), Ilivesin(v2, v1), Rule(r), Rule(439).
Ilivesin_exists(v0, v1, r) :- inv_0(v0, v2), Ilivesin_exists(v2, v1, r), Rule(r), Rule(439).
Ilivesin(v0, v1) :- inv_0(v2, v1), Ilivesin(v2, v0), Rule(440).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), Ilivesin(v2, v0), r = 440, Rule(440).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v2, v1, r), Ilivesin(v2, v0), Rule(r), Rule(440).
Ilivesin_exists(v0, v1, r) :- inv_0(v2, v1), Ilivesin_exists(v2, v0, r), Rule(r), Rule(440).
Ilivesin(v0, v1) :- inv_0(v1, v2), Ilivesin(v0, v2), Rule(441).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), Ilivesin(v0, v2), r = 441, Rule(441).
Ilivesin_exists(v0, v1, r) :- inv_0_exists(v1, v2, r), Ilivesin(v0, v2), Rule(r), Rule(441).
Ilivesin_exists(v0, v1, r) :- inv_0(v1, v2), Ilivesin_exists(v0, v2, r), Rule(r), Rule(441).
Ilivesin(v0, v1) :- Ilivesin(v0, v1), Ilivesin(v0, v1), Rule(442).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v1), Ilivesin(v0, v1), r = 442, Rule(442).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v0, v1, r), Ilivesin(v0, v1), Rule(r), Rule(442).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v1), Ilivesin_exists(v0, v1, r), Rule(r), Rule(442).
Ilivesin(v0, v1) :- Ilivesin(v0, v1), Ilivesin(v1, v0), Rule(443).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v1), Ilivesin(v1, v0), r = 443, Rule(443).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v0, v1, r), Ilivesin(v1, v0), Rule(r), Rule(443).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v1), Ilivesin_exists(v1, v0, r), Rule(r), Rule(443).
Ilivesin(v0, v1) :- Ilivesin(v1, v0), Ilivesin(v1, v0), Rule(444).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v0), Ilivesin(v1, v0), r = 444, Rule(444).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v1, v0, r), Ilivesin(v1, v0), Rule(r), Rule(444).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v0), Ilivesin_exists(v1, v0, r), Rule(r), Rule(444).
Ilivesin(v0, v1) :- Ilivesin(v1, v0), Ilivesin(v0, v1), Rule(445).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v0), Ilivesin(v0, v1), r = 445, Rule(445).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v1, v0, r), Ilivesin(v0, v1), Rule(r), Rule(445).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v0), Ilivesin_exists(v0, v1, r), Rule(r), Rule(445).
Ilivesin(v0, v1) :- Ilivesin(v2, v1), Ilivesin(v0, v2), Rule(446).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v1), Ilivesin(v0, v2), r = 446, Rule(446).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v2, v1, r), Ilivesin(v0, v2), Rule(r), Rule(446).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v1), Ilivesin_exists(v0, v2, r), Rule(r), Rule(446).
Ilivesin(v0, v1) :- Ilivesin(v1, v2), Ilivesin(v2, v0), Rule(447).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v2), Ilivesin(v2, v0), r = 447, Rule(447).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v1, v2, r), Ilivesin(v2, v0), Rule(r), Rule(447).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v2), Ilivesin_exists(v2, v0, r), Rule(r), Rule(447).
Ilivesin(v0, v1) :- Ilivesin(v2, v0), Ilivesin(v1, v2), Rule(448).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v0), Ilivesin(v1, v2), r = 448, Rule(448).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v2, v0, r), Ilivesin(v1, v2), Rule(r), Rule(448).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v0), Ilivesin_exists(v1, v2, r), Rule(r), Rule(448).
Ilivesin(v0, v1) :- Ilivesin(v2, v0), Ilivesin(v2, v1), Rule(449).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v0), Ilivesin(v2, v1), r = 449, Rule(449).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v2, v0, r), Ilivesin(v2, v1), Rule(r), Rule(449).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v0), Ilivesin_exists(v2, v1, r), Rule(r), Rule(449).
Ilivesin(v0, v1) :- Ilivesin(v0, v2), Ilivesin(v1, v2), Rule(450).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v2), Ilivesin(v1, v2), r = 450, Rule(450).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v0, v2, r), Ilivesin(v1, v2), Rule(r), Rule(450).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v2), Ilivesin_exists(v1, v2, r), Rule(r), Rule(450).
Ilivesin(v0, v1) :- Ilivesin(v0, v2), Ilivesin(v2, v1), Rule(451).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v2), Ilivesin(v2, v1), r = 451, Rule(451).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v0, v2, r), Ilivesin(v2, v1), Rule(r), Rule(451).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v0, v2), Ilivesin_exists(v2, v1, r), Rule(r), Rule(451).
Ilivesin(v0, v1) :- Ilivesin(v2, v1), Ilivesin(v2, v0), Rule(452).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v1), Ilivesin(v2, v0), r = 452, Rule(452).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v2, v1, r), Ilivesin(v2, v0), Rule(r), Rule(452).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v2, v1), Ilivesin_exists(v2, v0, r), Rule(r), Rule(452).
Ilivesin(v0, v1) :- Ilivesin(v1, v2), Ilivesin(v0, v2), Rule(453).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v2), Ilivesin(v0, v2), r = 453, Rule(453).
Ilivesin_exists(v0, v1, r) :- Ilivesin_exists(v1, v2, r), Ilivesin(v0, v2), Rule(r), Rule(453).
Ilivesin_exists(v0, v1, r) :- Ilivesin(v1, v2), Ilivesin_exists(v0, v2, r), Rule(r), Rule(453).
