.type V



.decl Rule(n: number)

.input Rule



.decl created(v0: V, v1: V)

.input created



.decl produced(v0: V, v1: V)

.input produced



.decl directed(v0: V, v1: V)

.input directed



.decl actedin(v0: V, v1: V)

.input actedin



.decl Iismarriedto(v0: V, v1: V)

.input Iismarriedto



.decl inv_0(v0: V, v1: V)

.output inv_0



.decl ismarriedto(v0: V, v1: V)

.output ismarriedto



ismarriedto(v0, v1) :- actedin(v0, v2), ismarriedto(v1, v2), Rule(538).


